(function(root,f){const n=typeof module==='object'&&module.exports,api=f(n?require('./later-story-data.js'):root.LaterStory);if(n)module.exports=api;else root.ChapterSix=api;})(globalThis,function(api){
 'use strict';const {Game,AREAS,state:S}=api,P=Game.prototype,old=Object.fromEntries(['enter','points','interact','step','emit'].map(k=>[k,P[k]]));
 P.emit=function(type,data={}){if(type==='victory'&&api.areas.includes(this.area)&&!data.title)return;return old.emit.call(this,type,data);};
 const dialog=(title,text,portrait='warden')=>({type:'dialog',title,text,portrait});
 P.enter=function(id){if(api.areas.includes(id)&&!api.canEnter(this,id))return false;const ok=old.enter.call(this,id);if(ok)this.laterRuntime={linked:false,suppress:0};return ok;};
 P.points=function(){return old.points.call(this).filter(p=>p.kind!=='later-gate'||api.canEnter(this,p.to));};
 P.interact=function(){const o=this.nearestPoint(),s=S(this);if(!o)return old.interact.call(this);if(o.kind==='later-gate'){if(!api.canEnter(this,o.to))return {type:'toast',text:'먼저 현재 이야기 목표를 완료하세요.'};this.enter(o.to);return {type:'travel'};}
  if(o.id==='warden'&&this.journey.phase===5){if(!s.six){s.six=1;return dialog('제6장 · 두 하늘의 호흡','적은 쓰러져도 파형은 돌아와. 외곽 대피는 우리가 맡을게. 안정화 현장에서 기록을 확인하고 네 몸의 호흡과 비교해 줘.');}if(s.six===4){s.six=5;api.reward(this,'six-report','두 하늘의 호흡 · 공동 조사 권한');return dialog('서린 · 이어진 구간','출력이 커진 게 아니라 끊어지던 구간이 이어졌어. 네가 두 세계에서 익힌 방식을 다음 공동 조사에도 함께 쓰자.');}if(s.six<5)return dialog('서린 · 남은 현장',s.six===2?'백련에게 현장의 흐름을 전해 줘.':s.six===3?'배운 쌍계 호흡으로 연계해 재생을 끊고 현장을 안정시켜 줘.':'안정화 현장의 기록을 확인해 줘.');}
  if(o.id==='master'&&s.six===2){s.six=3;s.dualBreath=true;api.record(this,'dual-breath','두 세계의 흐름을 비교해 쌍계 호흡을 완성했다.');return dialog('백련 · 두 하늘의 호흡','네 호흡이 틀린 것은 아니다. 만나 본 적 없는 흐름을 데려온 게지. 유수는 공통 무공과 기연을 유효하게 잇고, 집중은 호흡 뒤 첫 검격으로 연 틈에 기연을 겹쳐라. 첫 경지와는 별개의 운용이다.','master');}
  if(o.id==='six-record'){if(s.six===1){s.six=2;return dialog('윤서 · 되돌아오는 흐름','무공은 통하지만 현상은 남아 있다. 이 몸에 남은 흐름을 백련에게 보여 주자.','hero');}if(s.six===3&&!this.enemies.some(e=>e.hp>0)){this.enter('stabilization');return {type:'toast',text:'현장 재도전 · 살아 있는 위협에 쌍계 호흡을 연결하세요.'};}return dialog('안정화 현장',s.six>=4?'안정화 완료 · 현실 기지의 서린에게 보고하자.':'유수: 공통 무공과 기연을 4초 안에 유효하게 연결. 집중: 1.4초 호흡 뒤 수동 검격, 4초 안에 유효 기연. 적 처치만으로는 현상이 끝나지 않는다.','hero');}
  return old.interact.call(this);
 };
 P.onDualLink=function(){if(this.area==='stabilization'&&S(this).six===3){this.laterRuntime.linked=true;this.laterRuntime.suppress=this.playTime+6;}};
 P.step=function(dt,input){const time=this.playTime;old.step.call(this,dt,input);const d=this.playTime-time;if(this.area!=='stabilization'||d<=0)return;const s=S(this),r=this.laterRuntime;if(s.six===1||s.six===3){if(this.playTime>=r.suppress)for(const e of this.enemies)if(e.hp>0)e.hp=Math.min(e.maxHp,e.hp+d*4);if(s.six===3&&r.linked&&!this.enemies.some(e=>e.hp>0)){s.six=4;this.toast('안정화 완료 · 서린에게 보고하세요.');}}};
 P.laterObjective=function(){if(this.journey.phase!==5)return null;const s=S(this),status=s.six===0?'start':s.six===2?'learn':s.six===4?'report':'combat',destination=s.six===0||s.six>=4?{area:'city',id:'warden'}:s.six===2?{area:'village',id:'master'}:{area:'stabilization',id:'six-record'};return {kind:'story',chapter:6,purpose:'두 세계의 호흡으로 현실의 현장 안정화',condition:s.six===3?'유효 연계로 재생을 끊고 남은 적 처치':'기록 확인 → 백련과 운용 완성 → 현장 안정 → 보고',currentAction:s.six===0?'현실 기지의 서린과 후속 조사 시작':s.six===1?'안정화 현장의 기록 확인':s.six===2?'청운촌의 백련에게 흐름 전하기':s.six===3?'쌍계 호흡 연계 후 현장 위협 처치':s.six===4?'현실 기지의 서린에게 보고':'서린에게 다음 공동 조사 확인',status,destination,rewards:['쌍계 호흡 · 공동 조사 권한','보고 금화 100 · 경험치 120']};};
 return {...api};
});
