(function(root,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else root.Advancement=api;})(globalThis,function(){
 'use strict';
 const names={realm:['삼류','이류','일류','절정','초절정'],hunter:['E','D','C','B','A','S']},bases=[[12,8,2],[18,10,3],[24,12,4],[32,16,5]],gates={realm:[3,6,8,9],hunter:[3,5,7,8,9]},hubs={realm:'village',hunter:'city'},areas={realm:'realmAssessment',hunter:'hunterAssessment'};
 const clone=x=>x instanceof Set?new Set([...x].map(clone)):x instanceof Map?new Map([...x].map(([k,v])=>[clone(k),clone(v)])):Array.isArray(x)?x.map(clone):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,clone(v)])):x,zero=k=>k==='realm'?{attack:0,hp:0,mp:0}:{attack:0,hp:0,speed:0},validKind=k=>k==='realm'||k==='hunter';
 function state(g){g.worldState||={};return g.worldState.advancement||=( {realm:g.journey?.realm?1:0,hunter:0,realmAllocation:zero('realm'),hunterAllocation:zero('hunter'),pending:null,history:g.journey?.realm?['realm:1:legacy']:[]} );}
 function sync(g){const s=state(g);if(s.realm>0&&g.journey)g.journey.realm=1;return s;}
 function chapter(g,n){if(typeof g.v12ChapterCompleted==='function')return !!g.v12ChapterCompleted(n);return n===3?g.fate?.stage>=6:n===5?g.journey?.phase>=5:n===6?g.laterStory?.six===5:n===7?g.laterStory?.seven===5:false;}
 function requirements(g,k,n=state(g)[k]+1){if(n>=names[k].length)return [];const out=[{text:gates[k][n-1]+'장 결과 보고',met:chapter(g,gates[k][n-1])}];if(k==='realm'){const values=Object.values(g.worldGrowth?.murim?.mastery||{}),sum=values.reduce((a,b)=>a+b,0);if(n<=2)out.push({text:'무림 숙련 합계 '+(n===1?8:16),met:sum>=(n===1?8:16)});if(n===1){out.push({text:'기본 기연 계승·증명',met:!!g.revision?.inherited?.some(f=>g.fate?.proven?.includes(f))},{text:'두 세계 실전',met:(g.journey?.worlds?.length||0)>=2});}if(n===2)out.push({text:'한 계열 숙련 8',met:['ripple','echo','seal'].some(f=>(g.worldGrowth?.murim?.mastery?.[f]||0)>=8)},{text:'6장 심화 체득',met:!!g.laterStory?.dualBreath});}return out;}
 function describe(g,k){if(!validKind(k))return null;const s=state(g),stage=s[k],req=requirements(g,k),max=stage===names[k].length-1,allocation=clone(s[k+'Allocation']),spent=Object.values(allocation).reduce((a,b)=>a+b,0),pending=s.pending?.kind===k&&s.pending.stage===stage+1,active=g.advancementTrial?.kind===k,unlocked=!max&&req.every(x=>x.met),safe=g.area===hubs[k],base=k==='realm'?bases[stage]:null;return {kind:k,stage,name:names[k][stage],nextName:names[k][stage+1]||null,unlocked,requirements:req,reward:{hp:base?.[0]||0,mp:base?.[1]||0,attack:base?.[2]||0,points:max?0:2},points:{total:stage*2,spent,available:stage*2-spent},allocation,status:max?'complete':active?'active':pending?'passed':unlocked?'ready':'locked',canStart:unlocked&&safe&&!g.advancementTrial&&!s.pending,canConfirm:k==='realm'&&pending&&safe&&!g.advancementTrial,reason:max?'최종 단계 달성':active?'전장 목표를 수행하세요':pending?(k==='hunter'?'서린에게 평가 결과 보고':'거점에서 돌파 확정'):!safe?'해당 세계의 안전 거점에서 신청':req.find(x=>!x.met)?.text||'시련 신청 가능',trial:active?progress(g):null};}
 function bonus(g,world){const s=state(g),out={hp:0,mp:0,attack:0,speed:0},k=world==='murim'?'realm':'hunter',a=s[k+'Allocation'];if(k==='realm')for(let i=0;i<s.realm;i++){out.hp+=bases[i][0];out.mp+=bases[i][1];out.attack+=bases[i][2];}out.hp+=a.hp*8;out.attack+=a.attack*1.5;if(k==='realm')out.mp+=a.mp*5;else out.speed=Math.min(.1,a.speed*.01);return out;}
 function allocationValid(k,a,total){const keys=Object.keys(zero(k));return a&&typeof a==='object'&&!Array.isArray(a)&&Object.keys(a).length===3&&keys.every(x=>Number.isInteger(a[x])&&a[x]>=0&&a[x]<=10)&&keys.reduce((n,x)=>n+a[x],0)<=total;}
 function allocate(g,k,a){if(!validKind(k)||g.area!==hubs[k]||g.advancementTrial||!allocationValid(k,a,state(g)[k]*2))return false;const before=g.stats(),hp=Math.min(1,g.player.hp/before.hp),mp=Math.min(1,g.player.mp/before.mp);state(g)[k+'Allocation']=clone(a);const after=g.stats();g.player.hp=hp*after.hp;g.player.mp=mp*after.mp;return true;}
 function install(api){for(const k of ['realm','hunter'])api.AREAS[areas[k]]={...api.AREAS[k==='realm'?'forest':'rift'],name:k==='realm'?'백련의 경지 시련':'협회 공식 실전 평가',sub:'예고 대응 → 위협 제압 → 청색 지점 확보 · 보상 없는 훈련',safe:false,world:k==='realm'?'무림':'현실',spawn:[600,650],positions:[],blocks:[],roads:[],points:[{id:'exit',x:150,y:970,label:'시도 종료 · 거점 복귀',kind:'exit'}]};}
 const fields=['area','player','enemies','fx','activated','combo','gold','potions','combat','legendRuntime','realityRuntime','experimentRuntime','dualRuntime','trial','hitStop','shake','notice'];
 function snapshot(g){return {...Object.fromEntries(fields.filter(k=>g[k]!==undefined).map(k=>[k,clone(g[k])])),focus:g.fate?.focus};}
 function restore(g,s){for(const k of fields){if(Object.hasOwn(s,k))g[k]=clone(s[k]);else delete g[k];}if(g.fate&&s.focus!==undefined)g.fate.focus=s.focus;}
 function start(g,k){if(!describe(g,k)?.canStart)return false;const s=state(g),stage=s[k]+1,r={kind:k,stage,phase:0,phases:stage>=4?3:stage>=2?2:1,elapsed:0,phaseTime:0,responses:0,effects:[],kills:0,hold:0,pulse:null,pulseAfter:1,snapshot:snapshot(g)};g.advancementTrial=r;if(k==='hunter'&&stage>=4)g.potions=Math.min(g.potions,1);g.area=areas[k];g.fx=[];g.activated=[];g.player={...clone(g.player),x:600,y:650,hp:g.stats().hp,mp:g.stats().mp,invuln:1,dash:0,cool:Object.fromEntries(Object.keys(g.player.cool||{}).map(k=>[k,0]))};g.realityRuntime=null;g.combat={parry:0,charges:0,echo:null,field:null,pending:[]};g.legendRuntime={seen:new Set(),evade:null,scarAt:-10};g.experimentRuntime={pulse:null,timer:1,serial:0,echo:null,seen:new Set(),pending:[],guard:null,charge:0,lastAction:-100,focus:false,seq:0,companion:null,sense:0,held:false};g.dualRuntime={serial:0,cast:null,last:null,discount:0,opening:0,seen:new Set(),guard:null};if(g.fate)g.fate.focus=0;g.hitStop=0;spawn(g);return true;}
 function spawn(g){const r=g.advancementTrial,count=r.stage===1?1:r.phase===0?2:3;r.responses=0;r.effects=[];r.hold=0;r.phaseTime=0;r.pulse=null;r.pulseAfter=1;r.zone={x:r.phase%2?850:500,y:500,r:100};r.beacon=r.kind==='hunter'&&r.stage>=2&&r.phase===1?{hp:100,timer:0}:null;g.enemies=Array.from({length:count},(_,i)=>{const role=['pressure','heavy','ranged'][i],hp=100+r.stage*55+r.phase*25;return {id:'assessment-'+r.kind+'-'+r.stage+'-'+r.phase+'-'+i,assessment:true,comparison:true,boss:false,kind:i===2?'drone':'bandit',name:['기본 대응 대상','강타 대응 대상','원거리 우선 대상'][i],role,x:600+i*145,y:400,r:20,hp,maxHp:hp,damage:10+r.stage*3,speed:role==='heavy'?65:95,cd:1+i*.3,wind:0,windMax:1,tx:600,ty:650,range:65,flash:0,attacks:0,pattern:'strike',rewarded:false};});g.emit?.('toast',{text:progress(g).text});}
 function progress(g){const r=g.advancementTrial;if(!r)return null;const remaining=g.enemies.filter(e=>e.assessment&&e.hp>0).length,needed=r.phase>0?2:1;return {kind:r.kind,phase:r.phase+1,phases:r.phases,responses:r.responses,required:needed,remaining,hold:r.hold,zone:r.zone,elapsed:r.elapsed,beacon:r.beacon?.hp,text:(r.phase+1)+'/'+r.phases+'단계 · '+['예고 대응','복합 위협 통제','변화한 전장 확보'][r.phase]+' · 대응 '+Math.min(r.responses,needed)+'/'+needed+' · 적 '+remaining+(r.beacon?' · 보호 목표 '+Math.ceil(r.beacon.hp)+'% (원거리 적 우선 제압)':'')+(r.kind==='hunter'&&r.stage>=4?' · 제한 보급 회복약 '+g.potions+'개':'')+' · 제압 후 청색 지점 2초 확보'};}
 function onEffect(g,kind,target){const r=g.advancementTrial;if(!r||!target?.assessment||!g.enemies.includes(target))return false;if(!['counter','absorb','pursuit','weakness','suppress','reflect','guard','evade','link'].includes(kind))return false;const key=target.id+':'+(target.attacks||0)+':'+kind;if(r.effects.includes(key))return false;r.effects.push(key);r.responses++;return true;}
 function step(g,dt){const r=g.advancementTrial;if(!r||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.1);if(g.area!==areas[r.kind]||g.player.hp<=0){finish(g,false);return;}r.elapsed+=dt;r.phaseTime+=dt;if(r.elapsed>=150){finish(g,false);return;}const needed=r.phase>0?2:1;
  if(r.beacon&&g.enemies.some(e=>e.role==='ranged'&&e.hp>0)){r.beacon.hp-=dt*2;if(r.beacon.hp<=0){g.emit?.('toast',{text:'보호 목표 손실 · 원거리 위협을 먼저 제압하세요'});finish(g,false);return;}}
  // Residual telegraphs continue after early kills, so high damage never erases proof.
  if(r.pulse){r.pulse.time-=dt;if(r.pulse.time<=0){const outside=Math.hypot(g.player.x-r.pulse.x,g.player.y-r.pulse.y)>r.pulse.range+g.player.r*.4;if(outside||g.player.invuln>0)r.responses++;else {g.takeHit?.({damage:12+r.stage*3,x:r.pulse.x,y:r.pulse.y,assessment:true});if(!g.takeHit)g.player.hp=Math.max(0,g.player.hp-12-r.stage*3);}g.effect?.('impact',r.pulse.x,r.pulse.y,{range:r.pulse.range,life:.4,max:.4});r.pulse=null;r.pulseAfter=1.2;}}
  else if(r.responses<needed){r.pulseAfter-=dt;if(r.pulseAfter<=0){r.pulse={x:g.player.x,y:g.player.y,range:90+r.phase*25,time:1.4};g.effect?.('fate-field',r.pulse.x,r.pulse.y,{path:'seal',range:r.pulse.range,life:1.4,max:1.4});g.emit?.('toast',{text:'잔류 위협 · 표시된 원 밖으로 이동하거나 회피하세요'});}}
  const clear=g.enemies.every(e=>e.hp<=0);if(clear&&r.responses>=needed){g.effect?.('fate-field',r.zone.x,r.zone.y,{path:'ripple',range:r.zone.r,life:.15,max:.15});if(Math.hypot(g.player.x-r.zone.x,g.player.y-r.zone.y)<=r.zone.r)r.hold+=dt;else r.hold=0;if(r.hold>=2){if(++r.phase>=r.phases){r.earned=true;finish(g,true);}else spawn(g);}}
 }
 function finish(g,success=false){const r=g.advancementTrial;if(!r||success&&!r.earned)return false;const s=state(g);if(success)s.pending={kind:r.kind,stage:r.stage,event:r.kind+':'+r.stage+':passed'};restore(g,r.snapshot);g.advancementTrial=null;g.emit?.('toast',{text:success?(r.kind==='realm'?'시련 성공 · 거점 성장에서 돌파를 확정하세요':'평가 성공 · 서린에게 결과를 보고하세요'):'시도 종료 · 영구 성장과 소모품을 복구했습니다. 다시 도전할 수 있습니다.'});return true;}
 function canEnter(g,id){if(g.advancementTrial){finish(g,false);return false;}return !Object.values(areas).includes(id);}
 function applyConfirmation(g,k){const s=state(g);s[k]++;s.history.push(k+':'+s[k]+':confirmed');s.pending=null;sync(g);g.collectAchievements?.();return true;}
 function confirm(g,k){return k==='realm'&&describe(g,k)?.canConfirm?applyConfirmation(g,k):false;}
 function report(g,k='hunter'){const s=state(g);return k==='hunter'&&g.area==='city'&&!g.advancementTrial&&s.pending?.kind==='hunter'&&s.pending.stage===s.hunter+1?applyConfirmation(g,k):false;}
 function withSaveSnapshot(g,callback){const r=g.advancementTrial;if(!r)return callback();const current=snapshot(g);try{restore(g,r.snapshot);g.advancementTrial=null;return callback();}finally{restore(g,current);g.advancementTrial=r;}}
 const entryPending=new WeakSet();
 function entry(g,{entrance}={}){const kind=g.area==='village'?'realm':g.area==='city'?'hunter':null;if(!kind)return null;if(kind==='hunter'&&!chapter(g,3)&&!state(g).hunter)return null;if(kind==='realm'&&!state(g).realm&&!(g.revision?.inherited?.length&&g.journey?.worlds?.length>=2))return null;const d=describe(g,kind);if(!d.nextName)return null;const near=!entrance||Math.hypot(g.player.x-entrance.x,g.player.y-entrance.y)<90,reason=!near?'통합 탐험 입구로 이동하세요.':g.introActive?'도입부를 먼저 마치세요.':d.reason;return {id:'assessment:'+kind,assessment:true,kind,hub:hubs[kind],world:kind==='realm'?'무림':'현실',area:areas[kind],name:d.nextName+(kind==='realm'?' 경지 시련':'급 공식 평가'),purpose:kind==='realm'?'예고 대응과 위협 제압을 증명하고 거점에서 경지를 확정합니다.':'실전 평가 후 서린에게 직접 보고하여 공식 등급을 확정합니다.',threat:'공격 예고 대응 → 위협 제압 → 청색 지점 확보'+(kind==='hunter'&&d.stage>=1?' · 보호 목표와 원거리 위협 우선 판단':''),reason,canEnter:d.canStart&&near&&!g.introActive,status:d.status,statusText:d.status==='passed'?(kind==='realm'?'시련 성공 · 성장에서 확정':'평가 성공 · 서린에게 보고'):d.canStart?'선택 성장 · 도전 가능':'선택 성장 · 조건 미충족',rewardPolicy:'처치 경험치·금화·숙련 보상 없음. 시도 종료 시 기존 체력·자원·소모품 복원. 확정 후 '+(kind==='realm'?'무림 특화':'현실 훈련')+' 2포인트.',current:false,completed:false,report:d.status==='passed',requirements:d.requirements};}
 async function requestEntry(g,id,prepare,options={}){if(entryPending.has(g))return {ok:false,reason:'입장 준비 중입니다.'};const first=entry(g,options);if(!first||first.id!==id||!first.canEnter)return {ok:false,reason:first?.reason||'입장할 수 없습니다.'};entryPending.add(g);try{if(typeof prepare!=='function'||await prepare(first.area)===false)throw Error('preparation');const next=entry(g,options);if(!next||next.id!==id||!next.canEnter||!start(g,next.kind))return {ok:false,reason:next?.reason||'입장 조건이 변경되었습니다.'};return {ok:true,id:next.area};}catch(error){return {ok:false,reason:'지역 준비에 실패했습니다. 현재 위치에서 다시 시도하세요.'};}finally{entryPending.delete(g);}}
 function validate(g){const s=state(g);if(g.journey&&Number(g.journey.realm||0)!==(s.realm>0?1:0))throw Error('기존 경지와 성장 기록 불일치');for(const k of ['realm','hunter'])if(!Number.isInteger(s[k])||s[k]<0||s[k]>=names[k].length||!allocationValid(k,s[k+'Allocation'],s[k]*2))throw Error('경지·등급 성장 기록 오류');if(!Array.isArray(s.history)||s.history.length>10||new Set(s.history).size!==s.history.length||s.history.some(x=>typeof x!=='string'||! /^(realm:[1-4]|hunter:[1-5]):(confirmed|legacy)$/.test(x)))throw Error('성장 확정 기록 오류');for(const k of ['realm','hunter'])for(let n=1;n<=s[k];n++)if(s.history.filter(x=>x===k+':'+n+':confirmed'||k==='realm'&&n===1&&x==='realm:1:legacy').length!==1)throw Error('성장 단계별 지급 기록 누락');if(s.history.length!==s.realm+s.hunter)throw Error('성장 지급 기록 불일치');for(const k of ['realm','hunter'])for(let n=1;n<=s[k];n++)if(!(k==='realm'&&n===1&&s.history.includes('realm:1:legacy'))&&!requirements(g,k,n).every(x=>x.met))throw Error('경지·평가 선행 기록 누락');if(s.pending!==null&&(!validKind(s.pending?.kind)||s.pending.stage!==s[s.pending.kind]+1||s.pending.stage>=names[s.pending.kind].length||s.pending.event!==s.pending.kind+':'+s.pending.stage+':passed'))throw Error('시련 성공 기록 오류');if(s.pending&&!requirements(g,s.pending.kind,s.pending.stage).every(x=>x.met))throw Error('시련 선행 기록 누락');g.worldState.advancement={realm:s.realm,hunter:s.hunter,realmAllocation:clone(s.realmAllocation),hunterAllocation:clone(s.hunterAllocation),pending:s.pending?clone(s.pending):null,history:[...s.history]};sync(g);return g.worldState.advancement;}
 return {names,bases,gates,areas,state,sync,validate,bonus,describe,start,step,onEffect,finish,confirm,report,allocate,canEnter,install,progress,withSaveSnapshot,entry,requestEntry};
});
