(function(root,f){const n=typeof module==='object'&&module.exports,api=f(n?require('./chapter-six.js'):root.ChapterSix);if(n)module.exports=api;else root.ChapterSeven=api;})(globalThis,function(api){
 'use strict';const {Game,AREAS,state:S,point}=api,P=Game.prototype,old=Object.fromEntries(['interact','step','takeHit','laterObjective','onDualLink'].map(k=>[k,P[k]]));
 for(const [id,source,name,world]of [['woundPass','returnPass','천흔 외곽 · 압력을 흘릴 길','무림'],['woundDock','returnDock','공동 방어선 · 귀환 부두','현실'],['woundCore','returnPass','천흔 중심 · 두 세계의 상처','무림']]){AREAS[id]={...AREAS[source],name,world,chapter:7,hp:190,bossHp:id==='woundCore'?1150:950,damage:17,positions:[[430,780],[820,720],[1100,350]],blocks:AREAS[source].blocks.map(x=>({...x})),points:[point('exit',110,975,world==='현실'?'헌터 기지로 귀환':'청운촌으로 귀환','exit'),point('seven-status',350,880,'공동 대응 상황 확인')]};}
 AREAS.village.points.push(point('woundGate',850,640,'천흔 외곽','later-gate',{to:'woundPass'}),point('coreGate',1080,650,'천흔 중심부','later-gate',{to:'woundCore'}));AREAS.city.points.push(point('woundDockGate',1000,750,'공동 방어선','later-gate',{to:'woundDock'}));
 function battle(g){const prepared=S(g).passOpened;return {safeRadius:prepared?180:65,pulseInterval:prepared?6.4:3.2,x:730,y:700};}
 const dialog=(title,text,portrait='warden')=>({type:'dialog',title,text,portrait});
 P.interact=function(){const o=this.nearestPoint(),s=S(this);if(o?.id==='warden'&&s.six===5){if(!s.seven){s.seven=1;return dialog('제7장 · 같은 상처의 두 끝','한쪽만 봉합하면 다른 쪽 압력이 커져. 나는 현실 대피를 맡을게. 먼저 무림의 천흔 외곽에서 백련의 방호선을 돕고 압력을 흘릴 길을 열어 줘. 양쪽을 직접 비교해 전할 사람은 너뿐이야.');}if(s.seven===4){s.seven=5;s.completed=true;api.reward(this,'seven-report','두 세계의 귀환로 안정 · 공동 대응 제안권',160,180);return dialog('서린 · 네가 정할 다음 길','양쪽에서 버틴 사람들이 있었어. 너는 그들이 닿을 수 없는 두 길을 연결했지. 다음 공동 조사부터는 네가 다녀올 순서와 대응을 먼저 제안해 줘.');}return dialog('서린 · 공동 대응',s.completed?'귀환로는 안정됐어. 준비한 양쪽의 결과는 남아 있고, 다음 조사에는 네 판단을 반영할 거야.':this.laterObjective().currentAction);}
  if(o?.id==='master'&&s.seven>0)return dialog('백련 · 연결된 두 길',s.dockStabilized?'현실의 흐름을 네가 전해 준 덕에 방호선을 바꿀 수 있었다. 천흔 중심부로 가거라.':s.passOpened?'이쪽의 압력은 흘려보냈다. 현실의 방어선이 어떻게 달라졌는지 직접 확인하거라.':'우리도 방호선을 지키겠다. 쌍계 호흡으로 외곽의 흐름을 끊고 위협을 물리쳐라.','master');
  if(o?.id==='seven-status'){if(!this.enemies.some(e=>e.hp>0)&&!this.laterRuntime.linked&&s.seven<4){this.enter(this.area);return {type:'toast',text:'현장 재도전 · 실제 위협에 쌍계 호흡을 연결하세요.'};}return dialog('두 세계의 공동 대응',this.area==='woundDock'?s.passOpened?'무림에서 압력을 흘려보냈다. 안전 영역이 넓어지고 파동 간격이 길어졌다. 이 현장을 안정시키면 백련이 중심부 방호선을 바꿀 수 있다.':'아직 무림의 압력이 남아 있다. 천흔 외곽을 먼저 해결하자.':this.laterObjective().currentAction,'hero');}return old.interact.call(this);
 };
 P.onDualLink=function(e){old.onDualLink.call(this,e);if(['woundPass','woundDock','woundCore'].includes(this.area)){this.laterRuntime.linked=true;this.laterRuntime.suppress=this.playTime+6;}};
 P.takeHit=function(e){if(this.area==='woundDock'&&e.laterPulse){const b=battle(this);if(Math.hypot(this.player.x-b.x,this.player.y-b.y)<b.safeRadius)return;}return old.takeHit.call(this,e);};
 P.step=function(dt,input){const t=this.playTime;old.step.call(this,dt,input);const d=this.playTime-t,area=this.area;if(d<=0||!['woundPass','woundDock','woundCore'].includes(area))return;const s=S(this),r=this.laterRuntime;
  if(area==='woundDock'){const b=battle(this);r.pulse=(r.pulse||0)+d;if(r.pulse>=b.pulseInterval){r.pulse=0;this.effect('seal',b.x,b.y,{range:b.safeRadius,life:1,max:1});if(this.playTime>=r.suppress)this.takeHit({laterPulse:true,residual:true,id:'world-pressure',name:'되돌아오는 압력',x:this.player.x+20,y:this.player.y,hp:1,damage:14});}}
  if(area==='woundCore'&&this.playTime>=r.suppress)for(const e of this.enemies)if(e.hp>0)this.regenerateEnemy?this.regenerateEnemy(e,d*5):e.hp=Math.min(e.maxHp,e.hp+d*5);
  if(!r.linked||this.enemies.some(e=>e.hp>0))return;
  if(area==='woundPass'&&s.seven===1){s.passOpened=true;s.seven=2;api.record(this,'seven-pass','무림의 압력을 흘려 현실 안전 영역을 넓혔다.');this.toast('무림 준비 완료 · 현실 공동 방어선의 파동이 약해졌습니다.');}
  if(area==='woundDock'&&s.seven===2){s.dockStabilized=true;s.coreOpened=true;s.seven=3;api.record(this,'seven-dock','현실 안정 결과로 무림 중심부의 길을 열었다.');this.toast('현실 안정 완료 · 청운촌의 천흔 중심부 개방');}
  if(area==='woundCore'&&s.seven===3){s.seven=4;api.record(this,'seven-core','두 세계의 중심 위협을 제압했다.');this.toast('양쪽 귀환로 안정 · 현실 기지의 서린에게 최종 보고');}
 };
 P.laterObjective=function(){const s=S(this);if(s.six!==5||!s.seven)return old.laterObjective.call(this);const destination=s.seven===1?{area:'woundPass',id:'seven-status'}:s.seven===2?{area:'woundDock',id:'seven-status'}:s.seven===3?{area:'woundCore',id:'seven-status'}:{area:'city',id:'warden'};return {kind:'story',chapter:7,purpose:s.completed?'두 세계의 귀환로 안정 완료':'양쪽 귀환로를 연결해 안정시키기',condition:'쌍계 호흡으로 흐름 대응 후 각 현장의 위협 처치',currentAction:s.seven===1?'무림 천흔 외곽에서 압력을 흘릴 길 열기':s.seven===2?'현실 공동 방어선에서 넓어진 안전 영역을 이용해 현장 안정':s.seven===3?'현실의 해결 결과로 열린 무림 천흔 중심부 제압':s.seven===4?'현실 기지의 서린에게 최종 보고':'공동 대응 제안권 획득 · 자유 탐험과 실전 의뢰',status:s.seven===4?'report':s.completed?'complete':'combat',destination,rewards:['공동 대응 제안권 · 개인 행적','최종 보고 금화 160 · 경험치 180']};};
 return {...api,battle};
});
