(function(root,f){const n=typeof module==='object'&&module.exports,api=f(n?require('./later-story-data.js'):root.LaterStory);if(n)module.exports=api;else root.ChapterSix=api;})(globalThis,function(api){
 'use strict';const {Game,AREAS,state:S}=api,P=Game.prototype,old=Object.fromEntries(['enter','points','interact','step','emit','strike','reward'].map(k=>[k,P[k]]));
 P.emit=function(type,data={}){if(type==='victory'&&api.areas.includes(this.area)&&!data.title)return;return old.emit.call(this,type,data);};
 const direct=g=>!!(g.worldGrowth||g.journey?.directProgression);
 const dialog=(title,text,portrait='warden')=>({type:'dialog',title,text,portrait});
 P.enter=function(id){if(api.areas.includes(id)&&!api.canEnter(this,id))return false;const ok=old.enter.call(this,id);if(ok)this.laterRuntime={linked:false,suppress:0};return ok;};
 P.points=function(){return old.points.call(this).filter(p=>p.kind!=='later-gate'||api.canEnter(this,p.to)).map(p=>direct(this)&&p.id==='six-record'?{...p,label:'안정화 장치 · 점검과 수련'}:p);};
 P.interact=function(){const o=this.nearestPoint(),s=S(this);if(!o)return old.interact.call(this);if(o.kind==='later-gate'){if(!api.canEnter(this,o.to))return {type:'toast',text:'먼저 현재 이야기 목표를 완료하세요.'};this.enter(o.to);return {type:'travel'};}
  if(o.id==='warden'&&this.journey.phase===5){if(!s.six){s.six=1;return dialog('제6장 · 두 하늘의 호흡','적은 쓰러져도 파형은 돌아와. 외곽 대피는 우리가 맡을게. 안정화 현장의 장치를 점검한 뒤 백련에게 대응 방법을 배워 와 줘.');}if(s.six===4){s.six=5;api.reward(this,'six-report','두 하늘의 호흡 · 공동 조사 권한');return dialog('서린 · 이어진 구간','출력이 커진 게 아니라 끊어지던 구간이 이어졌어. 네가 두 세계에서 익힌 방식을 다음 공동 조사에도 함께 쓰자.');}if(s.six<5)return dialog('서린 · 남은 현장',s.six===2?'백련에게 현장의 흐름을 전해 줘.':s.six===3?'배운 심법 심화로 연계해 재생을 끊고 현장을 안정시켜 줘.':'안정화 현장의 장치를 점검해 줘.');}
  if(o.id==='master'&&s.six===2){s.six=3;if(this.worldGrowth){s.deepening={stage:'trial',observed:!direct(this),clue:true,interpreted:!direct(this),legacy:false};return dialog('백련 · 심법의 원리','현장의 재생을 네 몸으로 끊어 보거라. 안정화 현장에서 검격·회피로 위협을 정리한 뒤 도겸과 공급 연결을 끊거나, 공통 공격과 기연의 실제 효과를 연결하면 심법을 더 깊이 깨달을 수 있다. 위협이 사라졌다면 안정화 장치에서 잔류 파형 수련을 시작하거라.','master');}s.dualBreath=true;api.record(this,'dual-breath','두 세계의 흐름을 비교해 심법 심화를 완성했다.');return dialog('백련 · 두 하늘의 호흡','네 호흡이 틀린 것은 아니다. 만나 본 적 없는 흐름을 데려온 게지. 유수는 공통 무공과 기연을 유효하게 잇고, 집중은 호흡 뒤 첫 검격으로 연 틈에 기연을 겹쳐라. 첫 경지와는 별개의 운용이다.','master');}
  if(o.id==='six-record'){if(s.six===1){if(this.worldGrowth&&!direct(this)&&!s.deepening?.observed)return dialog('윤서 · 현장 관찰','되돌아오는 파형을 먼저 살펴보자. 살아 있는 위협의 재생이나 잔류 파동을 관찰하면 기록과 비교할 수 있다.','hero');s.six=2;if(this.worldGrowth)s.deepening={stage:'clue',observed:!direct(this),clue:true,interpreted:false,legacy:false};return dialog('윤서 · 되돌아오는 흐름','장치 점검을 마쳤다. 청운촌의 백련에게 재생을 끊을 대응 방법을 배우자.','hero');}if(s.six===3&&!this.enemies.some(e=>e.hp>0)){if(this.worldGrowth){this.startDeepeningExercise();return {type:'toast',text:'잔류 파형 수련 · 공통 공격과 기연의 실제 효과를 연결하세요. 처치 보상은 없습니다.'};}this.enter('stabilization');return {type:'toast',text:'현장 재도전 · 살아 있는 위협에 심법 심화을 연결하세요.'};}return dialog('안정화 현장',s.six>=4?'안정화 완료 · 현실 기지의 서린에게 보고하자.':'유수: 공통 무공과 기연을 4초 안에 유효하게 연결. 집중: 1.4초 호흡 뒤 수동 검격, 4초 안에 유효 기연. 적 처치만으로는 현상이 끝나지 않는다.','hero');}
  return old.interact.call(this);
 };
 P.onDualLink=function(e){if(this.area==='stabilization'&&S(this).six===3){if(this.worldGrowth&&!S(this).dualBreath&&S(this).deepening?.stage==='trial'){S(this).dualBreath=true;S(this).deepening.stage='acquired';api.record(this,'dual-breath','실제 전투 연계로 심법 심화를 체득했다.');this.toast('심법 심화 달성 · 연계 강화 체득');this.emit('deepening-acquired',{target:e?.id});}if(e?.deepeningExercise){e.hp=0;e.rewarded=true;}this.laterRuntime.linked=true;this.laterRuntime.suppress=this.playTime+6;}};
 P.startDeepeningExercise=function(){if(!this.worldGrowth||this.area!=='stabilization'||S(this).six!==3||this.enemies.some(e=>e.hp>0))return false;const p=this.player;this.enemies=this.enemies.filter(e=>!e.deepeningExercise);this.enemies.push({id:'six-residual',name:'잔류 파형',deepeningExercise:true,residual:true,comparison:true,rewarded:true,kind:'shade',boss:false,r:22,x:p.x+65,y:p.y,hp:1000000,maxHp:1000000,damage:0,speed:0,cd:.2,wind:.8,range:100,tx:p.x,ty:p.y,flash:0,attacks:0});return true;};
 P.strike=function(e,amount,...args){if(this.worldGrowth&&e?.deepeningExercise)amount=Math.min(amount,1);return old.strike.call(this,e,amount,...args);};
 P.reward=function(e){if(this.worldGrowth&&e?.deepeningExercise){e.rewarded=true;return;}return old.reward.call(this,e);};
 P.step=function(dt,input){const time=this.playTime;old.step.call(this,dt,input);const d=this.playTime-time;if(this.area!=='stabilization'||d<=0)return;const s=S(this),r=this.laterRuntime;if(this.worldGrowth&&!direct(this)&&s.six===1&&!s.deepening?.observed){r.observation=(r.observation||0)+d;if(r.observation>=.5){s.deepening={stage:'observed',observed:true,clue:false,interpreted:false,legacy:false};this.effect('seal',360,900,{range:110,life:1,max:1});this.toast('되돌아오는 파형 관찰 · 현장 기록과 비교하세요.');}}if(s.six===1||s.six===3){if(this.playTime>=r.suppress)for(const e of this.enemies)if(e.hp>0)this.regenerateEnemy?this.regenerateEnemy(e,d*4):e.hp=Math.min(e.maxHp,e.hp+d*4);if(s.six===3&&r.linked&&!this.enemies.some(e=>e.hp>0)){s.six=4;this.toast('안정화 완료 · 서린에게 보고하세요.');}}};
 P.laterObjective=function(){if(this.journey.phase!==5)return null;const s=S(this),status=s.six===0?'start':s.six===2?'learn':s.six===4?'report':'combat',destination=s.six===0||s.six>=4?{area:'city',id:'warden'}:s.six===2?{area:'village',id:'master'}:{area:'stabilization',id:s.six===3&&this.area==='stabilization'&&!this.enemies.some(e=>e.hp>0)?'six-cut':'six-record'};return {kind:'story',chapter:6,purpose:'두 세계의 호흡으로 현실의 현장 안정화',condition:s.six===3?'위협 제압 → 도겸의 공급 연결 차단 또는 유효 연계':'현장 장치 점검 → 백련의 지도 → 실제 연계 체득 → 현장 안정 → 보고',currentAction:s.six===0?'현실 기지의 서린과 후속 조사 시작':s.six===1?(direct(this)?'안정화 현장의 장치에 다가가 E로 점검':this.worldGrowth&&!s.deepening?.observed?'안정화 현장에서 되돌아오는 파형 관찰':'관찰한 파형을 현장 기록과 비교'):s.six===2?'청운촌의 백련에게 흐름 전하기':s.six===3?(s.dualBreath?'남은 위협 제압 후 공급 연결 확인':'일반 검격·회피로 위협 제압 → 도겸의 공급 연결 차단, 또는 기연 연계'):s.six===4?'현실 기지의 서린에게 보고':'서린에게 다음 공동 조사 확인',status,destination,rewards:['심법 심화 · 공동 조사 권한','보고 금화 100 · 경험치 120']};};
 return {...api};
});
