(function(root){'use strict';root.CharacterUI={create({game,show,node,grid,refresh=()=>{},openSection=()=>{}}){
 function open(world=WorldGrowth.worldOf(game())){
  const g=game(),s=WorldGrowth.stats(g,world),w=g.worldGrowth[world],body=node('section','character-screen profile-screen');body.dataset.world=world;
  const statusNews=g.unreadNews('status'),statusItems=g.newsList().filter(item=>item.section==='status');const portraits=node('nav','profile-worlds');portraits.setAttribute('aria-label','세계별 캐릭터');
  for(const [id,label]of [['reality','현실'],['murim','무림']]){const b=node('button','profile-world'),img=node('img');b.dataset.world=id;img.src='assets/art/'+id+'/hero/yunseo/runtime-portrait-neutral.webp';img.alt='';b.setAttribute('aria-label',label+' 캐릭터');b.setAttribute('aria-pressed',String(id===world));const copy=node('span','profile-world-copy');copy.append(node('small','',id==='reality'?'HUNTER':'MARTIAL ARTIST'),node('strong','',label),node('small','',id===world?'선택한 세계':'정보 보기'));b.append(img,copy);if(id==='reality'&&statusNews.length){b.classList.add('has-news');const dot=node('span','news-dot');dot.setAttribute('aria-hidden','true');b.append(dot);b.setAttribute('aria-description','새 소식 '+statusNews.length+'개');}b.onclick=()=>open(id);portraits.append(b);}body.append(portraits);
  const identity=node('div','profile-identity');identity.append(node('h3','','윤서'),node('span','profile-level','Lv. '+w.level),node('span','profile-rank',world==='reality'?Advancement.describe(g,'hunter').name+'급 헌터':Advancement.describe(g,'realm').name));body.append(identity);
  const exp=node('div','profile-exp'),bar=node('progress');bar.max=s.next;bar.value=w.xp;bar.setAttribute('aria-label','경험치');exp.append(node('span','','EXP'),bar,node('span','',w.xp+' / '+s.next));body.append(exp);
  const stats=node('div','profile-stats');for(const [icon,label,value]of [['♥','체력',s.hp],['◈',world==='murim'?'내력':'자원',s.mp],['⚔','공격력',s.attack]]){const row=node('div','profile-stat');const glyph=node('span','profile-stat-icon',icon);glyph.setAttribute('aria-hidden','true');row.append(glyph,node('span','',label),node('strong','',String(value)));stats.append(row);}body.append(stats);
  const equipped=g.worldGrowth[world].equipped;body.append(node('div','profile-equipped','장착 무공 · '+(equipped?(world==='reality'?(RealitySkills.table[equipped]?.[0]?.[0]||'기본 무공'):(globalThis.DualWorld.Fate.PATHS[equipped]?.name||'기본 무공')):'기본 무공')));
  if(world==='reality'&&statusItems.length){const list=node('section','profile-news');list.append(node('h3','','활동 · 귀환 성과'));for(const item of statusItems){const row=node('article','world-card'+(item.read?'':' has-news'));if(!item.read)row.append(node('span','news-dot'));row.append(node('h4','',item.title),node('p','',item.text));list.append(row);}body.append(list);}
  const nav=node('nav','profile-shortcuts');for(const [label,section]of [['성장','growth'],['무공','skills']]){const b=node('button','secondary',label);b.onclick=()=>openSection(section);nav.append(b);}body.append(nav);
  show('캐릭터',body,[{label:'닫기',secondary:true}],'system');if(world==='reality'){const unread=g.unreadNews('status');for(const item of unread)g.readNews(item.id);if(unread.length)refresh();}
 }return {open};}};})(globalThis);
