(function(root,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else root.CycleOne=api;})(globalThis,function(){
 'use strict';
 const flags=['regionalClosed','transportClue','roadFought','roadClear','roadReported','dockClear','eightComplete','planDelivered','supplyClear','supplyCut','supplyReported','evacuated','threatFought','threatClear','realityReported','nineComplete','approachClear','confronted','bossClear','murimEpilogue','epilogue','sighting','reunion','returnReceipt','recordDelivered','invited','legacyAccess'];
 const specs=[
  ['transportRoad','forest','옛 운송길 · 민간 통로',8,'무림',200,800],
  ['transportDock','harbor','반입 부두 · 움직이는 공급',8,'현실',215,900],
  ['supplyRidge','returnPass','본거지 외곽 · 공급 차단',9,'무림',240,1050],
  ['evacuationDock','returnDock','현실 출구 · 대피 작전',9,'현실',250,1100],
  ['overseerApproach','returnPass','감독관 본거지 · 진입로',10,'무림',240,1050],
  ['overseerHall','returnPass','개방실 · 흑조 감독관',10,'무림',250,1900]
 ];
 const areaIds=specs.map(s=>s[0]);
 function initial(){return Object.assign(Object.fromEntries(flags.map(k=>[k,false])),{version:1,routeChoice:null});}
 function normalize(raw){const s=initial();if(raw&&typeof raw==='object'){for(const k of flags)s[k]=raw[k]===true;if(['device','watcher'].includes(raw.routeChoice))s.routeChoice=raw.routeChoice;}return s;}
 function state(g){g.worldState||={};return g.worldState.cycleOne||(g.worldState.cycleOne=initial());}
 function sync(g){const s=state(g);if(g.laterStory?.seven===5||g.laterStory?.completed)s.regionalClosed=true;return s;}
 function validate(g){const s=state(g);for(const k of flags)if(typeof s[k]!=='boolean')throw Error('첫 사이클 상태 오류: '+k);if(![null,'device','watcher'].includes(s.routeChoice))throw Error('운송길 선택 오류');const dependencies={transportClue:['regionalClosed'],roadFought:['transportClue'],roadClear:['roadFought'],roadReported:['roadClear'],dockClear:['roadReported'],eightComplete:['dockClear'],planDelivered:['eightComplete'],supplyClear:['planDelivered'],supplyCut:['supplyClear'],supplyReported:['supplyCut'],evacuated:['supplyReported'],threatFought:['supplyReported'],threatClear:['evacuated','threatFought'],realityReported:['threatClear'],nineComplete:['realityReported'],approachClear:['nineComplete'],confronted:['approachClear'],bossClear:['confronted'],murimEpilogue:['bossClear'],epilogue:['murimEpilogue'],recordDelivered:['returnReceipt'],invited:['recordDelivered']};for(const [key,requires]of Object.entries(dependencies))if(s[key]&&requires.some(k=>!s[k]))throw Error('첫 사이클 선행 사건 누락: '+key);if(s.roadClear&&!s.routeChoice)throw Error('민간 통로 확보 누락');g.worldState.cycleOne=normalize(s);return true;}
 function canEnter(g,id){const s=sync(g);return id==='transportRoad'?s.transportClue:id==='transportDock'?s.roadReported:id==='supplyRidge'?s.planDelivered:id==='evacuationDock'?s.supplyReported:id==='overseerApproach'?s.nineComplete:id==='overseerHall'?s.approachClear:false;}
 function areas(base,point=(id,x,y,label,kind='cycle')=>({id,x,y,label,kind})){return Object.fromEntries(specs.map(([id,source,name,chapter,world,hp,bossHp])=>[id,{...base[source],name,world,chapter,hp,bossHp,damage:id==='overseerHall'?19:17,boss:id==='overseerHall'?'흑조 감독관':'흑조 운송 감시자',bossKind:id==='overseerHall'?'human-overseer':base[source].bossKind,artArea:source,backgroundAlias:source,positions:id==='overseerHall'?[[880,420]]:id==='overseerApproach'?[[410,810],[790,660],[1060,360]]:[[390,780],[780,660],[1060,360]],blocks:base[source].blocks.map(b=>({...b})),points:[point('exit',110,975,world==='현실'?'헌터 기지로 귀환':'청운촌으로 귀환','exit')]}]));}
 function entries(g){return specs.map(([id,source,name,chapter,world])=>({id,area:id,name,label:name,world,chapter,kind:'story',unlocked:canEnter(g,id),available:canEnter(g,id),lockedReason:'현재 이야기의 준비와 직접 보고를 완료하세요.',description:chapter===10?'9장 준비를 사용합니다. 경지·등급·심법 투자는 입장 조건이 아닙니다.':'민간인의 길을 확보하고 두 세계의 결과를 직접 전달합니다.'}));}
 function points(g){const s=sync(g),p=(id,x,y,label)=>({id,x,y,label,kind:'cycle'});if(g.area==='transportRoad')return [p('civilian-route',350,900,s.routeChoice?'민간 통로 · 확보 상태':'민간 통로 · 우선 대응 선택')];if(g.area==='supplyRidge')return [p('supply-cut',850,400,'외부 공급 장치 차단')];if(g.area==='evacuationDock')return [p('evacuation-route',350,900,'민간인 대피 경로 확보')];if(g.area==='overseerHall')return [p('overseer-confront',650,860,s.confronted?'흑조 감독관 · 재도전':'흑조 감독관과 대면'),p('overseer-charge',1080,450,'잔여 충전 장치 · 노출 시 차단')];return [];}
 const dialog=(title,text,portrait='hero')=>({type:'dialog',title,text,portrait});
 function interact(g,id,choice){const s=sync(g);
  if(id==='returned-yeonhwa'&&g.area==='village'&&s.regionalClosed&&!s.transportClue){s.transportClue=true;return dialog('연화 · 기록을 길로 바꾸다','이 표식은 비를 피해 바꾸는 운송길이에요. 큰 상자는 옛길로 지나갈 수 없죠. 민간 통로부터 열면 떨어진 화물표로도 목적지를 찾을 수 있어요. 7장에서 닫은 지역망은 안전하게 유지되고 있어요.','yeonhwa');}
  if(id==='civilian-route'&&g.area==='transportRoad'&&s.transportClue){if(!s.routeChoice){if(['device','watcher'].includes(choice)){s.routeChoice=choice;if(s.roadFought)s.roadClear=true;applyRoute(g);return dialog('윤서 · 사람의 길부터',choice==='device'?'위험 장치부터 끊었다. 중앙 통로가 안전해졌다. 남은 정예 감시자를 제압하자.':'원거리 감시자를 먼저 묶었다. 민간인을 위한 보호 구역이 생겼다. 남은 정예를 제압하자.');}return {type:'cycle-choice',title:'민간 통로 · 먼저 지킬 곳',text:'두 선택 모두 민간인을 구하고 운송 단서를 보존합니다.',choices:[{id:'device',label:'위험 장치를 먼저 차단'},{id:'watcher',label:'원거리 감시자를 먼저 억제'}],pointId:id};}return dialog('열린 민간 통로',s.roadClear?'화물표와 대체 운송길이 가리키는 곳을 현실의 서린에게 직접 전하자.':'선택한 안전 구역을 이용해 운송 정예를 제압하자.');}
  if(id==='warden'&&g.area==='city'){
   if(s.bossClear&&s.murimEpilogue&&!s.epilogue){s.epilogue=true;return dialog('서린 · 네 이름으로 남긴 판단','윤서: 감독관은 무림에서 구속됐어. 백련 측이 장치와 신병을 맡았고, 시설도 폐쇄했어.\n서린: 네 직접 보고와 현지 압수 기록을 함께 남길게. 이번 보고서, 네 판단으로 바뀐 구간은 네 이름으로 남겼어.\n도겸: 다음에도 장비는 내가 챙길 테니, 앞에서 혼자 다 맡겠다는 말은 하지 마.\n윤서: 청운촌에 다녀올게. 약속이 있어서.','warden');}
   if(s.threatClear&&!s.realityReported){s.realityReported=true;return dialog('서린 · 외부 연결 차단 확인','현지 기록과 대피 명부를 확인했어. 외부 재충전과 출구는 우리가 막을게. 내부에는 처음 확인한 충전분만 남아 있어. 이 결과를 백련에게 직접 전해 줘.','warden');}
   if(s.supplyCut&&!s.supplyReported){s.supplyReported=true;return dialog('서린 · 전해 받은 무림 준비','윤서: 무림 외곽 공급을 끊었어. 백련과 제자들이 후방을 지키고 있어.\n서린: 이제 여기 대피 경로와 출구 위협을 처리하자. 도겸은 후방을 맡을 거야.','warden');}
   if(s.dockClear&&!s.eightComplete){s.eightComplete=true;return dialog('제8장 완료 · 본거지의 위치','반입을 끊었고 네가 가져온 표식과 현실 운송 기록을 대조했어. 감독관의 회유 명령문도 확인했어. “협조하면 그자의 통행은 보장한다.” 하지만 경계석의 원리까지 아는 건 아니야. 외부 공급을 끊어도 내부 잔여 충전은 잠시 남아. 이 준비 순서를 백련에게 직접 전해 줘.','warden');}
   if(s.roadClear&&!s.roadReported){s.roadReported=true;return dialog('서린 · 직접 전한 운송 표식','윤서: 민간 통로를 열었어. 연화가 알려 준 길과 화물표를 가져왔어.\n서린: 여기 반입 계획과 일치해. 항만 보급 동선을 끊으면 본거지 위치를 좁힐 수 있어.','warden');}
  }
  if(id==='master'&&g.area==='village'){
   if(s.bossClear&&!s.murimEpilogue){s.murimEpilogue=true;return dialog('백련 · 돌아온 일상','감독관의 신병과 압수 장치는 우리가 관리하겠다. 본거지 통로도 폐쇄했다. 네 경계석은 별개로 남아 있다.\n연화: 이번 물건은 평소 길로 들어왔어요. 돌아서 올 필요가 없었대요.\n백련: 이제 앉아 식사부터 하거라. 현실의 이들에게는 네가 직접 결과를 전해 주고.','master');}
   if(s.realityReported&&!s.nineComplete){s.nineComplete=true;return dialog('제9장 완료 · 준비한 사람들','윤서: 현실의 대피와 외부 재충전 차단을 확인했습니다. 서린과 도겸이 출구를 지킵니다.\n백련: 뒤를 지키는 것은 내 몫이다. 네가 할 일을 빼앗으려고 가르친 것은 아니니. 본거지로 가거라.','master');}
   if(s.eightComplete&&!s.planDelivered){s.planDelivered=true;return dialog('백련 · 작전의 약점부터','네가 전해 준 현실 반입 기록으로 순서를 맞추겠다. 먼저 외곽 공급을 끊고 진입로를 열어라. 내부 충전분은 남지만 외부 지원과 도주는 우리가 막을 것이다.','master');}
  }
  if(id==='supply-cut'&&g.area==='supplyRidge'&&s.planDelivered){if(!s.supplyClear)return dialog('공급 장치','장치를 지키는 정예를 먼저 제압하자.');if(!s.supplyCut)s.supplyCut=true;return dialog('외부 공급 중단','공급 장치를 차단했다. 백련과 제자들이 이 자리를 유지한다. 내부 잔여 충전량은 제한되어 있다. 현실의 서린에게 준비 결과를 직접 전하자.');}
  if(id==='evacuation-route'&&g.area==='evacuationDock'&&s.supplyReported){s.evacuated=true;if(s.threatFought)s.threatClear=true;applyRoute(g);return dialog('도겸 · 대피 경로 확보','후방 통로로 민간인이 이동했어. 이 안전 구역은 유지할게. 이제 연결 시설의 핵심 위협을 맡아 줘.','hero');}
  if(id==='overseer-confront'&&g.area==='overseerHall'&&s.approachClear&&!s.bossClear){s.confronted=true;return {...dialog('흑조 감독관 · 돌아갈 길의 주인','감독관: 문 하나 여는 데 얼마나 많은 사람이 필요한지 아나? 너는 그 값을 치르지 않고 건너왔지.\n윤서: 그 값을 다른 사람 목숨으로 낸 건 너고.\n감독관: 내 편에 서라. 네가 오갈 길만은 막지 않겠다.\n윤서: 다른 사람들 길은 네 허락을 받아야 하고?\n감독관: 현실 쪽 연결이…….\n윤서: 끊고 왔어. 그쪽에서도 기다리는 사람들이 있거든.\n외부 지원·재충전·도주 차단 확인. 남은 내부 충전만으로 감독관이 검을 든다.'),portrait:'overseer',cycleCombatStart:true};}
  if(id==='overseer-charge'&&g.area==='overseerHall'&&s.confronted){const r=g.cycleRuntime;if(r?.chargeExposed>0){r.charges=0;r.chargeExposed=0;return dialog('잔여 충전 차단','노출된 내부 충전 장치를 끊었다. 외부 재충전은 이미 차단되어 있다.');}return dialog('충전 장치','감독관이 내부 충전을 쓸 때 장치가 잠시 노출된다.');}
  return null;
 }
 function applyRoute(g){const s=state(g);if(g.area==='transportRoad'&&s.routeChoice==='watcher'){const e=g.enemies?.find(e=>!e.boss&&e.hp>0);if(e){e.speed=45;e.damage=Math.min(e.damage,8);e.cycleSuppressed=true;}}if(g.area==='evacuationDock'&&s.evacuated)for(const e of g.enemies||[])if(!e.boss)e.speed=Math.min(e.speed,75);}
 function onDefeat(g,e){const s=sync(g);if(!e||e.hp>0||!g.enemies?.includes(e)||e.trial||e.residual||e.comparison||g.enemies.some(n=>n.hp>0))return false;const before=JSON.stringify(s);if(g.area==='transportRoad'&&s.transportClue){s.roadFought=true;if(s.routeChoice)s.roadClear=true;}if(g.area==='transportDock'&&s.roadReported)s.dockClear=true;if(g.area==='supplyRidge'&&s.planDelivered)s.supplyClear=true;if(g.area==='evacuationDock'&&s.supplyReported){s.threatFought=true;if(s.evacuated)s.threatClear=true;}if(g.area==='overseerApproach'&&s.nineComplete)s.approachClear=true;if(g.area==='overseerHall'&&s.confronted&&e.cycleBoss&&e.boss)s.bossClear=true;return before!==JSON.stringify(s);}
 function onEnter(g){const s=sync(g);g.cycleRuntime={charges:3,chargeExposed:0,pulse:0,suppressed:0,phase:1};applyRoute(g);if(g.area==='overseerApproach'&&g.enemies?.[0])Object.assign(g.enemies[0],{hp:180,maxHp:180,damage:12,name:'익숙한 경계병기'});if(g.area==='overseerHall')for(const e of g.enemies||[])if(e.boss)Object.assign(e,{id:'overseer',cycleBoss:true,human:true,kind:'human-overseer',name:'흑조 감독관',speed:88,range:110,cd:2});if(g.area==='overseerHall'&&s.bossClear)g.enemies=[];}
 function safeZone(g){const s=state(g);return g.area==='transportRoad'&&s.routeChoice==='device'?{x:530,y:820,radius:180,damageFactor:.6}:g.area==='evacuationDock'&&s.evacuated?{x:350,y:900,radius:175,damageFactor:.6}:null;}
 function onPlayerDefeat(g){g.cycleRuntime={charges:3,chargeExposed:0,pulse:0,suppressed:0,phase:1};return state(g);}
 function onDualLink(g){if(g.area==='overseerHall'&&g.cycleRuntime)g.cycleRuntime.suppressed=6;}
 function step(g,dt){if(g.area!=='overseerHall'||!state(g).confronted||state(g).bossClear||dt<=0)return;const r=g.cycleRuntime||(g.cycleRuntime={charges:3,chargeExposed:0,pulse:0,suppressed:0,phase:1}),e=g.enemies?.find(e=>e.cycleBoss&&e.hp>0);if(!e)return;r.suppressed=Math.max(0,r.suppressed-dt);r.chargeExposed=Math.max(0,r.chargeExposed-dt);const ratio=e.hp/e.maxHp;r.phase=ratio>.65?1:ratio>.3?2:3;e.cyclePhase=r.phase;if(r.phase===2&&r.charges>0){r.pulse+=dt;if(r.pulse>=6){r.pulse=0;r.charges--;r.chargeExposed=4;g.toast?.('감독관 내부 충전 · 장치가 4초간 노출됩니다. 외부 재충전 없음.');if(!r.suppressed)e.hp=Math.min(e.maxHp,e.hp+60);}}if(r.phase===3&&!r.supportShown){r.supportShown=true;g.toast?.('7~9장 준비 유지 · 외부 재충전·증원·도주 실패');}}
 function archiveAccess(g){const s=state(g);return s.legacyAccess||g.chapter4?.phase>=4&&s.returnReceipt&&s.recordDelivered&&s.invited;}
 function earlyObjective(g){const s=state(g);if(s.legacyAccess||s.invited||g.chapter4?.phase<4||!(g.chapter4?.phase>=4)||g.journey?.phase>2)return null;return {kind:'story',chapter:5,purpose:'귀환 확인과 환서정 초대',currentAction:!s.returnReceipt?'청운촌에서 연화의 귀환을 확인하고 운송 기록 받기':!s.recordDelivered?'백련에게 연화의 운송 기록 직접 전달':'백련과 다시 대화해 환서정 초대 수락',destination:{area:'village',id:!s.returnReceipt?'returned-yeonhwa':'master'},condition:'귀환 확인 → 기록 전달 → 초대 수락',status:'story',rewards:[]};}
 function objective(g){const s=sync(g);if(!s.regionalClosed)return earlyObjective(g);let chapter=8,purpose='운송망을 추적하고 민간 통로 확보',currentAction='청운촌 연화에게 압수 운송 기록 확인',destination={area:'village',id:'returned-yeonhwa'};const target=(area,id,action)=>{destination={area,id};currentAction=action;};if(s.transportClue&&!s.roadClear)target('transportRoad','civilian-route','민간 통로 우선 대응 선택 후 정예 제압');else if(s.roadClear&&!s.roadReported)target('city','warden','서린에게 운송 표식 직접 전달');else if(s.roadReported&&!s.dockClear)target('transportDock','exit','현실 반입 정예를 제압해 공급 차단');else if(s.dockClear&&!s.eightComplete)target('city','warden','현실 반입 차단 보고');if(s.eightComplete){chapter=9;purpose='공급 차단·대피로 확보·진입 준비';if(!s.planDelivered)target('village','master','백련에게 현실 운송 기록과 작전 순서 전달');else if(!s.supplyCut)target('supplyRidge','supply-cut','외곽 정예 제압 후 공급 장치 차단');else if(!s.supplyReported)target('city','warden','서린에게 무림 공급 차단 직접 보고');else if(!s.evacuated||!s.threatClear)target('evacuationDock','evacuation-route','민간 대피 경로 확보 후 핵심 위협 제압');else if(!s.realityReported)target('city','warden','서린과 현실 대피·차단 결과 확인');else target('village','master','백련에게 현실 작전 결과 직접 전달');}if(s.nineComplete){chapter=10;purpose='두 세계의 준비로 감독관을 막기';if(!s.approachClear)target('overseerApproach','exit','진입로 정예 제압 · 승인 서명 확보');else if(!s.confronted)target('overseerHall','overseer-confront','개방실에서 흑조 감독관과 대면');else if(!s.bossClear)target('overseerHall','overseer-confront','남은 내부 충전을 끊고 감독관을 실제 전투로 제압');else if(!s.murimEpilogue)target('village','master','백련과 구속·시설 폐쇄 확인');else if(!s.epilogue)target('city','warden','서린에게 구속 결과 직접 보고 · 후일담');else target('city','warden','첫 사이클 사건 해결 · 남은 공식 평가와 선택 성장');}return {kind:'story',chapter,purpose,currentAction,destination,condition:'현장 행동·실제 전투·직접 보고',status:s.epilogue?'complete':'story',rewards:['사건 해결 기록 · 추가 심법 포인트 없음']};}
 // These incremental scenes preserve existing chapter-five access on imported saves.
 function earlyDialogue(g,id){const s=state(g);if(id==='returned-yeonhwa'&&g.area==='village'&&g.chapter4?.rescued&&!s.returnReceipt){s.returnReceipt=true;return dialog('연화 · 귀환 확인과 기록','무사히 돌아왔어요. 저들은 사람보다 운송 상자를 먼저 챙겼어요. 이 운송 기록을 백련 어른께 전해 주세요.','yeonhwa');}if(id==='master'&&g.area==='village'&&g.chapter4?.phase>=4&&s.returnReceipt&&!s.recordDelivered){s.recordDelivered=true;return dialog('백련 · 네가 가져온 기록','연화가 무사히 돌아왔고 네가 기록을 전했구나. 폐사 장치와 닮은 원리가 있다. 다음에 말을 걸면 환서정의 기록을 함께 살펴보자.','master');}if(id==='master'&&g.area==='village'&&s.recordDelivered&&!s.invited){s.invited=true;return dialog('백련 · 환서정으로의 초대','이제 환서정에서 네 기연의 원리를 살펴보거라. 기록을 읽는 것과 몸으로 증명하는 것은 다르다.','master');}return null;}
 function sighting(g){const s=state(g);if(g.area==='ruins'&&!s.sighting){s.sighting=true;return dialog('첫 목격 · 흑조 감독관','검은 옷의 남자가 손목 표식을 드러내며 상자를 회수하라 명령한다. “우회로는 닫아. 늦어진 비용을 네가 댈 건가?” 얼굴과 장치를 확인하는 손버릇이 기억에 남는다.','overseer');}if(g.area==='station'&&!s.reunion){s.reunion=true;return dialog('현실에서의 재회','같은 얼굴, 같은 손목 표식. 감독관도 윤서의 시선을 알아본다. “너, 저쪽에서…….” 그가 사용하는 개방 장치는 소모 자원과 양쪽 준비에 의존한다. 윤서의 경계석 원리는 알지 못한다.','overseer');}return null;}
 return {initial,normalize,state,sync,validate,areaIds,specs,areas,entries,points,canEnter,interact,objective,onDefeat,onEnter,onPlayerDefeat,onDualLink,step,safeZone,archiveAccess,earlyObjective,earlyDialogue,sighting};
});
