/* First growth: hold the passage, retreat, learn one principle, return. */
(function(root,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else root.GrowthArc=api;})(globalThis,function(){
 'use strict';
 const phases=['new','defense','failed','reported','learned','returned'];
 const initial=(legacy=false)=>({version:1,phase:'new',legacy,held:0,learnedR:legacy,learnedF:legacy,returnProven:legacy,practiceR:false,practiceF:false});
 const state=g=>g.worldState?.growthArc;
 const evidence=(g,a)=>['murim','reality'].reduce((n,w)=>n+(g.worldGrowth?.[w]?.skillMastery?.[g.fate.path]?.[a]||0),0);
 const runtime=g=>g.growthArcRuntime||(g.growthArcRuntime={elapsed:0,hits:0,lessonR:false});
 const active=g=>!!state(g)&&!state(g).legacy;
 function validate(g){let s=state(g);if(!s){s=initial(!!(g.fate.path||g.revision.inherited.length));if(!s.legacy&&g.fate.stage>0)s.phase='reported';g.worldState.growthArc=s;}s.practiceR??=false;s.practiceF??=false;if(typeof s.practiceR!=='boolean'||typeof s.practiceF!=='boolean'||s.practiceF&&!s.learnedR||s.practiceR&&(!s.learnedR||evidence(g,'signature1')<1)||s.practiceF&&(!s.learnedF||evidence(g,'signature2')<1))throw Error('후속 성장 실전 증거 오류');if(s.version!==1||!phases.includes(s.phase)||!['legacy','learnedR','learnedF','returnProven'].every(k=>typeof s[k]==='boolean')||!Number.isInteger(s.held)||s.held<0||s.held>100||s.learnedF&&!s.learnedR)throw Error('첫 성장 기록 오류');
  if(!g.fate.ordinaryRoute&&!s.legacy&&(s.learnedR&&!s.practiceR&&g.chapter4.phase<4||s.learnedF&&!s.practiceF&&(g.laterStory?.seven||0)<4||['defense','failed'].includes(s.phase)&&g.fate.stage!==0||s.phase==='reported'&&![1,2].includes(g.fate.stage)||s.phase==='learned'&&g.fate.stage<3||s.phase==='returned'&&(!s.returnProven||g.fate.stage<4)||s.returnProven&&g.fate.stage<4))throw Error('첫 성장 진행과 이야기 증거가 일치하지 않습니다.');
 }
 function gate(g,a,k){if(!k||!active(g)||!['signature2','ultimate'].includes(a))return k;const s=state(g),practice=g.area==='sanctum'&&(a==='signature2'&&runtime(g).lessonR||a==='ultimate'&&runtime(g).lessonF),locked=a==='signature2'?!s.learnedR&&!practice:!s.learnedF&&!practice;return locked?{...k,locked:true,description:a==='signature2'?'핵심 기술의 실전 증명 후 청운촌 선택 수련에서 후속 운용을 체득하세요.':'후속 연계의 실전 증명 후 청운촌 선택 수련에서 오의를 체득하세요.'}:k;}
 function defense(g){return active(g)&&state(g).phase==='defense'&&g.area==='rift';}
 function onEnter(g){if(active(g)&&g.area==='heart'){const boss=g.enemies.find(e=>e.boss);if(boss){boss.passagePressure=true;boss.name='경계 포식자 · 통로 압력';}}if(!defense(g))return;g.growthArcRuntime={elapsed:0,hits:0,lessonR:false};g.activated=[];g.enemies=g.enemies.filter(e=>!e.boss).slice(0,3);for(const e of g.enemies)Object.assign(e,{hp:80,maxHp:80,damage:12,passageDefense:true,passagePressure:true});g.emit('dialog',{title:'재조사 · 귀환 통로 방어',text:'서린: 지난번 위협은 끝났어. 이번 파형은 통로 자체를 노리고 있어. 회수 인원이 빠져나갈 때까지 시간을 벌어 줘.\n\n최대 12초 동안 대응하세요. 이전 임무의 승리는 유지됩니다. 적을 제압하거나 회피하면 철수 보고에 남습니다.',portrait:'warden'});}
 function fail(g){const s=state(g),r=runtime(g);s.phase='failed';s.held=Math.min(100,r.hits);g.enter('city');g.player.hp=g.stats().hp;g.player.mp=g.stats().mp;g.emit('dialog',{title:'통로 붕괴 · 긴급 철수',text:'윤서: 적은 막았는데… 통로 안쪽의 압력을 붙잡을 수가 없어.\n서린: 회수 인원은 나왔어. 지금 돌아와!\n\n통로 방어 실패. '+(s.held?'네 대응 '+s.held+'회 덕분에 회수 시간을 확보했다.':'회수팀은 비상 신호를 따라 철수했다.')+'\n서린에게 보고한 뒤, 이 압력을 다룰 호흡을 백련과 찾으세요. 금화와 경험치는 잃지 않습니다.',portrait:'warden'});}
 function step(g,dt){if(!active(g))return;const s=state(g);if(defense(g)){runtime(g).elapsed+=dt;if(runtime(g).elapsed>=12||runtime(g).elapsed>=3&&g.enemies.every(e=>e.hp<=0)||g.player.hp<=0)fail(g);}}

 function interact(g,id){if(!active(g)||g.progress<12)return null;const s=state(g);
  if(id==='warden'&&g.fate.stage===0){if(s.phase==='new'){s.phase='defense';return {type:'dialog',title:'제3장 · 지킬 수 없었던 통로',text:'서린: 항만 임무는 끝났어. 하지만 익숙한 균열에서 새로운 파형이 잡혔어. 이번에는 귀환 통로를 향하고 있어.\n현실 던전 입구에서 균열 재조사에 들어가 회수 인원이 나올 시간을 벌어 줘.',portrait:'warden'};}if(s.phase==='defense')return {type:'dialog',title:'서린 · 통로 재조사',text:'현실 던전 입구에서 균열을 선택해. 공격은 네가 아는 것과 비슷하지만, 통로에 가해지는 압력은 달라.',portrait:'warden'};if(s.phase==='failed'){s.phase='reported';g.fate.stage=1;return {type:'dialog',title:'서린 · 버텨낸 시간',text:'서린: 네가 막아 준 덕분에 돌아온 사람들이 있어. 하지만 통로의 압력은 기존 검격으로 풀리지 않았어.\n윤서: 그 순간 검 안쪽에서 다른 호흡이 느껴졌어. 백련 사부에게 직접 물어볼게.\n\n청운촌의 백련에게 실패한 순간을 전하세요.',portrait:'warden'};}}
  if(id==='warden'&&g.fate.stage===3){g.fate.stage=4;return {type:'dialog',title:'서린 · 같은 압력, 달라진 호흡',text:'서린: 지난번 무너진 통로와 같은 파형이 경계의 심장에서 잡혔어. 이번에는 네 호흡으로 풀어 보자.\n윤서: 적을 베기만 하면 끝나는 게 아니었지. 공격 예고를 보고 Q로 압력을 다룰게.\n\n현실 던전 입구 → 경계의 심장. 호위와 두 매듭을 정리한 뒤, 포식자의 통로 압력에 Q로 실제 대응하세요. 기본 검격과 K/L로 마무리할 수 있습니다.',portrait:'warden'};}
  if(id==='master'&&g.fate.stage===1&&!g.fate.path){g.fate.stage=2;return {type:'dialog',title:'백련 · 무너진 곳에서 남은 호흡',text:'백련: 검으로 적을 쓰러뜨리는 것과 압력을 흘려 보내는 것은 다르다. 네가 버틴 순간을 다시 떠올려라.\n화산 전수자에게 검로와 거리 대응을 재수련하거라. 무명 비경의 흔적 탐색은 별도의 선택이다.\n처음부터 모든 기술을 가져오는 것은 아니다.',portrait:'master'};}
  if(id==='opportunity-training'&&g.fate.path){const next=!s.learnedR?'signature2':!s.learnedF?'ultimate':null,need=next==='signature2'?'signature1':'signature2';if(!next)return {type:'dialog',title:'백련 · 이어진 비전',text:'후속 연계와 오의를 체득했다. 남은 개별 성취는 실전에서 쌓아라.',portrait:'master'};if(evidence(g,need)<1)return {type:'dialog',title:'백련 · 먼저 네 실전으로',text:next==='signature2'?'체득한 핵심 기술로 실제 위협에 대응한 뒤 돌아오거라. 임시 시험은 실전 증거가 아니다.':'배운 후속 연계를 실제 위협에 적중시킨 뒤 돌아오거라. 본편을 다시 완료할 필요는 없다.',portrait:'master'};g.enter('sanctum');runtime(g).lessonR=next==='signature2';g.beginTrial(g.fate.path);runtime(g).lessonR=next==='signature2';runtime(g).lessonF=next==='ultimate';runtime(g).practiceFollow=false;for(const e of g.enemies)e.hp=e.maxHp=Math.max(1500,e.maxHp);if(next==='ultimate')g.fate.focus=100;return {type:'dialog',title:'백련 · 선택 비전 수련',text:next==='signature2'?'핵심 기술로 위협에 대응하고 후속 연계를 적중시키세요.':'핵심 대응 → 후속 연계 적중 → 오의를 시험 상대에게 적중시키세요. 장 진행과 별도로 체득합니다.',portrait:'master'};}
  return null;
 }
 function objective(g){if(!active(g)||g.progress<12)return null;const s=state(g),point=id=>g.points().find(p=>p.id===id);let title,text,target;
  if(defense(g)){title='통로 방어 · '+Math.max(0,Math.ceil(12-runtime(g).elapsed))+'초';text='공격에 대응해 회수 시간을 벌어 주세요. 통로 압력은 계속 커지고 있습니다.';target=g.enemies.find(e=>e.hp>0)||point('exit');}
  else if(g.fate.stage===0){title='제3장 · 통로 재조사';text=s.phase==='failed'?'서린에게 철수 결과를 보고하세요.':s.phase==='defense'?'현실 던전 입구에서 균열 재조사에 진입하세요.':'서린과 대화해 새 통로 위협을 확인하세요.';target=point(s.phase==='defense'?'dungeon-entry':'warden')||point('portal');}
  else if(runtime(g).lessonR&&g.area==='sanctum'){title='후속 운용 실습 · R';text='Q의 준비 효과를 만든 뒤 R을 적에게 적중시키세요.';target=g.enemies.find(e=>e.hp>0)||point('exit');}
  else if(!g.fate.ordinaryRoute&&g.area==='heart'&&!s.returnProven&&g.fate.stage===4){title='달라진 나 · 첫 호흡 재현';text='공격 예고에 Q로 실제 대응하세요. 이후 기본 검격과 K/L로 전장을 정리하세요. R과 F는 아직 배우지 않았습니다.';const guard=g.enemies.find(e=>e.hp>0&&!e.boss),seal=g.points().find(p=>p.kind==='seal'&&!g.activated.includes(p.id)),boss=g.enemies.find(e=>e.hp>0&&e.boss);target=guard?{...guard,label:guard.name,kind:'enemy'}:seal||(boss?{...boss,label:boss.name,kind:'enemy'}:point('exit'));text=guard?'기본 검격과 K/L로 호위를 정리하세요. 포식자는 두 매듭이 풀리면 압력을 드러냅니다.':seal?'균열 매듭에 접근해 E로 해제하세요. 포식자의 압력은 이후 Q로 대응합니다.':text;}

  return target?{priority:true,title,text,target,chapter:g.chapter4?.phase>=4?5:3}:null;
 }
 function onEffect(g,e){if(!active(g)||g.area!=='heart'||!e.target?.passagePressure||e.action!=='signature1'||!['absorb','evade','suppress'].includes(e.kind))return;const s=state(g);if(!s.returnProven){s.returnProven=true;s.phase='returned';g.toast('지난번 다룰 수 없던 압력에 대응했다. 내 호흡은 현실에서도 이어진다.');}}
 function afterAction(g,a,before,prepared){if(!active(g)||g.area!=='sanctum')return;const r=runtime(g),hit=g.enemies.some((e,i)=>e.hp<(before[i]??e.hp));if(a==='signature2'&&prepared&&hit){if(r.lessonR){state(g).learnedR=true;state(g).practiceR=true;r.lessonR=false;g.toast('후속 연계 체득 · 실전 이후의 선택 수련');}if(r.lessonF)r.practiceFollow=true;}if(a==='ultimate'&&r.lessonF&&r.practiceFollow&&hit){state(g).learnedF=true;state(g).practiceF=true;r.lessonF=false;g.toast('오의 체득 · 복합 운용의 완성');}}
 // Profiles stay immutable: only new-growth encounters receive this adjustment.
 function balance(g){if(!active(g))return;const factors={heart:[.85,.85],returnPass:[.85,.9],returnDock:[.85,.9]};const f=factors[g.area];if(!f)return;for(const e of g.enemies){if(e.growthAdjusted)continue;e.growthAdjusted=true;e.hp=e.maxHp=Math.round(e.maxHp*f[0]);e.damage=Math.round(e.damage*f[1]);}}
 return {initial,state,evidence,runtime,active,validate,gate,defense,onEnter,fail,step,interact,objective,onEffect,afterAction,balance};
});
