(function(root){'use strict';root.GrowthScreen={create({game,show,node,refresh,commit,close,character,skills,resonance}){
 const compare=(title,rows)=>{const box=node('section','growth-stat-table');box.append(node('h4','',title));for(const [label,before,after,unit='']of rows){const row=node('div','growth-stat-row');row.append(node('span','',label),node('strong','',before+unit),node('span','value-arrow','→'),node('strong','',after+unit));box.append(row);}return box;};
 let tab='passive',world=null,tree='flow',selected='F0',detail=false,draft=null,confirming=false;
 const labels={murim:'무림',reality:'현실'},trees={flow:'유수심법',focus:'집중심법'};
 const btn=(label,run,cls='secondary',disabled=false)=>{const b=node('button',cls,label);b.type='button';b.disabled=disabled;b.onclick=run;return b;};
 function open(section,keep=false){const g=game();if(!keep){world=section==='murim'?'murim':WorldGrowth.worldOf(g);detail=false;draft=null;confirming=false;if(section==='realm'||section==='hunter')tab=section;else tab='passive';tree=g.worldGrowth[world].mode;selected=tree==='flow'?'F1':'C1';}render();}
 function render(){if(tab==='passive'&&world==='reality'&&resonance)return resonance();if(tab!=='passive')world=tab==='realm'?'murim':'reality';const g=game(),actual=WorldGrowth.worldOf(g),body=node('section','growth-workspace'),heading=node('div','growth-context'),tabs=node('nav','growth-sections'),layout=node('div','growth-layout'),sidebar=node('nav','growth-list'),content=node('article','growth-detail');body.dataset.world=world;body.dataset.detail=String(detail);tabs.setAttribute('aria-label','성장 분야');if(resonance)tabs.append(btn('경계공명',resonance));sidebar.setAttribute('aria-label','성장 선택');
  heading.append(node('span','world-tag',labels[world]+' 적용'),node('span','',actual===world?'현재 세계의 성장':'다른 세계 정보 열람 중'),btn(labels[world==='murim'?'reality':'murim']+' 정보 보기',()=>{world=world==='murim'?'reality':'murim';draft=null;confirming=false;render();}));if(tab!=='passive')heading.lastChild.remove();body.append(heading);
  for(const [id,label]of [['passive','심법'],['realm','경지 돌파'],['hunter','헌터 승급']]){if(id==='realm'&&!(g.revision.inherited.length&&g.journey.worlds.length>=2))continue;if(id==='hunter'&&!g.v12ChapterCompleted(3))continue;const b=btn(label,()=>{tab=id;detail=false;draft=null;confirming=false;render();});b.setAttribute('aria-pressed',String(tab===id));tabs.append(b);}body.append(tabs);
  content.append(btn('목록으로',()=>{detail=false;render();},'secondary growth-back'));
  body.dataset.section=tab;let action=null,reason='',center=null,actionHint='';
  if(tab==='passive'){
   const model=PassiveGrowth.describe(g,world),current=g.worldGrowth[world].mode,canEdit=world==='murim'&&g.area==='village'&&!g.trial&&!g.enemies?.some(e=>e.hp>0);if(g.training>=1){
    body.append(node('p','growth-budget','남은 심법 포인트 '+model.available+' / 총 '+model.total+' · 사용 '+model.spent));
    const guide=node('section','growth-point-guide'),copy=node('div');guide.setAttribute('aria-label','심법 포인트 배분 안내');
    copy.append(node('strong','',canEdit?'포인트 배분 가능 · 무림 청운촌':world==='reality'?'현실 적용 정보 · 배분은 무림에서':actual==='reality'?'현재 현실 · 무림 심법 열람 중':'현재는 심법 정보 열람 중'),node('p','',canEdit?'노드를 선택한 뒤 하단 「1포인트 배분」을 누르세요.':'배분·재분배는 무림 청운촌의 안전한 상태에서 가능합니다. 현실 성장은 경계공명에서 각인으로 따로 강화합니다.'),node('small','',model.spent?'재분배하면 유수·집중에 사용한 '+model.spent+'포인트를 돌려받아 다시 배분할 수 있습니다.':'사용 0포인트 · 아직 재분배할 포인트가 없습니다.'));
    guide.append(copy,btn('포인트 재분배',()=>{confirming=confirming==='refund'?false:'refund';render();},'secondary growth-reset',!canEdit||!model.spent));body.append(guide);
    if(confirming==='refund'){const panel=node('section','growth-refund-confirm');panel.setAttribute('role','region');panel.setAttribute('aria-label','심법 포인트 재분배 확인');panel.append(node('strong','',model.spent+'포인트를 모두 돌려받을까요?'),node('p','','유수·집중에 배분한 포인트를 모두 돌려받습니다. 이야기에서 체득한 기본·심화 노드는 유지됩니다.'),btn(model.spent+'포인트 돌려받기',()=>{commit(g=>PassiveGrowth.reset(g));confirming=false;render();},'primary'),btn('취소',()=>{confirming=false;render();}));body.append(panel);}
   }
   for(const id of ['flow','focus']){if(id==='focus'&&g.training<2)continue;const b=btn(trees[id]+(current===id?' · 운용 중':''),()=>{tree=id;selected=id==='flow'?'F1':'C1';detail=false;render();});b.setAttribute('aria-pressed',String(tree===id));sidebar.append(b);}
   if(g.training<1){body.dataset.detail='true';content.append(node('h3','','첫 운기 체득'),node('p','','청운촌 백련에게 기본기를 배우면 유수심법과 첫 2포인트가 열립니다.'));content.append(btn('무공',skills),btn('캐릭터',()=>character.open()));layout.append(content);body.append(layout);show('성장 · 첫 운기',body,[{label:'닫기',secondary:true}],'system');return;}const ledger=node('details'),summary=node('summary','','포인트를 얻은 이야기');ledger.append(summary);const earned=PassiveGrowth.state(g).ledger,names={training:'백련의 기본기',realm:'첫 이류 돌파',chapter4:'연화 귀환',chapter5:'두 세계 진화 증명',six:'원리 체득',seven:'지역망 폐쇄'};for(const [id,value]of Object.entries(earned))ledger.append(node('p','',(names[id]||id)+' · '+value+'P'));body.append(ledger);const nodes=model.nodes.filter(n=>n.id.startsWith(tree==='flow'?'F':'C')&&(!['F4','C5'].includes(n.id)||g.laterStory?.dualBreath)),list=node('div','passive-tree');list.setAttribute('aria-label',trees[tree]+' 노드');
   center=node('section','growth-tree-panel');center.append(node('p','eyebrow','PASSIVE · '+(tree==='flow'?'01':'02')),node('h3','',trees[tree]),node('p','tree-caption',tree==='flow'?'기술 사이의 회복과 지속전':'준비된 첫 일격과 정확한 대응'));
   const positions=tree==='flow'?{F0:[1,0],F1:[0,1],F2:[2,1],F3:[0,2],F5:[2,2],F4:[1,3]}:{C0:[1,0],C1:[0,1],C2:[2,1],C3:[0,2],C4:[2,2],C5:[1,3]},glyphs={F0:'◉',F1:'◇',F2:'≋',F3:'◈',F4:'✦',F5:'⬡',C0:'◎',C1:'◇',C2:'✧',C3:'◈',C4:'⬡',C5:'✦'};
   const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 300 440');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('class','tree-connections');svg.setAttribute('aria-hidden','true');
   for(const n of nodes){if(n.prerequisite&&positions[n.prerequisite]){const a=positions[n.prerequisite],b=positions[n.id],line=document.createElementNS(svg.namespaceURI,'path');line.setAttribute('d',`M ${50+a[0]*100} ${52+a[1]*110} L ${50+b[0]*100} ${52+b[1]*110}`);line.dataset.from=n.prerequisite;line.dataset.to=n.id;line.classList.toggle('learned',!!nodes.find(x=>x.id===n.prerequisite)?.level);svg.append(line);}}list.dataset.deep=String(nodes.some(n=>n.id==='F4'||n.id==='C5'));if(list.dataset.deep==='false')svg.setAttribute('viewBox','0 0 300 330');list.append(svg);
   for(const n of nodes){const away=n.reason==='무림 안전 거점에서 변경 가능';const b=btn('',()=>{selected=n.id;detail=true;render();requestAnimationFrame(()=>document.querySelector('.growth-detail h3')?.focus());},'secondary passive-node');b.dataset.node=n.id;b.dataset.status=away?'preview':n.status;b.style.gridColumn=positions[n.id][0]+1;b.style.gridRow=positions[n.id][1]+1;b.setAttribute('aria-pressed',String(selected===n.id));b.setAttribute('aria-label',n.name+' · '+n.level+'/'+n.max);const icon=node('span','growth-glyph',glyphs[n.id]);icon.setAttribute('aria-hidden','true');b.append(icon,node('span','node-name',n.name),node('span','node-level',n.level+'/'+n.max+(away?' · 청운촌에서 배분':n.status==='locked'?' · 잠김':n.free?' · 체득':'')));list.append(b);}center.append(list,node('p','tree-legend','연결선: 선행 노드 1단계 · 하위 분기는 이류부터'));
   const n=nodes.find(n=>n.id===selected)||nodes[0];content.append(node('p','eyebrow',trees[tree]),node('h3','',n.name),node('p','effect-description',n.description||n.effect||n.name+'의 운용 효과를 확인하고 강화합니다.'),node('span','world-tag',labels[world]+' · '+(current===tree?'운용 중':'선택한 심법 미리보기')));
   content.querySelector('h3').tabIndex=-1;const values=node('div','growth-values');values.append(node('div','', world==='reality'?'귀환 적용':'현재'),node('strong','',String(world==='reality'?(n.appliedCurrent??n.current):n.current)),node('span','value-arrow','→'),node('div','',world==='reality'?'다음 정상 귀환':'다음'),node('strong','',String(world==='reality'?n.current:(n.next??'완료'))));content.append(values,node('p','growth-condition',n.reason||(n.free?'이야기에서 체득하는 무료 노드입니다.':'필요 1포인트 · 보유 '+model.available+'포인트')));
   reason=actual!=='murim'||g.area!=='village'?'강화와 재배분은 무림 청운촌에서 할 수 있습니다.':world!=='murim'?'현실은 다음 정상 귀환에 무림의 학습 기록이 반영됩니다.':n.reason||'';
   const canUpgrade=!n.free&&n.level<n.max&&model.available>0&&!n.reason&&world==='murim'&&g.area==='village';
   actionHint=n.name+' · '+n.current+(canUpgrade?' → '+n.next:'');action=btn(n.free?'이야기 체득 노드':'1포인트 배분',()=>{commit(g=>PassiveGrowth.upgrade(g,n.id));render();},'primary',!canUpgrade);
   content.append(btn(current===tree?'현재 운용 중':trees[tree]+' 운용하기',()=>{commit(g=>g.setBreath(tree));render();},'secondary',current===tree||actual!==world||!['village','city'].includes(g.area)||g.training<(tree==='flow'?1:2)));
   if(g.laterStory?.dualBreath)content.append(node('h4','','심법 심화 · 연계 강화'),node('p','','실제 대응과 타격을 연결하면 대상의 재생을 6초 억제합니다.'),btn(g.dualAssist?'연계 보조 8초 · 켜짐':'연계 보조 8초 · 꺼짐',()=>{commit(g=>{g.dualAssist=!g.dualAssist;});render();}));
  }else{
   const kind=tab,m=Advancement.describe(g,kind),target=kind==='realm'?'murim':'reality';world=target;body.dataset.world=world;heading.firstChild.textContent=labels[target]+' 적용';
   detail=true;body.dataset.detail='true';const names=kind==='realm'?['삼류','이류','일류','절정','초절정']:['E급','D급','C급','B급','A급','S급'];
   const rail=node('ol','growth-progression');rail.setAttribute('aria-label',kind==='realm'?'경지 진행':'공식 등급 진행');for(const [i,name]of names.entries()){const item=node('li','growth-stage'+(m.stage===i?' current':i<m.stage?' completed':''),name);if(i===m.stage)item.setAttribute('aria-current','step');rail.append(item);}body.append(rail);
   sidebar.append(node('p','eyebrow',kind==='realm'?'현재 무림 경지':'공식 헌터 등급'),node('strong','growth-rank',names[m.stage]),node('span','world-tag',labels[target]+' 적용'),node('p','',kind==='realm'?'시련으로 증명한 경지':'서린에게 보고한 공식 평가 결과'),node('p','growth-rank-note',kind==='realm'?'다음 한 단계의 조건과 보상을 확인하세요.':'현장 입장 자격과 공식 등급은 별개입니다.'));
   content.append(node('p','eyebrow',kind==='realm'?'시련으로 한계를 넘는 성장':'공식 평가와 실전 훈련'),node('h3','',m.name+' → '+(m.nextName||'최종 단계')),node('p','effect-description',kind==='realm'?'시련을 증명하고 돌파를 확정하면 무림의 몸이 강해집니다.':'평가를 통과해 서린에게 보고한 뒤, 현실에서 훈련 방향을 선택합니다.'));
   const requirements=node('ul','growth-requirements');for(const r of m.requirements||[])requirements.append(node('li',r.met?'met':'', (r.met?'충족 · ':'필요 · ')+r.text));
   const stats=WorldGrowth.stats(g,target);if(m.nextName&&m.reward){content.append(compare('다음 '+(kind==='realm'?'돌파':'승급')+' · 기본 능력',[['체력',stats.hp,stats.hp+m.reward.hp],['자원',stats.mp,stats.mp+m.reward.mp],['공격',stats.attack,stats.attack+m.reward.attack]]),node('p','growth-condition','추가 특화 '+m.reward.points+'포인트'+(kind==='hunter'?' · 공식 승급은 기본 능력치를 올리지 않습니다.':'')));}
   content.append(requirements);draft||={...(m.allocation||{})};const fields=kind==='realm'?[['attack','공격',1.5],['hp','생존',8],['mp','내력',5]]:[['attack','공격',1.5],['hp','생존',8],['speed','기동',1]];const total=m.points?.total||0,spent=()=>Object.values(draft).reduce((a,b)=>a+b,0);
   content.append(node('h4','','선택 성장 · '+total+'포인트 중 '+(total-spent())+' 미배분'));const allocation=node('div','growth-allocation');for(const [key,label,mult]of fields){draft[key]??=0;const row=node('div','allocation-card');row.append(node('strong','',label),node('output','',String(draft[key])),btn('−',()=>{draft[key]--;confirming=false;render();},'secondary',draft[key]<=0),btn('+',()=>{draft[key]++;confirming=false;render();},'secondary',spent()>=total),node('p','',`적용 시 +${draft[key]*mult}${key==='speed'?'%':''}`));const controls=row.querySelectorAll('button');controls[0].setAttribute('aria-label',label+' 포인트 감소');controls[1].setAttribute('aria-label',label+' 포인트 추가');row.dataset.selected=String(draft[key]>0);allocation.append(row);}content.append(allocation);
   const num=v=>Math.round(v*100)/100,rows=fields.map(([key,label,mult])=>key==='speed'?[label,(m.allocation[key]||0)*mult,draft[key]*mult,'%']:[label,stats[key],num(stats[key]+(draft[key]-(m.allocation[key]||0))*mult)]);content.append(compare('배분 미리보기 · 현재 → 적용 후',rows));
   const changed=fields.some(([key])=>draft[key]!==m.allocation[key]);content.append(btn('배분 적용',()=>{confirming='allocation';render();},'secondary',actual!==target||g.area!==(kind==='realm'?'village':'city')||!total||!changed));
   if(confirming==='allocation'){const panel=node('section','growth-confirm');panel.setAttribute('role','region');panel.setAttribute('aria-label','배분 최종 확인');panel.append(node('h4','','배분을 적용할까요?'),node('p','',labels[target]+' 전용 · '+spent()+' / '+total+'포인트 사용 · '+fields.map(([key,label])=>label+' '+draft[key]).join(' / ')),btn('배분 확정 · 적용',()=>{if(commit(g=>Advancement.allocate(g,kind,{...draft})))draft=null;confirming=false;render();},'primary'),btn('선택으로 돌아가기',()=>{confirming=false;render();}));content.append(panel);}
   if(confirming==='advance')content.append(node('p','growth-condition','위 보상으로 돌파를 확정합니다. 닫으면 취소됩니다.'));reason=m.reason||'';action=btn(m.canConfirm?(confirming==='advance'?'돌파 확정 · 보상 적용':'돌파 결과 확인'):m.status==='passed'?'서린에게 결과 보고':'시련 / 평가 시작',()=>{if(m.canConfirm){if(confirming!=='advance'){confirming='advance';render();return;}commit(g=>Advancement.confirm(g,kind));confirming=false;render();}else if(Advancement.start(g,kind)){close();refresh();}},'primary',!m.canConfirm&&!m.canStart);
  }
  layout.append(sidebar);if(center)layout.append(center);layout.append(content);body.append(layout);if(reason)body.append(node('p','growth-execution-reason',reason));const footer=node('div','growth-footer');if(actionHint){const hint=node('p','growth-action-hint',actionHint);hint.id='growthActionHint';footer.append(hint);action?.setAttribute('aria-describedby',hint.id);}if(action)footer.append(action);const skillButton=btn('무공',skills),unread=g.unreadNews('skills').length;if(unread){skillButton.classList.add('has-news');skillButton.setAttribute('aria-label','무공 · 새 소식 '+unread+'개');skillButton.append(node('span','news-dot'));}footer.append(btn('캐릭터',()=>character.open()),skillButton);body.append(footer);
  show('성장 · '+({passive:'심법',realm:'경지 돌파',hunter:'헌터 승급'}[tab]),body,[{label:'닫기',secondary:true}],'system','선택한 효과와 적용 세계를 확인하세요');
 }
 return {open};
}};})(globalThis);
