/* The new, deliberately bounded first-return journey; old saves never opt in implicitly. */
(function(root,f){const api=f(typeof module==='object'&&module.exports?require('./murim-growth.js'):root.MurimGrowth);if(typeof module==='object'&&module.exports)module.exports=api;else root.MurimJourney=api;})(globalThis,function(Growth){
 'use strict';
 const roadNames=['추적자의 죽림','갈림길 초소','무너진 잔도','물안개 계곡','버려진 역참','산사의 돌계단','매복의 협곡','운무 숲길','화산 외곽 관문','화산 산문'];
 const events=[
  '백련을 쫓던 자들이 길을 막았다. 정체를 단정할 증거는 아직 없다.','부러진 수레 옆에서 남궁의 여행자를 만났다. 칼끝의 거리를 읽는 법을 나눌 수 있다.','백련을 부축할 넓은 길을 확보했다. 천흔 쪽으로 되돌아가기에는 아직 위험하다.','무당의 여행자가 기운을 아끼는 호흡을 제안했다. 야영지에서 이야기를 들을 수 있다.','역참에서 추적자들의 보급 흔적을 발견했다. 백련은 마교 활동과 천흔의 관계를 조사 중이었다고 밝힌다.','아미의 여행자가 부상자를 지키는 발걸음을 보여 준다. 야영지에서 배울 수 있다.','협곡의 매복을 돌파했다. 백련은 힘을 보태려다 부상이 깊어져 다시 검을 거둔다.','구름 너머 화산의 능선이 보인다. 돌아가기 위해 먼저 살아남을 힘을 기른다.','관문을 점거한 무리를 물리치고 화산에 구조 신호를 보냈다.','산문까지 길을 열었다. 이제 화산에서 백련의 치료를 받을 수 있다.'
 ];
 const roads=roadNames.map((name,i)=>({id:'murimRoad'+(i+1),name:(i+1)+'. '+name,index:i,chapter:1,story:events[i]}));
 const returns=[{id:'murimReturn1',name:'귀환길 1 · 천흔 옛길',index:10,chapter:2,story:'백련과 함께 천흔의 위치를 다시 확인했다. 갈라진 기운의 흔적에서 선택 수련 기회가 열린다.'},{id:'murimReturn2',name:'귀환길 2 · 검은 진영',index:11,chapter:2,story:'적대 무리의 진영을 무너뜨렸다. 천흔을 지키는 우두머리만 남았다.'},{id:'murimReturn3',name:'귀환길 3 · 천흔 수문장',index:12,chapter:2,story:'천흔을 막던 우두머리를 제압했다. 돌아갈 길이 열렸다.'}];
 const special=[{id:'murimTutorial',name:'응급 전수 · 추적자의 습격',index:-1,chapter:1},{id:'murimChance',name:'선택 기연 · 천흔의 메아리',index:9,chapter:2}];
 const locations=[...roads,...returns,...special],byId=Object.fromEntries(locations.map(x=>[x.id,x]));
 const stages=['intro','tutorial','road','treatment','choice','return','complete'];
 const state=g=>g.worldState?.murimJourney,active=g=>!!state(g),area=id=>!!byId[id];
 const point=(id,x,y,label,kind='npc',extra={})=>({id,x,y,label,kind,role:'master',...extra});
 function areas(base){return Object.fromEntries(locations.map((d)=>{const i=Math.max(0,d.index),tutorial=d.id==='murimTutorial',n=tutorial?2:3+i%3,positions=Array.from({length:n},(_,k)=>[430+k*145,760-k*110+(i%2)*20]);return [d.id,{...base.forest,name:d.name,sub:tutorial?'이동 · 기본 공격 · 회피를 익히고 백련과 탈출':d.story||'천흔의 기운을 견디는 선택 실전',chapter:d.chapter,spawn:[175,900],positions,points:[point('journey-exit',110,945,'야영지로 돌아가기','exit')],hp:tutorial?24:55+i*9,bossHp:tutorial?38:130+i*26,damage:tutorial?3:7+Math.floor(i*.65),boss:tutorial?'추적자':'murimReturn3'===d.id?'천흔 수문장':d.id==='murimChance'?'천흔의 잔향':i%2?'길목 감시자':'추적대 우두머리',mob:'정체불명의 추적자',mobKind:'bandit',bossKind:d.id==='murimReturn3'?'guardian':'chief',blocks:[{x:180+i%3*45,y:180,w:170,h:170,kind:'rock'},{x:1060,y:650-i%3*70,w:140,h:160,kind:'rock'},{x:580+i%2*100,y:160,w:190,h:130,kind:'rock'}],roads:[[[110,945],[430,760],[800,550],[1100,330]]]}];}));}
 function start(g){if(active(g)||g.progress>1||g.training>0)return false;g.worldState.murimJourney={version:1,stage:'intro',scene:0,tutorial:{move:false,attack:false,dash:false},viewed:{stats:false,skills:false},cleared:[],mentors:[],disciple:null,rare:false};g.worldState.murimGrowth=Growth.initial();g.revision.intro=7;g.revision.aid=2;g.introActive=false;g.progress=2;g.training=1;g.worldState.planB.legacy=true;g.worldState.ordinaryGrowth.transmission=false;g.enter('village');g.events=[];return true;}
 function intro(g,skip=false){const s=state(g);if(!s||s.stage!=='intro')return false;s.scene=skip?3:Math.min(3,s.scene+1);if(s.scene===3){s.stage='tutorial';g.enter('murimTutorial');}return true;}
 function canEnter(g,id){if(!active(g))return true;const s=state(g);if(id==='village')return true;if(id==='city')return s.stage==='complete';if(!area(id))return false;if(id==='murimTutorial')return s.stage==='tutorial';if(id==='murimChance')return s.stage==='return'&&s.cleared.includes('murimReturn1');const d=byId[id];if(d.chapter===1)return ['road','treatment','choice','return'].includes(s.stage)&&(d.index===0||s.cleared.includes('murimRoad'+d.index));return s.stage==='return'&&s.disciple!==null&&(d.index===10||s.cleared.includes('murimReturn'+(d.index-10)));}
 function populate(g){if(!active(g)||!area(g.area))return;const s=state(g),d=byId[g.area];for(const [i,e]of g.enemies.entries()){e.journeyEnemy=true;e.speed=g.area==='murimTutorial'?48:65+i*5;e.role=e.boss?'boss':i%3===1?'ranged':i%3===2?'heavy':'pressure';if(s.cleared.includes(g.area)){e.hp=0;e.rewarded=true;}}g.murimEntry={x:g.player.x,y:g.player.y};}
 function reward(g,e){if(!active(g)||!e.journeyEnemy)return false;e.rewarded=true;if(g.enemies.some(e=>e.hp>0)||g.area==='murimTutorial')return true;const s=state(g),id=g.area;if(s.cleared.includes(id))return true;s.cleared.push(id);Growth.grant(g,id);g.grantExperience({world:'murim',amount:id==='murimChance'?100:80+byId[id].index*12,eventId:'journey:'+id.toLowerCase()});g.gold=Math.min(999999,g.gold+20);if(id==='murimRoad10')s.stage='treatment';if(id==='murimChance')s.rare=true;g.emit('toast',{text:(byId[id].story||'천흔 호흡 체득 · 무림 공격 +4 / 기력 +10')+' · 단련석 +'+Growth.value(id).stone+' / 수련첩 +'+Growth.value(id).scroll});return true;}
 function tutorialReady(g){const s=state(g);return Object.values(s.tutorial).every(Boolean)&&!g.enemies.some(e=>e.hp>0);}
 function step(g){if(!active(g)||g.area!=='murimTutorial')return;const s=state(g),p=g.murimEntry;if(p&&Math.hypot(g.player.x-p.x,g.player.y-p.y)>24)s.tutorial.move=true;}
 function contact(g,e,c){if(active(g)&&g.area==='murimTutorial'&&e.journeyEnemy&&c?.manual&&c.action==='attack')state(g).tutorial.attack=true;}
 function action(g,a,ok,held){if(!active(g)||!ok)return;const s=state(g),l=Growth.state(g).levels;if(a==='dash'){g.player.cool.dash=Math.max(.6,1.2-l.step*.1);g.player.invuln+=l.distance*.03;if(!held&&g.area==='murimTutorial')s.tutorial.dash=true;}}
 function points(g){const s=state(g);if(!s)return null;if(area(g.area))return [point('journey-exit',110,945,s.cleared.includes(g.area)||g.area==='murimTutorial'&&tutorialReady(g)?s.stage==='treatment'?'화산으로 들어가기':'확보 완료 · 야영지로':'야영지로 철수','exit')];if(g.area==='city')return [point('journey-end',600,330,'서린 · 돌아온 몸의 변화','npc',{role:'warden'})];const out=[point('journey-master',600,320,s.stage==='treatment'?'백련 · 화산에서 치료':s.stage==='choice'?'백련 · 정식 제자 제안':'백련 · 귀환을 위한 여정'),point('journey-route',1180,860,'화산으로 가는 길 · 여정 선택','journey-route'),point('journey-rest',440,540,'운기조식 · 무료 회복','rest'),point('journey-growth',820,480,'무림 성장 · 스탯과 스킬 확인','training')];for(const [i,id,name,tree]of [[2,'sword','남궁의 여행자','검술'],[4,'inner','무당의 여행자','내공'],[6,'movement','아미의 여행자','보법']])if(s.cleared.includes('murimRoad'+i))out.push(point('mentor-'+id,950,300+out.filter(x=>x.id.startsWith('mentor-')).length*130,name+' · '+tree));if(s.stage==='return'&&s.cleared.includes('murimReturn3'))out.push(point('journey-return',250,810,'천흔 · 현실로 귀환','portal'));return out;}
 const dialog=(title,text)=>({type:'dialog',title,text,portrait:'master'});
 function choose(g,choice){const s=state(g);if(!s||s.stage!=='choice'||g.area!=='village'||!['accept','decline'].includes(choice))return false;s.disciple=choice;s.stage='return';g.training=2;g.progress=4;return true;}
 function interact(g,id){const s=state(g);if(!s)return null;if(id==='journey-route')return {type:'journey-route'};if(id==='journey-growth')return {type:'journey-growth'};if(id==='journey-rest'){g.player.hp=g.stats().hp;g.player.mp=g.stats().mp;return dialog('운기조식','백련과 함께 숨을 고른다. 생명과 기력이 모두 회복되었다.');}if(id==='journey-exit'){if(g.area==='murimTutorial'){if(!tutorialReady(g))return dialog('먼저 살아남는 법','이동, 기본 검격 명중, 회피를 각각 한 번 실행하고 추적자를 제압하세요. 예고 회피 타이밍 성공은 필수 조건이 아닙니다.');s.cleared.push('murimTutorial');s.stage='road';}const finished=byId[g.area],done=s.cleared.includes(g.area);g.enter('village');return done&&finished.story?dialog(finished.name+' · 길 확보',finished.story+'\n야영지에서 성장 재료를 사용하거나 여정 목록의 다음 목적지로 향하세요.'):{type:'travel'};}if(id?.startsWith('mentor-')){const type=id.slice(7);if(!points(g).some(p=>p.id===id))return null;if(!s.mentors.includes(type))s.mentors.push(type);return dialog(points(g).find(p=>p.id===id).label,'문파의 이름보다 네가 필요한 기초를 골라라. 이 수련 기회는 다른 배움을 포기하게 하지 않는다.\n무공/스킬에서 '+({sword:'남궁의 거리 읽기',inner:'무당의 운기',movement:'아미의 거리 조절'})[type]+'의 선행 기술과 투자 효과를 확인하세요.');}if(id==='journey-master'){if(s.stage==='intro')return {type:'journey-intro'};if(s.stage==='tutorial'){g.enter('murimTutorial');return {type:'travel'};}if(s.stage==='treatment'){s.stage='choice';return dialog('화산 · 긴 치료의 끝','화산의 의원이 백련의 내상을 다스렸다.\n백련: 네 덕분에 여기까지 왔다. 천흔은 내가 조사하던 곳이다. 돌아갈 길을 함께 열자. 그 전에, 내 정식 제자가 되겠느냐?\n다시 대화하면 수락 또는 거절할 수 있다.');}if(s.stage==='choice')return {type:'journey-choice',title:'백련 · 정식 제자 제안',text:'수락하면 이십사수매화검법의 수련이 열리고 제1초식 매화노방을 배웁니다. 거절해도 삼재검법과 선택한 성장으로 천흔에 도전할 수 있습니다.\n이 선택은 이번 여정에서 확정됩니다.'};return dialog('백련 · 돌아갈 길','천흔으로 가려면 먼저 버틸 힘이 필요하다. 무림 성장 화면에서 단련석과 수련첩을 쓰고, 여정 목록에서 다음 목적지를 고르자.');}if(id==='journey-return'&&s.cleared.includes('murimReturn3')){s.stage='complete';g.enter('city');return dialog('제2장 완료 · 돌아온 몸','서린: 돌아왔구나.\n윤서: 무림에서 배운 호흡이 아직 남아 있어.\n무림의 성취는 기존 경계공명 원칙으로 현실 성장 재료에 연결됩니다. 확정 스탯·투자가 그대로 복제되지는 않습니다.\n이번 개편의 플레이 범위는 첫 현실 귀환까지입니다.');}if(id==='journey-end')return {type:'journey-complete'};return {type:'toast',text:'현재 목표에 표시된 인물이나 출입구로 이동하세요.'};}
 function next(g){const s=state(g);return s.stage==='road'?roads.find(d=>!s.cleared.includes(d.id)):s.stage==='return'?returns.find(d=>!s.cleared.includes(d.id)):null;}
 function objective(g){const s=state(g);if(!s)return null;let id,text;const d=byId[g.area];if(d){if(g.area==='murimTutorial'){const t=s.tutorial;text=`이동 ${t.move?'✓':'필요'} · 공격 ${t.attack?'✓':'필요'} · 회피 ${t.dash?'✓':'필요'} · 추적자 ${g.enemies.filter(e=>e.hp===0).length}/${g.enemies.length}`;}else text=s.cleared.includes(g.area)?'길 확보 완료 · 출구로 돌아가 다음 여정을 선택하세요.':'남은 위협을 제압하세요. 일반 검격과 회피로도 완료할 수 있습니다.';const e=g.enemies.find(e=>e.hp>0&&!e.boss)||g.enemies.find(e=>e.hp>0);return {priority:true,chapter:d.chapter,title:d.name,text,target:e?{...e,label:e.name,kind:'enemy'}:points(g)[0]};}if(s.stage==='complete'){id='journey-end';text='첫 현실 귀환 완료 · 무림의 성장과 공명 재료를 확인하세요.';}else if(['intro','tutorial','treatment','choice'].includes(s.stage)){id='journey-master';text=s.stage==='treatment'?'백련을 화산 의원에게 데려가 치료를 마치세요.':s.stage==='choice'?'치료를 마친 백련의 제자 제안을 수락하거나 거절하세요.':'백련에게 급히 배운 검격으로 추적자에게서 벗어나세요.';}else if(s.cleared.includes('murimReturn3')){id='journey-return';text='천흔 수문장 제압 완료 · 현실로 돌아가세요.';}else {id='journey-route';text=(s.stage==='road'?`화산까지 ${s.cleared.filter(x=>/^murimRoad/.test(x)).length}/10 · `:'천흔으로 돌아가는 길 · ')+(next(g)?.name||'목표 확인');if(!s.viewed.stats||!s.viewed.skills)text+=' · 스탯/스킬 메뉴에서 성장을 확인하세요.';}return {priority:true,chapter:['return','choice','complete'].includes(s.stage)?2:1,title:s.stage==='complete'?'돌아온 몸':s.stage==='return'?'천흔으로 돌아가는 길':'백련과 화산으로',text,target:points(g).find(p=>p.id===id)};}
 function validate(g){const s=state(g);if(!s)return;if(s.version!==1||!stages.includes(s.stage)||!Number.isInteger(s.scene)||s.scene<0||s.scene>3||!['move','attack','dash'].every(k=>typeof s.tutorial?.[k]==='boolean')||!['stats','skills'].every(k=>typeof s.viewed?.[k]==='boolean')||!Array.isArray(s.cleared)||new Set(s.cleared).size!==s.cleared.length||s.cleared.some(id=>!area(id))||!Array.isArray(s.mentors)||new Set(s.mentors).size!==s.mentors.length||s.mentors.some(id=>!['sword','movement','inner'].includes(id))||![null,'accept','decline'].includes(s.disciple)||typeof s.rare!=='boolean')throw Error('무림 여정 기록 오류');for(const list of [roads,returns])for(let i=1;i<list.length;i++)if(s.cleared.includes(list[i].id)&&!s.cleared.includes(list[i-1].id))throw Error('무림 여정 선행 누락');if(stages.indexOf(s.stage)>=2&&!s.cleared.includes('murimTutorial')||stages.indexOf(s.stage)>=3&&!s.cleared.includes('murimRoad10')||stages.indexOf(s.stage)>=5&&s.disciple===null||s.stage==='complete'&&!s.cleared.includes('murimReturn3')||s.rare!==s.cleared.includes('murimChance'))throw Error('무림 여정 단계 오류');Growth.validate(g);}
 return {state,active,area,areas,start,intro,canEnter,populate,reward,step,contact,action,points,choose,interact,objective,next,validate,roads,returns,locations,tutorialReady};
});
