/* Plan B event evidence. Historical completion exempts new scenes, never invents actions. */
(function(root,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else root.PlanBStory=api;})(globalThis,function(){
 'use strict';
 const flags=['introduced','basicHit','warnedEvade','recognized','rescuedWorker','rescueReported','retrained','medicineClue','ledgerDelivered'];
 function initial(legacy=false){return Object.assign({version:1,legacy},Object.fromEntries(flags.map(k=>[k,false])));}
 function state(g){return g.worldState.planB||(g.worldState.planB=initial(true));}
 function validate(g){const s=state(g);if(s.version!==1||typeof s.legacy!=='boolean'||flags.some(k=>typeof s[k]!=='boolean'))throw Error('B안 사건 기록 오류');if(s.rescueReported&&!s.rescuedWorker||s.recognized&&(!s.introduced||!s.basicHit||!s.warnedEvade))throw Error('B안 선행 증거 누락');if(g.fate.ordinaryRoute&&(!s.retrained||g.training<2))throw Error('일반 재수련 증거 누락');}
 const dialog=(title,text,portrait='master')=>({type:'dialog',title,text,portrait});
 function points(g){if(g.introActive)return [];const p=(id,x,y,label,kind='npc')=>({id,x,y,label,kind,role:'master'});if(g.area==='village'&&g.training>=1)return [...(g.fate.path?[p('opportunity-training',1010,720,'백련 · 선택 비전 수련','training')]:[]),p('huashan',790,420,'화산 전수자 · 기본 검로'),p('basic-practice',790,520,'기본기 실습 · 타격과 회피','training')];if(g.area==='stabilization'&&g.laterStory?.six===3)return [p('six-cut',420,880,'도겸 · 공급 연결 차단','device')];if(g.area==='rift'&&g.progress>=6&&!state(g).rescuedWorker&&!state(g).legacy)return [p('recover-worker',360,880,'도겸 · 고립 작업자 귀환','npc')];return [];}
 function practice(g){if(!g.enter('forest'))return false;g.planBPractice=true;g.enemies=[{id:'basic-practice',name:'거리·회피 수련 상대',demonstration:true,residual:true,rewarded:true,kind:'bandit',x:450,y:850,r:22,hp:500,maxHp:500,damage:1,speed:50,cd:1,wind:0,windMax:1,range:100,tx:400,ty:850,flash:0,attacks:0}];Object.assign(g.player,{x:380,y:850,hp:g.stats().hp,mp:g.stats().mp});return true;}
 function interact(g,id){const s=state(g);
  if(id==='basic-practice'){practice(g);return dialog('백련 · 기본기 실습','수련 상대에게 검격을 명중시키고, 붉은 공격 예고 안에서 회피해 타격을 피하거라. 보상 없는 연습이며 끝나면 출구로 돌아오면 된다.');}
  if(id==='huashan'){
   s.introduced=true;g.worldState.ordinaryGrowth.transmission=true;
   if(g.fate.stage>=2&&g.progress>=12){s.retrained=true;if(!g.fate.path)g.fate.ordinaryRoute=true;g.fate.stage=Math.max(3,g.fate.stage);return dialog('화산 전수자 · 다시 지킬 수 있는 길','적을 쫓는 검과 돌아올 길을 지키는 검을 구분해라. 호위를 제압하고 두 매듭을 풀면 압력의 근원에 닿는다. 기본 검로·회피·장치로도 해결할 수 있다. 현실의 서린에게 준비를 전해라. 기연 탐색은 별도 선택이다.');}
   if(g.progress>=3&&s.basicHit&&s.warnedEvade){s.recognized=true;return dialog('화산 전수자 · 실전 인정','죽림의 길과 네 기본기를 확인했다. 제한 전수로 매화노방과 매화접무의 검로를 수련해 보아라. 문파 가입과 전수권은 별개다. 백련에게 길을 열었다고 전해라.');}
   return dialog('화산 전수자 · 문밖에서 시작하는 검','백련은 네 생존과 판단을 가르치는 독립 스승이다. 나는 화산의 검로를 전한다. 죽림에서 유효 검격과 예고 회피를 보여라. 부족한 동작은 옆 실습에서 보충할 수 있다. 기본 검로는 1~9성, 매화검법은 초식별 성취로 기록한다.');
  }
  if(id==='master'&&g.progress===3&&!s.legacy&&!s.recognized)return dialog('백련 · 승리는 남는다','길을 연 승리는 그대로다. 화산 전수자에게 검격과 예고 회피를 확인받거라. 부족한 동작만 기본기 실습에서 보충하면 된다.');
  if(id==='recover-worker'){if(g.enemies.some(e=>e.hp>0))return dialog('도겸 · 아직 남은 위협','위협을 정리하면 작업자를 데리고 나가겠다.','hunter');s.rescuedWorker=true;return dialog('도겸 · 작업자 귀환','인원 확인 끝. 돌아갈 길이 열렸어. 서린에게 구조 결과를 직접 전해 줘.','hunter');}
  if(id==='warden'&&g.progress===6&&!s.legacy){if(!s.rescuedWorker)return dialog('서린 · 사람까지 돌아와야 해','외곽의 도겸에게 작업자 귀환을 확인해 줘. 이미 제압한 적을 다시 쓰러뜨릴 필요는 없어.','warden');s.rescueReported=true;}
  if(id==='warden'&&g.fate.stage===3&&s.retrained){g.fate.stage=4;return dialog('서린 · 재도전 준비 확인','네가 가져온 훈련 결과와 도겸의 관측을 맞췄어. 경계의 심장에서 호위와 두 매듭을 정리하고 압력의 근원을 제압해 줘. 일반 검격·회피도 유효하고, 배운 특별한 힘은 추가 해법이야.','warden');}
  if(id==='warden'&&g.fate.stage===5&&!g.fate.path){g.fate.stage=6;g.gold=Math.min(999999,g.gold+160);return dialog('제3장 완료 · 다시 지킨 통로','도겸: 통로가 안정됐고 회수 인원도 돌아왔어.\n서린: 일반 수련과 현장 장치로 길을 지켰구나. 기연을 얻었는지와 상관없이 네 성과야.\n금화 +160 · 초동 대응 기록','warden');}
  if(id==='shop'&&g.area==='village'&&g.fate.stage>=6&&g.chapter4.phase<2&&!s.medicineClue){s.medicineClue=true;g.chapter4.phase=Math.max(1,g.chapter4.phase);return dialog('청운 약방 · 오지 않은 상행','약을 싣고 올 사람이 오지 않았어요. 연화 일행이 청운 귀환로로 들어갔다는 연락이 마지막이에요. 길을 확인해 주겠어요?','hero');}
  if(id==='warden'&&g.chapter4.phase===0&&g.fate.stage>=6&&!s.legacy){return dialog('서린 · 서로 모르는 현장','부두의 신호는 조사 중이야. 그쪽에서 확인한 일이 있으면 직접 전해 줘. 청운촌 약방에도 돌아온 소식을 알려 줘.','warden');}
  if(id==='warden'&&g.chapter4.phase===4&&g.journey.phase<3&&g.worldState.cycleOne?.returnReceipt&&!s.ledgerDelivered){s.ledgerDelivered=true;g.worldState.cycleOne.recordDelivered=true;g.worldState.cycleOne.invited=true;g.journey.phase=3;return dialog('서린 · 같은 표식, 다른 장부','윤서가 가져온 연화의 운송 기록을 보급소 인수 장부와 대조했어. 수량은 맞지만 통과한 길이 달라. 관측소에서 기록을 지키고 위협을 정리해 줘. 도겸이 대피와 엄호를 맡을 거야.','warden');}
  if(id==='six-cut'&&g.laterStory?.six===3&&!g.enemies.some(e=>e.hp>0)){g.laterStory.dualBreath=true;g.laterStory.deepening={stage:'acquired',observed:true,clue:true,interpreted:true,legacy:false};g.laterRuntime.linked=true;g.laterRuntime.suppress=g.playTime+6;return dialog('도겸 · 재생 연결 차단','남은 위협을 제압한 틈에 공급 연결을 끊었어. 이제 인원이 대피할 수 있어. 서린에게 결과를 전하자.','hunter');}
  if(id==='seven-status'&&g.laterStory?.seven>=1&&!g.enemies.some(e=>e.hp>0)){g.laterRuntime.linked=true;g.laterRuntime.suppress=g.playTime+6;return dialog('공동 대응 · 안전 확인','위협 제압과 인원 이동을 확인했다. 동료에게 결과를 전하고 다음 현장으로 가자.','hero');}
  return null;
 }
 function contact(g,e,c){const s=state(g);if(!c?.manual||!['attack','moon','storm'].includes(c.action)||!g.enemies.includes(e)||e.assessment||e.comparison||e.trial)return;if(g.area==='forest')s.basicHit=true;}
 function beforeAction(g,a,held){if(a!=='dash'||held)return null;return g.enemies.filter(e=>e.hp>0&&e.wind>0&&g.enemyThreatContains(e)&&g.lineClear(e,g.player)).map(e=>({e,at:g.playTime+e.wind,hp:g.player.hp}));}
 function afterAction(g,pending,ok){if(ok&&pending?.length)g.planBEvade={area:g.area,threats:pending};}
 function step(g){const p=g.planBEvade;if(!p)return;if(g.area!==p.area){g.planBEvade=null;return;}for(const t of p.threats)if(!t.done&&g.playTime>=t.at){t.done=true;if(g.area==='forest'&&g.player.hp>=t.hp&&t.e.hp>0)state(g).warnedEvade=true;}if(p.threats.every(t=>t.done))g.planBEvade=null;}
 function objective(g){if(g.introActive)return null;const s=state(g);let id,text,chapter=1;if(g.area==='village'&&g.training>=1&&!s.legacy&&g.progress<=3&&!g.journey.phase&&!g.chapter4.phase){id='huashan';text=!s.introduced?'화산 전수자에게 기본 검로 소개받기':g.progress===3&&!s.recognized?'화산 전수자에게 실전 인정 · 부족한 타격/예고 회피는 옆 기본기 실습':'죽림에서 기본 검로와 예고 회피를 실전 사용하세요.';if(s.recognized){id='master';text='백련에게 죽림의 길 확보 보고';}}if(g.area==='forest'&&g.planBPractice){id='exit';text='유효 검격 '+(s.basicHit?'완료':'필요')+' · 예고 회피 '+(s.warnedEvade?'완료':'필요')+' · 완료 후 출구로 귀환';}if(g.area==='rift'&&g.progress===6&&!s.legacy&&!s.rescuedWorker){id='recover-worker';text='도겸에게 작업자 귀환 확인';}if(g.area==='village'&&g.fate.stage===2&&!s.retrained){id='huashan';text='화산 전수자에게 일반 재수련 · 무명 비경은 선택 기연';chapter=3;}if(g.fate.stage===4&&g.area==='heart'){const target=g.enemies.find(e=>e.hp>0&&!e.boss)||g.points().find(p=>p.kind==='seal'&&!g.activated.includes(p.id))||g.enemies.find(e=>e.hp>0);if(target)return {priority:true,title:'제3장 · 다시 지킬 수 있는 길',text:'호위 → 두 매듭 → 압력의 근원 제압. 기본 검격·회피로 완료할 수 있습니다.',target,chapter:3};}if(['village','city'].includes(g.area)&&g.fate.stage>=6&&!g.chapter4.phase&&!s.legacy){id=g.area==='village'?'shop':'portal';text='청운 약방에서 미도착 상행 소식 확인';chapter=4;}const target=id&&g.points().find(p=>p.id===id);return target?{priority:true,title:'제'+chapter+'장 · 돌아온 손끝',text,target,chapter}:null;}
 return {initial,state,validate,points,interact,contact,beforeAction,afterAction,step,objective,practice};
});
