/* Bounded observations from the fixed reality comparison encounter. No rewards. */
(function(root,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else root.ResonanceProof=api;})(globalThis,function(){
 'use strict';const initial=()=>({version:1,active:null,records:[]}),state=g=>g.worldState.resonanceProof||(g.worldState.resonanceProof=initial());
 const active=g=>g.area==='comparison'&&g.worldState?.resonanceProof?.active;
 function start(g){const t=g.stats(),s=state(g);s.active={seconds:0,damage:0,hits:0,skills:0,shortages:0,attempts:0,responses:0,potions:0,startPotions:g.potions,hp:t.hp,mp:t.mp,attack:t.attack,level:g.level,family:g.worldGrowth.reality.equipped,mode:g.worldGrowth.reality.mode,remainingHp:g.player.hp,remainingMp:g.player.mp};g.resonanceProofSeen=new Set();}
 function leave(g){if(g.worldState?.resonanceProof)state(g).active=null;g.resonanceProofSeen=null;}
 function action(g,a,ok,k,mp,held){const r=active(g);if(!r||held)return;if(!ok&&k&&!k.locked&&k.cost>mp&&g.player.cool[a]<=0)r.shortages++;if(ok&&['moon','storm','signature1','signature2'].includes(a))r.skills++;if(ok&&a==='signature1')r.attempts++;}
 function effect(g,e){const r=active(g);if(!r||!e.manual||e.action!=='signature1'||!['absorb','evade','suppress'].includes(e.kind))return;g.resonanceProofSeen||=new Set();const key=e.castId+':'+e.kind;if(g.resonanceProofSeen.has(key))return;g.resonanceProofSeen.add(key);r.responses++;}
 function damage(g,n){const r=active(g);if(r)r.damage+=Math.max(0,n);}
 function hit(g,ok){const r=active(g);if(r&&ok)r.hits++;}
 function step(g,dt){const r=active(g);if(!r)return;r.seconds=Math.min(99999,r.seconds+Math.max(0,Math.min(.05,dt)));r.remainingHp=g.player.hp;r.remainingMp=g.player.mp;r.potions=Math.max(0,r.startPotions-g.potions);if(g.player.hp<=0||g.enemies.some(e=>e.hp>0))return;r.seconds=Math.round(r.seconds*10)/10;r.damage=Math.round(r.damage);const s=state(g);s.records.push({...r});s.records=s.records.slice(-2);s.active=null;g.emit('resonance-proof',{title:'현실 비교 연습 완료',text:`${r.seconds}초 · 피해 ${r.damage} · 타격 ${r.hits}회\n기술 ${r.skills}회 · 자원 부족 ${r.shortages}회\nQ 대응 ${r.responses}/${r.attempts}회 · 회복약 ${r.potions}개\n캐릭터에서 스탯을 확인하거나 무공/스킬에서 다음 강화를 선택하세요.`});}
 function validate(g){const s=state(g),fail=()=>{throw Error('현실 비교 기록 오류');};if(!s||s.version!==1||Object.keys(s).length!==3||!Array.isArray(s.records)||s.records.length>2)fail();for(const r of [...s.records,...(s.active===null?[]:[s.active])]){if(!r||Object.keys(r).length!==17||!['ripple','echo','seal'].includes(r.family)||!['flow','focus'].includes(r.mode))fail();for(const k of ['seconds','damage','hits','skills','shortages','attempts','responses','potions','startPotions','hp','mp','attack','level','remainingHp','remainingMp'])if(!Number.isFinite(r[k])||r[k]<0||r[k]>999999)fail();if(r.responses>r.attempts||r.potions>99||r.startPotions>99||r.level<1||r.level>80)fail();}return s;}
 return {initial,state,start,leave,action,effect,damage,hit,step,validate};
});
