/* The player-facing, transactional surface for one-way growth. */
(function(root){'use strict';root.ResonanceUI={create({game,show,node,commit,close,refresh,prepare,back,skills}){
 const R=BoundaryResonance,C=ResonanceChallenges;let section='goals',draft=null,ticket=0;
 const button=(label,run,disabled=false)=>{const b=node('button','secondary',label);b.type='button';b.disabled=disabled;b.onclick=run;return b;};
 function icon(kind){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 64 64');s.setAttribute('class','resonance-icon '+kind);s.setAttribute('aria-hidden','true');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',kind==='crystal'?'M32 3 52 23 44 48 32 61 20 48 12 23Z M32 3V61 M12 23H52 M12 23 32 44 52 23':'M15 7H49V57H15Z M23 17H41 M23 27H41 M24 44 32 34 40 44 M32 34V51');s.append(p);return s;}
 function open(id='goals'){section=id;draft=null;ticket++;render();}
 function change(fn){commit(fn);draft=null;render();}
 function render(){const g=game(),m=R.describe(g),s=R.state(g),body=node('section','resonance-screen'),head=node('header','resonance-heading'),nav=node('nav','resonance-tabs'),content=node('div','resonance-content');body.dataset.world='reality';
 head.append(node('span','resonance-kicker','무림의 성취 → 현실의 성장'),node('h2','','경계공명'),node('p','','남겨 온 무공의 흔적을, 다음 싸움의 힘으로.'));body.append(head);
 const wallet=node('div','resonance-wallet');for(const [key,label,hint]of [['crystal','공명 결정','현실 능력치 배분'],['seal','무공 각인','현실 공통·계열 강화']]){const card=node('article');card.append(icon(key),node('span','',label),node('strong','',String(m.balance[key])),node('small','',hint));wallet.append(card);}body.append(wallet);
 nav.setAttribute('aria-label','경계공명 분야');for(const [id,label]of [['goals','성장 목표'],['stats','능력치'],['skills','현실 스킬'],['records','보관함·기록']]){const b=button(label,()=>open(id));b.setAttribute('aria-pressed',String(section===id));nav.append(b);}nav.append(button('무림 심법·경지·헌터',()=>{ticket++;back();}));body.append(nav);
 if(!m.safe)content.append(node('p','resonance-notice','지금은 조회 중입니다. 능력치·스킬 변경은 현실 기지에서 가능합니다. 목표는 여기서도 선택할 수 있습니다.'));
 if(section==='goals'){
  content.append(node('h3','','다음 귀환에서 무엇이 달라질까?'),node('p','','목표를 고르면 해당 무림 도전을 먼저 보여줍니다. 목표는 보상 종류나 다른 도전을 제한하지 않습니다.'));
  const cards=node('div','resonance-goals');for(const [id,label]of Object.entries(R.goals)){const c=node('article','resonance-card');c.dataset.selected=String(s.goal===id);c.append(node('h3','',label),node('p','',{survival:'결정으로 체력을 높여 더 오래 버팁니다.',sustain:'기력과 절약 운용으로 기술을 이어갑니다.',precision:'계열 Q 운용을 바꿔 대응을 안정시킵니다.'}[id]),button(s.goal===id?'선택 중 · 목표 해제':label+' 목표 선택',()=>change(g=>R.setGoal(g,s.goal===id?null:id))));cards.append(c);}content.append(cards,node('h3','','무림 공명 도전'),node('p','','각 도전의 첫 완료: 결정 1 · 각인 1. 처치 보상은 없으며 소모품은 귀환 시 복원됩니다.'));
  const rows=C.list(g).sort((a,b)=>Number(b.current)-Number(a.current));for(const row of rows){const c=node('article','resonance-challenge');c.append(node('h4','',row.name+(row.current?' · 현재 목표':'')),node('p','',row.threat),node('small','',row.completed?'최초 보상 수령 완료':row.reason||'첫 완료 보상 가능'));const b=button('입장 · '+row.name,async()=>{const my=++ticket;b.disabled=true;const result=await C.request(game(),row.id,async id=>{const ok=await prepare(id);return ok!==false&&my===ticket&&body.isConnected&&document.querySelector('#dialog')?.open;});if(result.ok){close();refresh();}else if(body.isConnected){b.disabled=!row.canEnter;c.append(node('p','',result.reason));}},!row.canEnter);c.append(b);content.append(c);}
 }else if(section==='stats'){
  draft||={...m.allocation};const total=Object.values(draft).reduce((a,b)=>a+b,0),used=Object.values(m.allocation).reduce((a,b)=>a+b,0),free=m.balance.crystal+used-total,cap=m.limits,stats=WorldGrowth.stats(g,'reality');
  content.append(node('h3','','공명 결정 배분'),node('p','',`배분 후 잔액 ${free} · 투자 ${total+cap.occupied}/${cap.total} · 공격 ${draft.attack+cap.legacyAttack}/${cap.attack}`),node('p','',cap.next));
  for(const [key,label,unit]of [['attack','공격',1],['hp','체력',6],['mp','기력',3]]){const row=node('div','resonance-stat');row.append(node('strong','',label),node('span','',`${stats[key]} → ${stats[key]+(draft[key]-m.allocation[key])*unit}`),button(label+' 감소',()=>{draft[key]--;render();},!m.safe||draft[key]<=0),node('span','',String(draft[key])),button(label+' 증가',()=>{draft[key]++;render();},!m.safe||free<=0||total+cap.occupied>=cap.total||key==='attack'&&draft.attack+cap.legacyAttack>=cap.attack));content.append(row);}
  content.append(node('p','','결정 1개 = 공격 +1 / 체력 +6 / 기력 +3. 레벨 성장과 별도로 더해집니다. 체력·기력 비율은 유지됩니다.'),button('배분 적용',()=>change(g=>R.allocate(g,draft)),!m.safe||JSON.stringify(draft)===JSON.stringify(m.allocation)),button('능력치 전액 환불',()=>change(g=>R.reset(g,'stats')),!m.safe||!used));
  if(cap.occupied)content.append(node('p','','이전 기록의 성장 효과는 보존되며 투자 상한에 포함됩니다. 이전 효과는 환불되지 않습니다.'));
 }else if(section==='skills'){
  content.append(node('h3','','현실 독립 강화'),node('p','','각인 1개로 한 단계 해금합니다. 무림 심법 배분과는 독립적이며 Q/R/F의 이야기 체득 조건은 유지됩니다.'),button('현실 대응 장착·진화',skills));
  const mode=g.worldGrowth.reality.mode;content.append(node('p','',`운용 심법: ${mode==='flow'?'유수':'집중'} · 해당 심법의 공통 강화만 적용`));for(const [id,label]of [['flow','유수심법'],['focus','집중심법']])content.append(button(label+' 운용',()=>change(g=>g.setBreath(id)),!m.safe||mode===id||g.training<(id==='flow'?1:2)));
  const grid=node('div','resonance-tree');for(const n of m.common){const c=node('article','resonance-card');c.dataset.node=n.id;c.append(node('small','',n.tree==='flow'?'유수심법':'집중심법'),node('h4','',n.name+' '+n.rank+'/'+n.max),node('p','',n.description),node('p','',`${n.current} → ${n.next}`),node('small','',n.prerequisite?'선행: '+n.prerequisite+' 1단계':''),node('p','',n.reason||'각인 1 사용'),button(n.id+' · 각인 1 사용',()=>change(g=>R.upgrade(g,n.id)),!!n.reason));grid.append(c);}content.append(grid);
  for(const f of R.families){const branch=node('section','resonance-family');branch.append(node('h3','',R.familyNames[f]+' · Q 운용 → R 후속'),node('p','','Q 강화는 두 방향 중 하나만 활성화됩니다. 해금한 방향은 무료로 전환할 수 있습니다.'));const tree=node('div','resonance-tree');for(const n of m.skills.filter(n=>n.family===f)){const c=node('article','resonance-card');c.dataset.selected=String(n.selected);c.append(node('h4','',n.name+(n.selected?' · 활성':'')),node('p','',n.description),node('small','',n.reason||'각인 1 사용'));c.append(n.learned?button(n.branch?'이 방향 활성화':'후속 강화 적용 중',()=>change(g=>R.select(g,f,n.id)),!m.safe||!n.branch||n.selected):button(n.name+' · 각인 1 사용',()=>change(g=>R.upgrade(g,n.id)),!!n.reason));tree.append(c);}branch.append(tree);content.append(branch);}
  const equipped=g.worldGrowth.reality.equipped;if(equipped){content.append(node('h4','','현재 장착의 실제 비용'));for(const a of ['signature1','signature2','ultimate']){const info=g.growthWorld()==='reality'?g.skillInfo(a):null;if(info)content.append(node('p','',`${info.name} · ${info.locked?'이야기 체득 필요':info.cost+' 기력 · 재사용 '+info.cool+'초'}`));}}
  content.append(button('스킬 각인 전액 환불',()=>change(g=>R.reset(g,'skills')),!m.safe||!(s.learned.length||Object.values(s.common).some(Boolean))));
 }else{
  content.append(node('h3','','경계공명 원핵 · 영구 기록'),node('p','',g.training>=3?'경계공명 체득 · 무림 기초 경감 15%. 전승한 기본기와 계열의 이야기 권한은 환불해도 유지됩니다.':'백련의 기본기와 두 세계의 경험으로 공명의 원리를 체득합니다.'));content.append(node('h3','','획득한 공명'),node('p','','자동 판매·소비되지 않는 성장 매개체입니다. 무림 숙련은 무림 피해를 높이며, 숙련 5·10의 첫 달성만 공명 결정을 남깁니다. 현실에서 얻은 재화의 역방향 전이는 없습니다.'));
  if(!m.sources.length)content.append(node('p','','아직 보관된 공명이 없습니다. 백련의 기본기와 첫 기연 영구 계승을 진행하세요.'));for(const row of m.sources)content.append(node('p','resonance-source',row.name+' · 결정 '+row.crystal+' · 각인 '+row.seal));
  content.append(node('h3','','현실 비교 전투 · 최근 2회'));const records=ResonanceProof.state(g).records;for(const [i,r]of records.entries())content.append(node('p','resonance-source',`${i+1}. Lv.${r.level} ${R.familyNames[r.family]} · 공격 ${r.attack} / 체력 ${r.hp} / 기력 ${r.mp} · ${r.seconds}초 · 피해 ${r.damage} · 타격 ${r.hits}회 · 기술 ${r.skills}회 · 부족 ${r.shortages}회 · Q 대응 ${r.responses}/${r.attempts} · 약 ${r.potions} · 남은 체력 ${Math.round(r.remainingHp)}`));content.append(node('p','','같은 적 2종·체력 140·피해 18의 현장입니다. 레벨·장착·운용과 플레이 차이도 결과에 영향을 줍니다.'));content.append(node('h3','','무림 도전 기록'));for(const [id,r]of Object.entries(C.state(g).results))content.append(node('p','',C.list(g).find(x=>x.challengeId===id)?.name+` · ${r.seconds}초 / 피해 ${r.damage} / 유료 무공 ${r.paid}회 / 대응 ${r.responses}회 / 소모품 ${r.potions}`));
  content.append(node('p','','위 기록은 무림 도전 결과입니다. 현실의 변화는 같은 대응 비교 전투에서 확인하세요.'),button('현실 비교 전투',()=>{ticket++;close();g.beginComparison();refresh();},g.area!=='city'||!g.worldGrowth.reality.equipped));
 }
 body.append(content);show('성장 · 경계공명',body,[{label:'닫기',secondary:true}],'system','v0.2 · 무림 → 현실');
 }
 return {open};
}};})(globalThis);
