/* Optional, rewardless before/after encounter. Permanent evidence and runtime are separate. */
(function(root,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else root.ReturnProof=api;})(globalThis,function(){
 'use strict';
 const modes=['baseline','proof','application'],families=['ripple','echo','seal'],effects={ripple:'absorb',echo:'evade',seal:'suppress'},pending=new WeakSet();
 const profile=Object.freeze({version:1,spawn:[400,700],zone:{x:700,y:700,radius:75},enemies:[{role:'pressure',x:570,y:700,hp:180,damage:14,speed:90,cd:.5},{role:'heavy',x:780,y:650,hp:420,damage:24,speed:65,cd:1.4},{role:'ranged',x:860,y:750,hp:150,damage:12,speed:55,cd:3.3}]});
 const clone=x=>x instanceof Set?new Set([...x].map(clone)):x instanceof Map?new Map([...x].map(([k,v])=>[clone(k),clone(v)])):Array.isArray(x)?x.map(clone):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,clone(v)])):x;
 const initial=()=>({version:1,baselineCompleted:false,proofCompleted:false,verifiedFamily:null,evidence:null,reported:false,roleChoice:null,applicationCompleted:false});
 const state=g=>g.worldState.returnProof||(g.worldState.returnProof=initial());
 function describe(g){return clone(g.worldState?.returnProof||initial());}
 function install(api){api.AREAS.returnProof={...api.AREAS.rift,name:'귀환 대응 · 회수 현장',sub:'같은 위협, 달라진 대응 · 무보상 선택 체험',spawn:[...profile.spawn],positions:[],points:[]};}
 const fields=['area','player','enemies','fx','activated','combo','gold','potions','combat','legendRuntime','realityRuntime','experimentRuntime','dualRuntime','trial','hitStop','shake','notice'];
 function snapshot(g){return {...Object.fromEntries(fields.map(k=>[k,clone(g[k])])),focus:g.fate.focus};}
 function restore(g,s){for(const k of fields)g[k]=clone(s[k]);g.fate.focus=s.focus;}
 function available(g,mode){const s=describe(g);return modes.includes(mode)&&g.progress>=12&&g.fate.stage>=1&&!g.introActive&&g.area==='city'&&!g.trial&&!g.advancementTrial&&!g.proofRuntime&&(mode==='baseline'||mode==='proof'&&s.baselineCompleted&&families.some(f=>g.worldState.achievements?.settled.includes('inherit:'+f))||mode==='application'&&s.reported&&!!s.roleChoice);}
 function near(g){return g.area==='city'&&Math.hypot(g.player.x-1170,g.player.y-850)<90;}
 function entry(g,{entrance=true}={}){if(g.progress<12||g.fate.stage<1)return [];return modes.map((mode,i)=>({id:'proof:'+mode,mode,name:['귀환 전 · 같은 위협 체험','귀환 후 · 현실 대응 검증','현장 적용 · 역할 분담'][i],canEnter:available(g,mode)&&(!entrance||near(g)),reason:!available(g,mode)?['2장 보고 후 거점에서 시작','첫 체험과 기연 계승·현실 귀환 필요','검증 결과 직접 보고와 역할 선택 필요'][i]:entrance&&!near(g)?'현실 던전 입구로 이동하세요.':'',warning:mode==='proof'&&!g.worldGrowth.reality.equipped?'현실 대응 미장착 · 기본 공격 연습은 가능합니다.':''}));}
 async function requestEntry(g,mode,prepare,options={}){if(pending.has(g))return {ok:false,reason:'입장 준비 중입니다.'};if(!entry(g,options).find(r=>r.mode===mode)?.canEnter)return {ok:false,reason:'입장 조건을 확인하세요.'};pending.add(g);try{if(typeof prepare!=='function'||await prepare('returnProof')===false)return {ok:false,reason:'지역 준비가 취소되었습니다.'};return {ok:!!entry(g,options).find(r=>r.mode===mode)?.canEnter&&begin(g,mode)};}catch(e){return {ok:false,reason:'지역 준비에 실패했습니다.'};}finally{pending.delete(g);}}
 function begin(g,mode){if(!available(g,mode)||!near(g))return false;const s=state(g),r={mode,profileVersion:1,choice:mode==='application'?s.roleChoice:null,encounterId:'proof-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10),elapsed:0,hold:0,seen:new Set(),snapshot:snapshot(g)};g.proofRuntime=r;g.area='returnProof';g.fx=[];g.activated=[];g.player={...clone(g.player),x:profile.spawn[0],y:profile.spawn[1],hp:g.stats().hp,mp:g.stats().mp,invuln:0,dash:0,cool:Object.fromEntries(Object.keys(g.player.cool).map(k=>[k,0]))};g.realityRuntime=null;g.combat={parry:0,charges:0,echo:null,field:null,pending:[]};g.legendRuntime={seen:new Set(),evade:null,scarAt:-10};g.experimentRuntime={pulse:null,timer:1,serial:0,echo:null,seen:new Set(),pending:[],guard:null,charge:0,lastAction:-100,focus:false,seq:0,companion:null,sense:0,held:false};g.dualRuntime={serial:0,cast:null,last:null,discount:0,opening:0,seen:new Set(),guard:null};g.fate.focus=0;g.hitStop=0;g.enemies=profile.enemies.filter(e=>!(r.choice==='cut-support'&&e.role==='ranged')).map((p,i)=>({...p,id:'return-proof-'+p.role,returnProofTarget:r.encounterId,boss:false,kind:p.role==='ranged'?'drone':'bandit',name:{pressure:'압박 · 접근 위협',heavy:'강타 · 받아내기 기회',ranged:'사격 · 측면 위협'}[p.role],maxHp:p.hp,r:20,wind:0,windMax:1,tx:p.x,ty:p.y,range:62,flash:0,attacks:0,pattern:'strike',rewarded:false}));g.emit('proof-start',{mode,profileVersion:1,choice:r.choice,eligible:!g.revision.inherited.length,hp:g.stats().hp,mp:g.stats().mp,attack:g.stats().attack});return true;}
 function progress(g){const r=g.proofRuntime;if(!r)return null;return {mode:r.mode,remaining:g.enemies.filter(e=>e.returnProofTarget===r.encounterId&&e.hp>0).length,hold:r.hold,zone:profile.zone};}
 function objective(g){const p=progress(g);return p?{chapter:0,purpose:'귀환 대응 · '+({baseline:'첫 체험',proof:'현실 검증',application:'역할 적용'}[p.mode]),target:g.enemies.find(e=>e.hp>0)||points(g).find(p=>p.id==='proof-recover'),currentAction:p.remaining?'남은 위협 '+p.remaining+'개 제압':p.hold<2?'사각 회수 지점 2초 확보':'회수 지점에서 직접 상호작용',condition:'기본 공격으로도 완료 가능 · 처치 보상 없음',rewards:[],status:'return-proof'}:null;}
 function points(g){if(!g.proofRuntime)return null;return [{id:'proof-exit',x:150,y:970,label:'시도 종료 · 자원 복구',kind:'exit'},{id:'proof-recover',x:700,y:700,label:'□ 회수 지점 · '+Math.min(2,g.proofRuntime.hold).toFixed(1)+'/2초',kind:'npc'},...(g.proofRuntime.mode==='application'?[{id:'proof-dokyeom',x:610,y:780,label:'도겸 · 후방 회수 담당',kind:'npc'}]:[])];}
 function step(g,dt){const r=g.proofRuntime;if(!r||!Number.isFinite(dt)||dt<=0)return;r.elapsed+=dt;const p=progress(g),z=profile.zone;r.hold=p.remaining===0&&Math.hypot(g.player.x-z.x,g.player.y-z.y)<=z.radius?Math.min(2,r.hold+dt):0;}
 function finish(g,outcome){const r=g.proofRuntime;if(!r||!['complete','retreat','defeat'].includes(outcome))return false;if(outcome==='complete'&&(progress(g).remaining||r.hold<2||Math.hypot(g.player.x-700,g.player.y-700)>75))return false;if(outcome==='complete')state(g)[{baseline:'baselineCompleted',proof:'proofCompleted',application:'applicationCompleted'}[r.mode]]=true;restore(g,r.snapshot);g.proofRuntime=null;g.emit('proof-result',{mode:r.mode,outcome,choice:r.choice,verifiedFamily:state(g).verifiedFamily});return true;}
 function interact(g,id){if(!g.proofRuntime)return null;if(id==='proof-exit'){finish(g,'retreat');return {type:'toast',text:'입장 전 자원으로 복구했습니다.'};}if(id==='proof-recover'){const ok=finish(g,'complete');return {type:'toast',text:ok?'현장 회수 완료':'모든 위협을 제압하고 회수 지점을 2초 확보하세요.'};}if(id==='proof-dokyeom')return {type:'dialog',title:'도겸 · 후방 회수',text:'선택한 배치대로 후방 회수를 맡겠습니다. 현장 위협 제압은 부탁드립니다.'};return {type:'toast',text:'위협 제압 후 사각 회수 지점에서 상호작용하세요.'};}
 function onEffect(g,e){const r=g.proofRuntime;if(!r||r.mode!=='proof'||g.area!=='returnProof'||!e.manual||!Number.isInteger(e.castId)||e.castId<1||effects[e.family]!==e.kind||!g.enemies.includes(e.target)||e.target.returnProofTarget!==r.encounterId||!g.worldState.achievements?.settled.includes('inherit:'+e.family))return false;const key=e.castId+':'+e.target.id+':'+e.kind;if(r.seen.has(key))return false;r.seen.add(key);const s=state(g);if(!s.verifiedFamily){s.verifiedFamily=e.family;s.evidence={family:e.family,profileVersion:1,encounterId:r.encounterId,castId:e.castId,targetId:e.target.id,kind:e.kind};}g.emit('proof-evidence',{family:e.family,kind:e.kind,castId:e.castId,targetId:e.target.id});return true;}
 function prepareEnemy(g,e){if(!e.returnProofTarget)return false;e.wind=e.windMax=e.role==='heavy'?1.2:e.role==='ranged'?1:.85;e.pattern=e.role==='ranged'?'shot':e.role==='heavy'?'heavy':'strike';e.range=e.role==='ranged'?24:e.role==='heavy'?95:62;e.telegraph={x:e.x,y:e.y,tx:e.tx,ty:e.ty,width:24};return true;}
 function mayStartAttack(g,e){return !g.enemies.some(x=>x!==e&&x.hp>0&&x.wind>0);}
 function safeZone(g){return g.proofRuntime?.choice==='secure-route'?{x:700,y:700,radius:100,damageFactor:.75}:null;}

 function validate(g){
  const raw=g.worldState.returnProof;if(raw===undefined){g.worldState.returnProof=initial();return;}
  const fail=()=>{throw Error('귀환 검증 기록 오류');},keys=Object.keys(initial());
  if(!raw||Array.isArray(raw)||Object.keys(raw).length!==keys.length||Object.keys(raw).some(k=>!keys.includes(k))||raw.version!==1)fail();
  for(const k of ['baselineCompleted','proofCompleted','reported','applicationCompleted'])if(typeof raw[k]!=='boolean')fail();
  if(raw.baselineCompleted&&(g.progress<12||g.fate.stage<1)||raw.proofCompleted&&!raw.baselineCompleted)fail();
  if(raw.verifiedFamily!==null){const f=raw.verifiedFamily,e=raw.evidence;if(!families.includes(f)||!raw.baselineCompleted||!g.revision.inherited.includes(f)||!g.worldState.achievements.settled.includes('inherit:'+f)||!e||Array.isArray(e)||Object.keys(e).length!==6||e.family!==f||e.profileVersion!==1||e.kind!==effects[f]||typeof e.encounterId!=='string'||!/^proof-[a-z0-9-]{1,64}$/.test(e.encounterId)||!Number.isInteger(e.castId)||e.castId<1||e.castId>1000000||!profile.enemies.some(p=>e.targetId==='return-proof-'+p.role))fail();}else if(raw.evidence!==null)fail();
  if(raw.reported&&(!raw.proofCompleted||!raw.verifiedFamily||!g.worldState.reports?.reported.includes('first-response'))||raw.roleChoice!==null&&(!['cut-support','secure-route'].includes(raw.roleChoice)||!raw.reported)||raw.applicationCompleted&&(!raw.reported||!raw.roleChoice))fail();
  g.worldState.returnProof=clone(raw);
 }
 function session(g){const r=g.proofRuntime;return r?{version:1,mode:r.mode,profileVersion:r.profileVersion,choice:r.choice}:null;}
 function withSaveSnapshot(g,serialize){const r=g.proofRuntime;if(!r)return serialize();const live=Object.fromEntries(fields.map(k=>[k,g[k]])),focus=g.fate.focus;try{restore(g,r.snapshot);return serialize();}finally{for(const k of fields)g[k]=live[k];g.fate.focus=focus;}}
 function restoreSession(g,d){if(d===undefined)return;if(!d||Array.isArray(d)||Object.keys(d).length!==4||d.version!==1||d.profileVersion!==1||!modes.includes(d.mode)||d.choice!==(d.mode==='application'?describe(g).roleChoice:null)||!available(g,d.mode)||!near(g)||!begin(g,d.mode))throw Error('귀환 임무 재개 기록 오류');g.restoreNotice='귀환 대응 임무를 시작 지점부터 다시 진행합니다. 확정한 증거는 유지됩니다.';}

 function practiceEvent(g,{kind,target}){if(g.area!=='sanctum'||g.trial?.path!=='ripple'&&!(kind==='followup'&&target?.id==='trial-ripple'&&g.proofPracticeRuntime?.absorbed))return false;if(kind==='start'){g.proofPracticeRuntime={observed:false,absorbed:false,followup:false,failures:0};return true;}const r=g.proofPracticeRuntime;if(!r||target&&(!target.trial||!g.enemies.includes(target)))return false;if(kind==='observed')r.observed=true;else if(kind==='absorbed')r.absorbed=true;else if(kind==='followup')r.followup=true;else if(kind==='miss')r.failures++;else return false;return true;}
 function practiceView(g){const r=g.proofPracticeRuntime;if(g.area!=='sanctum'||!r)return null;return {...r,helpAvailable:r.failures>=2,next:!r.observed?'공격 예고의 모양과 끝나는 순간을 관찰하세요.':!r.absorbed?'예고가 끝날 무렵 받아내기를 사용하세요.':!r.followup?'축적한 파문으로 후속기를 적중해 보세요.':'거리 응용 · 다음 예고는 옆으로 피하고 빈틈을 노려 보세요.',optional:true};}

 function report(g){const s=state(g);if(g.area!=='city'||g.nearestPoint()?.id!=='warden'||!s.proofCompleted||!s.verifiedFamily||g.proofRuntime)return {ok:false,firstReport:false};const firstReport=!s.reported;s.reported=true;return {ok:true,firstReport};}
 function choiceView(g,id){if(!['cut-support','secure-route'].includes(id))return null;return {id,title:id==='cut-support'?'사격 지원 차단':'안전 회수로 확보',text:id==='cut-support'?'측면 사격 위협 1개를 차단합니다. 안전 영역은 없습니다.':'사격 위협은 유지됩니다. 표시된 회수 영역 안에서 받는 피해가 25% 줄어듭니다.',canChoose:g.area==='city'&&describe(g).reported&&!g.proofRuntime};}
 function choose(g,id){if(!choiceView(g,id)?.canChoose)return false;state(g).roleChoice=id;g.emit('proof-choice',{choice:id});return true;}
 return {report,choiceView,choose,practiceEvent,practiceView,validate,session,withSaveSnapshot,restoreSession,profile,initial,state,describe,install,entry,requestEntry,begin,progress,objective,points,step,finish,interact,onEffect,prepareEnemy,mayStartAttack,safeZone,clone,snapshot,restore};
});
