/* The single workspace for common operation, learned skills and equipment. */
(function(root){'use strict';
root.SkillsScreen={create({game,show,node,refresh,commit,close}){
 const R=root.BoundaryResonance,P=root.PassiveGrowth,W=root.WorldGrowth;
 const families=['ripple','echo','seal'],names={ripple:'파문',echo:'잔영',seal:'봉인'},actions=['signature1','signature2','ultimate'];
 let world='reality',type='active',category='common',selected='attack',detailOpen=false,message='',resetting=false,history=false,listScroll=0,viewportScroll=0;
 const copy=v=>JSON.parse(JSON.stringify(v));
 const current=g=>W.worldOf(g),place=()=>world==='murim'?'청운촌':'현실 기지';
 function allowed(g){return current(g)===world&&!g.introActive&&!g.trial&&!g.advancementTrial&&g.player.hp>0&&(world==='murim'?g.area==='village'&&!g.enemies?.some(e=>e.hp>0):R.safe(g));}
 function viewport(element){for(let e=element?.parentElement;e;e=e.parentElement)if(/auto|scroll/.test(getComputedStyle(e).overflowY))return e;return document.scrollingElement;}
 const mobile=()=>matchMedia('(max-width:640px)').matches;
 function button(label,fn,id,disabled=false){const b=node('button','secondary',label);b.type='button';b.disabled=disabled;if(id)b.dataset.skillsFocus=id;b.onclick=fn;return b;}
 function change(fn,focus){let ok=false;try{ok=commit(fn)===true;}catch(_){ok=false;}message=ok?'변경 사항이 저장되었습니다.':'저장하지 못했습니다. 변경은 적용되지 않았습니다. 다시 시도하세요.';resetting=false;if(ok)refresh?.();render(focus);return ok;}
 function storyChange(fn){close?.();let ok=false;try{ok=commit(fn)===true;}catch(_){ok=false;}if(ok){refresh?.();return;}message='저장하지 못했습니다. 변경은 적용되지 않았습니다. 다시 시도하세요.';render('detail-title');}
 function transact(fn,focus){return change(g=>allowed(g)?fn(g):false,focus);}
 function mastery(g,f,a){return W.skillMastery?W.skillMastery(g,world,f,a):{value:0,max:30,tracked:false};}
 function masteryText(g,f,a){const m=mastery(g,f,a);return m.tracked?`개별 숙련 ${m.value}/${m.max}`:'이전 개별 기록 없음 · 업데이트 이후 측정';}
 function owned(g,f){return !!g.revision.inherited.includes(f);}
 function story(g,a){const arc=g.worldState.growthArc;if(!arc||arc.legacy)return '';return a==='signature2'&&!arc.learnedR?'4장 구조 완료 후 백련의 후속 실습을 마치세요.':a==='ultimate'&&!arc.learnedF?'7장 위기 실전에서 체득합니다.':'';}
 function learned(g,f,a){return owned(g,f)&&!story(g,a)&&(world==='murim'||root.RealitySkills.status(g,f)!=='locked');}
 function level(g,f,a){if(!learned(g,f,a))return 0;if(world==='murim'||a==='ultimate')return 1;const s=R.state(g);return a==='signature1'?(s.selected[f]?2:1):s.learned.includes(f+'-follow')?2:1;}
 // Evaluate the game's actual skill calculation on an isolated view; never equip the real player.
 function skillInfo(g,f,a){const view=Object.create(g);view.worldGrowth=copy(g.worldGrowth);view.worldState=copy(g.worldState);view.journey=copy(g.journey);view.fate=copy(g.fate);view.dualRuntime={...g.dualRuntime};view.trial=null;view.growthArcRuntime={...g.growthArcRuntime,lessonR:false};view.area=world==='murim'?'village':'city';view.worldGrowth[world].equipped=f;view.fate.path=f;view.journey.selected={...view.worldGrowth[world].interpretations};view.journey.breath=view.worldGrowth[world].mode;view.journey.mastery=view.worldGrowth[world].mastery;if(current(g)!==world||g.worldGrowth[world].equipped!==f)view.dualRuntime.discount=0;return view.skillInfo(a);}
 function readDetail(subject){const ids=(game().unreadNews?.('skills')||[]).filter(x=>x.subject===subject&&!x.id.startsWith('resonance:seal:')).map(x=>x.id);if(!ids.length)return;try{if(commit(g=>{for(const id of ids)g.readNews(id);return true;})===true)refresh?.();}catch(_){/* Keep unread state when persistence fails. */}}
 function choose(id){const list=document.querySelector('.skills-list');listScroll=list?.scrollTop||0;viewportScroll=viewport(list)?.scrollTop||0;readDetail(type==='passive'?'mode':category);selected=id;detailOpen=true;resetting=false;message='';render('detail-title');}
 function open(view,subject){const g=game();if(g.introActive)return;world=['murim','reality'].includes(view)?view:current(g);type='active';category='common';selected='attack';detailOpen=false;resetting=false;history=false;message='';listScroll=0;const passive=P.nodes.find(n=>n.id===subject);if(passive){type='passive';category=passive.tree;selected=subject;detailOpen=true;}else if(['mode','flow','focus'].includes(subject)){type='passive';category=subject==='mode'?g.worldGrowth[world].mode:subject;selected=category==='focus'?'C0':'F0';}else if(subject==='discovery'||subject==='inheritance'){category='inheritance';selected='ripple';}else{const family=families.find(f=>subject===f||String(subject||'').startsWith(f+'-'));if(family){category=family;selected=String(subject).includes('-')?'equipment':'signature1';detailOpen=true;}}if(subject&&subject!=='discovery')readDetail(subject);render();}
 function render(focus,restoreList=false){const g=game(),safe=allowed(g),body=node('section','skills-screen'),head=node('header','skills-heading'),nav=node('nav','skills-categories');body.dataset.world=world;body.dataset.detail=String(detailOpen);body.dataset.subject=category;body.dataset.type=type;head.append(node('p','skills-location',`조회: ${world==='murim'?'무림':'현실'} · 현재 위치: ${root.DualWorld.AREAS[g.area]?.name||g.area}`));
  const worlds=node('nav','skills-worlds');worlds.setAttribute('aria-label','조회 세계');for(const [id,label]of [['reality','현실 보기'],['murim','무림 보기']]){const b=button(label,()=>open(id),id);b.setAttribute('aria-pressed',String(world===id));worlds.append(b);}head.append(worlds);body.append(head);
  const passive=world==='murim'?P.describe(g,'murim'):null,res=R.describe(g),balance=world==='murim'?passive.available:res.balance.seal;
  const wallet=node('section','skills-wallet');wallet.append(node('strong','',`${world==='murim'?'수련 포인트':'무공 각인'} · 보유 ${balance}`),node('span','',world==='murim'?'무림 심법 강화에 사용':'현실 심법·Q/R 강화에 사용'));
  if(world==='reality'){const byId=new Map(res.sources.filter(x=>x.seal>0).map(x=>[x.id,x])),sources=(R.state(g)?.grants||[]).map(id=>byId.get(id)).filter(Boolean),last=sources.at(-1);wallet.append(node('small','',last?`최근 획득 +${last.seal} · ${last.name}`:'백련의 기본기와 기연 영구 체득으로 획득합니다.'),button(history?'획득 내역 접기':'획득 내역',()=>{history=!history;if(history){const ids=(g.unreadNews?.('skills')||[]).filter(x=>x.subject==='seal'&&x.id.startsWith('resonance:seal:')).map(x=>x.id);if(ids.length){change(current=>{for(const id of ids)current.readNews(id);return true;},'history');return;}}render('history');},'history'));if(history){const record=node('div','skills-history');record.append(node('h3','','무공 각인 획득 내역'));for(const s of sources)record.append(node('p','',`${s.name} · 무공 각인 +${s.seal}`));if(!sources.length)record.append(node('p','','아직 획득한 무공 각인이 없습니다.'));wallet.append(record);}}
  body.append(wallet);if(!safe)body.append(node('p','skills-notice',`조회 중 · 변경은 ${place()}의 안전한 상태에서 가능합니다.`));
  const types=node('nav','skills-types');types.setAttribute('aria-label','스킬 종류');for(const [id,label]of [['active','일반 스킬'],['passive','심법 (패시브)']]){const b=button(label,()=>{type=id;category=id==='active'?'common':'flow';selected=id==='active'?'attack':'F0';message='';resetting=false;render('type-'+id);},'type-'+id);b.setAttribute('aria-pressed',String(type===id));types.append(b);}body.append(types);
  nav.setAttribute('aria-label',type==='active'?'기술 계열':'심법 트리');for(const [id,label]of (type==='active'?[['common','공통 기본기'],...families.map(f=>[f,names[f]]),['inheritance','계열 계승']]:[['flow','유수심법'],['focus','집중심법']])){const b=button(label,()=>{category=id;selected=type==='passive'?(id==='flow'?'F0':'C0'):id==='common'?'attack':id==='inheritance'?'ripple':'signature1';detailOpen=false;message='';resetting=false;listScroll=0;render('category-'+id);},'category-'+id);b.setAttribute('aria-pressed',String(category===id));nav.append(b);}body.append(nav);
  const layout=node('div','skills-layout'),list=node('nav','skills-list'),detail=node('section','skills-detail');list.setAttribute('aria-label','기술 목록');detail.setAttribute('aria-label','선택 기술 상세');
  function row(id,title,summary,data,parent=list){const b=button('',()=>choose(id),'row-'+id);b.className='skills-list-item';b.dataset[data]=id;b.setAttribute('aria-pressed',String(selected===id));b.append(node('strong','',title),node('small','',summary));parent.append(b);return b;}
  detail.append(button('기술 목록',()=>{detailOpen=false;render('row-'+selected,true);},'back'));detail.firstChild.classList.add('skills-back');
  function title(text){const h=node('h3','skills-detail-title',text);h.tabIndex=-1;h.dataset.skillsFocus='detail-title';detail.append(h);}
  if(category==='common'||type==='passive'){
   const levels=world==='murim'?P.state(g).levels:R.levels(g);
   if(type==='active')for(const [i,a]of ['attack','moon','storm'].entries()){const info=skillInfo(g,null,a);row(a,`${root.Controls?.key(a)||a} · ${info.name}`,g.training>=i?'체득 완료':'백련의 기본기 수련 필요','basic');}
   else{list.classList.add('skills-tree');const tree=P.nodes.filter(n=>n.tree===category);list.append(node('h3','',category==='flow'?'유수심법 트리':'집중심법 트리'),node('p','skills-muted','연결된 선은 선행 체득 조건입니다. 노드를 선택해 바로 강화하세요.'));function branch(n,parent){const group=node('div','skills-tree-branch');parent.append(group);const rank=levels[n.id],model=(world==='murim'?passive.nodes:res.common).find(x=>x.id===n.id);const b=row(n.id,`${n.name} · ${rank}/${n.max}`,rank>=n.max?'체득 완료':n.free?'이야기로 체득':model?.reason||'강화 가능 · 비용 1','passive',group);b.dataset.state=rank>=n.max?'complete':n.free||model?.reason?'locked':'available';const children=tree.filter(x=>x.prerequisite===n.id);if(children.length){const links=node('div','skills-tree-children');group.append(links);for(const child of children){const edge=node('div','skills-tree-edge');edge.dataset.prerequisite=n.id;edge.dataset.dependent=child.id;edge.append(node('small','skills-tree-condition',`${n.name} 1단계 →`));links.append(edge);branch(child,edge);}}}for(const n of tree.filter(n=>!n.prerequisite)){const section=node('section',n.id==='F4'||n.id==='C5'?'skills-tree-story':'skills-tree-root');if(n.id==='F4'||n.id==='C5')section.append(node('h4','','이야기 체득 · 6장'));branch(n,section);list.append(section);}}
   if(['attack','moon','storm'].includes(selected)){const info=skillInfo(g,null,selected),need={attack:0,moon:1,storm:2}[selected];title(info.name);detail.append(node('p','',info.description||'전방의 적에게 기본 검격을 가합니다.'),node('p','',`최종 기력 ${info.cost} · 재사용 ${info.cool}초`),node('p','',g.training>=need?'체득 완료 · 추가 강화 없음':'백련과 본편 수련을 통해 체득합니다.'),node('p','',`공통 검술 계열 숙련 ${g.worldGrowth[world].mastery.sword}/30`),node('small','skills-muted','공통 검술은 기존 계열 숙련으로 기록합니다.'));
   }else{
   const n=P.nodes.find(x=>x.id===selected)||P.nodes[0],rank=levels[n.id],model=world==='murim'?passive.nodes.find(x=>x.id===n.id):res.common.find(x=>x.id===n.id),mode=g.worldGrowth[world].mode;
   title(n.name+` · ${rank}/${n.max}`);detail.append(node('p','',n.description),node('p','',`현재: ${P.value(n.id,rank)}`),node('p','',`다음: ${P.value(n.id,Math.min(n.max,rank+1))}`),node('p','',`${n.tree==='flow'?'유수심법':'집중심법'} 운용 시 적용 · ${mode===n.tree?'현재 적용 심법':'현재 다른 심법 운용 중'}`),node('p','skills-muted','패시브 · 숙련 대상 아님'));
   if(n.free)detail.append(node('p','',rank?'이야기 체득 완료 · 추가 강화 없음':n.id==='F0'?'백련의 첫 운기를 체득하면 열립니다.':n.id==='C0'?'집중 원리를 체험하면 열립니다.':'6장 원리 체득 후 개방'));
   else{const why=rank>=n.max?'최대 단계':!safe?place()+'에서 변경 가능':model.reason;detail.append(node('p','',why||`${world==='murim'?'수련 포인트':'무공 각인'} 1개 소비`));const b=button((world==='murim'?'수련 포인트':'무공 각인')+' 1개로 강화',()=>transact(x=>world==='murim'?P.upgrade(x,n.id):R.upgrade(x,n.id),'upgrade-'+n.id),'upgrade-'+n.id,!!why);b.dataset.upgrade=n.id;detail.append(b);}
   const modes=node('div','skills-modes');modes.append(node('h4','','운용 심법'));for(const [id,label]of [['flow','유수심법'],['focus','집중심법']])modes.append(button(label+(mode===id?' · 운용 중':' 운용'),()=>transact(x=>x.setBreath(id),'mode-'+id),'mode-'+id,!safe||mode===id||g.training<(id==='flow'?1:2)));detail.append(modes);}
  }else if(category==='inheritance'){
   for(const f of families){const have=owned(g,f),ready=g.legend.ready.includes(f)||g.fate.proven.includes(f);row(f,root.DualWorld.Fate.PATHS[f].name,have?'계승 완료':ready?'계승 가능':'이야기 진행 필요','discovery');}
   const f=selected,have=owned(g,f),field=g.legend.ready.includes(f),ready=field||g.fate.proven.includes(f),equipped=g.worldGrowth[world].equipped===f;
   title(root.DualWorld.Fate.PATHS[f].name);detail.append(node('p','',have?'이 계열을 영구 계승했습니다.':ready?'이야기 조건을 완료했습니다. 계승을 수락하면 Q 기술이 열립니다.':'무림 본편의 계열 실습과 시험을 완료하면 계승할 수 있습니다.'));
   if(world!=='murim')detail.append(node('p','','계열 계승은 무림에서 진행합니다.'),button('무림 계승 보기',()=>{world='murim';render();},'discover-murim'));
   else if(have||ready){const can=current(g)==='murim'&&!g.introActive&&!g.trial&&!g.advancementTrial&&g.player.hp>0&&(field?(!g.fate.path||g.fate.path===f||root.DualWorld.AREAS[g.area].safe):g.area==='village'&&g.fate.stage>=2);detail.append(button(equipped?'현재 운용 계열':have?'이 계열로 재수련':'계승 수락',()=>storyChange(x=>can?(field?x.awaken(f):x.acceptFate(f)):false),'inherit',!can||equipped));if(!can)detail.append(node('p','','시험을 마친 뒤 청운촌에서 계승을 선택하세요.'));}
   detail.append(node('p','skills-muted','계열 계승 → Q 체득 · 4장 후속 실습 → R 체득 · 7장 위기 실전 → F 체득'));
  }else{
   const f=category;for(const a of actions){const info=skillInfo(g,f,a),have=learned(g,f,a);row(a,`${root.Controls?.key(a)||({signature1:'Q',signature2:'R',ultimate:'F'}[a])} · ${info.name} · ${have?'Lv.'+level(g,f,a):'잠금'}`,have?masteryText(g,f,a):story(g,a)||'계열 영구 계승 필요','skill');if(a==='signature1'&&world==='reality'){const branches=node('section','skills-active-tree');branches.append(node('p','skills-muted','Q 운용 · 둘 중 하나 활성화'));for(const n of res.skills.filter(n=>n.family===f&&n.branch)){const edge=node('div','skills-tree-edge');edge.dataset.prerequisite='signature1';edge.dataset.dependent=n.id;row(n.id,n.name,n.selected?'활성 · Lv.2':n.learned?'해금 완료':n.reason||'강화 가능 · 각인 1','branch',edge);branches.append(edge);}const link=node('p','skills-tree-join','↓ Q 운용 하나 해금 + R 이야기 체득 → R 후속 강화');link.dataset.prerequisite=f+'-window|'+f+'-economy';link.dataset.dependent=f+'-follow';branches.append(link);list.append(branches);}}row('equipment','계열 장착','선택한 계열을 실제 전투에 사용합니다.','equipment');
   if(selected==='equipment'){title(names[f]+' · 계열 장착');const equipped=g.worldGrowth[world].equipped===f;detail.append(node('p','',equipped?'현재 장착 계열':'조회 중 · 현재 장착되지 않음'));const why=!safe?place()+'에서 장착 가능':!owned(g,f)?'계열 영구 계승 필요':world==='reality'&&root.RealitySkills.status(g,f)==='locked'?'무림 체득 후 현실 귀환 필요':'';
    detail.append(button(equipped?'현재 장착 중':'이 계열 장착',()=>world==='reality'?transact(x=>x.equipReality(f),'equip'):storyChange(x=>allowed(x)?x.legend.ready.includes(f)?x.awaken(f):x.acceptFate(f):false),'equip',!!why||equipped));if(why)detail.append(node('p','',why));
    if(!owned(g,f))detail.append(button('계열 계승 보기',()=>{category='inheritance';selected=f;render('detail-title');},'inheritance-'+f));
   }else{const branchNode=res.skills.find(n=>n.id===selected&&n.family===f),a=actions.includes(selected)?selected:'signature1',info=skillInfo(g,f,a),have=learned(g,f,a);title((branchNode?branchNode.name+' · '+info.name:info.name)+' · '+(have?'Lv.'+level(g,f,a):'미체득'));if(owned(g,f))detail.append(node('p','',info.description),node('p','skills-cost',`최종 기력 ${info.cost} · 재사용 ${info.cool}초${a==='ultimate'?' · 기세 100 필요':''}`));detail.append(node('p','',have?'이야기 체득 완료':story(g,a)||'계열을 영구 계승하고 현실 운용은 정상 귀환 후 사용할 수 있습니다.'),node('p','skills-mastery',masteryText(g,f,a)));if(current(g)!==world||g.worldGrowth[world].equipped!==f)detail.append(node('small','skills-muted','선택 세계에서 이 계열 장착 시의 비용·효과입니다.'));
    if(a==='ultimate')detail.append(node('p','','추가 강화 없음 · 이야기 체득 후 Lv.1'));
    else if(world==='murim')detail.append(node('p','','무림 기술은 이야기 진행으로 체득합니다. 계열 강화는 현실에서 무공 각인을 사용합니다.'));
    else{detail.append(node('p','',a==='signature1'?'Q 기본 Lv.1 → 활성 운용 Lv.2. 안정/절약 중 하나만 활성화되며 두 방향을 해금해도 Lv.3이 되지 않습니다.':'Q 운용 하나 해금 + R 체득 후 Lv.2로 강화합니다.'));for(const n of res.skills.filter(n=>n.family===f&&(branchNode?n.id===branchNode.id:(a==='signature1'?n.branch:!n.branch)))){const card=node('article','skills-upgrade');card.append(node('h4','',n.name+(n.selected?' · 활성':'')),node('p','',n.description.replace(' · 정박 해석은 6초 유지','')),node('p','',`현재: ${n.learned?'해금 완료':'미해금'} · 다음: ${n.branch?'Q Lv.2 · 선택 운용 활성화':'R Lv.2'}`));if(n.id==='seal-window'&&g.worldGrowth.reality.interpretations?.seal==='seal-hold')card.append(node('p','skills-notice','기존 적용 효과: 실제 6초 유지 · 추가 시간 효과 없음'));const why=!safe?place()+'에서 변경 가능':story(g,a)||n.reason;if(n.learned){const b=button(n.selected?'현재 활성 운용':n.branch?'이 운용 활성화 · 무료':'후속 강화 적용 중',()=>transact(x=>R.select(x,f,n.id),'select-'+n.id),'select-'+n.id,!safe||!n.branch||n.selected);b.dataset.select=n.id;card.append(b);}else{card.append(node('p','',why||(n.branch?'구매 후 이 운용 활성화 · 기존 운용은 비활성화':'각인 1개 소비')));const b=button((a==='signature1'&&level(g,f,a)===2?'다른 운용 해금 · ':'')+'각인 1개로 강화',()=>transact(x=>R.upgrade(x,n.id),'upgrade-'+n.id),'upgrade-'+n.id,!!why);b.dataset.upgrade=n.id;card.append(b);}detail.append(card);}}
   }
   const m=g.worldGrowth[world].mastery[f],percent=[5,10,20,30].filter(n=>m>=n).length*3;detail.append(node('p','skills-family-mastery',`기존 계열 숙련 ${m}/30 · 해당 계열 피해 +${percent}%`),node('small','skills-muted','개별 숙련은 유효 행동 기록이며 추가 피해 보너스를 중복 적용하지 않습니다.'));
  }
  layout.append(list,detail);body.append(layout);const status=node('p','skills-status',message);status.setAttribute('role','status');body.append(status);
  const management=node('footer','skills-management'),spent=world==='murim'?passive.spent:Object.values(R.state(g).common).reduce((a,b)=>a+b,0)+R.state(g).learned.length;
  management.append(button('스킬 초기화',()=>{resetting=true;render('reset-confirm');},'reset',!safe||!spent));
  if(resetting){const box=node('section','skills-reset');box.setAttribute('aria-label','스킬 초기화 확인');box.append(node('p','',`${world==='murim'?'수련 포인트':'무공 각인'} ${spent}개를 환불합니다. 투자한 공통 운용${world==='reality'?'과 Q/R 강화':''} 효과가 사라집니다. 이야기 체득·계열 숙련·개별 숙련은 유지되며 현재 생명·기력 비율을 보존합니다.`),button('초기화 확정',()=>transact(x=>world==='murim'?P.reset(x):R.reset(x,'skills'),'reset'),'reset-confirm'),button('취소',()=>{resetting=false;render('reset');},'reset-cancel'));management.append(box);}body.append(management);
  show('무공/스킬',body,[{label:'닫기',secondary:true}],'hero',world==='murim'?'무림 무공':'현실 스킬');list.scrollTop=listScroll;if(focus){const target=[...body.querySelectorAll('[data-skills-focus]')].find(e=>e.dataset.skillsFocus===focus&&!e.disabled);(target||body.querySelector('.skills-detail-title'))?.focus({preventScroll:true});}if(mobile()){const scroller=viewport(body);if(restoreList)scroller.scrollTop=viewportScroll;else if(focus==='detail-title'&&detailOpen)scroller.scrollTop+=detail.getBoundingClientRect().top-scroller.getBoundingClientRect().top;}
 }
 return {open};
}};
})(globalThis);
