(function(root,f){const api=f(typeof module==='object'&&module.exports?require('./passive-growth.js'):root.PassiveGrowth,typeof module==='object'&&module.exports?require('./advancement.js'):root.Advancement,typeof module==='object'&&module.exports?require('./boundary-resonance.js'):root.BoundaryResonance);if(typeof module==='object'&&module.exports)module.exports=api;else root.WorldGrowth=api;})(globalThis,function(Passive,Advance,Resonance){
 'use strict';const families=['ripple','echo','seal'],skillActions=['signature1','signature2','ultimate'],skillMax=30,skillCasts=new WeakMap(),mastery=()=>({sword:0,ripple:0,echo:0,seal:0}),entry=()=>({level:1,xp:0,mastery:mastery(),skillMastery:{},equipped:null,mode:'flow'}),initial=()=>({reality:entry(),murim:entry()});
 function normalizeSkillMastery(raw){const out={};if(!raw||typeof raw!=='object'||Array.isArray(raw))return out;for(const family of families){const row=raw[family];if(!row||typeof row!=='object'||Array.isArray(row))continue;for(const action of skillActions){const n=row[action];if(Number.isInteger(n)&&n>=0)(out[family]||={})[action]=Math.min(skillMax,n);}}return out;}
 function skillMastery(g,world,family,action){const n=['reality','murim'].includes(world)&&families.includes(family)&&skillActions.includes(action)?g.worldGrowth?.[world]?.skillMastery?.[family]?.[action]:undefined,tracked=Number.isInteger(n)&&n>=0;return {value:tracked?Math.min(skillMax,n):0,max:skillMax,tracked};}
 function skillAttainment(g,w,f,a){const m=skillMastery(g,w,f,a),stars=1+[4,8,12,15,19,23,27,30].filter(n=>m.value>=n).length;return {...m,stars,bonus:(stars-1)*.01,proposal:true};}
 function recordSkillMastery(g,world,family,action,token){
  if(!g.worldGrowth?.[world]||!['reality','murim'].includes(world)||world!==worldOf(g)||!families.includes(family)||!skillActions.includes(action)||token==null||g.trial||g.advancementTrial||g.worldState?.resonanceChallenges?.active||['comparison','realmAssessment','hunterAssessment','resonanceForest','resonanceRuins','resonancePass'].includes(g.area))return false;
  const current=skillMastery(g,world,family,action);if(current.value>=skillMax)return false;
  let seen=skillCasts.get(g);if(!seen){seen=new Map();skillCasts.set(g,seen);}const key=world+':'+family+':'+action;let casts=seen.get(key);if(!casts){casts=new Set();seen.set(key,casts);}if(casts.has(token))return false;casts.add(token);
  const w=g.worldGrowth[world];w.skillMastery=normalizeSkillMastery(w.skillMastery);(w.skillMastery[family]||={})[action]=current.value+1;return true;
 }
 const worldOf=g=>g.area&&['resonanceForest','resonanceRuins','resonancePass','village','forest','ruins','sanctum','returnPass','archive','woundPass','woundCore','transportRoad','supplyRidge','overseerApproach','overseerHall','realmAssessment'].includes(g.area)?'murim':'reality';
 function stats(g,world=worldOf(g)){const w=g.worldGrowth[world],murim=world==='murim',resonance=murim?{hp:0,mp:0,attack:0}:Resonance.bonus(g),extra=Advance.bonus(g,world),passive=Passive.bonus(g,world),b=!murim&&g.achievementBonuses?g.achievementBonuses():{hp:0,mp:0,attack:0};return {hp:120+(w.level-1)*18+extra.hp+passive.hp+b.hp+resonance.hp,mp:80+(w.level-1)*5+extra.mp+passive.mp+b.mp+resonance.mp,attack:16+(w.level-1)*3+(murim?(g.training||0)*6:0)+extra.attack+b.attack+resonance.attack,next:70+w.level*45};}
 function grantExperience(g,{world,amount,eventId}){if(!['reality','murim'].includes(world)||!Number.isInteger(amount)||amount<0||amount>100000)throw Error('경험치 지급 정보 오류');if(eventId!==undefined&&(typeof eventId!=='string'||!/^[-a-z0-9:]{1,64}$/.test(eventId)))throw Error('보상 ID 오류');g.questRewards||=[];if(eventId&&g.questRewards.includes(eventId))return false;const w=g.worldGrowth[world],before=w.level;w.xp+=amount;while(w.level<80&&w.xp>=70+w.level*45){w.xp-=70+w.level*45;w.level++;}w.xp=Math.min(w.xp,70+w.level*45-1);if(eventId)g.questRewards.push(eventId);if(w.level>before)g.emit('level-up',{world,level:w.level,count:w.level-before,hp:18*(w.level-before),mp:5*(w.level-before),attack:3*(w.level-before)});g.collectAchievements?.();return true;}
 function validate(raw){const out=initial();for(const world of ['reality','murim']){const w=raw?.[world];if(!w||!Number.isInteger(w.level)||w.level<1||w.level>80||!Number.isInteger(w.xp)||w.xp<0||w.xp>=70+w.level*45||!['flow','focus'].includes(w.mode)||w.equipped!==null&&!families.includes(w.equipped))throw Error('세계 성장 정보 오류');for(const id of ['sword',...families]){if(!Number.isInteger(w.mastery?.[id])||w.mastery[id]<0||w.mastery[id]>30)throw Error('세계 숙련 정보 오류');out[world].mastery[id]=w.mastery[id];}Object.assign(out[world],{level:w.level,xp:w.xp,equipped:w.equipped,mode:w.mode});}return out;}
 const interpretationKeys=['ripple-return','ripple-guard','echo-return','echo-replay','seal-hold','seal-guide'];
 function interpretationMap(raw){if(!raw||Array.isArray(raw)||Object.keys(raw).length!==3||families.some(f=>!Object.hasOwn(raw,f)||raw[f]!==null&&(!interpretationKeys.includes(raw[f])||!raw[f].startsWith(f+'-'))))throw Error('세계별 진화 장착 오류');return {...raw};}
 function installInterpretations(g){
  const old={...g.journey.selected};
  for(const world of ['murim','reality'])if(!g.worldGrowth[world].interpretations)g.worldGrowth[world].interpretations=Object.fromEntries(families.map(f=>[f,g.journey.known.includes(old[f])&&(world==='murim'||g.journey.sync[old[f]]>=1)?old[f]:null]));
  Object.defineProperty(g.journey,'selected',{configurable:true,enumerable:true,get(){return g.worldGrowth[worldOf(g)].interpretations;},set(value){g.worldGrowth[worldOf(g)].interpretations=interpretationMap(value);}});
 }
 function canEquipInterpretation(g,key,world=worldOf(g)){return interpretationKeys.includes(key)&&g.journey.known.includes(key)&&(world==='murim'||g.journey.sync[key]>=1);}
 function settleInterpretations(g){for(const key of g.journey.known)if(interpretationKeys.includes(key)&&g.journey.sync[key]===0)g.journey.sync[key]=1;}
 function validateInterpretations(g){for(const world of ['murim','reality']){const map=interpretationMap(g.worldGrowth[world].interpretations);for(const key of Object.values(map))if(key!==null&&!canEquipInterpretation(g,key,world))throw Error('보유하지 않은 세계 진화');g.worldGrowth[world].interpretations=map;}}
 function validateWithInterpretations(raw){const out=validate(raw);for(const world of ['murim','reality']){out[world].skillMastery=normalizeSkillMastery(raw[world].skillMastery);if(raw[world].interpretations!==undefined)out[world].interpretations=interpretationMap(raw[world].interpretations);}return out;}
 return {families,initial,worldOf,stats,grantExperience,skillMastery,skillAttainment,recordSkillMastery,validate:validateWithInterpretations,installInterpretations,canEquipInterpretation,settleInterpretations,validateInterpretations};
});
