(function(root,f){const n=typeof module==='object'&&module.exports;if(n)require('./chapter-seven.js');const api=f(n?require('./save-v9.js'):root.SaveV9,n?require('./world-growth.js'):root.WorldGrowth,n?require('./save-v10.js'):root.SaveV10,n?require('./world-achievements.js'):root.WorldAchievements,n?require('./reality-skills.js'):root.RealitySkills,n?require('./world-reports.js'):root.WorldReports,n?require('./dual-breath.js'):root.DualBreath,n?require('./personal-news.js'):root.PersonalNews,n?require('./encounter-director.js'):root.EncounterDirector,n?require('./dungeon-entry.js'):root.DungeonEntry,n?require('./passive-growth.js'):root.PassiveGrowth,n?require('./advancement.js'):root.Advancement,n?require('./cycle-one.js'):root.CycleOne,n?require('./growth-arc.js'):root.GrowthArc,n?require('./boundary-resonance.js'):root.BoundaryResonance);if(n)module.exports=api;else root.WorldGame=api;})(globalThis,function(api,Growth,Save,Achievements,Reality,Reports,Dual,News,Director,Dungeon,Passive,Advance,Cycle,Arc,Resonance){
 'use strict';const Base=api.Game,baseSave=Base.prototype.save,baseLoad=Base.load;
 Advance.install(api);Object.assign(api.AREAS,Cycle.areas(api.AREAS));
 api.AREAS.comparison={...api.AREAS.rift,name:'현실 대응 비교 현장',sub:'선택 체험 · 처치 보상 없음',positions:[[470,700],[710,700]],points:[{id:'exit',x:150,y:970,label:'헌터 기지로 귀환',kind:'exit'}]};
 class Game extends Base{
  constructor(){super();this.worldGrowth=Growth.initial();this.questRewards=[];this.worldState={news:{items:[]},growthArc:Arc.initial(),resonance:Resonance.initial()};this.installWorldState();}
  installWorldState(){const g=this;Object.defineProperty(this.journey,'mastery',{configurable:true,enumerable:true,get(){return g.worldGrowth[Growth.worldOf(g)].mastery;},set(v){g.worldGrowth[Growth.worldOf(g)].mastery=v;}});Object.defineProperty(this.journey,'breath',{configurable:true,enumerable:true,get(){return g.worldGrowth[Growth.worldOf(g)].mode;},set(v){g.worldGrowth[Growth.worldOf(g)].mode=v;}});Growth.installInterpretations?.(this);}
  get level(){return this.worldGrowth?this.worldGrowth[Growth.worldOf(this)].level:this._oldLevel||1;}set level(v){if(this.worldGrowth)this.worldGrowth[Growth.worldOf(this)].level=v;else this._oldLevel=v;}
  get xp(){return this.worldGrowth?this.worldGrowth[Growth.worldOf(this)].xp:this._oldXp||0;}set xp(v){if(this.worldGrowth)this.worldGrowth[Growth.worldOf(this)].xp=v;else this._oldXp=v;}
  senseUnlocked(){return !!(Cycle.state(this).invited||Cycle.state(this).legacyAccess||this.journey.phase>0||this.journey.facts.length||this.journey.known.length);}
  sense(){return this.senseUnlocked()?super.sense():false;}
  growthWorld(){return Growth.worldOf(this);}
  passiveEffects(){return Passive.effects(this,Growth.worldOf(this));}
  paidSkillCost(action,cost){return this.worldGrowth&&['moon','storm','signature1','signature2'].includes(action)&&cost>0?Math.max(1,cost-this.passiveEffects().discount):cost;}
  v12ChapterCompleted(n){const c=Cycle.state(this);return n===3?this.fate.stage>=6:n===5?this.journey.phase>=5:n===6?this.laterStory?.six===5:n===7?this.laterStory?.seven===5:n===8?c.eightComplete:n===9?c.nineComplete:false;}
  setBreath(mode){if(!this.worldGrowth)return super.setBreath(mode);if(this.training<(mode==='focus'?2:1)||!api.AREAS[this.area].safe)return false;const before=this.stats(),hp=this.player.hp/before.hp,mp=this.player.mp/before.mp,ok=super.setBreath(mode);if(ok){this.player.hp=hp*this.stats().hp;this.player.mp=mp*this.stats().mp;}return ok;}
  stats(){return this.worldGrowth?Growth.stats(this):super.stats();}
  syncResonance(){return Resonance.sync(this);}
  collectAchievements(){if(this.worldState)return Achievements.collect(this);}
  achievementBonuses(){return Achievements.bonuses(this);}
  validateWorldState(){Arc.validate(this);Growth.validateInterpretations?.(this);Achievements.validate(this);Reality.validate(this);Reports.validate(this);News.validate(this);Dungeon.validate(this);Advance.validate(this);Passive.validate(this);Cycle.validate(this);if(this.worldState.resonance)Resonance.validate(this);const {achievements,reality,reports,news,dungeons,passive,advancement,cycleOne,growthArc,resonance,potionHintSeen=false}=this.worldState;if(typeof potionHintSeen!=='boolean')throw Error('회복약 안내 기록 오류');this.worldState={achievements,reality,reports,news,dungeons,passive,advancement,cycleOne,growthArc,resonance,potionHintSeen};if(this.contract?.status!=='idle'||this.contract?.completed)throw Error('개편판에는 반복 의뢰가 없습니다.');}
  reportFact(id){Reports.collect(this);return Reports.report(this,id);}
  publishNews(item){return News.publish(this,item);}
  refreshNews(){return News.refresh(this);}
  newsList(){return News.list(this);}
  readNews(id){return News.read(this,id);}
  dismissNews(id){return News.dismiss(this,id);}
  unreadNews(section){return News.unread(this,section);}
  realmReady(){return News.realmReady(this);}
  restoreWorldEncounter(){Director.populate(this);Arc.balance(this);Arc.onEnter(this);Cycle.onEnter(this);this.applySevenPreparation?.();this.realityRuntime=null;}
  allowEnemyStep(e){return !(this.area==='overseerHall'&&!Cycle.state(this).confronted)&&Director.allow(this,e); }
  mayStartAttack(e){return Director.mayStartAttack(this,e);}
  prepareEnemyAttack(e){if(e.passagePressure){e.wind=e.windMax=1.2;e.pattern='heavy';e.range=130;e.telegraph={x:e.x,y:e.y,tx:e.tx,ty:e.ty,width:24};return;}if(e.cycleBoss){e.wind=e.windMax=e.cyclePhase===3?.9:1.2;e.pattern=e.attacks%2?'shot':'heavy';e.range=e.pattern==='shot'?24:120;e.telegraph={x:e.x,y:e.y,tx:e.tx,ty:e.ty,width:24};return;}return Director.prepare(this,e);}
  enemyImpact(e){return Director.impact(this,e);}
  enemyThreatContains(e){return Director.contains(this.player,e);}
  laterObjective(){const trial=Advance.progress(this);if(trial)return {chapter:0,purpose:'성장 실전 · '+trial.phase+'/'+trial.phases,currentAction:trial.text,condition:'실제 대응·제압·지점 확보',rewards:[],status:'assessment'};const cycle=Cycle.objective(this);if(cycle)return cycle;const o=super.laterObjective();if(!o)return o;return {...o,currentAction:o.currentAction.replace('자유 탐험과 실전 의뢰','자유 탐험과 무공 운용'),rewards:o.rewards.map(text=>text.replace('경험치 120','현실 경험치 60 · 무림 경험치 60').replace('경험치 180','현실 경험치 90 · 무림 경험치 90'))};}
  objective(){return this.worldState&&Arc.objective(this)||super.objective();}
  target(){return this.worldState&&Arc.objective(this)?.target||super.target();}
  startContract(){return false;}
  claimContract(){return false;}
  cancelContract(){return false;}
  points(){return Dungeon.points(this,[...super.points().filter(p=>p.id!=='contract-board'),...Cycle.points(this)]);}
  potionHint(){if(this.worldState.potionHintSeen||this.potions<=0||this.player.hp>this.stats().hp*.4)return '';this.worldState.potionHintSeen=true;return '회복약을 직접 사용하면 최대 체력의 55%를 회복합니다. 보유 '+this.potions+'개 · 자동 사용되지 않습니다.';}
  regenerateEnemy(e,amount){if(e.realitySuppressedUntil>this.playTime){if(e.hp<e.maxHp&&e.realitySuppressionCast){e.realitySuppressionProven=true;Reality.onEffect(this,e.realitySuppressionCast,e,'suppress');}return;}e.hp=Math.min(e.maxHp,e.hp+amount);}
  onDualLink(e){super.onDualLink(e);Advance.onEffect(this,'link',e);Cycle.onDualLink(this);}
  trainingSpeed(){return Advance.bonus(this,Growth.worldOf(this)).speed;}
  onRealityEffect(e){Arc.onEffect(this,e);Advance.onEffect(this,e.kind,e.target);if(this.advancementTrial)return;const {family,kind,target}=e,key=e.evolution;if(key&&this.journey.known.includes(key)){this.journey.sync[key]=2;this.onInterpretation(key,target);}Dual.contact(this,target,{id:'reality-'+e.castId,family,action:e.action,manual:e.manual,effect:kind});}
  realityStatus(f){return Reality.status(this,f);}
  beginComparison(){if(this.area!=='city'||!this.worldGrowth.reality.equipped)return false;return this.enter('comparison');}
  chooseInterpretation(key){if(Growth.canEquipInterpretation&&!Growth.canEquipInterpretation(this,key))return false;if(Growth.worldOf(this)==='reality'){if(this.area!=='city'||this.advancementTrial||key.split('-')[0]!==this.worldGrowth.reality.equipped)return false;this.journey.selected[key.split('-')[0]]=key;this.realityRuntime=null;return true;}const ok=super.chooseInterpretation(key);if(ok)this.realityRuntime=null;return ok;}
  clearInterpretation(){if(Growth.worldOf(this)==='reality'){if(this.area!=='city'||!this.worldGrowth.reality.equipped)return false;this.journey.selected[this.worldGrowth.reality.equipped]=null;this.realityRuntime=null;return true;}return super.clearInterpretation();}
  equipReality(f){if(!api.AREAS[this.area].safe||Growth.worldOf(this)!=='reality'||!['ripple','echo','seal'].includes(f)||this.realityStatus(f)==='locked')return false;this.worldGrowth.reality.equipped=f;this.realityRuntime=null;return true;}
  skillInfo(a){const k=this.rawSkillInfo(a);return this.worldGrowth?Arc.gate(this,a,k):k;}
  rawSkillInfo(a){if(this.worldGrowth&&Growth.worldOf(this)==='reality')return Reality.info(this,a)||super.skillInfo(a);const k=super.skillInfo(a);return k&&this.worldGrowth?{...k,cost:this.paidSkillCost(a,k.cost)}:k;}
  act(a,held=false){if(this.worldGrowth&&Arc.gate(this,a,this.rawSkillInfo(a))?.locked)return false;const before=this.enemies.map(e=>e.hp),prepared=!!this.trial?.feat&&(this.combat.charges>0||!!this.combat.echo||!!this.combat.field);const ok=this.performAction(a,held);if(ok){if(Arc.defense(this)&&a==='dash'&&this.enemies.some(e=>e.hp>0&&e.wind>0&&this.enemyThreatContains(e)))Arc.runtime(this).hits++;Arc.afterAction(this,a,before,prepared);}return ok;}
  performAction(a,held=false){if(this.worldGrowth&&Growth.worldOf(this)==='reality'){const result=Reality.act(this,a,held);if(result!==null)return result;}return super.act(a,held);}
  takeHit(e){if(Arc.defense(this)&&this.player.invuln<=0&&this.player.hp<=e.damage){Arc.fail(this);return;}const zone=Cycle.safeZone(this);if(zone&&Math.hypot(this.player.x-zone.x,this.player.y-zone.y)<=zone.radius)e={...e,damage:Math.round(e.damage*zone.damageFactor)};if(this.worldGrowth&&Growth.worldOf(this)==='reality'){const radius=this.laterStory?.preparation==='evacuation'?(this.laterStory?.passOpened?240:145):(this.laterStory?.passOpened?180:65);if(this.area==='woundDock'&&e.laterPulse&&Math.hypot(this.player.x-730,this.player.y-700)<radius)return;if(this.player.invuln>0||Reality.absorb(this,e))return;const p=this.player,damage=Math.round((this.area==='returnDock'&&this.chapter4.route==='ripple'&&Math.hypot(p.x-750,p.y-610)<155?e.damage*.5:e.damage)*Reality.damageFactor(this,e));p.hp=Math.max(0,p.hp-damage);p.invuln=.5;p.flash=.18;this.shake=.18;this.effect('text',p.x,p.y-58,{text:'−'+damage,color:'#ffa98e',life:.7,max:.7});this.emit('sound',{name:'hurt'});return;}return super.takeHit(e);}
  strike(e,damage,source='attack',cast=null){if(Arc.defense(this)&&e.hp>0)Arc.runtime(this).hits++;if(Arc.active(this)&&this.area==='heart'&&e.boss&&!Arc.state(this).returnProven){this.toast('공격 예고에 Q로 대응해 새 호흡을 먼저 재현하세요.');return 0;}if(e.cycleBoss&&!Cycle.state(this).confronted)return 0;if(this.worldGrowth&&/^reality(?:-ultimate)?:/.test(source)){const value=this.worldGrowth.reality.mastery[source.split(':')[1]]||0;damage=Math.round(damage*(1+.03*[5,10,20,30].filter(n=>value>=n).length));}if(this.worldGrowth&&Growth.worldOf(this)==='reality'&&source==='attack'&&this.legendRuntime.manual){const r=Reality.runtime(this);if(r.boost?.until>this.playTime){damage=Math.round(damage*r.boost.mult);r.boost=null;}}if(this.worldGrowth&&e?.hp>0)e.alerted=true;return super.strike(e,damage,source,cast);}
  step(dt,input={}){const at=this.playTime,area=this.area;if(this.worldGrowth&&Number.isFinite(dt)&&dt>0&&this.hitStop<=0)Director.step(this,Math.min(dt,.05));super.step(dt,input);Arc.step(this,this.playTime-at);Advance.step(this,this.playTime-at);Cycle.step(this,this.playTime-at);const zone=Cycle.safeZone(this);if(zone)this.effect('fate-field',zone.x,zone.y,{path:'ripple',range:zone.radius,life:.1,max:.1});if(this.worldGrowth&&area===this.area&&this.playTime>at&&Growth.worldOf(this)==='reality')Reality.step(this);if(this.worldState){Reports.collect(this);this.refreshNews();}}
  breakthrough(){return Advance.confirm(this,'realm');}
  grantExperience(info){return Growth.grantExperience(this,info);}
  activeFamily(){return this.worldGrowth?this.worldGrowth[Growth.worldOf(this)].equipped:this.fate.path;}
  acceptFate(path){if(this.worldGrowth&&this.worldGrowth.murim.equipped===path&&this.revision.inherited.includes(path))return false;const ok=super.acceptFate(path);if(ok&&Arc.active(this))Arc.state(this).phase='learned';if(ok&&this.worldGrowth){this.worldGrowth.murim.equipped=path;this.syncResonance();}return ok;}
  awaken(path){if(Arc.active(this)&&this.fate.stage<2)return false;const ok=super.awaken(path);if(ok&&Arc.active(this))Arc.state(this).phase='learned';if(ok&&this.worldGrowth){this.worldGrowth.murim.equipped=path;this.syncResonance();}return ok;}
  emit(type,extra){if(this.worldGrowth&&type==='transfer')return;const start=this.events.length,result=super.emit(type,extra);if(Arc.active(this)&&type==='awakening'&&extra?.path){for(const e of this.events.slice(start))if(e.type==='awakening'&&e.inheritance)e.text='지키지 못했던 통로의 압력을 하나의 호흡으로 받아냈다.'+'\n\nQ · '+api.Fate.PATHS[extra.path].skills[0][0]+'\nR은 구조 경험 이후 별도 수련으로, F는 7장 위기의 실전에서 완성합니다.';}return result;}
  reward(e){if(e.passageDefense){e.rewarded=true;return;}if(e.assessment){e.rewarded=true;return;}Cycle.onDefeat(this,e);if(e.residual)return;if(e.comparison){e.rewarded=true;return;}if(!this.worldGrowth)return super.reward(e);const w=Growth.worldOf(this),before=this.level,xp=this.xp,events=this.events.length;super.reward(e);Reports.onDefeat(this,e);const after=this.level;let amount=this.xp-xp;for(let level=before;level<after;level++)amount+=70+level*45;this.worldGrowth[w].level=before;this.worldGrowth[w].xp=xp;this.events=this.events.filter((e,i)=>i<events||e.type!=='level-up');if(amount>0)this.grantExperience({world:w,amount});}
  interact(){if(!this.worldGrowth)return super.interact();const pointId=this.nearestPoint()?.id;const arcScene=Arc.interact(this,pointId);if(arcScene)return arcScene;if(pointId==='warden'&&Advance.report(this))return {type:'dialog',title:'공식 평가 결과 · 승급 확정',text:Advance.describe(this,'hunter').name+'급 평가를 승인했습니다. 현실 거점의 성장 화면에서 훈련 방향을 선택하세요.',portrait:'warden'};const scene=Cycle.interact(this,pointId)||Cycle.earlyDialogue(this,pointId);if(scene)return scene;if(this.nearestPoint()?.kind===Dungeon.ENTRANCE)return {type:'dungeon-select'};const before=Object.fromEntries(Object.entries(this.worldGrowth).map(([k,v])=>[k,{level:v.level,xp:v.xp}])),six=this.laterStory?.six,seven=this.laterStory?.seven,point=this.nearestPoint()?.id,progress=this.progress,events=this.events.length,result=super.interact();let total=0;for(const [world,start]of Object.entries(before)){const current=this.worldGrowth[world];let amount=current.xp-start.xp;for(let level=start.level;level<current.level;level++)amount+=70+level*45;total+=amount;Object.assign(current,start);}const report=six!==5&&this.laterStory?.six===5?'six':seven!==5&&this.laterStory?.seven===5?'seven':null;if(total>0||report){this.events=this.events.filter((e,i)=>i<events||e.type!=='level-up');if(report){for(const world of ['murim','reality'])this.grantExperience({world,amount:report==='six'?60:90,eventId:report+'-report-'+world});}else this.grantExperience({world:['master'].includes(point)?'murim':Growth.worldOf(this),amount:total,eventId:'quest:'+progress+':'+point+':'+(this.chapter4?.phase||0)+':'+(this.journey?.phase||0)});}const dialogue=Reports.dialogue(this,point,result);if(dialogue?.type==='dialog')dialogue.text=dialogue.text.replace('항만 출입구를 열어 뒀어','현실 던전 입구에서 항만을 선택할 수 있어').replace('동북쪽 항만 출입구를 열어두었어요','현실 던전 입구에서 항만을 선택해 주세요').replace('동북쪽 월영 폐사로 가거라','무림 탐험지 입구에서 월영 폐사를 선택하거라').replace('남동쪽 D급 균열을 맡아 주세요','현실 던전 입구에서 균열을 선택해 주세요');return dialogue;}
  enter(id){if(this.worldGrowth&&this.area==='overseerHall'&&this.player.hp<=0){id='overseerHall';Cycle.onPlayerDefeat(this);this.player.hp=this.stats().hp;this.player.mp=this.stats().mp;}if(this.worldGrowth&&(!Advance.canEnter(this,id)||Cycle.areaIds.includes(id)&&!Cycle.canEnter(this,id)||!Dungeon.canEnter(this,id)))return false;const previous=this.area,normalReturn=this.player.hp>0;if(this.worldGrowth)this.collectAchievements();const ok=super.enter(id);if(ok){if(this.worldGrowth){Director.populate(this);Arc.balance(this);Arc.onEnter(this);this.applySevenPreparation?.();Cycle.onEnter(this);const scene=Cycle.sighting(this);if(scene)this.emit('dialog',scene);}this.realityRuntime=null;if(id==='comparison'){this.enemies=this.enemies.slice(0,2);for(const e of this.enemies)Object.assign(e,{boss:false,comparison:true,hp:140,maxHp:140,damage:18});Object.assign(this.player,{x:400,y:700,face:0});}}if(ok&&this.worldGrowth&&Growth.worldOf({area:previous})!==Growth.worldOf(this)){this.combat.charges=0;this.combat.echo=null;this.combat.field=null;if(this.experimentRuntime){this.experimentRuntime.pending=[];this.experimentRuntime.charge=0;this.experimentRuntime.guard=null;}if(Growth.worldOf(this)==='reality'){Achievements.settle(this);if(normalReturn&&Arc.active(this)&&!this.worldGrowth.reality.equipped&&this.worldGrowth.murim.equipped&&api.AREAS[this.area].safe){this.equipReality(this.worldGrowth.murim.equipped);this.emit('dialog',{title:'현실에 이어진 첫 호흡',text:'무림에서 익힌 원리가 현실의 몸에도 남았다.\n\nQ · '+Reality.table[this.worldGrowth.reality.equipped][0][0]+'\n지금 사용할 수 있습니다. 압력의 예고를 보고 Q로 대응한 뒤, 기본 검격이나 K/L로 이어 가세요. R과 F는 아직 익히지 않았습니다.',portrait:'hero'});}if(normalReturn){Passive.settle(this);Growth.settleInterpretations?.(this);}if(api.AREAS[this.area].safe){this.player.hp=this.stats().hp;this.player.mp=this.stats().mp;}}}return ok;}
  save(){this.syncResonance();this.refreshNews();Passive.sync(this);Advance.sync(this);Cycle.sync(this);return Advance.withSaveSnapshot(this,()=>Save.save(this,baseSave));}
  static load(raw){return Save.load(raw,Game,baseLoad);}
 }
 return {...api,Game,Growth};
});
