const test=require('node:test'),assert=require('node:assert/strict');
let R;try{R=require('../boundary-resonance.js');}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
function game(){return {area:'city',training:1,progress:12,player:{hp:60,mp:40},enemies:[],revision:{inherited:['ripple']},worldGrowth:{murim:{level:1,mastery:{ripple:0,echo:0,seal:0}},reality:{mode:'flow',equipped:'ripple'}},journey:{realm:0,phase:0,known:[],sync:{}},chapter4:{phase:0},laterStory:{},worldState:{achievements:{settled:['inherit:first','inherit:ripple'],results:[]},growthArc:{learnedR:false}},stats(){const b=R.bonus(this);return {hp:120+b.hp,mp:80+b.mp,attack:16+b.attack};}};}
function setup(){assert.ok(R,'BoundaryResonance model is available');const g=game();g.worldState.resonance=R.initial();R.sync(g);return g;}
test('permanent first inheritance gives eight crystals once; recommended allocation preserves health ratio',()=>{const g=setup();assert.equal(R.balance(g).crystal,8);const before=R.balance(g).seal;R.sync(g);assert.deepEqual(R.balance(g),{crystal:8,seal:before});assert.ok(R.allocate(g,{attack:4,hp:4,mp:0}));assert.deepEqual(g.stats(),{hp:144,mp:80,attack:20});assert.equal(g.player.hp,72);assert.equal(R.balance(g).crystal,0);assert.equal(R.reset(g,'stats'),false);assert.equal(R.balance(g).crystal,0);assert.equal(g.player.hp,72);});
test('confirmed crystal stats cannot be reduced, reallocated or reset, even when the total increases',()=>{const g=setup();assert.ok(R.allocate(g,{attack:1,hp:1,mp:0}));const before=JSON.stringify({state:g.worldState.resonance,player:g.player});for(const a of [{attack:0,hp:1,mp:0},{attack:0,hp:2,mp:0},{attack:0,hp:3,mp:0}]){assert.equal(R.allocate(g,a),false);assert.equal(JSON.stringify({state:g.worldState.resonance,player:g.player}),before);}assert.equal(R.reset(g,'stats'),false);assert.equal(JSON.stringify({state:g.worldState.resonance,player:g.player}),before);assert.ok(R.allocate(g,{attack:1,hp:2,mp:0}));assert.equal(R.balance(g).crystal,5);});
test('foreign world and combat reject investments without losing currency',()=>{const g=setup(),s=JSON.stringify(g.worldState.resonance);g.area='village';assert.equal(R.allocate(g,{attack:1,hp:0,mp:0}),false);assert.equal(R.upgrade(g,'ripple-window'),false);assert.equal(JSON.stringify(g.worldState.resonance),s);g.area='city';g.enemies=[{hp:1}];assert.equal(R.allocate(g,{attack:1,hp:0,mp:0}),false);});
test('node purchase is idempotent and Q variants are mutually active; R requires learned R',()=>{const g=setup();assert.equal(R.upgrade(g,'ripple-follow'),false);assert.ok(R.upgrade(g,'ripple-window'));const b=R.balance(g);assert.equal(R.upgrade(g,'ripple-window'),false);assert.deepEqual(R.balance(g),b);assert.ok(R.upgrade(g,'ripple-economy'));assert.equal(R.effects(g,'ripple').discountQ,2);assert.equal(R.effects(g,'ripple').guardWindow,.7);assert.ok(R.select(g,'ripple','ripple-window'));assert.equal(R.effects(g,'ripple').guardWindow,.9);assert.equal(R.effects(g,'ripple').discountQ,0);g.chapter4.phase=4;g.worldState.growthArc.learnedR=true;R.sync(g);assert.ok(R.upgrade(g,'ripple-follow'));assert.equal(R.effects(g,'ripple').discountR,2);});
test('limits, malformed allocations and forged grants are rejected',()=>{const g=setup();for(const a of [{attack:5,hp:0,mp:0},{attack:-1,hp:0,mp:0},{attack:1.5,hp:0,mp:0},{attack:0,hp:9,mp:0},{attack:0,hp:0,mp:0,other:1}])assert.equal(R.allocate(g,a),false);R.validate(g);g.worldState.resonance.grants.push('mastery:seal:10');assert.throws(()=>R.validate(g),/공명/);});
test('common upgrades retain rank costs and prerequisites, reset returns only spent points',()=>{const g=setup();assert.equal(R.upgrade(g,'F3'),false);assert.ok(R.upgrade(g,'F1'));assert.equal(R.levels(g).F1,1);assert.equal(R.levels(g).F0,1);assert.equal(R.levels(g).C0,0);assert.ok(R.upgrade(g,'F1'));assert.equal(R.levels(g).F1,2);const total=R.balance(g).seal+2;assert.ok(R.reset(g,'skills'));assert.equal(R.balance(g).seal,total);assert.equal(R.levels(g).F1,0);assert.equal(R.levels(g).F0,1);});
test('goal tracking is optional and never pays a reward',()=>{const g=setup(),b=R.balance(g);assert.ok(R.setGoal(g,'precision'));assert.equal(R.describe(g).goal,'precision');assert.ok(R.setGoal(g,null));assert.equal(R.setGoal(g,'unlimited'),false);assert.deepEqual(R.balance(g),b);});
test('observatory practical completion opens the last cap before NPC reporting',()=>{const g=setup();g.fate={stage:6};g.journey.phase=3;assert.equal(R.limits(g).total,20);g.journey.phase=4;assert.equal(R.limits(g).total,30);assert.equal(R.limits(g).attack,12);});
