'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const readyModule=fs.existsSync(require('node:path').join(__dirname,'../sequel.js'));
const api=readyModule?require('../sequel.js'):require('../game.js');
const {Game,AREAS}=api;
function base(path='ripple'){const g=new Game();g.progress=12;g.training=3;g.fate={stage:6,path,proven:[path],discovered:[path],feats:{ripple:1,echo:1,seal:1},focus:100};return g;}
function talk(g,id){const o=AREAS[g.area].points.find(x=>x.id===id);assert.ok(o,`point ${id} exists`);Object.assign(g.player,{x:o.x,y:o.y});return g.interact();}
function start(path='ripple'){assert.ok(readyModule,'chapter-four rules must exist');const g=base(path);g.enter('city');talk(g,'warden');assert.equal(g.chapter4.phase,1);g.enter('returnPass');return g;}
function pulse(g){g.storyRuntime.pulse={wind:.5,max:1,cd:0,x:700,y:630,range:135};Object.assign(g.player,{x:660,y:630,invuln:0,mp:500});g.events=[];}
function resolve(path){const g=start(path);pulse(g);if(path==='ripple'){g.act('signature1');g.takeHit({storyPulse:true,hp:9999,id:'return-pulse',x:700,y:630,damage:20,r:10,wind:0,attacks:1});}if(path==='echo'){g.player.face=Math.PI;g.act('signature1');for(let i=0;i<6;i++)g.step(.05);g.storyRuntime.pulse.wind=.5;g.act('signature2');}if(path==='seal'){g.act('signature1');g.step(.02);}return g;}
function defeatAll(g){for(const e of g.enemies.filter(e=>!e.boss))g.strike(e,100000,'storm');const b=g.enemies.find(e=>e.boss);g.strike(b,100000,'storm');}
test('chapter four has a gated start and no automatic skill award',()=>{assert.ok(readyModule);const g=new Game();talk(g,'warden');assert.equal(g.chapter4.phase,0);const h=base();const before=JSON.stringify(h.fate);talk(h,'warden');assert.equal(h.chapter4.phase,1);assert.equal(JSON.stringify(h.fate),before);});
for(const path of ['ripple','echo','seal'])test(`real ${path} action changes route without a mentor hand-in`,()=>{const g=resolve(path);assert.equal(g.chapter4.route,path);assert.equal(g.chapter4.rescued,true);assert.equal(g.area,'returnPass');assert.equal(g.fate.path,path);assert.ok(g.chapter4.feed.some(x=>x.kind==='npc'));});
test('quiet button presses and arbitrary skill grants cannot unlock rescue',()=>{const g=start('seal');g.enemies=[];g.storyRuntime.pulse={wind:0,max:1,cd:10,x:700,y:630,range:135};g.player.x=660;g.player.y=630;g.act('signature1');g.step(.02);assert.equal(g.chapter4.route,null);});
test('a common-combat detour remains possible without the correct timing',()=>{const g=start();defeatAll(g);const before=g.gold;talk(g,'winch');assert.equal(g.chapter4.route,'detour');assert.equal(g.chapter4.rescued,true);assert.equal(g.chapter4.phase,2);talk(g,'winch');assert.equal(g.gold,before);});
test('world collision opens and the rescued NPC actually returns to village',()=>{const g=start();assert.equal(g.blocked(775,600,16),true);defeatAll(g);talk(g,'winch');assert.equal(g.blocked(775,600,16),false);g.enter('village');const npc=AREAS.village.points.find(x=>x.id==='returned-yeonhwa');assert.ok(api.visiblePoint(g,npc));assert.match(talk(g,'returned-yeonhwa').text,/돌아|기억|길/);});
test('unrescued NPC and unopened entrances are not interactable',()=>{const g=new Game();const npc=AREAS.village.points.find(x=>x.id==='returned-yeonhwa');assert.equal(api.visiblePoint(g,npc),false);g.enter('village');assert.equal(g.nearestPoint()?.id==='returned-yeonhwa',false);});
test('three outcomes carry a different useful world effect into the next battle',()=>{for(const path of ['ripple','echo','seal']){const g=resolve(path);defeatAll(g);assert.equal(g.chapter4.phase,2);g.enter('returnDock');const hp=g.player.hp;Object.assign(g.player,{x:750,y:610,invuln:0});if(path==='ripple'){g.takeHit({damage:20,id:'attack-fixture',hp:500,x:800,y:610});assert.ok(g.player.hp>hp-17);}if(path==='echo'){const e=g.enemies[0];e.x=790;e.y=610;e.hp=500;g.strike(e,10,'attack');assert.ok(e.hp<490);}if(path==='seal'){const e=g.enemies[0];Object.assign(e,{x:750,y:610,wind:.7,windMax:1,attacks:2});g.step(.01);assert.equal(e.wind,0);}}});
test('story resolves through both encounters and reporting but no new path is dispensed',()=>{const g=resolve('echo');defeatAll(g);g.enter('returnDock');defeatAll(g);assert.equal(g.chapter4.phase,3);g.enter('city');talk(g,'warden');assert.equal(g.chapter4.phase,4);assert.equal(g.fate.path,'echo');assert.equal(g.progress,12);const feed=g.chapter4.feed.length;talk(g,'warden');assert.equal(g.chapter4.feed.length,feed);});
test('v0.6 checkpoint preserves world consequences and truthful bounded NPC feed',()=>{const g=resolve('ripple');defeatAll(g);const h=Game.load(g.save());assert.equal(JSON.parse(g.save()).version,5);assert.equal(h.chapter4.route,'ripple');assert.equal(h.chapter4.rescued,true);assert.equal(h.area,'village');assert.ok(h.chapter4.feed.length>0);});
test('v4 migration does not invent chapter-four history or online users',()=>{const g=base();const d=JSON.parse(g.save());d.version=4;delete d.chapter4;const h=Game.load(JSON.stringify(d));assert.equal(h.chapter4.phase,0);assert.equal(h.chapter4.feed.length,0);assert.equal(h.fate.path,'ripple');});
test('invalid future-world saves are rejected instead of poisoning UI',()=>{const g=resolve('seal');const d=JSON.parse(g.save());d.chapter4.route='constructor';assert.throws(()=>Game.load(JSON.stringify(d)));d.chapter4.route='seal';d.chapter4.phase=50;assert.throws(()=>Game.load(JSON.stringify(d)));});
test('broken river crossing cannot be bypassed by just walking around the lower barrier',()=>{const g=start();assert.equal(g.blocked(775,820,16),true);assert.equal(g.blocked(775,500,16),true);assert.equal(g.blocked(775,340,16),false);});
test('both chapter-four routes and actors are walk-reachable via the visible northern detour',()=>{
 for(const area of ['returnPass','returnDock']){const g=start();g.enter(area);const a=AREAS[area],step=20,cols=Math.floor(a.w/step),rows=Math.floor(a.h/step),seen=new Set(),q=[];
 const cx=Math.round(g.player.x/step),cy=Math.round(g.player.y/step);q.push([cx,cy]);seen.add(cx+','+cy);
 for(let i=0;i<q.length;i++){const [x,y]=q[i];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=nx+','+ny;if(nx<=0||ny<=0||nx>=cols||ny>=rows||seen.has(key)||g.blocked(nx*step,ny*step,16))continue;seen.add(key);q.push([nx,ny]);}}
 for(const o of [...a.points,...g.enemies])assert.ok(q.some(([x,y])=>Math.hypot(x*step-o.x,y*step-o.y)<65),`${area}: ${o.id} unreachable`);
 }
});
test('after the ending village guidance points to the person actually saved',()=>{const g=resolve('ripple');defeatAll(g);g.enter('returnDock');defeatAll(g);g.enter('city');talk(g,'warden');g.enter('village');assert.equal(g.objective().target.id,'returned-yeonhwa');});
test('a chapter-three finisher in the martial world is guided back to reality for the new story',()=>{const g=base();g.enter('village');assert.equal(g.objective().chapter,4);assert.equal(g.objective().target.id,'portal');assert.match(g.objective().text,/서린/);});
