const test=require('node:test'),assert=require('node:assert/strict');
const Audio=require('../combat-audio.js');
function context(){const nodes=[];const param=()=>({setValueAtTime(){},exponentialRampToValueAtTime(){},cancelScheduledValues(){}});return {state:'running',currentTime:0,destination:{},nodes,resume:async()=>{},createGain(){return {gain:param(),connect(){},disconnect(){}};},createOscillator(){const n={frequency:param(),connect(){},disconnect(){},start(){},stop(){this.stopped=true;}};nodes.push(n);return n;}};}
test('gesture unlock is required; mute and all gains survive reload',async()=>{const data={},storage={getItem:k=>data[k],setItem:(k,v)=>data[k]=v},c=context(),a=Audio.create({storage,contextFactory:()=>c});assert.equal(a.play({kind:'hit'}),false);a.setSettings({muted:false,master:.4,combat:.2,music:0,ui:.6});await a.unlock();assert.equal(a.play({kind:'hit'}),true);assert.deepEqual(Audio.create({storage}).settings(),a.settings());a.setSettings({muted:true});assert.equal(a.play({kind:'telegraph'}),false);});
test('blocked context never queues stale sounds or rejects',async()=>{const a=Audio.create({contextFactory:()=>{throw Error('blocked');}});a.setSettings({muted:false});assert.equal(await a.unlock(),false);assert.equal(a.play({kind:'hurt'}),false);const b=Audio.create({contextFactory:()=>({...context(),state:'suspended',resume:()=>Promise.reject(Error('blocked'))})});assert.equal(await b.unlock(),false);b.clear();});
test('dedup includes cast hit target result; variations never repeat successively',async()=>{const a=Audio.create({contextFactory:context});a.setSettings({muted:false});await a.unlock();const e={kind:'hit',castId:1,hit:0,target:'a',result:'hit'};assert.equal(a.play(e),true);assert.equal(a.play(e),false);assert.equal(a.play({...e,target:'b'}),true);assert.equal(a.play({...e,hit:1}),true);const variants=[];for(let i=0;i<12;i++){a.play({...e,castId:2+i});variants.push(a.inspect().lastVariant);}assert.ok(variants.every((v,i)=>!i||v!==variants[i-1]));});
test('20 ordinary voices leave four critical slots and danger displaces repetition',async()=>{const c=context(),a=Audio.create({contextFactory:()=>c});a.setSettings({muted:false});await a.unlock();for(let i=0;i<30;i++)a.play({kind:'hit',castId:i});assert.equal(a.inspect().voices,20);for(let i=0;i<8;i++)assert.equal(a.play({kind:'telegraph',castId:'danger'+i}),true);assert.equal(a.inspect().voices,24);assert.equal(a.inspect().critical,8);a.clear();assert.equal(a.inspect().voices,0);assert.ok(c.nodes.every(n=>n.stopped));});
test('success grouping excludes telegraphs and previews do not emit game events',async()=>{const a=Audio.create({contextFactory:context});a.setSettings({muted:false});await a.unlock();assert.equal(a.play({kind:'counter',castId:1}),true);assert.equal(a.play({kind:'counter',castId:2}),false);assert.equal(a.play({kind:'telegraph',castId:3}),true);assert.equal(a.play({kind:'telegraph',castId:4}),true);assert.equal(await a.preview('hurt'),false);assert.equal(await a.preview('hit'),true);});

test('fresh audio is audible after gesture, explicit mute remains muted',async()=>{const a=Audio.create({contextFactory:context});assert.equal(a.settings().muted,false);await a.unlock();assert.equal(a.play({kind:'hit'}),true);const b=Audio.create({storage:{getItem:()=>JSON.stringify({muted:true})},contextFactory:context});await b.unlock();assert.equal(b.play({kind:'hit'}),false);});
