const test=require('node:test'),assert=require('node:assert/strict'),Events=require('../combat-events.js');
class Game{constructor(){this.events=[];this.area='forest';this.playTime=1;this.player={hp:100,x:0,y:0};this.enemies=[];this.combat={charges:0};}emit(type,e){this.events.push({type,...e});}act(action){if(action==='blocked')return false;if(this.enemies[0])this.strike(this.enemies[0],10);return true;}strike(e,n){if(e.hp<=0)return 0;const hp=e.hp;e.hp=Math.max(0,hp-n);return hp-e.hp;}takeHit(e){if(this.player.invuln)return;this.player.hp-=e.damage;}prepareEnemyAttack(e){e.wind=1;}enemyImpact(){return false;}enter(id){this.area=id;return true;}onRealityEffect(){}onDualLink(){}step(){}move(p,x,y){p.x+=x;p.y+=y;}}
Events.install(Game,{worldOf:()=> 'murim'});
const sounds=g=>g.events.filter(e=>e.type==='combat-sound');
test('rejected action silent; miss has swing only, contact and kill are actual',()=>{const g=new Game();g.act('blocked');assert.equal(sounds(g).length,0);g.act('attack');assert.deepEqual(sounds(g).map(e=>e.kind),['swing']);g.events=[];g.enemies=[{id:'a',hp:10}];g.act('attack');assert.deepEqual(sounds(g).map(e=>e.kind),['swing','hit','kill']);const s=sounds(g);assert.equal(s[0].castId,s[1].castId);g.events=[];g.strike(g.enemies[0],10);assert.equal(sounds(g).length,0);});
test('damage, immunity, actual ability outcomes, warnings and transition',()=>{const g=new Game(),e={id:'a',hp:10,damage:5};g.takeHit(e);assert.equal(sounds(g)[0].kind,'hurt');g.events=[];g.player.invuln=1;g.takeHit(e);assert.equal(sounds(g).length,0);g.onRealityEffect({kind:'suppress',castId:7,target:e});g.onRealityEffect({kind:'evade',castId:8,target:e});g.prepareEnemyAttack(e);g.enemyImpact(e);assert.deepEqual(sounds(g).map(e=>e.kind),['suppress','evade','telegraph','launch']);g.enter('city');assert.equal(g.events.at(-1).type,'audio-clear');});
test('dash only sounds after successful movement',()=>{const g=new Game();g.act('dash');assert.equal(sounds(g).length,0);g.player.dash=.1;g.move(g.player,0,0);assert.equal(sounds(g).length,0);g.move(g.player,10,0);assert.equal(sounds(g)[0].kind,'move');g.move(g.player,10,0);assert.equal(sounds(g).length,1);});
test('real runtime emits actual absorption, suppression and two separate delayed hits',()=>{const api=require('../world-game.js'),{inherited,opponent}=require('./world-fixtures.cjs');Events.install(api.Game,{worldOf:api.Growth.worldOf});const g=inherited('ripple'),e=opponent(g);g.events=[];assert.equal(g.act('signature1'),true);g.takeHit(e);assert.ok(sounds(g).some(x=>x.kind==='absorb'));assert.ok(!sounds(g).some(x=>x.kind==='hurt'));g.events=[];assert.equal(g.act('signature1'),false);assert.equal(sounds(g).length,0);g.player.cool.storm=0;g.act('storm');g.hitStop=0;for(let i=0;i<6;i++){g.hitStop=0;g.step(.05);}const hits=sounds(g).filter(x=>x.kind==='hit');assert.equal(hits.length,2);assert.equal(hits[0].castId,hits[1].castId);assert.notEqual(hits[0].hit,hits[1].hit);const seal=inherited('seal'),target=opponent(seal);target.wind=.8;seal.events=[];seal.act('signature1');assert.equal(sounds(seal).filter(x=>x.kind==='suppress').length,1);});
test('attainment from nested action/link is announced once and previous saves remain quiet',()=>{class Learning{constructor(known=false){this.player={x:0,y:0};this.enemies=[];this.events=[];this.laterStory={dualBreath:known};}emit(type,e){this.events.push({type,...e});}act(){this.onDualLink();return true;}onDualLink(){this.laterStory.dualBreath=true;}step(){this.act();}}Events.install(Learning);const g=new Learning();g.act();g.step(.05);assert.equal(sounds(g).filter(e=>e.kind==='attain').length,1);const saved=new Learning(true);saved.act();saved.step(.05);assert.equal(sounds(saved).filter(e=>e.kind==='attain').length,0);});
