'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const api=fs.existsSync(path.join(__dirname,'../cultivation.js'))?require('../cultivation.js'):require('../journey.js');
const {Game,AREAS}=api;const {g0,experiment}=require('./helpers/journey.cjs');
function equipped(p,m){const g=g0(p);experiment(g,p,m);g.chooseInterpretation(p+'-'+m);g.enter('forest');g.events=[];g.player.invuln=0;g.player.mp=500;g.hitStop=0;return g;}
function foe(g){const e=g.enemies[0];g.enemies=[e];Object.assign(g.player,{x:850,y:700,face:0});Object.assign(e,{x:895,y:700,hp:4000,maxHp:4000,wind:0,cd:99,range:50});return e;}
function step(g,n=20){for(let i=0;i<n;i++){g.hitStop=0;g.step(.05);}}
test('effective progression and safe trade APIs exist',()=>{assert.equal(typeof Game.prototype.tradeMaterial,'function');assert.equal(typeof Game.prototype.breakthrough,'function');});
test('ripple return charges an actual piercing follow-up and spends it on a whiff',()=>{const g=equipped('ripple','return'),e=foe(g);g.act('signature2');assert.ok(g.experimentRuntime.charge>0);const hp=e.hp;g.player.cool.attack=0;g.act('attack');assert.ok(e.hp<hp-g.stats().attack);assert.equal(g.experimentRuntime.charge,0);g.player.cool.signature2=0;g.act('signature2');g.enemies=[];g.player.cool.attack=0;g.act('attack');assert.equal(g.experimentRuntime.charge,0);});
test('ripple guard protects its actual area independently of a parry',()=>{const g=equipped('ripple','guard'),e=foe(g);g.act('signature1');g.combat.parry=0;const hp=g.player.hp;g.takeHit({...e,damage:40});assert.ok(hp-g.player.hp<=24);assert.ok(g.experimentRuntime.guard);});
test('echo replay does not teleport but deals a delayed hit at a remaining echo',()=>{const g=equipped('echo','replay'),e=foe(g);g.combat.echo={x:e.x,y:e.y,life:4};g.player.x=780;const x=g.player.x,hp=e.hp;assert.equal(g.act('signature2'),true);assert.equal(g.player.x,x);assert.equal(e.hp,hp);step(g);assert.ok(e.hp<hp);});
test('echo return still moves to the anchor and adds a return pulse',()=>{const g=equipped('echo','return'),e=foe(g);g.combat.echo={x:800,y:700,life:4};g.act('signature2');assert.equal(g.player.x,800);assert.ok(g.player.invuln>=.69);assert.ok(g.fx.some(f=>f.kind==='interpret-echo-return'));});
test('seal hold extends the field and locks an actual telegraphed enemy',()=>{const g=equipped('seal','hold'),e=foe(g);e.wind=.7;g.act('signature1');assert.ok(g.combat.field.life>=6);assert.ok(e.root>0);});
test('seal guide repositions a hostile target without bypassing collision',()=>{const g=equipped('seal','guide'),e=foe(g);e.wind=.7;const x=e.x;g.act('signature2');assert.ok(e.x>x);assert.ok(!g.blocked(e.x,e.y,e.r));assert.ok(g.fx.some(f=>f.kind==='interpret-seal-guide'));});
test('empty inputs grant no mastery, invalid targets cannot mint resources',()=>{const g=equipped('echo','return');g.enemies=[];g.act('attack');assert.equal(g.journey.mastery.sword,0);const fake={hp:10,boss:false,rewarded:false};g.reward(fake);assert.equal(g.journey.materials,0);});
test('live basic attacks earn bounded mastery and world experience',()=>{const g=g0();g.enter('rift');const e=foe(g);for(let i=0;i<20;i++){g.player.cool.attack=0;g.act('attack');}assert.ok(g.journey.mastery.sword>0&&g.journey.mastery.sword<=3);assert.deepEqual(g.journey.worlds,['현실']);});
test('a live reality kill grants one bounded material reward, never twice',()=>{const g=g0();g.enter('rift');const e=foe(g);g.strike(e,99999);assert.equal(g.journey.materials,1);g.reward(e);assert.equal(g.journey.materials,1);});
test('lens and material sales require a hub and enough resources',()=>{const g=g0();g.journey.materials=3;g.gold=100;g.enter('village');assert.equal(g.tradeMaterial('lens'),true);assert.equal(g.senseRange(),340);assert.equal(g.journey.materials,1);assert.equal(g.gold,40);assert.equal(g.tradeMaterial('sell'),true);assert.equal(g.gold,70);assert.equal(g.tradeMaterial('sell'),false);g.enter('forest');assert.equal(g.tradeMaterial('lens'),false);});
test('breath is reversible at a hub, focus benefits spaced actual attacks',()=>{const g=g0();g.enter('village');assert.equal(g.setBreath('focus'),true);g.enter('forest');const e=foe(g),hp=e.hp;g.act('attack');assert.ok(hp-e.hp>g.stats().attack);assert.equal(g.setBreath('flow'),false);});
test('realm breakthrough requires mastery, both worlds, and an actual interpretation',()=>{const g=equipped('ripple','return');g.enter('village');assert.equal(g.breakthrough(),false);g.journey.mastery.ripple=8;g.journey.worlds=['무림','현실'];const hp=g.stats().hp;assert.equal(g.breakthrough(),true);assert.ok(g.stats().hp>hp);assert.equal(g.breakthrough(),false);});
test('travel removes all delayed attacks and field guards',()=>{const g=equipped('echo','replay'),e=foe(g);g.combat.echo={x:e.x,y:e.y,life:5};g.act('signature2');g.enter('city');assert.deepEqual(g.experimentRuntime.pending,[]);assert.equal(g.experimentRuntime.guard,null);});
