'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game}=require('../world-game.js'),Dungeon=require('../dungeon-entry.js'),Objective=require('../objective-model.js');
const {five,response,clear}=require('./helpers/world-journey.cjs'),{talk}=require('./world-fixtures.cjs');
const reload=g=>Game.load(g.save());
function briefing(family){const g=five(family,'briefing');assert.equal(g.journey.phase,1);assert.equal(g.journey.directProgression,true);return g;}
function station(family){let g=briefing(family);g=reload(g);g.enter('city');talk(g,'warden');assert.equal(g.journey.phase,3);g=reload(g);assert.equal(g.enter('station'),true);return g;}
for(const family of ['ripple','echo','seal'])test(family+' direct chapter five and six complete and reload without observations or interpretations',()=>{
 let g=station(family);assert.equal(Dungeon.list(g).some(x=>x.id==='archive'),false);assert.equal(Objective.resolve(g).status,'combat');
 response(g,family);assert.equal(g.journey.measured,true);g=reload(g);clear(g);assert.equal(g.journey.phase,4);g=reload(g);g.enter('city');talk(g,'warden');assert.equal(g.journey.phase,5);g=reload(g);
 assert.deepEqual(g.journey.known,[]);assert.deepEqual(g.journey.facts,[]);
 talk(g,'warden');g=reload(g);g.enter('stabilization');talk(g,'six-record');assert.equal(g.laterStory.six,2);g=reload(g);g.enter('village');talk(g,'master');assert.equal(g.laterStory.deepening.stage,'trial');assert.equal(g.laterStory.dualBreath,false);g=reload(g);
 g.enter('stabilization');response(g,family);assert.equal(g.laterStory.dualBreath,true);g=reload(g);clear(g);g.hitStop=0;g.step(.05);assert.equal(g.laterStory.six,4);g=reload(g);g.enter('city');talk(g,'warden');g=reload(g);assert.equal(g.laterStory.six,5);assert.deepEqual(g.journey.known,[]);assert.deepEqual(g.journey.facts,[]);
});
test('empty or companion effects are not responses, but full ordinary defeat completes the field',()=>{const g=station('seal');Object.assign(g.player,{x:150,y:940,mp:g.stats().mp});assert.equal(g.act('signature1'),true);assert.equal(g.journey.measured,false);const e=g.enemies.find(x=>!x.boss);g.strike(e,1,'companion');g.strike(e,1,'attack');assert.equal(g.journey.measured,false);clear(g);assert.equal(g.journey.phase,4);assert.equal(g.journey.measured,true);});
test('direct progress requires genuine completion evidence and keeps old data',()=>{let g=station('ripple');const raw=JSON.parse(g.save());raw.journey.phase=4;assert.throws(()=>Game.load(JSON.stringify(raw)));raw.journey.directProgression='true';assert.throws(()=>Game.load(JSON.stringify(raw)));g=reload(g);assert.deepEqual(g.journey.facts,[]);assert.deepEqual(g.journey.selected,{ripple:null,echo:null,seal:null});});
function oldDiscoverySave(){const d=JSON.parse(briefing('ripple').save());delete d.journey.directProgression;d.journey.phase=2;d.journey.items=['ripple'];d.journey.known=['ripple-return'];d.journey.sync={'ripple-return':1};d.journey.facts=['sense-ripple','item-ripple','proof-ripple-return'].map(id=>({id,area:'archive',at:0}));d.journey.selected.ripple='ripple-return';for(const world of ['murim','reality'])d.worldGrowth[world].interpretations.ripple='ripple-return';return d;}
test('old discovery saves retain exact evidence and equipped effects while using direct missions',()=>{const raw=oldDiscoverySave(),g=Game.load(JSON.stringify(raw));assert.equal(g.journey.directProgression,true);assert.deepEqual(g.journey.facts,raw.journey.facts);assert.deepEqual(g.journey.known,raw.journey.known);assert.equal(g.worldGrowth.murim.interpretations.ripple,'ripple-return');assert.equal(g.worldGrowth.reality.interpretations.ripple,'ripple-return');g.enter('city');talk(g,'warden');assert.equal(g.journey.phase,3);const loaded=reload(g);assert.deepEqual(loaded.journey.facts,raw.journey.facts);assert.equal(loaded.worldGrowth.reality.interpretations.ripple,'ripple-return');});
test('old archive saves retain a usable exit without observation points or new archive entry',()=>{const raw=oldDiscoverySave();raw.area='archive';delete raw.encounter;const g=Game.load(JSON.stringify(raw));assert.equal(g.area,'archive');assert.ok(g.points().find(p=>p.id==='exit'));assert.ok(g.points().every(p=>['exit','rest'].includes(p.kind)));talk(g,'exit');assert.equal(g.area,'village');assert.equal(g.enter('archive'),false);assert.equal(Dungeon.list(g).some(p=>p.id==='archive'),false);});
