const test=require('node:test'),assert=require('node:assert/strict');
const {Game,AREAS}=require('../chapter-seven.js');
let D;try{D=require('../dungeon-entry.js');}catch{}
function game(area='village'){const g=new Game();g.finishIntro();g.worldGrowth={};g.worldState={};g.area=area;g.progress=2;g.player.x=1180;g.player.y=860;return g;}
test('one entrance replaces only hub dungeon gates, preserving boundary stone and internal devices',()=>{assert.ok(D);const g=game();const p=D.points(g,AREAS.village.points);assert.equal(p.filter(x=>x.kind==='dungeon-entry').length,1);assert.ok(p.some(x=>x.id==='portal'));assert.ok(p.some(x=>x.id==='master'));assert.ok(!p.some(x=>x.id==='forest'));g.area='ruins';assert.deepEqual(D.points(g,AREAS.ruins.points),AREAS.ruins.points);delete g.worldGrowth;g.area='village';assert.deepEqual(D.points(g,AREAS.village.points),AREAS.village.points);});
test('quest predicates gate future spoilers, entry prerequisites and archive invitation',()=>{assert.ok(D);const g=game();assert.equal(D.evaluate(g,'forest').unlocked,true);assert.equal(D.evaluate(g,'archive').unlocked,false);g.worldState.cycleOne.legacyAccess=true;assert.equal(D.evaluate(g,'archive').unlocked,true);const future=D.evaluate(g,'woundCore');assert.equal(future.unlocked,false);assert.equal(future.name,'아직 알려지지 않은 탐험지');assert.equal(future.purpose,'');assert.equal(D.canEnter(g,'ruins'),false);g.progress=12;g.fate.stage=2;assert.equal(D.canEnter(g,'sanctum'),true);assert.equal(D.canEnter(g,'heart'),false);g.fate.stage=4;assert.equal(D.canEnter(g,'heart'),true);g.laterStory={six:5,seven:1,coreOpened:false};assert.equal(D.canEnter(g,'woundDock'),false);g.laterStory.seven=2;assert.equal(D.canEnter(g,'woundDock'),true);});
test('reports, completed revisits, unseen unlocks and seen rows remain distinct',()=>{assert.ok(D);const g=game();assert.equal(D.evaluate(g,'forest').status,'new');D.markSeen(g,'forest');assert.equal(D.evaluate(g,'forest').status,'progress');g.progress=3;assert.equal(D.evaluate(g,'forest').status,'report');g.progress=4;assert.equal(D.evaluate(g,'forest').status,'revisit');assert.equal(D.evaluate(g,'forest').rewardPolicy.includes('다시'),true);});
test('remote and other-world requests do not prepare or move',async()=>{assert.ok(D);const g=game();let loads=0;g.player.x=0;assert.equal((await D.request(g,'forest',async()=>loads++)).ok,false);g.player.x=1180;assert.equal((await D.request(g,'rift',async()=>loads++)).ok,false);assert.equal(loads,0);});
test('failed preparation preserves gameplay, allows retry, and concurrent requests do not commit twice',async()=>{assert.ok(D);const g=game();const before=JSON.stringify({area:g.area,player:g.player,progress:g.progress,worldState:g.worldState});const fail=await D.request(g,'forest',async()=>{throw Error('art');});assert.equal(fail.ok,false);assert.equal(JSON.stringify({area:g.area,player:g.player,progress:g.progress,worldState:g.worldState}),before);let ready,commits=0;g.enter=id=>{commits++;g.area=id;return true;};const pending=D.request(g,'forest',()=>new Promise(resolve=>ready=resolve));assert.equal((await D.request(g,'forest',async()=>{})).ok,false);ready();assert.equal((await pending).ok,true);assert.equal(commits,1);});
test('conditions and entrance distance are checked again after async preparation',async()=>{assert.ok(D);const g=game();let commits=0;g.enter=()=>{commits++;return true;};const r=await D.request(g,'forest',async()=>{g.progress=1;});assert.equal(r.ok,false);assert.equal(commits,0);});
test('migration derives permanent unlocks from actual facts and translates old pins',()=>{assert.ok(D);const g=game();const s=D.migrate(g,{unlocked:['woundCore'],selected:{village:'woundCore'}});assert.ok(s.unlocked.includes('forest'));assert.ok(!s.unlocked.includes('woundCore'));assert.deepEqual(D.migratePin({area:'village',pointId:'passGate'}),{area:'village',pointId:'dungeon-entry',destinationId:'returnPass'});});
test('seventh chapter entry shares preparation and actual report prerequisites',()=>{const g=game();g.laterStory={six:5,seven:1,coreOpened:false};assert.equal(D.evaluate(g,'woundPass').unlocked,true);assert.equal(D.canEnter(g,'woundPass'),false);g.laterStory.preparation='evacuation';assert.equal(D.canEnter(g,'woundPass'),true);Object.assign(g.laterStory,{seven:3,coreOpened:true});assert.equal(D.evaluate(g,'woundCore').unlocked,true);assert.equal(D.canEnter(g,'woundCore'),false);g.worldState.reports={reported:['seven-dock-stable']};assert.equal(D.canEnter(g,'woundCore'),true);});
