'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game,AREAS}=require('../game.js');
function at(g,id){const o=AREAS[g.area].points.find(p=>p.id===id);assert.ok(o,id);g.player.x=o.x;g.player.y=o.y;return g.interact();}
function tick(g,n=1){for(let i=0;i<n;i++)g.step(.05);}
function ready(){const g=new Game();g.progress=12;g.training=3;g.level=8;g.enter('city');at(g,'warden');at(g,'portal');at(g,'master');return g;}
function trial(path){const g=ready();at(g,'sanctum');at(g,'relic-'+path);assert.equal(g.beginTrial(path),true);return g;}
function armed(path){const g=trial(path);g.fate.proven=[path];g.trial=null;g.retreat();assert.equal(g.acceptFate(path),true);g.enter('heart');g.events=[];return g;}
function near(g){const e=g.enemies[0];g.player.x=e.x-45;g.player.y=e.y;g.player.face=0;g.player.invuln=0;e.hp=e.maxHp=2000;return e;}
function hitSoon(g,e){e.wind=.01;e.windMax=.85;e.tx=g.player.x;e.ty=g.player.y;e.range=110;g.player.invuln=0;}
test('fate state is absent of forced choice and version three is explicit',()=>{const g=new Game();assert.ok(g.fate);assert.equal(g.fate.path,null);assert.deepEqual(g.fate.proven,[]);assert.equal(JSON.parse(g.save()).version,3);});
test('chapter three opens only after chapter two and provides next target',()=>{const g=new Game();at(g,'warden');assert.equal(g.fate.stage,0);const h=ready();assert.equal(h.fate.stage,2);assert.equal(h.target().id,'sanctum');assert.equal(h.objective().chapter,3);});
test('investigation discovers a path without automatically assigning a class',()=>{const g=ready();at(g,'sanctum');const r=at(g,'relic-echo');assert.equal(r.type,'fate-trial');assert.ok(g.fate.discovered.includes('echo'));assert.equal(g.fate.path,null);assert.equal(g.acceptFate('echo'),false);});
test('invalid and undiscovered trials cannot be started',()=>{const g=ready();for(const path of ['echo','__proto__','constructor','bogus'])assert.equal(g.beginTrial(path),false);});
test('training trial temporarily exposes two skills but never the ultimate',()=>{const g=trial('echo');assert.equal(g.skillInfo('signature1').name,'잔영각');assert.equal(g.act('ultimate'),false);assert.equal(g.fate.path,null);});
test('ripple parry prevents the hit and charges a counter',()=>{const g=trial('ripple'),e=near(g),hp=g.player.hp;assert.equal(g.act('signature1'),true);hitSoon(g,e);tick(g);assert.equal(g.player.hp,hp);assert.ok(g.combat.charges>0);assert.ok(g.trial.feat);assert.ok(e.hp<e.maxHp);});
test('unprotected or expired parry takes damage',()=>{const g=armed('ripple'),e=near(g);g.act('signature1');g.player.x=200;g.player.y=950;tick(g,20);g.player.x=e.x-45;g.player.y=e.y;hitSoon(g,e);const hp=g.player.hp;tick(g);assert.ok(g.player.hp<hp);});
test('reverse slash consumes its accumulated charge and respects cooldown',()=>{const g=armed('ripple'),e=near(g);g.combat.charges=2;const hp=e.hp;assert.ok(g.act('signature2'));assert.equal(g.combat.charges,0);assert.ok(hp-e.hp>g.stats().attack*3);assert.equal(g.act('signature2'),false);});
test('echo dash leaves a usable timed afterimage and return hits from it',()=>{const g=trial('echo'),e=near(g);assert.ok(g.act('signature1'));tick(g,5);assert.ok(g.combat.echo);const hp=e.hp;assert.ok(g.act('signature2'));assert.ok(e.hp<hp);assert.ok(g.trial.feat);assert.equal(g.combat.echo,null);});
test('return without an echo spends neither mana nor cooldown',()=>{const g=armed('echo'),mp=g.player.mp;assert.equal(g.act('signature2'),false);assert.equal(g.player.mp,mp);assert.equal(g.player.cool.signature2,0);});
test('echo return refuses a route obstructed by a wall',()=>{const g=armed('echo'),b=AREAS.heart.blocks[0];g.player.x=b.x-30;g.player.y=b.y+50;g.combat.echo={x:b.x+b.w+30,y:b.y+50,life:4};assert.equal(g.act('signature2'),false);assert.ok(g.player.x<b.x);});
test('seal field slows approaching enemies and suppresses a telegraph',()=>{const g=trial('seal'),e=near(g);hitSoon(g,e);assert.ok(g.act('signature1'));assert.ok(g.combat.field);assert.equal(e.wind,0);assert.ok(g.trial.feat);assert.ok(g.fate.feats.seal>0);});
test('binding deals damage and roots at most two enemies, bosses briefly',()=>{const g=armed('seal'),e=near(g);const second=g.enemies[1];second.x=e.x+30;second.y=e.y;const third=g.enemies[2];third.x=e.x+55;third.y=e.y;assert.ok(g.act('signature2'));assert.ok(e.root>0);assert.ok(second.root>0);assert.ok(!third.root);});
for(const path of ['ripple','echo','seal'])test(path+' ultimate requires focus and unlocked path, produces its own effect',()=>{const g=armed(path);near(g);g.fate.focus=99;const mp=g.player.mp;assert.equal(g.act('ultimate'),false);assert.equal(g.player.mp,mp);g.fate.focus=100;assert.ok(g.act('ultimate'));assert.equal(g.fate.focus,0);assert.ok(g.fx.some(f=>f.kind==='fate-ultimate'&&f.path===path));assert.ok(g.events.some(e=>e.type==='ultimate'));assert.equal(g.act('ultimate'),false);});
test('trial cannot be finished by ordinary attacks before demonstrating its mechanic',()=>{const g=trial('echo'),e=g.enemies[0];g.player.x=e.x-45;g.player.y=e.y;e.hp=1;g.act('attack');assert.equal(e.hp,1);assert.deepEqual(g.fate.proven,[]);});
function prove(g,path){const e=g.enemies[0];g.player.x=e.x-45;g.player.y=e.y;g.player.face=0;g.player.invuln=0;
 if(path==='ripple'){g.act('signature1');hitSoon(g,e);tick(g);}else if(path==='echo'){g.act('signature1');tick(g,5);g.act('signature2');}else{hitSoon(g,e);g.act('signature1');}
 assert.ok(g.trial.feat);for(let i=0;i<180&&e.hp>0;i++){g.player.x=e.x-45;g.player.y=e.y;g.act('attack');g.player.x=180;g.player.y=960;tick(g,8);}assert.equal(e.hp,0);}
for(const path of ['ripple','echo','seal'])test(path+' full earned path: trial, acceptance, world transfer, finale and save',()=>{const g=trial(path);prove(g,path);assert.ok(g.fate.proven.includes(path));g.retreat();assert.ok(g.acceptFate(path));assert.equal(g.fate.stage,3);assert.equal(g.fate.path,path);at(g,'portal');at(g,'warden');assert.equal(g.fate.stage,4);at(g,'heart');assert.equal(g.area,'heart');
 for(const e of g.enemies.filter(e=>!e.boss)){for(let i=0;i<180&&e.hp>0;i++){g.player.x=e.x-40;g.player.y=e.y;g.act('attack');g.player.x=180;g.player.y=960;tick(g,8);}assert.equal(e.hp,0);}
 for(const p of AREAS.heart.points.filter(p=>p.kind==='seal'))at(g,p.id);
 const boss=g.enemies.find(e=>e.boss);for(let i=0;i<300&&boss.hp>0;i++){g.player.x=boss.x-40;g.player.y=boss.y;g.act('attack');g.player.x=180;g.player.y=960;tick(g,8);}assert.equal(boss.hp,0);assert.equal(g.fate.stage,5);g.retreat();at(g,'warden');assert.equal(g.fate.stage,6);const h=Game.load(g.save());assert.equal(h.fate.path,path);assert.equal(h.fate.stage,6);assert.equal(h.progress,12);});
test('re-attunement is safe-hub only and never grants repeated rewards',()=>{const g=armed('echo');g.fate.proven.push('seal');g.fate.discovered.push('seal');assert.equal(g.acceptFate('seal'),false);g.enter('village');const gold=g.gold;assert.ok(g.acceptFate('seal'));assert.equal(g.gold,gold);assert.equal(g.fate.path,'seal');});
test('retreat/load clears temporary trial and combat objects but preserves discovery',()=>{const g=trial('echo');g.act('signature1');const h=Game.load(g.save());assert.equal(h.area,'village');assert.equal(h.trial,null);assert.equal(h.combat.echo,null);assert.ok(h.fate.discovered.includes('echo'));assert.equal(h.fate.path,null);});
test('old version two saves migrate without changing chapters or resources',()=>{const g=new Game(),d=JSON.parse(g.save());d.version=2;delete d.fate;d.gold=147;const h=Game.load(JSON.stringify(d));assert.equal(h.gold,147);assert.equal(h.fate.stage,0);});
test('corrupt, inconsistent, or prototype-named fate data is rejected',()=>{const g=new Game();for(const change of [{path:'__proto__'},{stage:99},{path:'echo',stage:3},{proven:['echo']},{feats:{ripple:-1,echo:0,seal:0}},{focus:Infinity}]){const d=JSON.parse(g.save());Object.assign(d.fate,change);assert.throws(()=>Game.load(JSON.stringify(d)),JSON.stringify(change));}});
test('trials cannot award repeated gold and all effects expire',()=>{const g=trial('echo');prove(g,'echo');const gold=g.gold;assert.ok(g.beginTrial('echo'));prove(g,'echo');assert.equal(g.gold,gold);g.retreat();tick(g,200);assert.equal(g.fx.length,0);assert.equal(g.combat.echo,null);assert.equal(g.combat.field,null);});
test('a previously awakened character cannot use a different path ultimate in a trial',()=>{const g=armed('ripple');g.retreat();g.enter('sanctum');at(g,'relic-echo');g.beginTrial('echo');g.fate.focus=100;assert.equal(g.act('ultimate'),false);});
test('defeat in a borrowed trial costs no gold and preserves discoveries',()=>{const g=trial('ripple'),gold=g.gold;g.player.hp=0;g.step(.05);assert.equal(g.gold,gold);assert.equal(g.area,'village');assert.equal(g.trial,null);assert.ok(g.fate.discovered.includes('ripple'));});
test('attack pose and hitstop expire instead of freezing the next fight',()=>{const g=armed('ripple');near(g);g.act('attack');assert.ok(g.player.swing>0);assert.ok(g.hitStop>0);g.player.x=180;g.player.y=960;tick(g,30);assert.equal(g.player.swing,0);assert.equal(g.hitStop,0);});
test('new public runtime modules are served by the local server',async()=>{const {createServer}=require('../server.cjs'),s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));try{for(const file of ['fate.js','fate-art.js']){const res=await fetch(`http://127.0.0.1:${s.address().port}/${file}`);assert.equal(res.status,200,file);assert.match(res.headers.get('content-type'),/javascript/);}}finally{await new Promise(r=>s.close(r));}});
