'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game,AREAS}=require('../world-game.js');
function ready(){const g=new Game();g.finishIntro();g.progress=12;g.training=3;return g;}
function talk(g,id){const o=g.points().find(o=>o.id===id);assert.ok(o,id);Object.assign(g.player,{x:o.x,y:o.y});return g.interact();}
function arm(g,f='ripple'){g.fate.stage=2;g.fate.discovered=[f];g.fate.proven=[f];g.enter('village');assert.ok(g.acceptFate(f));return g;}
function proof(g){g.enter('forest');const e=g.enemies[0];Object.assign(g.player,{x:e.x-35,y:e.y,face:0,invuln:0});g.act('signature1');g.takeHit(e);g.enter('village');}
test('new characters learn Q before R/F; locked actions spend nothing',()=>{const g=arm(ready());assert.equal(g.skillInfo('signature1').locked,false);for(const a of ['signature2','ultimate']){assert.equal(g.skillInfo(a).locked,true);const mp=g.player.mp;assert.equal(g.act(a),false);assert.equal(g.player.mp,mp);}});
test('chapter three starts with a passage defense and narrative retreat',()=>{const g=ready();const r=talk(g,'warden');assert.match(r.text,/通路|통로/);assert.equal(g.fate.stage,0);assert.equal(g.worldState.growthArc.phase,'defense');g.enter('rift');const gold=g.gold,xp=g.xp;for(let i=0;i<360;i++)g.step(.05);assert.equal(g.area,'city');assert.equal(g.worldState.growthArc.phase,'failed');assert.equal(g.gold,gold);assert.equal(g.xp,xp);assert.ok(g.player.hp>0);talk(g,'warden');assert.equal(g.fate.stage,1);});
test('new growth state survives save; missing state migrates learned skills',()=>{const g=arm(ready()),raw=JSON.parse(g.save());const h=Game.load(JSON.stringify(raw));assert.equal(h.skillInfo('signature2').locked,true);delete raw.worldState.growthArc;const old=Game.load(JSON.stringify(raw));assert.equal(old.skillInfo('signature2').locked,false);assert.equal(old.skillInfo('ultimate').locked,false);});
test('R follows actual proof and practice; chapter seven alone cannot grant F',()=>{const g=arm(ready());g.chapter4.phase=4;g.chapter4.rescued=true;proof(g);talk(g,'opportunity-training');assert.equal(g.area,'sanctum');assert.equal(g.worldState.growthArc.learnedR,false);const e=g.enemies[0];Object.assign(g.player,{x:e.x-40,y:e.y,face:0});g.act('signature1');g.player.invuln=0;g.takeHit(e);assert.ok(g.act('signature2'));assert.equal(g.worldState.growthArc.learnedR,true);g.enter('village');assert.equal(g.skillInfo('signature2').locked,false);assert.equal(g.skillInfo('ultimate').locked,true);g.laterStory.seven=5;g.step(.05);assert.equal(g.skillInfo('ultimate').locked,true);});
test('corrupt growth progression is rejected',()=>{const g=ready(),d=JSON.parse(g.save());d.worldState.growthArc={version:1,phase:'bogus',legacy:false};assert.throws(()=>Game.load(JSON.stringify(d)),/성장/);});
for(const f of ['ripple','echo','seal'])test(f+' first trial can be proven with Q only',()=>{const g=ready();g.fate.stage=2;g.fate.discovered=[f];g.enter('sanctum');assert.ok(g.beginTrial(f));const e=g.enemies[0];Object.assign(g.player,{x:e.x-40,y:e.y,face:0,invuln:0});Object.assign(e,{wind:1,tx:g.player.x,ty:g.player.y,range:90});assert.equal(g.skillInfo('signature2').locked,true);assert.ok(g.act('signature1'));if(f==='ripple'){g.player.invuln=0;g.takeHit(e);}for(let i=0;i<7;i++){g.hitStop=0;g.step(.05);}assert.equal(g.trial.feat,true);});
test('heart revisits passage pressure; Q use without effect cannot certify it',()=>{const g=arm(ready());g.fate.stage=4;g.enter('city');g.equipReality('ripple');g.enter('heart');const boss=g.enemies.find(e=>e.boss);assert.ok(boss.passagePressure);for(const e of g.enemies.filter(e=>!e.boss))g.strike(e,99999);for(const p of g.points().filter(p=>p.kind==='seal'))talk(g,p.id);assert.ok(g.strike(boss,30)>0);g.act('signature1');assert.equal(g.worldState.growthArc.returnProven,false);g.player.invuln=0;g.takeHit(boss);assert.equal(g.worldState.growthArc.returnProven,true);assert.ok(g.strike(boss,30)>0);});
test('new balance changes only early growth encounters; saves keep exact scaled HP',()=>{const g=arm(ready());g.fate.stage=4;g.enter('heart');const hp=g.enemies.map(e=>e.maxHp),h=Game.load(g.save());assert.deepEqual(h.enemies.map(e=>e.maxHp),hp);const legacy=arm(ready());legacy.worldState.growthArc=require('../growth-arc.js').initial(true);legacy.fate.stage=4;legacy.enter('heart');assert.ok(hp.every((n,i)=>n<=legacy.enemies[i].maxHp));g.enter('rift');assert.equal(g.enemies.find(e=>e.boss).maxHp,require('../encounter-director.js').profiles.rift.bossHp);});
test('lethal passage attack retreats without death penalty and saved attempt restarts',()=>{const g=ready();talk(g,'warden');g.enter('rift');const h=Game.load(g.save());assert.equal(h.area,'rift');assert.equal(h.worldState.growthArc.phase,'defense');const gold=h.gold;h.player.hp=1;h.player.invuln=0;h.takeHit(h.enemies[0]);assert.equal(h.area,'city');assert.equal(h.gold,gold);assert.equal(h.worldState.growthArc.phase,'failed');});
test('practice R alone does not unlock the followup principle',()=>{const g=arm(ready());g.chapter4.phase=4;g.chapter4.rescued=true;proof(g);talk(g,'opportunity-training');const e=g.enemies[0];Object.assign(g.player,{x:e.x-40,y:e.y,face:0});assert.ok(g.act('signature2'));assert.equal(g.worldState.growthArc.learnedR,false);});
test('invulnerable defense dodge does not cause premature retreat',()=>{const g=ready();talk(g,'warden');g.enter('rift');g.player.hp=1;g.player.invuln=.2;g.takeHit(g.enemies[0]);assert.equal(g.area,'rift');assert.equal(g.worldState.growthArc.phase,'defense');});
test('Q echo can open the rescue passage without R',()=>{const g=arm(ready(),'echo');g.fate.stage=6;g.chapter4.phase=1;g.enter('returnPass');g.enemies=[];Object.assign(g.player,{x:630,y:630,face:Math.PI,invuln:0});g.storyRuntime.pulse.wind=1;assert.equal(g.skillInfo('signature2').locked,true);assert.ok(g.act('signature1'));for(let i=0;i<7;i++){g.hitStop=0;g.step(.05);}assert.equal(g.chapter4.rescued,true);assert.equal(g.chapter4.route,'echo');});
test('first normal reality return equips the learned Q automatically',()=>{const g=arm(ready(),'seal');assert.equal(g.worldGrowth.reality.equipped,null);g.enter('city');assert.equal(g.worldGrowth.reality.equipped,'seal');assert.equal(g.skillInfo('signature1').name,'균열 억제');assert.equal(g.skillInfo('signature1').locked,false);assert.equal(g.skillInfo('signature2').locked,true);});
test('comeback guidance follows guards then seals then the pressure boss',()=>{const g=arm(ready());g.fate.stage=4;g.enter('city');g.enter('heart');for(const e of g.enemies.filter(e=>!e.boss))g.strike(e,99999);const seal=g.points().find(p=>p.kind==='seal');assert.equal(g.target().id,seal.id);for(const p of g.points().filter(p=>p.kind==='seal'))talk(g,p.id);assert.equal(g.target().id,g.enemies.find(e=>e.boss).id);});
test('forged R/F and incompatible defense phases are rejected on load',()=>{const g=arm(ready()),raw=JSON.parse(g.save());for(const change of [{learnedR:true},{learnedR:true,learnedF:true},{phase:'defense'},{returnProven:true}]){const d=structuredClone(raw);Object.assign(d.worldState.growthArc,change);assert.throws(()=>Game.load(JSON.stringify(d)),/성장/);}});
test('old pre-inheritance saves join new arc while owned skills remain legacy',()=>{const g=ready(),d=JSON.parse(g.save());delete d.worldState.growthArc;const h=Game.load(JSON.stringify(d));assert.equal(h.worldState.growthArc.legacy,false);talk(h,'warden');assert.equal(h.worldState.growthArc.phase,'defense');});
test('R practice dialog teaches the followup instead of first-Q tutorial',()=>{const g=arm(ready());g.chapter4.phase=4;g.chapter4.rescued=true;proof(g);g.events=[];talk(g,'opportunity-training');const dialogs=g.events.filter(e=>e.type==='dialog');assert.ok(dialogs.some(e=>/Q.*R/.test(e.text)));assert.ok(dialogs.every(e=>!e.text.includes('Q 버튼으로 첫 원리')));});
