const {run}=require('./browser-harness.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');require('../chapter-seven.js');require('../save-v9.js');const {ready}=require('./helpers/later.cjs');
run(async p=>{const saved=ready().save();await p.addInitScript(raw=>{if(!sessionStorage.getItem('laterFixture')){localStorage.setItem('dualworld.save.v1',raw);sessionStorage.setItem('laterFixture','1');}},saved);await p.reload();await p.waitForFunction(()=>ArtPreview.ready);await p.click('#continue');
 async function close(){for(let i=0;i<12&&await p.locator('#dialog').evaluate(x=>x.open);i++)await p.keyboard.press('KeyG');}
 async function talk(id){await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world===(DualWorld.AREAS[__game.area].world==='현실'?'reality':'murim'));await p.evaluate(id=>{const o=__game.points().find(x=>x.id===id);if(!o)throw Error('Missing '+id);Object.assign(__game.player,{x:o.x,y:o.y});},id);await p.keyboard.press('KeyG');await close();}
 async function enter(area){await close();await p.evaluate(area=>{__game.enter(area);__game.events=[];},area);await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world===(DualWorld.AREAS[__game.area].world==='현실'?'reality':'murim'));}
 async function win(){await p.evaluate(()=>{const g=__game,e=g.enemies.find(e=>!e.boss);Object.assign(g.player,{x:730,y:700,mp:200});Object.assign(e,{x:780,y:700,hp:4000});g.player.cool.moon=0;g.player.cool.signature2=0;g.act('moon');g.combat.echo={x:730,y:700,life:4};g.act('signature2');for(const x of [...g.enemies].sort((a,b)=>a.boss-b.boss))g.strike(x,99999);g.hitStop=0;g.step(.02);g.events=[];});}
 await talk('warden');assert.equal(await p.evaluate(()=>__game.laterStory.six),1);await enter('stabilization');await talk('six-record');await enter('village');await talk('master');await enter('stabilization');await win();await enter('city');await talk('warden');assert.equal(await p.evaluate(()=>__game.laterStory.six),5);await talk('warden');
 await enter('woundPass');await win();await enter('woundDock');assert.equal(await p.evaluate(()=>ChapterSeven.battle(__game).safeRadius),180);fs.mkdirSync('.codex_doc_review/v011',{recursive:true});await p.screenshot({path:'.codex_doc_review/v011/seven-dock.png'});await win();await enter('woundCore');await win();await enter('city');await talk('warden');assert.equal(await p.evaluate(()=>__game.laterStory.completed),true);
 await p.click('#inventory');assert.match(await p.locator('#dialog').innerText(),/쌍계 호흡/);await p.screenshot({path:'.codex_doc_review/v011/completed-growth.png'});await close();await p.evaluate(()=>localStorage.setItem('dualworld.save.v1',__game.save()));await p.reload();await p.waitForFunction(()=>ArtPreview.ready);await p.click('#continue');assert.equal(await p.evaluate(()=>__game.laterStory.completed),true);
 console.log('chapter six/seven browser progression, rendering and final reload passed');
});
