'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game,AREAS}=require('../game.js');
function field(area='forest'){const g=new Game();g.progress=2;g.training=1;g.enter(area);g.events=[];g.player.invuln=0;return g;}
function counter(g,index=0,serial=1){const e=g.enemies[index];e.x=650;e.y=650;e.hp=e.maxHp=500;e.attacks=serial;e.wind=.2;e.windMax=1;e.tx=610;e.ty=650;e.range=90;g.player.x=610;g.player.y=650;g.player.face=0;g.player.cool.attack=0;g.hitStop=0;g.act('attack');return e;}
function earn(g,path){if(path==='ripple'){counter(g,0);counter(g,1);}return g;}
test('first real counter leaves a contextual manifestation, not a quest award',()=>{const g=field();counter(g);assert.equal(g.legend.counts.ripple,1);assert.equal(g.fate.path,null);assert.equal(g.legend.memories[0].area,'forest');assert.equal(g.legend.memories[0].foe,'흑풍 산적');assert.ok(g.events.some(e=>e.type==='manifestation'));});
test('same telegraph cannot be farmed by repeated hits',()=>{const g=field();const e=counter(g);e.wind=.2;g.player.cool.attack=0;g.act('attack');assert.equal(g.legend.counts.ripple,1);});
test('ordinary attacks without enemy wind-up do not unlock a path',()=>{const g=field();const e=g.enemies[0];e.x=650;e.y=650;e.hp=10000;g.player.x=610;g.player.y=650;for(let i=0;i<12;i++){g.player.cool.attack=0;g.act('attack');}assert.equal(g.legend.counts.ripple,0);assert.deepEqual(g.legend.ready,[]);});
test('two actual events offer rather than force a field path',()=>{const g=earn(field(),'ripple');assert.deepEqual(g.legend.ready,['ripple']);assert.equal(g.fate.path,null);assert.ok(g.events.some(e=>e.type==='legend-ready'&&e.path==='ripple'));});
test('field awakening unlocks Q immediately without returning to a mentor',()=>{const g=earn(field(),'ripple'),gold=g.gold;assert.equal(g.awaken('ripple'),true);assert.equal(g.area,'forest');assert.equal(g.fate.path,'ripple');assert.equal(g.fate.stage,0);assert.equal(g.gold,gold);assert.equal(g.act('signature1'),true);});
test('unknown and unwitnessed paths cannot be accepted',()=>{const g=field();for(const path of ['echo','constructor','__proto__',null])assert.equal(g.awaken(path),false);});
test('early field path survives save load before chapter three',()=>{const g=earn(field(),'ripple');g.awaken('ripple');const raw=g.save();assert.equal(JSON.parse(raw).version,4);const h=Game.load(raw);assert.equal(h.fate.path,'ripple');assert.equal(h.progress,2);assert.equal(h.legend.memories.length,2);assert.equal(h.area,'village');});
test('v3 earned path is preserved without invented memories',()=>{const g=field();const raw=JSON.parse(g.save());raw.version=3;delete raw.legend;raw.progress=12;raw.training=3;raw.fate={stage:4,path:'echo',proven:['echo'],discovered:['echo'],feats:{ripple:0,echo:2,seal:0},focus:10};const h=Game.load(JSON.stringify(raw));assert.equal(h.fate.path,'echo');assert.equal(h.legend.memories.length,0);});
test('poisoned counts and forged early path are rejected',()=>{const g=field();const raw=JSON.parse(g.save());raw.legend={...g.legend,counts:{ripple:-1,echo:0,seal:0}};assert.throws(()=>Game.load(JSON.stringify(raw)));const other=JSON.parse(g.save());other.fate.path='seal';other.fate.proven=['seal'];other.fate.discovered=['seal'];assert.throws(()=>Game.load(JSON.stringify(other)));});
test('real hazard dodge then counter creates a remembered echo',()=>{const g=field(),e=g.enemies[0];g.enemies=[e];e.x=680;e.y=650;e.hp=500;e.wind=.10;e.windMax=1;e.attacks=1;e.tx=610;e.ty=650;e.range=65;e.cd=10;g.player.x=610;g.player.y=650;g.player.face=Math.PI;g.act('dash');for(let i=0;i<5;i++)g.step(.05);e.x=g.player.x+45;e.y=g.player.y;g.player.cool.attack=0;g.act('attack');assert.equal(g.legend.counts.echo,1);assert.ok(g.fx.some(f=>f.kind==='legend-echo'));});
test('dashing in an empty field and hitting later grants no echo',()=>{const g=field();g.act('dash');for(let i=0;i<5;i++)g.step(.05);g.strike(g.enemies[0],1,'attack');assert.equal(g.legend.counts.echo,0);});
test('quiet scar is not a skill reward and does not consume a choice',()=>{const g=field();const o=AREAS.forest.points.find(p=>p.kind==='scar');assert.ok(o);Object.assign(g.player,{x:o.x,y:o.y});g.interact();assert.equal(g.legend.counts.seal,0);});
test('stabilizing a scar during a hostile telegraph records a seal manifestation',()=>{const g=field(),o=AREAS.forest.points.find(p=>p.kind==='scar'),e=g.enemies[0];assert.ok(o);Object.assign(g.player,{x:o.x,y:o.y});Object.assign(e,{x:o.x+40,y:o.y,wind:.6,windMax:1,attacks:1});g.interact();assert.equal(g.legend.counts.seal,1);assert.equal(e.wind,0);});
test('trial actions do not manufacture field memories',()=>{const g=field();g.trial={path:'ripple',feat:false};counter(g);assert.equal(g.legend.counts.ripple,0);});
test('a trained personal legend no longer needs the chapter-three mentor reward',()=>{const g=earn(field(),'ripple');g.awaken('ripple');g.progress=12;g.training=3;g.enter('city');let o=AREAS.city.points.find(p=>p.id==='warden');Object.assign(g.player,{x:o.x,y:o.y});g.interact();g.enter('village');o=AREAS.village.points.find(p=>p.id==='master');Object.assign(g.player,{x:o.x,y:o.y});g.interact();assert.equal(g.fate.stage,3);assert.equal(g.objective().target.id,'portal');});
test('held auto-attacks do not pretend to be deliberate last-instant counters',()=>{const g=field(),e=g.enemies[0];g.enemies=[e];Object.assign(e,{x:650,y:650,hp:500,wind:.25,windMax:1,attacks:1,tx:610,ty:650,range:90});Object.assign(g.player,{x:610,y:650});g.step(.01,{attack:true});assert.equal(g.legend.counts.ripple,0);});
test('an existing path can gain a truthful field origin without replacing it or giving gold',()=>{const g=earn(field(),'ripple');g.fate.path='ripple';g.fate.proven=['ripple'];const gold=g.gold;assert.equal(g.awaken('ripple'),true);assert.deepEqual(g.legend.awakened,['ripple']);assert.equal(g.fate.path,'ripple');assert.equal(g.gold,gold);assert.equal(g.awaken('ripple'),false);});
