const test=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../world-game.js'),O=require('../objective-model.js');
function talk(g,id){const p=g.points().find(p=>p.id===id);assert.ok(p,id);Object.assign(g.player,{x:p.x,y:p.y});return g.interact();}
test('old chapter one introduction guides to the dungeon entrance instead of repeating the teacher',()=>{const g=new Game();g.beginIntro(true);g.finishIntro();g.enter('village');talk(g,'master');talk(g,'huashan');assert.equal(O.resolve(g).target.id,'dungeon-entry');});
test('new journey begins in murim, blocks premature return, and does not grant plum sword',()=>{const g=new Game();assert.equal(typeof g.startMurimJourney,'function');g.startMurimJourney();assert.equal(g.area,'village');assert.equal(g.enter('city'),false);assert.match(g.skillInfo('attack').name,/삼재/);assert.equal(g.skillInfo('storm').locked,true);assert.equal(Game.load(g.save()).worldState.murimJourney.version,1);});
module.exports={talk};
function start(){const g=new Game();assert.equal(typeof g.startMurimJourney,'function');g.startMurimJourney();g.advanceMurimIntro(true);return g;}
function clear(g){for(const boss of [false,true])for(const e of g.enemies.filter(e=>!!e.boss===boss)){let n=0;while(e.hp>0&&n++<500){Object.assign(g.player,{x:e.x-35,y:e.y,face:0});g.player.cool.attack=0;g.act('attack');}assert.equal(e.hp,0);}g.events=[];}
function tutorial(g){g.step(.05,{x:1,y:0});g.player.x+=35;g.step(.05);g.act('dash');clear(g);talk(g,'journey-exit');assert.equal(g.worldState.murimJourney.stage,'road');}
for(const choice of ['accept','decline'])test('ten distinct road stages and '+choice+' disciple path return without required rare power',()=>{let g=start();tutorial(g);for(let i=1;i<=10;i++){assert.equal(g.enter('murimRoad'+(i+1)),false);assert.ok(g.enter('murimRoad'+i));clear(g);g=Game.load(g.save());talk(g,'journey-exit');}assert.equal(g.worldState.murimJourney.stage,'treatment');talk(g,'journey-master');assert.equal(g.worldState.murimJourney.stage,'choice');assert.ok(g.chooseDisciple(choice));assert.equal(g.skillInfo('storm').locked,choice!=='accept');assert.equal(g.chooseDisciple(choice==='accept'?'decline':'accept'),false);for(let i=1;i<=3;i++){assert.ok(g.enter('murimReturn'+i));clear(g);g=Game.load(g.save());talk(g,'journey-exit');}talk(g,'journey-return');assert.equal(g.area,'city');assert.equal(g.worldState.murimJourney.stage,'complete');assert.equal(g.worldState.murimJourney.rare,false);assert.doesNotThrow(()=>Game.load(g.save()));});
test('old victory without one movement proof points to practice, then back to recognition',()=>{const g=new Game();g.beginIntro(true);g.finishIntro();g.enter('village');talk(g,'master');talk(g,'huashan');g.progress=3;assert.equal(O.resolve(g).target.id,'basic-practice');g.worldState.planB.basicHit=true;g.worldState.planB.warnedEvade=true;assert.equal(O.resolve(g).target.id,'huashan');});
test('optional rare is earned once and death, retreat and partial combat reload preserve growth',()=>{let g=start();tutorial(g);for(let i=1;i<=10;i++){g.enter('murimRoad'+i);clear(g);talk(g,'journey-exit');}talk(g,'journey-master');g.chooseDisciple('decline');g.enter('murimReturn1');clear(g);talk(g,'journey-exit');g.enter('murimChance');const e=g.enemies[0];Object.assign(g.player,{x:e.x-30,y:e.y});g.act('attack');const hp=e.hp;g=Game.load(g.save());assert.equal(g.enemies[0].hp,hp);clear(g);const balance=require('../murim-growth.js').balance(g);assert.equal(g.worldState.murimJourney.rare,true);talk(g,'journey-exit');g.enter('murimChance');clear(g);assert.deepEqual(require('../murim-growth.js').balance(g),balance);g.player.hp=0;g=Game.load(g.save());assert.equal(g.area,'village');assert.deepEqual(require('../murim-growth.js').balance(g),balance);});
