const assert=require('node:assert/strict'),fs=require('node:fs'),{run}=require('./browser-harness.cjs'),H=require('./helpers/murim-browser.cjs');
run(async p=>{
 fs.mkdirSync('browser-results/murim-scenes',{recursive:true});await p.waitForSelector('.murim-story-scene img');assert.equal(await p.locator('.murim-story-scene').getAttribute('data-scene'),'intro-0');await p.waitForFunction(()=>document.querySelector('.murim-story-scene img').naturalWidth>0);
 await p.screenshot({path:'browser-results/murim-scenes/departure-desktop.png'});for(const a of ['moon','storm'])assert.equal(await p.locator('[data-action='+a+']').isVisible(),false);assert.match(await p.locator('[data-action=attack] small').innerText(),/삼재/);
 const first=await p.evaluate(()=>JSON.stringify(__game.worldState.murimJourney.sceneState));await p.evaluate(()=>{window.__set=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('full');};});await p.getByRole('button',{name:'계속하기',exact:true}).click();assert.equal(await p.evaluate(()=>JSON.stringify(__game.worldState.murimJourney.sceneState)),first);await p.evaluate(()=>Storage.prototype.setItem=window.__set);
 await p.route('**/assets/art/intro/stone.webp',r=>r.abort());await p.getByRole('button',{name:'인트로 건너뛰기',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.murim-message')?.textContent.includes('이미지를 불러오지'));assert.equal(await p.getByRole('button',{name:'계속하기',exact:true}).isDisabled(),true);assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.sceneState.id),'intro-1');await p.unroute('**/assets/art/intro/stone.webp');await p.getByRole('button',{name:'이미지 다시 불러오기',exact:true}).click();await H.scenes(p);
 await H.dismiss(p);assert.equal(await p.locator('#characterMenu').evaluate(e=>e.classList.contains('has-news')),true);await p.click('#characterMenu');await H.dismiss(p);await p.waitForFunction(()=>!document.querySelector('#characterMenu').classList.contains('has-news'));assert.equal(await p.evaluate(()=>MurimGrowth.balance(__game).stone),3);
 await p.click('#growthStatus');await p.locator('[data-murim-node=edge]').click();await p.getByRole('button',{name:'수련첩 1개로 확정',exact:true}).click();await p.locator('[data-murim-node=arc]').click();await p.getByRole('button',{name:'수련첩 1개로 확정',exact:true}).click();assert.equal(await p.evaluate(()=>__game.worldState.murimLoadout.slots.moon),null);
 await p.getByRole('button',{name:'기술 단축키 설정',exact:true}).click();const moon=p.locator('[data-slot=moon]'),storm=p.locator('[data-slot=storm]');assert.ok((await moon.locator('h3').innerText()).startsWith(await p.evaluate(()=>Controls.key('moon'))+' · '));await p.evaluate(()=>{window.__set=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('full');};});await moon.locator('[data-assign=samjae-arc]').click();assert.equal(await p.evaluate(()=>__game.worldState.murimLoadout.slots.moon),null);await p.evaluate(()=>Storage.prototype.setItem=window.__set);
 await moon.locator('[data-assign=samjae-arc]').click();await storm.locator('[data-assign=samjae-arc]').click();assert.deepEqual(await p.evaluate(()=>__game.worldState.murimLoadout.slots),{moon:null,storm:'samjae-arc'});await H.dismiss(p);await p.waitForFunction(()=>document.querySelector('[data-action=moon]').hidden&&!document.querySelector('[data-action=storm]').hidden);assert.match(await p.locator('[data-action=storm]').getAttribute('aria-label'),/횡검/);assert.doesNotMatch(await p.locator('#canvas').getAttribute('aria-label'),/월영참|천뢰격|연환검|매화/);
 await p.evaluate(()=>{Controls.bind('storm','KeyZ',true);__game.player.mp=__game.stats().mp;});const mp=await p.evaluate(()=>__game.player.mp);await p.keyboard.press('KeyQ');assert.equal(await p.evaluate(()=>__game.player.mp),mp);await p.keyboard.press('KeyZ');assert.ok(await p.evaluate(()=>__game.player.cool.moon>0));
 await p.click('#growthStatus');await p.getByRole('button',{name:'기술 단축키 설정',exact:true}).click();await p.evaluate(()=>{window.__set=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('full');};});await moon.locator('[data-assign=samjae-arc]').click();assert.ok(await p.evaluate(()=>__game.player.cool.moon>0),'failed swap preserves technique cooldown');assert.equal(await p.evaluate(()=>__game.worldState.murimLoadout.slots.storm),'samjae-arc');await p.evaluate(()=>Storage.prototype.setItem=window.__set);await moon.locator('[data-assign=samjae-arc]').click();assert.ok(await p.evaluate(()=>__game.player.cool.moon>0));await moon.getByRole('button',{name:'배치 해제',exact:true}).click();assert.deepEqual(await p.evaluate(()=>__game.worldState.murimLoadout.slots),{moon:null,storm:null});await moon.locator('[data-assign=samjae-arc]').click();await p.setViewportSize({width:360,height:740});assert.ok(await p.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));fs.mkdirSync('browser-results/murim-scenes',{recursive:true});await p.screenshot({path:'browser-results/murim-scenes/loadout-mobile.png'});
 await H.dismiss(p);await p.keyboard.press('F1');assert.doesNotMatch(await p.locator('#dialogBody').innerText(),/월영참|천뢰격|연환검|헌터 승급|안전 왕복|별도 전수자/);await H.dismiss(p);await p.click('#menu');await p.getByRole('button',{name:'조작 안내',exact:true}).click();assert.doesNotMatch(await p.locator('#dialogBody').innerText(),/월영참|천뢰격|연환검|호위와 봉인/);await H.dismiss(p);await p.click('#menu');await p.getByRole('button',{name:'입력 설정',exact:true}).click();assert.doesNotMatch(await p.locator('#dialogBody').innerText(),/월영참|천뢰격|연환검|오의|매화노방/);await H.dismiss(p);
 await p.reload();await p.waitForFunction(()=>ArtPreview.ready);await p.click('#continue');assert.equal(await p.evaluate(()=>__game.worldState.murimLoadout.slots.moon),'samjae-arc');assert.equal(await p.evaluate(()=>MurimNotices.unread(__game,'stats').length),0);await H.enter(p,'murimTutorial');await H.fight(p);await H.exit(p);await H.enter(p,'murimRoad1');await H.fight(p);await H.exit(p);assert.ok(await p.evaluate(()=>MurimNotices.unread(__game,'stats').length>0));
 console.log('Scene retry/rollback, notices, learned-only HUD, key remap, loadout swap/unset, mobile and reload passed');
},{classic:false,skipIntro:false}).catch(e=>{console.error(e);process.exitCode=1;});
