const assert=require('node:assert/strict'),fs=require('node:fs'),{run}=require('./browser-harness.cjs'),H=require('./helpers/murim-browser.cjs');
run(async p=>{
 assert.equal(await p.locator('#dialogTitle').innerText(),'되돌아오는 신호');await H.scenes(p,{skip:false});await H.enter(p,'murimTutorial');assert.equal((await H.fight(p)).waves,3);await H.exit(p);
 for(let i=1;i<=10;i++){await H.enter(p,'murimRoad'+i);await H.fight(p);await H.exit(p);}
 assert.deepEqual(await p.evaluate(()=>__game.worldState.murimJourney.mentors),['sword','inner','movement']);assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.disciple),null);
 await p.getByRole('button',{name:'제안 거절 · 나의 길',exact:true}).click();await H.scenes(p);assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.disciple),'decline');
 for(let i=1;i<=3;i++){await H.enter(p,'murimReturn'+i);await H.fight(p);if(i===3){await H.exit(p,false);await p.evaluate(()=>{window.__prepare=ArtPreview.prepare;ArtPreview.prepare=async()=>{throw Error('offline');};});await p.getByRole('button',{name:'장면 건너뛰기',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.murim-message')?.textContent.includes('귀환 준비에 실패'));assert.equal(await p.evaluate(()=>__game.area),'village');assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.stage),'return');await p.evaluate(()=>ArtPreview.prepare=window.__prepare);await H.scenes(p);}else await H.exit(p);if(i===1){await p.getByRole('button',{name:'선택 기연에 도전',exact:true}).click();await p.waitForFunction(()=>__game.area==='murimChance');await H.fight(p);await H.exit(p);}}
 await p.waitForFunction(()=>__game.area==='city');assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.rare),true);assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.cleared.length),15);assert.equal(await p.evaluate(()=>Object.values(__game.worldState.murimGrowth.levels).some(Boolean)),false);
 await p.reload();await p.waitForFunction(()=>ArtPreview.ready);await p.click('#continue');assert.equal(await p.evaluate(()=>__game.worldState.murimJourney.stage),'complete');fs.mkdirSync('browser-results/murim-scenes',{recursive:true});await p.screenshot({path:'browser-results/murim-scenes/first-return.png'});
 console.log('Image scenes, three tutorial waves, ten roads, three meetings, decline, optional chance and first return passed');
},{classic:false,skipIntro:false}).catch(e=>{console.error(e);process.exitCode=1;});
