const test=require('node:test'),assert=require('node:assert/strict');
const {Game}=require('../world-game.js'),J=require('../murim-journey.js'),G=require('../murim-growth.js');
function fresh(){const g=new Game();g.startMurimJourney();return g;}
function read(g,skip=false){let n=0;while(J.scene(g)&&J.state(g).stage!=='choice'&&n++<100)assert.ok(J.advanceScene(g,skip));assert.ok(n<100);}
function clear(g){let n=0;while(g.enemies.some(e=>e.hp>0)&&n++<20){for(const e of [...g.enemies]){e.hp=0;J.reward(g,e);}}assert.ok(n<20);}
function exit(g){return J.interact(g,'journey-exit');}
function tutorial(g){read(g,true);assert.equal(J.next(g).id,'murimTutorial');assert.ok(J.prepare(g,'murimTutorial'));Object.assign(J.state(g).tutorial,{move:true,attack:true,dash:true});clear(g);exit(g);read(g,true);}
function roads(g){tutorial(g);for(let i=1;i<=10;i++){assert.ok(J.prepare(g,'murimRoad'+i));clear(g);exit(g);read(g,true);}}
test('scene read and skip preserve the same first-entry story and never select a disciple',()=>{const a=fresh(),b=fresh();assert.equal(typeof J.scene,'function');assert.equal(J.scene(a).id,'intro-0');assert.match(J.scene(a).current.image,/signal.webp$/);assert.equal(J.prepare(a,'murimTutorial'),false);read(a);read(b,true);assert.deepEqual(J.state(a),J.state(b));assert.equal(J.state(a).disciple,null);assert.equal(J.next(a).id,'murimTutorial');});
test('three tutorial waves spawn 2/2/3 and survive wave save/reload without grants',()=>{let g=fresh();read(g,true);J.prepare(g,'murimTutorial');assert.equal(g.enemies.length,2);for(const e of [...g.enemies]){e.hp=0;J.reward(g,e);}assert.equal(J.state(g).tutorial.wave,1);assert.equal(g.enemies.length,2);g=Game.load(g.save());assert.equal(g.enemies.length,2);for(const e of [...g.enemies]){e.hp=0;J.reward(g,e);}assert.equal(g.enemies.length,3);assert.equal(J.state(g).tutorial.wave,2);clear(g);assert.equal(J.tutorialReady(g),false);assert.ok(J.practice(g));assert.equal(J.state(g).tutorial.wave,0);assert.deepEqual(G.state(g).grants,['start']);});
for(const choice of ['accept','decline'])test('single destination scenes reach first return with '+choice+' and zero investment',()=>{let g=fresh();roads(g);assert.equal(J.state(g).stage,'choice');assert.equal(J.advanceScene(g,true),false);assert.equal(J.state(g).disciple,null);assert.ok(J.choose(g,choice));read(g,true);assert.equal(J.choose(g,'accept'),false);for(let i=1;i<=3;i++){assert.equal(J.next(g).id,'murimReturn'+i);assert.ok(J.prepare(g,'murimReturn'+i));clear(g);const balance=G.balance(g);g=Game.load(g.save());assert.deepEqual(G.balance(g),balance);exit(g);read(g,true);if(i===1)assert.ok(J.skipChance(g));}assert.equal(J.state(g).stage,'complete');assert.equal(g.area,'city');assert.deepEqual(Object.values(G.state(g).levels),Array(9).fill(0));assert.equal(J.state(g).rare,false);assert.doesNotThrow(()=>Game.load(g.save()));});
test('completion and scene replay cannot duplicate grants or reopen cleared destinations',()=>{const g=fresh();tutorial(g);J.prepare(g,'murimRoad1');clear(g);const reward=JSON.stringify({growth:G.state(g),xp:g.xp,gold:g.gold});exit(g);assert.equal(J.prepare(g,'murimRoad2'),false);read(g,true);assert.equal(J.prepare(g,'murimRoad1'),false);assert.equal(J.advanceScene(g,true),false);assert.equal(JSON.stringify({growth:G.state(g),xp:g.xp,gold:g.gold}),reward);assert.equal(J.next(g).id,'murimRoad2');assert.equal(J.points(g).some(p=>p.kind==='npc'||p.kind==='training'||p.kind==='journey-route'),false);});
test('legacy journey migration preserves grants, investments, choices and completed history',()=>{const g=fresh();roads(g);J.choose(g,'decline');read(g,true);const s=J.state(g);delete s.sceneState;delete s.completedScenes;delete s.chanceChoice;delete s.tutorial.wave;delete s.tutorial.waves;const growth=JSON.stringify(G.state(g)),cleared=JSON.stringify(s.cleared);J.validate(g);assert.equal(JSON.stringify(G.state(g)),growth);assert.equal(JSON.stringify(s.cleared),cleared);assert.equal(s.disciple,'decline');assert.equal(J.next(g).id,'murimReturn1');assert.equal(J.scene(g),null);});
test('invalid mentor timing and scene page are rejected without resetting investments',()=>{const g=fresh();J.state(g).mentors=['sword'];assert.throws(()=>J.validate(g),/여정/);J.state(g).mentors=[];J.state(g).sceneState.page=999;assert.throws(()=>J.validate(g),/장면/);});
test('retreat from a live final tutorial wave cannot count as tutorial completion',()=>{const g=fresh();read(g,true);J.prepare(g,'murimTutorial');Object.assign(J.state(g).tutorial,{move:true,attack:true,dash:true});for(let wave=0;wave<2;wave++)for(const e of [...g.enemies]){e.hp=0;J.reward(g,e);}assert.equal(J.state(g).tutorial.wave,2);g.retreat();assert.equal(J.state(g).stage,'tutorial');assert.equal(J.state(g).cleared.includes('murimTutorial'),false);assert.equal(J.next(g).id,'murimTutorial');});
test('legacy completed encounter snapshot restores without replaying story or granting again',()=>{const g=fresh();tutorial(g);J.prepare(g,'murimRoad1');clear(g);const raw=JSON.parse(g.save()),s=raw.worldState.murimJourney;for(const key of ['sceneState','completedScenes','chanceChoice'])delete s[key];delete s.tutorial.wave;delete s.tutorial.waves;const restored=Game.load(JSON.stringify(raw));assert.equal(restored.area,'murimRoad1');assert.equal(restored.enemies.some(e=>e.hp>0),false);assert.deepEqual(G.state(restored),G.state(g));exit(restored);assert.equal(J.scene(restored),null);assert.equal(J.next(restored).id,'murimRoad2');});
test('scene cursor resumes on the exact page without consuming it on load',()=>{const g=fresh();J.advanceScene(g);const before=J.scene(g);const restored=Game.load(g.save());assert.equal(J.scene(restored).id,before.id);assert.equal(J.scene(restored).page,before.page);assert.deepEqual(J.state(restored).completedScenes,[]);});
test('old two-enemy tutorial snapshot retains its roster and learned controls on migration',()=>{const g=fresh();read(g,true);J.state(g).tutorial.waves=false;J.prepare(g,'murimTutorial');Object.assign(J.state(g).tutorial,{move:true,attack:true,dash:true});g.enemies[0].hp=0;g.enemies[0].rewarded=true;g.enemies[1].hp=20;const raw=JSON.parse(g.save()),s=raw.worldState.murimJourney;for(const key of ['sceneState','completedScenes','chanceChoice'])delete s[key];delete s.tutorial.wave;delete s.tutorial.waves;delete raw.worldState.murimLoadout;const restored=Game.load(JSON.stringify(raw));assert.equal(restored.enemies.length,2);assert.equal(restored.enemies[1].hp,20);clear(restored);exit(restored);assert.equal(J.state(restored).stage,'road');assert.equal(J.scene(restored).id,'murim-departure');assert.deepEqual(G.state(restored).grants,['start']);});
test('death returns to current preparation and retry does not grant partial encounter rewards',()=>{let g=fresh();tutorial(g);J.prepare(g,'murimRoad1');g.enemies[0].hp=0;J.reward(g,g.enemies[0]);const grants=[...G.state(g).grants];g.player.hp=0;g=Game.load(g.save());assert.equal(g.area,'village');assert.equal(J.next(g).id,'murimRoad1');assert.deepEqual(G.state(g).grants,grants);assert.ok(J.prepare(g,'murimRoad1'));clear(g);assert.equal(G.state(g).grants.filter(id=>id==='murimRoad1').length,1);});
test('a chosen disciple path cannot load the contradictory acceptance scene',()=>{const g=fresh();roads(g);J.choose(g,'decline');J.state(g).sceneState.id='murim-disciple-accept';assert.throws(()=>J.validate(g),/장면/);});
test('pending scenes cannot move a later-stage save back to earlier story',()=>{const g=fresh();roads(g);J.choose(g,'decline');read(g,true);J.state(g).completedScenes=J.state(g).completedScenes.filter(id=>id!=='murim-departure');J.state(g).sceneState={id:'murim-departure',page:0};assert.throws(()=>J.validate(g),/장면/);});
module.exports={fresh,read,clear,exit,tutorial,roads};

test('new journey guidance never falls back to a classic dungeon gate',()=>{const g=fresh();assert.equal(g.target(),null);read(g,true);assert.equal(g.target(),null);J.prepare(g,'murimTutorial');assert.ok(g.target()?.journeyEnemy);});
