const assert=require('node:assert/strict'),fs=require('node:fs'),{run}=require('./browser-harness.cjs');
run(async p=>{
 assert.equal(await p.evaluate(()=>!!__game.worldState.murimJourney),true,'default new game uses the new murim journey');
 assert.equal(await p.evaluate(()=>__game.area),'murimTutorial');
 await require('./helpers/murim-browser.cjs').fight(p);await require('./helpers/murim-browser.cjs').exit(p);await require('./helpers/murim-browser.cjs').dismiss(p);
 await p.click('#growthStatus');await p.waitForSelector('.murim-tree');assert.equal(await p.locator('.murim-tree-column').count(),3);assert.equal(await p.getByRole('button',{name:'현실 보기',exact:true}).count(),0);await p.locator('[data-murim-node="edge"]').click();await p.evaluate(()=>{window.__storageSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('full');};});await p.getByRole('button',{name:'수련첩 1개로 확정',exact:true}).click();assert.match(await p.locator('.murim-skill-detail').innerText(),/현재 투자 0\/3/);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem(SaveSlots.keys.current)).worldState.murimGrowth.levels.edge),0);await p.evaluate(()=>{Storage.prototype.setItem=window.__storageSet;});await p.getByRole('button',{name:'수련첩 1개로 확정',exact:true}).click();assert.equal(await p.evaluate(()=>__game.worldState.murimGrowth.levels.edge),1);
 fs.mkdirSync('browser-results/murim-journey',{recursive:true});await p.screenshot({path:'browser-results/murim-journey/skills-desktop.png'});
 await p.keyboard.press('Escape');await p.click('#characterMenu');await p.getByRole('button',{name:'공격 증가',exact:true}).click();await p.getByRole('button',{name:'단련석 1개로 확정',exact:true}).click();assert.equal(await p.evaluate(()=>__game.worldState.murimGrowth.allocation.attack),1);
 await p.setViewportSize({width:360,height:740});await p.screenshot({path:'browser-results/murim-journey/stats-mobile.png'});assert.ok(await p.locator('.murim-growth-screen').evaluate(e=>e.scrollWidth<=innerWidth));
 await p.keyboard.press('Escape');await p.click('#growthStatus');assert.ok(await p.locator('.murim-tree').evaluate(e=>e.scrollWidth<=innerWidth));await p.screenshot({path:'browser-results/murim-journey/skills-mobile.png'});
 await p.keyboard.press('Escape');await p.click('#missionsMenu');assert.equal(await p.locator('[data-journey-destination]').count(),1);assert.equal(await p.locator('[data-journey-destination]').getAttribute('data-journey-destination'),'murimRoad1');await p.evaluate(()=>{window.__artPrepare=ArtPreview.prepare;ArtPreview.prepare=async()=>{throw Error('offline');};});await p.getByRole('button',{name:'다음 지역으로',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.murim-message')?.textContent.includes('실패'));assert.equal(await p.getByRole('button',{name:'다음 지역으로',exact:true}).isEnabled(),true);await p.evaluate(()=>{ArtPreview.prepare=window.__artPrepare;});await p.getByRole('button',{name:'다음 지역으로',exact:true}).click();await p.waitForFunction(()=>__game.area==='murimRoad1');
 await p.evaluate(()=>localStorage.setItem(SaveSlots.keys.current,__game.save()));await p.reload();await p.waitForFunction(()=>ArtPreview.ready);await p.click('#continue');assert.equal(await p.evaluate(()=>__game.area),'murimRoad1');assert.equal(await p.evaluate(()=>__game.worldState.murimGrowth.allocation.attack),1);
 console.log('Murim journey UI: tutorial, three trees, permanent stats, ten destinations, mobile and reload passed');
},{classic:false});
