const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {Game}=require('../world-game.js'),{talk}=require('./world-fixtures.cjs'),{clear}=require('./helpers/world-journey.cjs'),Cycle=require('../cycle-one.js');
const tick=g=>{g.hitStop=0;g.step(.05);};
function ordinaryStart(){let g=Game.load(fs.readFileSync('tests/fixtures/plan-b/a8d6214-before.json','utf8'));g.enter('rift');for(let i=0;i<300&&g.area==='rift';i++)tick(g);g.enter('city');talk(g,'warden');g.enter('village');talk(g,'master');talk(g,'huashan');g.enter('city');talk(g,'warden');assert.equal(g.enter('heart'),true);clear(g);g.enter('city');talk(g,'warden');assert.equal(g.fate.stage,6);return g;}
test('ordinary retraining opens chapter three and save preserves zero opportunity ownership',()=>{let g=ordinaryStart();assert.equal(g.fate.path,null);assert.deepEqual(g.revision.inherited,[]);g=Game.load(g.save());assert.equal(g.fate.stage,6);assert.equal(g.fate.path,null);});
test('ordinary play completes every later chapter and direct report without rare skill',()=>{let g=ordinaryStart();talk(g,'warden');g.enter('village');talk(g,'shop');g.enter('returnPass');clear(g);talk(g,'winch');g.enter('city');talk(g,'warden');g.enter('returnDock');clear(g);g.enter('city');talk(g,'warden');g.enter('village');talk(g,'returned-yeonhwa');talk(g,'master');talk(g,'master');g.enter('city');talk(g,'warden');if(g.journey.phase<3)talk(g,'warden');assert.equal(g.enter('station'),true);clear(g);assert.equal(g.journey.phase,4);g.enter('city');talk(g,'warden');assert.equal(g.journey.phase,5);talk(g,'warden');g.enter('stabilization');talk(g,'six-record');g.enter('village');talk(g,'master');g.enter('stabilization');clear(g);talk(g,'six-cut');tick(g);assert.equal(g.laterStory.six,4);g.enter('city');talk(g,'warden');talk(g,'warden');g.chooseSevenPreparation('evacuation');for(const area of ['woundPass','woundDock','woundCore']){if(area==='woundCore'){g.enter('village');talk(g,'master');}assert.ok(g.enter(area));clear(g);talk(g,'seven-status');tick(g);g=Game.load(g.save());}g.enter('city');talk(g,'warden');assert.equal(g.laterStory.seven,5);g.enter('village');talk(g,'returned-yeonhwa');g.enter('transportRoad');Cycle.interact(g,'civilian-route','device');clear(g);g.enter('city');talk(g,'warden');g.enter('transportDock');clear(g);g.enter('city');talk(g,'warden');g.enter('village');talk(g,'master');g.enter('supplyRidge');clear(g);talk(g,'supply-cut');g.enter('city');talk(g,'warden');g.enter('evacuationDock');talk(g,'evacuation-route');clear(g);g.enter('city');talk(g,'warden');g.enter('village');talk(g,'master');g.enter('overseerApproach');clear(g);g.enter('overseerHall');talk(g,'overseer-confront');clear(g);g.enter('village');talk(g,'master');g.enter('city');talk(g,'warden');g=Game.load(g.save());assert.equal(g.worldState.cycleOne.epilogue,true);assert.equal(g.fate.path,null);assert.deepEqual(g.revision.inherited,[]);});
test('chapter one introduces a separate transmitter and requires real basics before promotion',()=>{const g=new Game();g.beginIntro(true);g.finishIntro();g.enter('village');talk(g,'master');assert.ok(g.points().some(p=>p.id==='huashan'));talk(g,'huashan');assert.equal(g.worldState.ordinaryGrowth.transmission,true);assert.equal(g.worldState.planB.basicHit,false);g.enter('forest');clear(g);g.enter('village');const p=g.progress;talk(g,'master');assert.equal(g.progress,p,'boss victory retained but missing practice is guided separately');assert.match(g.objective().text,/수련|회피|전수/);});

test('fresh enlarged chapter one through chapter ten uses actual ordinary attacks',()=>{const g=require('./helpers/ordinary-journey.cjs').complete();assert.ok(g.worldState.planB.recognized);assert.ok(g.worldState.planB.rescueReported);assert.ok(g.worldGrowth.reality.mastery.sword>=8);assert.equal(g.fate.path,null);});
test('ordinary sword practice qualifies for the first realm without a rare inheritance',()=>{const A=require('../advancement.js'),g=require('./helpers/ordinary-journey.cjs').three();g.enter('village');assert.deepEqual(g.revision.inherited,[]);assert.ok(A.describe(g,'realm').canStart);assert.ok(A.start(g,'realm'));let n=0;while(g.advancementTrial&&n++<5000){const r=g.advancementTrial;for(const e of g.enemies.filter(e=>e.hp>0))g.strike(e,99999);if(r.pulse)Object.assign(g.player,{x:r.pulse.x+250,y:r.pulse.y});else if(r.responses>=(r.phase?2:1))Object.assign(g.player,{x:r.zone.x,y:r.zone.y});g.hitStop=0;g.step(.05);}assert.ok(n<5000);assert.ok(g.breakthrough());assert.equal(Game.load(g.save()).worldState.advancement.realm,1);});
