const test=require('node:test'),assert=require('node:assert/strict');
const {Game}=require('../progression.js'),Presentation=require('../presentation.js');
function veteran(){const g=new Game();g.progress=6;g.training=2;return g;}
function enemy(g){g.enter('forest');const e=g.enemies[0];Object.assign(e,{hp:10000,maxHp:10000,wind:0});return e;}
test('family mastery increases only its own damage at 5/10/20/30',()=>{
 for(const [value,expected]of [[4,100],[5,103],[9,103],[10,106],[20,109],[30,112]]){const g=veteran(),e=enemy(g);g.journey.mastery.sword=value;assert.equal(g.strike(e,100,'attack'),expected);}
 const g=veteran(),e=enemy(g);g.journey.mastery.ripple=30;assert.equal(g.strike(e,100,'attack'),100);
});
test('trial and unrelated manifestation damage do not receive mastery bonuses',()=>{const g=veteran(),e=enemy(g);g.journey.mastery.sword=30;assert.equal(g.strike(e,100,'manifestation'),100);g.trial={path:'ripple',feat:true};assert.equal(g.strike(e,100,'attack'),100);});
test('level up reports actual permanent stat deltas',()=>{const g=veteran(),e=enemy(g);g.xp=g.stats().next-1;g.strike(e,20000,'attack');assert.ok(g.events.some(e=>e.type==='level-up'&&e.hp===18&&e.mp===5&&e.attack===3));});
test('equipped interpretation guide offers return instead of repeated equip command',()=>{const g=veteran();g.fate.path='ripple';g.journey.known=['ripple-guard'];g.enter('archive');g.chooseInterpretation('ripple-guard');const hint=Presentation.guide(g,'ripple');assert.equal(hint.stage,'equipped');assert.equal(hint.target.id,'exit');assert.doesNotMatch(hint.text,/이어가기.*선택/);assert.notEqual(g.objective().target?.id,'archive-rest');});
test('equipped guidance outside archive resumes current story rather than returning to archive',()=>{const g=veteran();g.fate.path='ripple';g.journey.known=['ripple-guard'];g.journey.selected.ripple='ripple-guard';g.enter('village');const hint=Presentation.guide(g,'ripple');assert.equal(hint.stage,'equipped');assert.notEqual(hint.target?.id,'archiveGate');assert.equal(hint.target?.id,g.objective().target?.id);});
test('contract locks early and spawns four independent enemies without moving the story',()=>{const g=new Game();assert.equal(typeof g.startContract,'function');assert.equal(g.startContract(),false);g.progress=6;g.training=2;assert.equal(g.startContract(),true);assert.equal(g.area,'rift');assert.equal(g.enemies.length,4);assert.ok(g.enemies.every(e=>e.contract&&!e.boss));assert.equal(g.progress,6);assert.equal(g.startContract(),false);});
test('contract pays once only after actual kills and report at city; story untouched',()=>{const g=veteran();assert.equal(typeof g.startContract,'function');const start={gold:g.gold,xp:g.xp,materials:g.journey.materials};g.startContract();assert.equal(g.claimContract(),false);g.reward(g.enemies[0]);assert.equal(g.contract.kills,0);for(const e of g.enemies)g.strike(e,9999,'attack');assert.equal(g.contract.status,'ready');assert.equal(g.gold,start.gold);assert.equal(g.progress,6);assert.equal(g.clears,0);assert.equal(g.claimContract(),false);g.enter('city');assert.equal(g.claimContract(),true);assert.equal(g.gold,start.gold+80);assert.equal(g.xp,start.xp+100);assert.equal(g.journey.materials,start.materials+2);assert.equal(g.claimContract(),false);});
test('contract retreat, death entry and active save load cancel without granting rewards',()=>{for(const mode of ['retreat','load','death']){const g=veteran();assert.equal(typeof g.startContract,'function');g.startContract();g.strike(g.enemies[0],9999,'attack');let r=g;if(mode==='load')r=Game.load(g.save());else if(mode==='retreat')g.retreat();else {g.player.hp=0;for(let i=0;i<5;i++)g.step(.05);}assert.equal(r.contract.status,'idle',mode);assert.equal(r.gold<=40,true);assert.equal(r.progress,6);}});
test('ready contract survives load and corrupted completion is rejected',()=>{const g=veteran();assert.equal(typeof g.startContract,'function');g.startContract();for(const e of g.enemies)g.strike(e,9999,'attack');g.enter('city');const r=Game.load(g.save());assert.equal(r.contract.status,'ready');assert.equal(r.claimContract(),true);const d=JSON.parse(g.save());d.contract.kills=3;assert.throws(()=>Game.load(JSON.stringify(d)));});
test('v7 migration preserves earned mastery and never fabricates contract completion',()=>{const g=veteran();g.journey.mastery.sword=20;const d=JSON.parse(g.save());d.version=7;delete d.contract;const r=Game.load(JSON.stringify(d));assert.equal(r.journey.mastery.sword,20);assert.equal(r.contract?.completed,0);});
test('old companion saves no longer create a fighting companion',()=>{const g=veteran();g.journey.companion=true;g.enter('station');assert.equal(g.experimentRuntime.companion,null);const o=g.points().find(p=>p.id==='partner');assert.ok(o);Object.assign(g.player,o);g.interact();assert.equal(g.experimentRuntime.companion,null);});
test('contract board is reachable and interacts without changing story',()=>{const g=veteran(),o=g.points().find(p=>p.id==='contract-board');assert.ok(o);assert.ok(g.lineClear(g.player,o));Object.assign(g.player,{x:o.x,y:o.y});assert.equal(g.interact().type,'contract-board');assert.equal(g.progress,6);});
test('contract rejects inconsistent save states and intro cannot start it',()=>{const g=veteran(),d=JSON.parse(g.save());for(const c of [{status:'idle',kills:1,completed:0},{status:'ready',kills:4,completed:-1},{status:'active',kills:2,completed:0},{status:'idle',kills:0,completed:1.5}])assert.throws(()=>Game.load(JSON.stringify({...d,contract:c})));g.beginIntro(true);assert.equal(g.startContract(),false);assert.equal(g.points().some(p=>p.id==='contract-board'),false);});
test('level cap has no next-level preview or false level-up notice',()=>{const {levelPreview}=require('../progression.js'),g=veteran();g.level=80;assert.equal(levelPreview(g).next,null);g.startContract();for(const e of g.enemies)g.strike(e,9999,'attack');g.enter('city');g.claimContract();assert.equal(g.level,80);assert.equal(g.events.some(e=>e.type==='level-up'),false);});
test('contract claim emits its level-up stat notice after the reward toast',()=>{const g=veteran();g.startContract();for(const e of g.enemies)g.strike(e,9999,'attack');g.enter('city');g.xp=g.stats().next-1;g.events=[];g.claimContract();assert.equal(g.events.at(-1).type,'level-up');assert.equal(g.events.at(-1).attack,3);});
