const test=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../world-game.js');
function setup(family){const g=new Game();g.finishIntro?.();g.enter('village');g.fate.path=family;g.fate.discovered=[family];g.fate.proven=[family];g.legend.awakened=[family];g.revision.inherited=[family];g.worldGrowth.murim.equipped=family;g.enter('city');g.enter('rift');Object.assign(g.player,{x:400,y:700,face:0,mp:80,hp:120,invuln:0});g.enemies=[{id:'real-target',x:470,y:700,r:20,hp:500,maxHp:500,boss:false,kind:'shade',damage:18,speed:0,cd:5,wind:0,range:62,tx:400,ty:700,flash:0,attacks:0}];return g;}
test('reality inheritance requires an explicit equip and an actual absorbed attack',()=>{const g=setup('ripple');assert.equal(typeof g.equipReality,'function');assert.equal(g.skillInfo('signature1').locked,true);assert.equal(g.equipReality('ripple'),false,'only safe base equips');g.enter('city');assert.equal(g.equipReality('ripple'),true);g.enter('rift');const e=g.enemies[0];g.player.invuln=0;const hp=g.player.hp;assert.equal(g.act('signature1'),true);assert.equal(g.realityStatus('ripple'),'available');g.takeHit(e);assert.equal(g.player.hp,hp);assert.equal(g.realityStatus('ripple'),'settled');assert.equal(g.combat.charges,0);});
test('acceleration without a live telegraph never settles or leaves a return echo',()=>{const g=setup('echo');g.worldGrowth.reality.equipped='echo';assert.equal(g.act('signature1'),true);assert.equal(g.combat.echo,null);assert.equal(g.realityStatus?.('echo'),'available');});
test('suppression needs a telegraph and is single target, not a field',()=>{const g=setup('seal');g.worldGrowth.reality.equipped='seal';g.enemies.push({...g.enemies[0],id:'second',x:480});g.enemies[0].wind=1;g.enemies[1].wind=1;assert.equal(g.act('signature1'),true);assert.equal(g.enemies[0].wind,0);assert.equal(g.enemies[1].wind,1);assert.equal(g.combat.field,null);assert.equal(g.realityStatus?.('seal'),'settled');assert.equal(g.worldGrowth.murim.mastery.seal,0);assert.equal(g.worldGrowth.reality.mastery.seal,1);});
test('invalid targets, held skills and empty safe use cannot grant settlement',()=>{const g=setup('seal');g.worldGrowth.reality.equipped='seal';g.act('signature1');assert.equal(g.realityStatus?.('seal'),'available');g.player.cool.signature1=0;g.enemies[0].wind=1;g.act('signature1',true);assert.equal(g.realityStatus?.('seal'),'available');});
test('reality basic attacks do not use murim training damage reduction',()=>{const g=setup('ripple');g.training=3;g.takeHit(g.enemies[0]);assert.equal(g.player.hp,102);});
module.exports={setup};
test('successful evasion persists but temporary boost clears on travel',()=>{const {inherited,opponent}=require('./world-fixtures.cjs'),g=inherited('echo'),e=opponent(g);e.wind=.15;g.act('signature1');for(let i=0;i<5;i++)g.step(.05);assert.equal(g.realityStatus('echo'),'settled');assert.ok(g.realityRuntime.boost);g.enter('city');assert.equal(g.realityRuntime,null);assert.equal(Game.load(g.save()).realityStatus('echo'),'settled');});
test('comparison field has two rewardless foes and returns safely',()=>{const {inherited}=require('./world-fixtures.cjs'),g=inherited();assert.equal(typeof g.beginComparison,'function');const gold=g.gold,xp=g.xp;assert.equal(g.beginComparison(),true);assert.equal(g.enemies.length,2);g.act('signature1');g.player.invuln=0;g.takeHit(g.enemies[0]);assert.equal(g.realityStatus('ripple'),'settled');for(const e of g.enemies)g.strike(e,99999);assert.equal(g.gold,gold);assert.equal(g.xp,xp);assert.equal(g.progress,12);g.retreat();assert.equal(g.area,'city');});
test('residual attacks certify without awarding settlement or mastery',()=>{const g=setup('ripple');g.worldGrowth.reality.equipped='ripple';g.enemies[0].residual=true;g.act('signature1');g.takeHit(g.enemies[0]);assert.equal(g.player.hp,120);assert.equal(g.realityStatus('ripple'),'available');assert.equal(g.worldGrowth.reality.mastery.ripple,0);});
