const test=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../world-game.js'),R=require('../boundary-resonance.js');let C;try{C=require('../resonance-challenges.js');}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
function ready(){assert.ok(C,'resonance challenges exist');const g=new Game();g.finishIntro();g.training=3;g.progress=12;g.enter('village');return g;}
function clear(g){for(const e of g.enemies)g.strike(e,99999);g.hitStop=0;}
test('nine optional challenges respect source unlocks and only start at Murim hub',()=>{const g=ready();assert.equal(C.list(g).length,9);assert.equal(C.list(g).filter(x=>x.canEnter).length,6);assert.equal(C.start(g,'returnPass:survival'),false);assert.equal(C.start(g,'forest:survival'),true);assert.equal(C.start(g,'ruins:sustain'),false);assert.equal(g.growthWorld(),'murim');});
test('survival secures target for two seconds, pays once, preserves main progress and saved completion',()=>{const g=ready(),before={progress:g.progress,gold:g.gold,xp:g.xp,mastery:{...g.journey.mastery}};C.start(g,'forest:survival');clear(g);const target=C.target(g);Object.assign(g.player,{x:target.x,y:target.y});for(let i=0;i<39;i++){g.hitStop=0;g.step(.05);}assert.equal(C.state(g).completed.length,0);for(let i=0;i<4;i++){g.hitStop=0;g.step(.05);}assert.ok(C.state(g).completed.includes('forest:survival'));assert.equal(R.balance(g).crystal,1);assert.deepEqual({progress:g.progress,gold:g.gold,xp:g.xp,mastery:{...g.journey.mastery}},before);g.enter('village');assert.equal(C.start(g,'forest:survival'),true);clear(g);Object.assign(g.player,{x:C.target(g).x,y:C.target(g).y});for(let i=0;i<44;i++){g.hitStop=0;g.step(.05);}assert.equal(R.balance(g).crystal,1);g.enter('village');const h=Game.load(g.save());assert.deepEqual(C.state(h).completed,['forest:survival']);});
test('sustain requires three actual paid contacts, not empty skill presses',()=>{const g=ready();C.start(g,'forest:sustain');Object.assign(g.player,{x:100,y:100,face:0});g.act('moon');assert.equal(C.state(g).active.paid,0);const e=g.enemies[0];Object.assign(g.player,{x:e.x-35,y:e.y,face:0});for(let i=0;i<3;i++){g.player.cool.moon=0;g.player.mp=100;g.act('moon');}assert.equal(C.state(g).active.paid,3);clear(g);g.step(.05);assert.ok(C.state(g).completed.includes('forest:sustain'));});
test('precision credits real evasion at impact and not an unthreatened dash',()=>{const g=ready();C.start(g,'forest:precision');Object.assign(g.player,{x:100,y:100});g.act('dash');for(let i=0;i<8;i++)g.step(.05);assert.equal(C.state(g).active.responses,0);const e=g.enemies[0];for(let j=0;j<2;j++){Object.assign(g.player,{x:500,y:650,face:Math.PI/2,invuln:0});Object.assign(e,{x:540,y:650,wind:.2,tx:500,ty:650,range:62,attacks:j+1,cd:5});g.player.cool.dash=0;assert.ok(g.act('dash'));for(let i=0;i<9;i++){g.hitStop=0;g.step(.05);}}assert.equal(C.state(g).active.responses,2);clear(g);g.step(.05);assert.ok(C.state(g).completed.includes('forest:precision'));});
test('active challenge restores consistently and retreat cannot grant rewards',()=>{const g=ready();C.start(g,'ruins:sustain');g.enemies[0].hp-=10;const h=Game.load(g.save());assert.equal(h.area,g.area);assert.equal(h.enemies[0].hp,g.enemies[0].hp);assert.equal(C.state(h).active.paid,0);h.retreat();assert.equal(h.area,'village');assert.equal(C.state(h).active,null);assert.equal(R.balance(h).crystal,0);});
test('completion validation rejects counters that cannot meet the named challenge',()=>{const g=ready();C.start(g,'forest:sustain');clear(g);const s=C.state(g);s.completed=['forest:sustain'];s.results={'forest:sustain':{seconds:1,paid:0,responses:0,damage:0,potions:0}};assert.throws(()=>C.validate(g),/도전/);});
test('death and retreat restore consumables without charging gold',()=>{const g=ready();g.potions=3;g.gold=100;C.start(g,'forest:survival');g.potions=2;g.player.hp=1;g.player.invuln=0;g.takeHit({...g.enemies[0],damage:99999});g.hitStop=0;g.step(.05);assert.equal(g.gold,100);assert.equal(g.potions,3);assert.equal(g.area,'village');assert.equal(C.state(g).active,null);});
test('deferred paid attack cannot count an empty cast or a different later attack',()=>{const g=ready();C.start(g,'forest:sustain');const r=C.beginAction(g,'storm',false);C.endAction(g,r,false);C.deferred(g,r.id,1);assert.equal(C.state(g).active.paid,0);});
test('entry preparation cancelled by its caller cannot enter a challenge',async()=>{const g=ready();const result=await C.request(g,'forest:survival',async()=>false);assert.equal(result.ok,false);assert.equal(g.area,'village');assert.equal(C.state(g).active,null);});
test('echo replay delayed R contact counts its paid cast exactly once',()=>{const {five}=require('./helpers/world-journey.cjs'),{historicalInterpretation}=require('./world-fixtures.cjs'),g=five('echo');historicalInterpretation(g,'echo-replay');g.enter('village');assert.ok(g.chooseInterpretation('echo-replay'));assert.ok(C.start(g,'forest:sustain'));const e=g.enemies[0];Object.assign(g.player,{x:e.x-35,y:e.y,face:0,mp:g.stats().mp});for(const k of Object.keys(g.player.cool))g.player.cool[k]=0;assert.ok(g.act('signature1'));assert.ok(g.act('signature2'));for(let i=0;i<15;i++){g.hitStop=0;g.step(.05);}assert.ok(e.hp<e.maxHp);assert.equal(C.state(g).active.paid,1);for(let i=0;i<15;i++){g.hitStop=0;g.step(.05);}assert.equal(C.state(g).active.paid,1);});
