const assert=require('node:assert/strict'),{run}=require('./browser-harness.cjs'),path=require('node:path'),fs=require('node:fs');
const evidence=path.join(__dirname,'..','browser-results');fs.mkdirSync(evidence,{recursive:true});
run(async p=>{
 await p.evaluate(()=>{const g=window.__game;g.training=3;g.progress=12;g.fate.stage=2;g.fate.discovered=['ripple'];g.fate.proven=['ripple'];g.enter('village');g.acceptFate('ripple');g.enter('city');g.events=[];g.save();});
 await p.click('#characterMenu');await p.locator('.character-growth').waitFor();
 await p.getByRole('button',{name:'첫 정착 추천',exact:true}).click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).allocation.attack),0,'preview must not spend crystals');
 await p.getByRole('button',{name:'결정 8개로 배분 확정',exact:true}).click();
 assert.deepEqual(await p.evaluate(()=>BoundaryResonance.bonus(__game)),{attack:4,hp:24,mp:0});
 await p.getByRole('button',{name:'공명 결정 투자 환불',exact:true}).click();await p.getByRole('button',{name:'결정 8개 환불 확정',exact:true}).click();
 await p.getByRole('button',{name:'공격 증가',exact:true}).focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'공격 증가');
 await p.getByRole('button',{name:'결정 1개로 배분 확정',exact:true}).click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).allocation.attack),1);
 await p.keyboard.press('Escape');await p.click('#growthStatus');await p.getByRole('button',{name:'파문',exact:true}).click();await p.locator('[data-skill=signature1]').click();await p.locator('[data-upgrade=ripple-window]').click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.effects(__game,'ripple').guardWindow),.9);
 await p.keyboard.press('Escape');await p.click('#characterMenu');
 await p.evaluate(()=>{const old=WorldGame.Game.load;WorldGame.Game.load=function(...args){return window.__game=old.apply(this,args);};window.__setItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('quota');};});
 await p.getByRole('button',{name:'공격 증가',exact:true}).click();await p.getByRole('button',{name:'결정 1개로 배분 확정',exact:true}).click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).allocation.attack),1);
 await p.evaluate(()=>{Storage.prototype.setItem=window.__setItem;});
 await p.setViewportSize({width:360,height:800});await p.evaluate(()=>document.documentElement.style.fontSize='200%');
 assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.keyboard.press('Escape');await p.getByRole('button',{name:'초안 버리기',exact:true}).click();await p.click('#missionsMenu');await p.getByRole('button',{name:'공명 도전',exact:true}).click();await p.getByRole('button',{name:'버티는 힘 목표 선택',exact:true}).click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).goal),'survival');
 await p.screenshot({path:path.join(evidence,'resonance-mobile.png')});
 await p.setViewportSize({width:1280,height:900});await p.evaluate(()=>document.documentElement.style.fontSize='100%');
 await p.keyboard.press('Escape');await p.click('#characterMenu');await p.getByRole('button',{name:'공명 결정 투자 환불',exact:true}).click();await p.getByRole('button',{name:'결정 1개 환불 확정',exact:true}).click();assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).allocation.attack),0);
 await p.keyboard.press('Escape');await p.click('#growthStatus');await p.getByRole('button',{name:'스킬 초기화',exact:true}).click();await p.getByRole('button',{name:'초기화 확정',exact:true}).click();assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).learned.length),0);
 await p.keyboard.press('Escape');await p.evaluate(()=>{__game.enter('village');__game.events=[];});await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world==='murim');await p.click('#missionsMenu');await p.getByRole('button',{name:'공명 도전',exact:true}).click();
 await p.getByRole('button',{name:'입장 · 흑풍 죽림 · 버티는 힘',exact:true}).click();await p.waitForFunction(()=>__game.area==='resonanceForest');
 await p.evaluate(()=>{window.__setItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('quota');};});
 await p.evaluate(()=>{for(const e of __game.enemies)__game.strike(e,99999);Object.assign(__game.player,{x:800,y:780});for(let i=0;i<45;i++){__game.hitStop=0;__game.step(.05);}});
 await p.waitForFunction(()=>ResonanceChallenges.runtime(__game).rewardBlocked);assert.equal(await p.evaluate(()=>ResonanceChallenges.state(__game).completed.length),0);await p.evaluate(()=>Storage.prototype.setItem=window.__setItem);await p.click('#interact');
 await p.getByRole('button',{name:'청운촌으로 귀환',exact:true}).click();await p.waitForFunction(()=>__game.area==='village');
 assert.deepEqual(await p.evaluate(()=>ResonanceChallenges.state(__game).completed),['forest:survival']);
 await p.reload();await p.waitForFunction(()=>ArtPreview.ready);await p.click('#continue');await p.waitForFunction(()=>window.__game?.area==='village');
 assert.deepEqual(await p.evaluate(()=>ResonanceChallenges.state(__game).completed),['forest:survival']);
 await p.click('#characterMenu');await p.getByRole('button',{name:'현실 캐릭터',exact:true}).click();await p.getByRole('button',{name:'획득 내역',exact:true}).click();await p.screenshot({path:path.join(evidence,'resonance-desktop.png')});

}).then(()=>console.log('resonance browser passed')).catch(e=>{console.error(e);process.exitCode=1;});
