const {run}=require('./browser-harness.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
run(async p=>{
 await p.evaluate(()=>{const g=__game;g.progress=12;g.training=3;g.fate.stage=1;g.enter('city');g.events=[];Object.assign(g.player,{x:1170,y:850});});
 await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world==='reality');await p.keyboard.press('g');await p.getByRole('button',{name:/귀환 전 · 같은 위협 체험/}).click();await p.getByText('보상과 재방문 안내',{exact:true}).click();assert.match(await p.locator('.dungeon-detail').innerText(),/무보상/);
 await p.getByRole('button',{name:'입장하기',exact:true}).click();await p.waitForFunction(()=>__game.area==='returnProof');assert.equal(await p.evaluate(()=>__game.enemies.length),3);
 await p.evaluate(()=>{const g=__game;for(const e of g.enemies)g.strike(e,99999);Object.assign(g.player,{x:700,y:700});g.hitStop=0;for(let i=0;i<41;i++)g.step(.05);});await p.keyboard.press('g');await p.getByRole('button',{name:'계속하기',exact:true}).click();assert.equal(await p.evaluate(()=>ReturnProof.describe(__game).baselineCompleted),true);
 await p.evaluate(()=>{const g=__game;g.fate.stage=2;g.fate.discovered=['ripple'];g.fate.proven=['ripple'];g.enter('village');g.acceptFate('ripple');g.events=[];g.enter('city');});await p.waitForFunction(()=>document.querySelector('#dialogTitle')?.textContent.includes('현실에서')||document.querySelector('#dialog')?.textContent.includes('현실에서 달라진 대응'));
 await p.getByRole('button',{name:'현실 대응 장착하기',exact:true}).click();assert.match(await p.locator('[data-subject="ripple"]').innerText(),/E · 충격 흡수/);await p.evaluate(()=>Controls.bind('signature1','KeyJ'));await p.locator('.growth-tabs button').filter({hasText:'무공'}).click();assert.match(await p.locator('[data-subject="ripple"]').innerText(),/J · 충격 흡수/);await p.evaluate(()=>Controls.preset('default'));await p.locator('.growth-tabs button').filter({hasText:'무공'}).click();await p.getByRole('button',{name:'현실 대응 장착',exact:true}).click();await p.keyboard.press('Escape');
 await p.evaluate(()=>{Object.assign(__game.player,{x:1170,y:850});});await p.keyboard.press('g');await p.getByRole('button',{name:/귀환 후 · 현실 대응 검증/}).click();await p.getByRole('button',{name:'입장하기',exact:true}).click();await p.waitForFunction(()=>__game.area==='returnProof');
 await p.evaluate(()=>{const g=__game,e=g.enemies[0];Object.assign(g.player,{x:500,y:700,invuln:0,face:0});Object.assign(e,{x:550,y:700,speed:0,cd:99});for(const x of g.enemies)x.cd=99;});await p.keyboard.press('e');await p.evaluate(()=>__game.takeHit(__game.enemies[0]));await p.waitForFunction(()=>ReturnProof.describe(__game).verifiedFamily==='ripple');await p.waitForFunction(()=>document.querySelector('#responseOpportunity').textContent.includes('보관 충격'));
 await p.evaluate(()=>{const g=__game;for(const e of g.enemies)g.strike(e,99999);Object.assign(g.player,{x:700,y:700});g.hitStop=0;for(let i=0;i<41;i++)g.step(.05);});await p.keyboard.press('g');await p.getByRole('button',{name:'계속하기',exact:true}).click();await p.evaluate(()=>{const g=__game,o=g.points().find(x=>x.id==='warden');Object.assign(g.player,{x:o.x,y:o.y});});await p.keyboard.press('g');await p.getByRole('button',{name:'귀환 대응 결과 보고',exact:true}).click();await p.getByRole('button',{name:'검증 결과 보고',exact:true}).click();await p.getByRole('button',{name:'안전 회수로 확보',exact:true}).click();assert.equal(await p.evaluate(()=>ReturnProof.describe(__game).roleChoice),null);
 fs.mkdirSync('/workspace/.project-a-setup/return-proof',{recursive:true});for(const [w,h]of [[360,640],[844,390]]){await p.setViewportSize({width:w,height:h});assert.ok(await p.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));assert.ok(await p.getByRole('button',{name:'이 배치로 확정',exact:true}).isVisible());await p.screenshot({path:'/workspace/.project-a-setup/return-proof/choice-'+w+'.png'});}await p.evaluate(()=>document.documentElement.style.fontSize='200%');assert.ok(await p.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.getByRole('button',{name:'이 배치로 확정',exact:true}).click();assert.equal(await p.evaluate(()=>ReturnProof.describe(__game).roleChoice),'secure-route');
 await p.evaluate(()=>{document.documentElement.style.fontSize='100%';Object.assign(__game.player,{x:1170,y:850});});await p.setViewportSize({width:1280,height:900});await p.keyboard.press('g');await p.getByRole('button',{name:/현장 적용 · 역할 분담/}).click();await p.getByRole('button',{name:'입장하기',exact:true}).click();await p.waitForFunction(()=>__game.proofRuntime?.mode==='application');assert.equal(await p.evaluate(()=>!!ReturnProof.safeZone(__game)),true);
 await p.evaluate(()=>{const g=__game;for(const e of g.enemies)g.strike(e,99999);Object.assign(g.player,{x:700,y:700});g.hitStop=0;for(let i=0;i<41;i++)g.step(.05);});await p.keyboard.press('g');await p.getByRole('button',{name:'계속하기',exact:true}).click();assert.equal(await p.evaluate(()=>ReturnProof.describe(__game).applicationCompleted),true);
 console.log('return proof: entry, recovery, return card, equip, real response, direct report, choice preview/confirm, mobile and 200% passed');
});
