/* Exercise the actual developer checkpoint, not a manually edited game fixture. */
const {chromium}=require('playwright'),{createServer}=require('../server.cjs'),assert=require('node:assert/strict');
(async()=>{const server=createServer({artReview:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.setDefaultTimeout(8000);
await page.addInitScript(()=>{let api;Object.defineProperty(window,'DualWorld',{configurable:true,get:()=>api,set(v){api=v;const old=v.Game.prototype.save;v.Game.prototype.save=function(...args){window.__game=this;return old.apply(this,args);};}});});
await page.goto('http://127.0.0.1:'+server.address().port+'/art-play.html?dev=1');await page.getByRole('button',{name:'2장 보고 후부터',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#continue').hidden);await page.click('#continue');await page.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world==='reality');
assert.deepEqual(await page.evaluate(()=>({progress:__game.progress,stage:__game.fate.stage,inherited:__game.revision.inherited})),{progress:12,stage:1,inherited:[]});
await page.evaluate(()=>Object.assign(__game.player,{x:1170,y:850}));await page.keyboard.press('g');
for(const [width,height]of [[1280,900],[360,640],[844,390]]){await page.setViewportSize({width,height});const row=page.getByRole('button',{name:/귀환 전 · 같은 위협 체험/});assert.equal(await row.evaluate(e=>{const r=e.getBoundingClientRect(),list=e.closest('.dungeon-list');const b=list.getBoundingClientRect();return list.scrollTop===0&&r.top>=b.top-2&&r.bottom<=b.bottom+2;}),true,'baseline must be visible without scrolling at '+width+'x'+height);}
await page.setViewportSize({width:1280,height:900});await page.getByRole('button',{name:/귀환 전 · 같은 위협 체험/}).click();await page.getByRole('button',{name:'입장하기',exact:true}).click();await page.waitForFunction(()=>__game.area==='returnProof');assert.deepEqual(errors,[]);console.log('actual chapter-two checkpoint: proof entry visible without scrolling on desktop/mobile/landscape and enters successfully');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
