const {run}=require('./browser-harness.cjs'),assert=require('node:assert/strict');
run(async p=>{
 await p.evaluate(()=>{const g=__game;g.progress=12;g.training=3;g.fate.stage=2;g.fate.discovered=['ripple'];g.fate.proven=['ripple'];g.enter('village');g.acceptFate('ripple');g.enter('city');g.equipReality('ripple');Object.assign(g.player,{x:1170,y:850});const complete=()=>{for(const e of g.enemies)g.strike(e,99999);Object.assign(g.player,{x:700,y:700});g.proofRuntime.hold=2;ReturnProof.finish(g,'complete');};ReturnProof.begin(g,'baseline');complete();ReturnProof.begin(g,'proof');g.act('signature1');g.takeHit(g.enemies[0]);complete();const w=g.points().find(x=>x.id==='warden');Object.assign(g.player,{x:w.x,y:w.y});g.events=[];});
 await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world==='reality');await p.keyboard.press('g');await p.getByRole('button',{name:'귀환 대응 결과 보고',exact:true}).click();const potions=await p.evaluate(()=>__game.potions);await p.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;window.savedBefore=localStorage.getItem(SaveSlots.keys.current);Storage.prototype.setItem=()=>{throw Error('quota');};});await p.getByRole('button',{name:'검증 결과 보고',exact:true}).click();await p.waitForFunction(()=>!ReturnProof.describe(__game).reported);assert.equal(await p.evaluate(()=>__game.potions),potions);assert.equal(await p.evaluate(()=>localStorage.getItem(SaveSlots.keys.current)===savedBefore),true);assert.match(await p.locator('#toasts').innerText(),/변경을 취소/);await p.evaluate(()=>Storage.prototype.setItem=originalSetItem);
 await p.keyboard.press('g');await p.getByRole('button',{name:'귀환 대응 결과 보고',exact:true}).click();await p.getByRole('button',{name:'검증 결과 보고',exact:true}).click();assert.equal(await p.evaluate(()=>__game.potions),potions+2);await p.keyboard.press('Escape');
 // The production entry UI in a real DOM, with a controllable asset promise.
 for(const scenario of ['close','replace','duplicate','failure']){
  await p.evaluate(scenario=>{const source=__game.save();let current=WorldGame.Game.load(source);Object.assign(current.player,{x:1170,y:850});window.entryOriginal=current;const host=document.createElement('dialog');host.id='safetyEntry';document.body.append(host);const node=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};window.safetyUI=DungeonUI.create({game:()=>current,node,show:(title,body,actions)=>{host.replaceChildren(body);for(const a of actions){const b=node('button','',a.label);b.disabled=!!a.disabled;b.onclick=a.run;host.append(b);}if(!host.open)host.showModal();},close:()=>host.close(),isOpen:()=>host.open,refresh(){},prepare:()=>new Promise(r=>window.finishPreparation=r)});window.replaceEntryGame=()=>{current=WorldGame.Game.load(source);};safetyUI.open();},scenario);
  await p.locator('#safetyEntry').getByRole('button',{name:/귀환 전 · 같은 위협 체험/}).click();await p.locator('#safetyEntry').getByRole('button',{name:'입장하기',exact:true}).click();if(scenario==='close')await p.locator('#safetyEntry').getByRole('button',{name:'닫기',exact:true}).click();if(scenario==='replace')await p.evaluate(()=>replaceEntryGame());if(scenario==='duplicate')assert.equal(await p.locator('#safetyEntry').getByRole('button',{name:'입장 준비 중…',exact:true}).isDisabled(),true);await p.evaluate(ok=>finishPreparation(ok),scenario!=='failure');await p.waitForTimeout(60);assert.equal(await p.evaluate(()=>entryOriginal.area),scenario==='duplicate'?'returnProof':'city');await p.evaluate(()=>{safetyUI.cancel();document.querySelector('#safetyEntry').remove();});
 }
 console.log('return proof: real DOM async cancel/replacement/duplicate/failure and atomic report storage failure passed');
});
