const test=require('node:test'),assert=require('node:assert/strict'),{Game,state,summary}=require('../revision.js');
test('skip and direct rescue converge without skills or bonus rewards',()=>{
 const a=new Game();a.beginIntro(true);a.finishIntro();const b=new Game();b.beginIntro(true);b.advanceIntro();b.advanceIntro();b.advanceIntro();assert.equal(b.area,'village');assert.equal(b.act('attack'),false);
 Object.assign(b.player,{x:400,y:740});b.interact();Object.assign(b.player,{x:480,y:680});b.interact();assert.equal(state(b).intro,4);while(state(b).intro<7)b.advanceIntro();
 for(const g of [a,b]){assert.equal(g.progress,1);assert.equal(g.training,0);assert.equal(g.gold,40);assert.equal(g.potions,3);assert.equal(state(g).history.length,2);assert.deepEqual(state(g).history.map(h=>h.area),['village','city']);assert.equal(Game.load(g.save()).progress,1);}
});
test('intro resumes direct rescue, old saves retain progress without invented memories',()=>{const g=new Game();g.beginIntro(true);g.advanceIntro();g.advanceIntro();g.advanceIntro();Object.assign(g.player,{x:400,y:740});g.interact();const resumed=Game.load(g.save());assert.equal(resumed.area,'village');assert.equal(resumed.revision.aid,1);const old=JSON.parse(new Game().save());old.version=6;delete old.revision;const migrated=Game.load(JSON.stringify(old));assert.equal(migrated.revision.origin,'legacy');assert.deepEqual(migrated.revision.history,[]);});
test('inheritance is only announced once per family and remembered on reload',()=>{const g=new Game();g.progress=12;g.training=3;g.fate.stage=2;g.fate.proven=['echo','ripple'];g.fate.discovered=['echo','ripple'];g.enter('village');g.acceptFate('echo');assert.equal(g.events.filter(e=>e.inheritance).length,1);g.events=[];g.acceptFate('ripple');g.acceptFate('echo');assert.equal(g.events.filter(e=>e.inheritance).length,1);assert.deepEqual(Game.load(g.save()).revision.inherited,['echo','ripple']);});
test('growth components add to actual combat totals',()=>{const g=new Game();g.level=8;g.training=3;g.upgrade=2;g.journey.realm=1;const s=summary(g);for(const k of ['attack','hp','mp'])assert.equal(Object.values(s[k]).reduce((a,b)=>a+b),g.stats()[k]);});
