'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {Game}=require('../chapter-five.js');const {g0,experiment}=require('./helpers/journey.cjs');
test('save seed changes clue locations, not access to any path',()=>{const g=g0();g.enter('archive');g.journey.seed=1;const a=g.points().filter(p=>p.kind==='discovery');g.journey.seed=2;const b=g.points().filter(p=>p.kind==='discovery');assert.notEqual(a[0].x,b[0].x);assert.deepEqual(a.map(x=>x.id),b.map(x=>x.id));});
test('residual training targets cannot mint mastery or physical materials',()=>{const g=g0();g.enter('station');const e=g.enemies[0];e.residual=true;e.hp=e.maxHp=900;g.strike(e,20,'attack');assert.equal(g.journey.mastery.sword,0);g.strike(e,900);assert.equal(g.journey.materials,0);});
test('a hidden proof fact without a learned interpretation is inconsistent',()=>{const g=new Game(),d=JSON.parse(g.save());d.journey.facts.push({id:'proof-echo-replay',area:'archive',at:0});assert.throws(()=>Game.load(JSON.stringify(d)));});
test('a purported realization must have occurred in the documented location',()=>{const g=new Game(),d=JSON.parse(g.save());d.journey.facts.push({id:'sense-ripple',area:'city',at:0});assert.throws(()=>Game.load(JSON.stringify(d)));});
test('early artifacts neither fabricate the old Legend biography nor erase its memory',()=>{const g=g0('ripple');experiment(g,'ripple','guard');assert.equal(g.legend.memories.length,0);assert.equal(g.legend.awakened.length,0);assert.equal(g.journey.known[0],'ripple-guard');});
test('all relics and paired mechanisms remain walkable for each of the three seed layouts',()=>{const g=g0();g.enter('archive');for(const seed of [1,2,3]){g.journey.seed=seed;for(const o of g.points())assert.equal(g.blocked(o.x,o.y,16),false,o.id);}});
test('interpreted button names describe the slot that actually changed',()=>{const g=g0('ripple');experiment(g,'ripple','guard');g.chooseInterpretation('ripple-guard');assert.equal(g.skillInfo('signature1').name,'잔파 · 수호진');assert.equal(g.skillInfo('signature2').name,'역류참');});
