const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {run}=require('./browser-harness.cjs');
run(async p=>{
 assert.ok(fs.existsSync(path.join(__dirname,'../skills-screen.js')),'dedicated skills workspace exists');
 await p.addScriptTag({path:path.join(__dirname,'../skills-screen.js')});
 await p.addStyleTag({path:path.join(__dirname,'../skills-screen.css')});
 await p.evaluate(()=>{
  const g=__game;g.training=3;g.progress=12;g.fate.stage=2;g.fate.discovered=['ripple','seal'];g.fate.proven=['ripple','seal'];g.enter('village');g.acceptFate('ripple');g.acceptFate('seal');g.acceptFate('ripple');g.enter('city');g.events=[];g.save();
  document.querySelector('#dialog')?.close();g.paused=true;g.step=()=>{};
  const host=document.createElement('div');host.id='skills-test-host';document.body.append(host);
  host.style.cssText='position:fixed;inset:0;overflow:auto;background:#14202c;z-index:9999;color:white';
  window.__skillCloses=0;window.__skillEvents=[];window.__skills=SkillsScreen.create({game:()=>__game,node:(tag,cls='',text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;},show:(_,body)=>host.replaceChildren(body),refresh:()=>{},close:()=>{window.__skillCloses++;},notes:{open:()=>{}},commit:fn=>{
   if(window.__failSkillsSave)return false;
   const result=fn(__game)!==false;
   // The component harness owns its modal and event delivery; prevent the live app
   // from consuming its story events and opening a second, unrelated modal.
   window.__skillEvents.push(...__game.events.splice(0));return result;
  }});__skills.open('reality','ripple');
 });
 assert.equal(await p.getByRole('button',{name:'일반 스킬',exact:true}).count(),1,'active skills are distinct from passive principles');
 await p.getByRole('button',{name:'심법 (패시브)',exact:true}).click();
 assert.equal(await p.locator('[data-passive]').count(),6);
 assert.equal(await p.locator('[data-basic]').count(),0);
 assert.equal(await p.locator('[data-prerequisite="F0"][data-dependent="F1"]').count(),1,'tree displays the real prerequisite');
 await p.locator('[data-passive="F3"]').click();assert.equal(await p.locator('[data-upgrade="F3"]').isDisabled(),true,'locked descendants cannot be purchased');
 assert.doesNotMatch(await p.locator('.skills-screen').innerText(),/발견한 해석|해석 장착|관찰 기록|흔적을 관찰/);
 await p.evaluate(()=>__skills.open('reality','mode'));
 assert.equal(await p.getByRole('button',{name:'심법 (패시브)',exact:true}).getAttribute('aria-pressed'),'true','mode receipt routes to passive growth');
 await p.evaluate(()=>__skills.open('reality','ripple'));
 const before=await p.evaluate(()=>__game.worldGrowth.reality.equipped);
 const liveView=await p.evaluate(()=>JSON.stringify({area:__game.area,fate:__game.fate,worldGrowth:__game.worldGrowth,dual:__game.dualRuntime,reality:__game.realityRuntime,player:__game.player}));
 await p.getByRole('button',{name:'무림 보기',exact:true}).click();await p.getByRole('button',{name:'봉인',exact:true}).click();await p.locator('[data-skill="signature1"]').click();
 assert.equal(await p.evaluate(()=>JSON.stringify({area:__game.area,fate:__game.fate,worldGrowth:__game.worldGrowth,dual:__game.dualRuntime,reality:__game.realityRuntime,player:__game.player})),liveView,'off-world skill calculations do not mutate live state or runtime');
 await p.evaluate(()=>{const s=BoundaryResonance.state(__game);s.grants=s.grants.filter(x=>x!=='practice:training').concat('practice:training');__skills.open('reality','ripple');});
 assert.match(await p.locator('.skills-wallet').innerText(),/최근 획득 \+2 · 백련의 기본기/,'latest receipt follows grant order, not catalog order');
 await p.evaluate(()=>{__game.refreshNews();for(const n of __game.worldState.news.items)n.read=false;__skills.open('reality','ripple');});
 assert.equal(await p.evaluate(()=>__game.unreadNews('skills').some(n=>n.id==='inherit:ripple')),false,'viewed family receipt is persisted as read');
 assert.equal(await p.evaluate(()=>__game.unreadNews('skills').some(n=>n.id==='inherit:seal')),true,'other family receipt stays unread');
 await p.getByRole('button',{name:'봉인',exact:true}).click();assert.equal(await p.evaluate(()=>__game.worldGrowth.reality.equipped),before,'view never equips');
 await p.getByRole('button',{name:'파문',exact:true}).click();
 await p.locator('[data-branch="ripple-economy"]').click();
 assert.equal(await p.locator('.skills-detail [data-upgrade]').count(),1,'selecting a branch focuses its own level-up');
 assert.equal(await p.locator('.skills-detail [data-upgrade="ripple-economy"]').count(),1);
 await p.locator('[data-skill="signature1"]').click();
 assert.match(await p.locator('.skills-detail').innerText(),/이전 개별 기록 없음/);
 await p.locator('[data-upgrade="ripple-window"]').click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.effects(__game,'ripple').guardWindow),.9);
 await p.locator('[data-upgrade="ripple-economy"]').click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.effects(__game,'ripple').guardWindow),.7);
 assert.equal(await p.evaluate(()=>BoundaryResonance.effects(__game,'ripple').discountQ),2);
 assert.match(await p.locator('[data-skill="signature1"]').innerText(),/Lv\.2/);
 assert.doesNotMatch(await p.locator('[data-skill="signature1"]').innerText(),/Lv\.3/);
 await p.locator('[data-select="ripple-window"]').click();
 assert.equal(await p.evaluate(()=>BoundaryResonance.effects(__game,'ripple').discountQ),0);
 await p.locator('[data-skill="signature2"]').click();assert.match(await p.locator('.skills-detail').innerText(),/4장 구조 완료 후 백련/);
 assert.equal(await p.locator('[data-upgrade="ripple-follow"]').isDisabled(),true);
 await p.locator('[data-skill="ultimate"]').click();assert.match(await p.locator('.skills-detail').innerText(),/7장 위기 실전/);assert.equal(await p.locator('.skills-detail [data-upgrade]').count(),0);
 await p.evaluate(()=>{__game.worldState.growthArc.learnedR=true;__game.worldState.growthArc.learnedF=true;__game.chapter4.phase=4;BoundaryResonance.sync(__game);__game.worldGrowth.reality.skillMastery={ripple:{signature1:4,signature2:2}};__skills.open('reality','ripple');});
 await p.locator('[data-skill="signature1"]').click();assert.match(await p.locator('.skills-mastery').innerText(),/4\/30/);
 await p.locator('[data-skill="signature2"]').click();assert.match(await p.locator('.skills-mastery').innerText(),/2\/30/);await p.locator('[data-upgrade="ripple-follow"]').click();assert.equal(await p.evaluate(()=>BoundaryResonance.effects(__game,'ripple').discountR),2);
 await p.locator('[data-skill="ultimate"]').click();assert.match(await p.locator('.skills-detail').innerText(),/Lv\.1/);assert.equal(await p.locator('.skills-detail [data-upgrade]').count(),0);
 await p.getByRole('button',{name:'공통 기본기',exact:true}).click();
 assert.equal(await p.locator('[data-passive]').count(),0);
 assert.equal(await p.locator('[data-basic]').count(),3,'common active techniques remain discoverable');
 await p.getByRole('button',{name:'심법 (패시브)',exact:true}).click();
 await p.getByRole('button',{name:'집중심법',exact:true}).click();
 assert.equal(await p.locator('[data-passive]').count(),6);
 await p.locator('[data-passive="C1"]').click();
 await p.evaluate(()=>window.__failSkillsSave=true);const balance=await p.evaluate(()=>BoundaryResonance.balance(__game).seal);
 await p.locator('[data-upgrade="C1"]').click();assert.equal(await p.evaluate(()=>BoundaryResonance.balance(__game).seal),balance);assert.match(await p.locator('.skills-screen [role="status"]').innerText(),/저장하지 못/);
 await p.evaluate(()=>window.__failSkillsSave=false);await p.locator('[data-upgrade="C1"]').focus();await p.keyboard.press('Enter');
 assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).common.C1),1);assert.equal(await p.evaluate(()=>document.activeElement.dataset.upgrade),'C1');
 await p.getByRole('button',{name:'스킬 초기화',exact:true}).click();assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).common.C1),1);
 await p.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).common.C1),1);
 await p.getByRole('button',{name:'스킬 초기화',exact:true}).click();await p.getByRole('button',{name:'초기화 확정',exact:true}).click();assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).common.C1),0);assert.equal(await p.evaluate(()=>BoundaryResonance.state(__game).learned.length),0);assert.equal(await p.evaluate(()=>WorldGrowth.skillMastery(__game,'reality','ripple','signature1').value),4);
 await p.getByRole('button',{name:'무림 보기',exact:true}).click();assert.match(await p.locator('.skills-screen').innerText(),/청운촌/);await p.getByRole('button',{name:'심법 (패시브)',exact:true}).click();await p.locator('[data-passive="F1"]').click();assert.equal(await p.locator('[data-upgrade="F1"]').isDisabled(),true);
 await p.evaluate(()=>{__game.enter('village');__game.events=[];__skills.open('murim','F1');});
 await p.evaluate(()=>{__game.fate.discovered.push('echo');__game.fate.proven.push('echo');__skills.open('murim','discovery');});await p.locator('[data-discovery="echo"]').click();await p.getByRole('button',{name:'계승 수락',exact:true}).click();
 assert.ok(await p.evaluate(()=>__game.revision.inherited.includes('echo')));assert.equal(await p.evaluate(()=>window.__skillCloses),1,'acceptance yields workspace to its story event');
 assert.equal(await p.evaluate(()=>__skillEvents.some(e=>e.type==='awakening'&&e.path==='echo')),true,'acceptance still emits its real story event');
 await p.evaluate(()=>__skills.open('murim','F1'));
 await p.locator('[data-upgrade="F1"]').click();assert.equal(await p.evaluate(()=>PassiveGrowth.state(__game).levels.F1),1);
 await p.evaluate(()=>{__game.enter('city');__game.events=[];__game.journey.known.push('seal-hold');__game.journey.sync['seal-hold']=1;__game.refreshNews();__skills.open('reality','seal-hold');});
 assert.equal(await p.evaluate(()=>__game.worldGrowth.reality.interpretations.seal),null,'opening interpretation does not equip it');
 assert.equal(await p.evaluate(()=>__game.unreadNews('skills').some(n=>n.id==='interpret:seal-hold')),false);
 assert.equal(await p.evaluate(()=>__game.unreadNews('skills').some(n=>n.id.startsWith('resonance:seal:'))),true,'viewing seal family leaves currency receipts unread');
 await p.getByRole('button',{name:'이 계열 장착',exact:true}).click();
 assert.equal(await p.getByRole('button',{name:'이 해석 장착',exact:true}).count(),0,'interpretations cannot be managed from skills');
 await p.evaluate(()=>{__game.worldGrowth.reality.interpretations.seal='seal-hold';__skills.open('reality','seal');});
 await p.locator('[data-skill="signature1"]').click();assert.match(await p.locator('.skills-detail').innerText(),/실제 6초 유지 · 추가 시간 효과 없음/);
 await p.getByRole('button',{name:'획득 내역',exact:true}).click();assert.equal(await p.evaluate(()=>__game.unreadNews('skills').some(n=>n.id.startsWith('resonance:seal:'))),false);
 await p.evaluate(()=>{__game.enter('village');__game.events=[];__skills.open('murim','F1');});
 await p.setViewportSize({width:360,height:800});await p.evaluate(()=>document.documentElement.style.fontSize='200%');
 await p.getByRole('button',{name:'기술 목록',exact:true}).click();assert.equal(await p.locator('.skills-detail').isVisible(),true);
 await p.locator('[data-passive="F2"]').click();assert.equal(await p.locator('.skills-list').isVisible(),true,'mobile retains the tree alongside the selected upgrade');
 assert.ok(await p.evaluate(()=>document.querySelector('.skills-screen').scrollWidth<=innerWidth),'mobile workspace has no horizontal overflow');
 await p.evaluate(()=>{const host=document.querySelector('#skills-test-host'),body=document.querySelector('#dialogBody'),dialog=document.querySelector('#dialog');body.replaceChildren(host);host.style.cssText='background:#14202c;color:white';body.style.cssText='height:500px;overflow:auto';dialog.style.width='360px';dialog.showModal();});
 await p.getByRole('button',{name:'기술 목록',exact:true}).click();
 await p.getByRole('button',{name:'집중심법',exact:true}).click();await p.locator('[data-passive="C4"]').scrollIntoViewIfNeeded();
 const listPosition=await p.evaluate(()=>document.querySelector('#dialogBody').scrollTop);assert.ok(listPosition>500);
 await p.locator('[data-passive="C4"]').click();await p.getByRole('button',{name:'기술 목록',exact:true}).click();
 assert.ok(await p.locator('[data-passive="C4"]').isVisible(),'mobile back keeps the tree available');
 assert.equal(await p.evaluate(()=>document.activeElement.dataset.passive),'C4');
 await p.evaluate(()=>{__game.enter('village');__game.acceptFate('seal');__game.enter('archive');__game.area='archive';__game.enemies=[];__game.events=[];__skills.open('murim','seal-hold');});
 assert.equal(await p.getByRole('button',{name:'이 해석 장착',exact:true}).count(),0,'archive does not restore removed interpretation controls');
 assert.equal(await p.getByRole('button',{name:'기본 운용으로 복귀',exact:true}).count(),0);
 assert.doesNotMatch(await p.locator('.skills-screen').innerText(),/발견한 해석|해석 장착|관찰 기록|흔적을 관찰/);
 await p.evaluate(()=>__game.enemies=[]);
 await p.evaluate(()=>__skills.open('murim','F1'));assert.equal(await p.locator('[data-upgrade="F1"]').isDisabled(),true,'archive never permits paid passive upgrades');
}).then(()=>console.log('skills workspace browser passed')).catch(e=>{console.error(e);process.exitCode=1;});
