const {run}=require('./browser-harness.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
run(async p=>{
 await p.evaluate(()=>{const g=__game;g.progress=12;g.training=3;g.fate.stage=2;g.fate.discovered=['echo'];g.fate.proven=['echo'];g.enter('village');g.acceptFate('echo');g.events=[];g.refreshNews();});
 await p.locator('.main-navigation').getByRole('button',{name:'캐릭터',exact:true}).click();await p.locator('.character-tabs').getByRole('button',{name:'성장',exact:true}).click();const skills=p.locator('.growth-tabs button').filter({hasText:'무공'});
 assert.equal(await skills.locator('.news-dot').count(),1);assert.match(await skills.getAttribute('aria-label'),/새 소식/);
 const rgb=await skills.locator('.news-dot').evaluate(e=>getComputedStyle(e).backgroundColor);const channels=rgb.match(/\d+/g).map(Number);assert.ok(channels[0]>channels[1]*1.5&&channels[0]>channels[2]*1.5);
 assert.equal(await p.locator('.growth-tabs button[aria-pressed="true"]').innerText(),'성장');
 assert.ok(await p.locator('.growth-tabs').evaluate(e=>e.getBoundingClientRect().top>=document.querySelector('#dialogBody').getBoundingClientRect().top));
 assert.equal(await p.locator('.growth-tabs button').filter({hasText:'성장'}).locator('.news-dot').count(),0);
 await skills.click();await p.locator('[data-node="family:echo"]').click();assert.equal(await p.locator('.growth-tabs button').filter({hasText:'무공'}).locator('.news-dot').count(),0);
 for(const [width,height]of [[1280,900],[360,640],[844,390]]){await p.setViewportSize({width,height});await p.keyboard.press('Escape');await p.locator('.main-navigation').getByRole('button',{name:'캐릭터',exact:true}).click();await p.locator('.character-tabs').getByRole('button',{name:'성장',exact:true}).click();assert.ok(await p.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));assert.ok(await p.locator('.growth-tabs button').first().evaluate(e=>e.getBoundingClientRect().height>=44));assert.ok(await p.locator('.growth-tabs').evaluate(e=>e.getBoundingClientRect().top>=document.querySelector('#dialogBody').getBoundingClientRect().top));fs.mkdirSync('.codex_doc_review/ui-polish',{recursive:true});await p.screenshot({path:'.codex_doc_review/ui-polish/growth-'+width+'.png'});}
 await p.keyboard.press('Escape');await p.locator('.main-navigation').getByRole('button',{name:'기록',exact:true}).click();await p.locator('#dialogBody').getByRole('button',{name:'내 소식',exact:true}).click();const unread=p.locator('.news-item.has-news');if(await unread.count()){await unread.first().click();await p.getByRole('button',{name:'목록으로',exact:true}).click();}
 await p.keyboard.press('Escape');await p.evaluate(()=>{const g=__game,o=g.points().find(o=>o.id==='master');Object.assign(g.player,{x:o.x,y:o.y});});await p.keyboard.press('KeyG');assert.equal(await p.getByRole('button',{name:'잔영보 수락',exact:true}).count(),0);assert.match(await p.locator('#dialog').innerText(),/백련/);
 console.log('red badges, immediate reads, selected tabs, readable touch targets and mentor dialogue passed');
});
