const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const {createServer}=require('../server.cjs');
(async()=>{const server=createServer({artReview:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:process.env.CHROMIUM_PATH?undefined:'chrome',executablePath:process.env.CHROMIUM_PATH});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));p.setDefaultTimeout(8000);
 await p.addInitScript(()=>{let api;Object.defineProperty(window,'DualWorld',{configurable:true,get(){return api;},set(v){api=v;for(const method of ['save','enter','step']){const old=v.Game.prototype[method];v.Game.prototype[method]=function(...a){const result=old.apply(this,a);window.__game=this;return result;};}}});});
 await p.goto('http://127.0.0.1:'+server.address().port+'/art-play.html');await p.waitForFunction(()=>ArtPreview.ready);await p.click('#start');await p.getByRole('button',{name:'인트로 건너뛰기',exact:true}).click();await p.keyboard.press('KeyI');await p.getByRole('button',{name:'무공',exact:true}).click();
 await p.locator('.tree-node[data-node="family:ripple"]').click({timeout:2000});assert.match(await p.locator('.tree-detail').innerText(),/미확인/);assert.doesNotMatch(await p.locator('.tree-detail').innerText(),/파문검|두 번|2회/);
 await p.evaluate(()=>__game.journey.known=['ripple-guard']);await p.getByRole('button',{name:'무공',exact:true}).click();await p.locator('[data-node="variant:ripple-guard"]').click();assert.doesNotMatch(await p.locator('.tree-detail').innerText(),/파문세|기본: 0.7/);await p.locator('[data-node="family:ripple"]').click();
 fs.mkdirSync('.codex_doc_review/v010',{recursive:true});await p.screenshot({path:'.codex_doc_review/v010/tree-unknown.png'});await p.getByRole('button',{name:'돌아가기',exact:true}).click();
 await p.evaluate(()=>{const g=__game;g.progress=6;g.training=2;g.journey.mastery.sword=10;g.fate.stage=2;g.fate.proven=['ripple'];g.fate.discovered=['ripple'];g.enter('village');g.events=[];});await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world==='murim');await p.keyboard.press('KeyI');await p.getByRole('button',{name:'무공',exact:true}).click();await p.locator('[data-node="family:ripple"]').focus();await p.keyboard.press('Enter');assert.doesNotMatch(await p.locator('.tree-detail').innerText(),/파문검/);await p.getByRole('button',{name:'계승 수락',exact:true}).click();await p.getByRole('button',{name:'계속하기',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('#inheritanceNotice').hidden);await p.waitForTimeout(550);assert.match(await p.locator('#inheritanceNotice').innerText(),/이 여정의 첫 계승.*싱글플레이/s);await p.screenshot({path:'.codex_doc_review/v010/inheritance.png'}); 
 await p.evaluate(()=>{__game.journey.known=['ripple-guard'];__game.enter('archive');__game.events=[];});await p.keyboard.press('KeyI');await p.getByRole('button',{name:'무공',exact:true}).click();await p.locator('[data-node="variant:ripple-guard"]').click();await p.getByRole('button',{name:'이 해석 장착',exact:true}).click();assert.match(await p.locator('.tree-detail').innerText(),/장착 중/);assert.equal(await p.evaluate(()=>__game.journey.selected.ripple),'ripple-guard');assert.equal(await p.evaluate(()=>Presentation.guide(__game,'ripple').stage),'equipped');await p.screenshot({path:'.codex_doc_review/v010/tree-known.png'});
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:'.codex_doc_review/v010/tree-mobile.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.getByRole('button',{name:'돌아가기',exact:true}).click();
 assert.equal(await p.locator('#rumorPanel').isVisible(),false);await p.keyboard.press('Tab');assert.equal(await p.getByRole('button',{name:'다른 여정',exact:true}).count(),0);await p.getByRole('button',{name:'돌아가기',exact:true}).click();await p.setViewportSize({width:1440,height:1000});
 await p.evaluate(()=>{__game.enter('city');__game.events=[];});await p.waitForFunction(()=>ArtPreview.ready&&ArtPreview.world==='reality');await p.click('#contractButton');await p.getByRole('button',{name:'의뢰 수주',exact:true}).click();await p.waitForFunction(()=>__game.contract.status==='active');assert.match(await p.locator('#quest').innerText(),/현장 의뢰/);await p.evaluate(()=>{for(const e of __game.enemies)__game.strike(e,9999,'attack');});await p.getByText('잔당 토벌 완료',{exact:true}).waitFor();await p.getByRole('button',{name:'기지로 귀환',exact:true}).click();await p.click('#contractButton');const gold=await p.evaluate(()=>{__game.xp=__game.stats().next-1;return __game.gold;});await p.getByRole('button',{name:'보상 수령',exact:true}).click();assert.equal(await p.evaluate(()=>__game.gold),gold+80);assert.match(await p.locator('#levelNotice').textContent(),/최대 체력 \+18.*공격력 \+3/);assert.equal(await p.getByRole('button',{name:'보상 수령',exact:true}).count(),0);await p.screenshot({path:'.codex_doc_review/v010/contracts.png'});
 await p.getByRole('button',{name:'돌아가기',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('#levelNotice').hidden);assert.equal(await p.locator('#artPreviewBadge').count(),0);await p.waitForTimeout(450);await p.screenshot({path:'.codex_doc_review/v010/level-up.png'});const x=await p.evaluate(()=>__game.player.x);await p.keyboard.down('ArrowRight');await p.waitForFunction(x=>__game.player.x>x+20,x);await p.keyboard.up('ArrowRight');await p.setViewportSize({width:390,height:844});await p.screenshot({path:'.codex_doc_review/v010/level-mobile.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.waitForFunction(()=>document.querySelector('#levelNotice').hidden,{timeout:5000});
 assert.deepEqual(errors,[]);console.log('v0.10 browser passed: hidden/equipped tree, first inheritance, removed clutter, responsive layout and contract claim');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
