const test=require('node:test'),assert=require('node:assert/strict'),{inherited}=require('./world-fixtures.cjs');
test('dungeon save resumes position, damaged enemies and health without rewards',()=>{
 const g=inherited();g.enter('rift');const e=g.enemies[0];e.hp=0;e.rewarded=true;g.enemies[1].hp=12;g.player.hp=45;g.player.mp=20;const before={x:g.player.x,y:g.player.y,gold:g.gold,xp:g.xp};
 const loaded=g.constructor.load(g.save());assert.equal(loaded.area,'rift');assert.equal(loaded.enemies[0].hp,0);assert.equal(loaded.enemies[0].rewarded,true);assert.equal(loaded.enemies[1].hp,12);assert.equal(loaded.player.hp,45);assert.equal(loaded.player.mp,20);assert.equal(loaded.gold,before.gold);assert.equal(loaded.xp,before.xp);assert.equal(loaded.player.x,before.x);
});
test('invalid encounter data is rejected and invalid coordinates alone fall back safely',()=>{
 const g=inherited();g.enter('rift');const raw=g.save(),d=JSON.parse(raw);assert.ok(d.encounter);d.encounter.enemies[0].hp=1e9;assert.throws(()=>g.constructor.load(JSON.stringify(d)));assert.equal(g.area,'rift');
 const location=JSON.parse(raw);location.encounter.player.x=-200;const restored=g.constructor.load(JSON.stringify(location));assert.equal(restored.area,'city');assert.match(restored.restoreNotice,/위치/);
});
test('old v10 dungeon save keeps area and progression without inventing combat details',()=>{
 const g=inherited();g.enter('rift');const d=JSON.parse(g.save());delete d.encounter;delete d.improvementVersion;const loaded=g.constructor.load(JSON.stringify(d));assert.equal(loaded.area,'rift');assert.equal(loaded.progress,g.progress);
});
const {five,six,clear,response}=require('./helpers/world-journey.cjs'),{talk}=require('./world-fixtures.cjs');
function residualReady(){const g=five('seal');talk(g,'warden');g.enter('stabilization');for(let i=0;i<15;i++){g.hitStop=0;g.step(.05);}talk(g,'six-record');g.enter('village');talk(g,'master');g.enter('stabilization');clear(g);return g;}
test('residual exercise saves cleared roster and resumes only exercise, then finishes with no payouts',()=>{let g=residualReady();const corpses=g.enemies.map(e=>e.id);talk(g,'six-record');const before={gold:g.gold,xp:g.xp,mastery:JSON.stringify(g.worldGrowth)};assert.deepEqual(g.enemies.filter(e=>!e.residual).map(e=>e.id),corpses);g=g.constructor.load(g.save());assert.equal(g.area,'stabilization');assert.equal(g.laterStory.deepening.stage,'trial');assert.equal(g.enemies.filter(e=>!e.residual&&e.hp>0).length,0);assert.equal(g.enemies.filter(e=>e.deepeningExercise&&e.hp>0).length,1);response(g,'seal');g.hitStop=0;g.step(.05);assert.equal(g.laterStory.six,4);assert.equal(g.gold,before.gold);assert.equal(g.xp,before.xp);assert.equal(JSON.stringify(g.worldGrowth),before.mastery);g=g.constructor.load(g.save());assert.equal(g.laterStory.six,4);assert.equal(g.enemies.filter(e=>e.hp>0).length,0);});
test('comparison snapshot restores two unrewarded practice opponents and player resources',()=>{const g=inherited();g.beginComparison();g.enemies[0].hp=0;g.enemies[0].rewarded=true;g.enemies[1].hp=42;g.player.hp=43;const h=g.constructor.load(g.save());assert.equal(h.area,'comparison');assert.equal(h.enemies.length,2);assert.equal(h.enemies[0].hp,0);assert.equal(h.enemies[1].hp,42);assert.equal(h.player.hp,43);assert.ok(h.enemies.every(e=>e.comparison));});
test('save after successful trial keeps proof and safely restores sanctum, not trial corpse roster',()=>{const g=inherited();g.enter('sanctum');talk(g,'relic-seal');assert.equal(g.beginTrial('seal'),true);g.trial.feat=true;g.strike(g.enemies[0],999999);assert.equal(g.trial,null);const before=g.gold,h=g.constructor.load(g.save());assert.equal(h.area,'sanctum');assert.ok(h.fate.proven.includes('seal'));assert.equal(h.gold,before);assert.ok(h.enemies.every(e=>!e.trial));});
test('late link suppression survives a save and malformed exercise flags cannot grant progress',()=>{const g=six(five('seal'),'seal');g.enter('stabilization');g.laterRuntime.linked=true;g.laterRuntime.suppress=g.playTime+4;const raw=g.save(),h=g.constructor.load(raw);assert.equal(h.laterRuntime.linked,true);assert.ok(Math.abs(h.laterRuntime.suppress-h.playTime-4)<1e-9);const d=JSON.parse(raw);d.encounter.exercise=true;assert.throws(()=>g.constructor.load(JSON.stringify(d)));});
test('older acquired dungeon without process provenance keeps location and gains legacy provenance only',()=>{const g=six(five('seal'),'seal');g.enter('stabilization');const d=JSON.parse(g.save());delete d.encounter;delete d.improvementVersion;delete d.laterStory.deepening;const h=g.constructor.load(JSON.stringify(d));assert.equal(h.area,'stabilization');assert.equal(h.laterStory.dualBreath,true);assert.deepEqual(h.laterStory.deepening,{stage:'legacy',observed:false,clue:false,interpreted:false,legacy:true});});
test('a corpse before its reward callback does not make a valid roster unloadable or replay payment',()=>{const g=inherited();g.enter('rift');g.enemies[0].hp=0;g.enemies[0].rewarded=false;const before=g.gold,h=g.constructor.load(g.save());assert.equal(h.enemies[0].hp,0);assert.equal(h.gold,before);h.hitStop=0;h.step(.05);assert.equal(h.gold,before);});
test('activated seals and a damaged unlocked boss survive dungeon reload',()=>{const g=inherited();g.enter('ruins');for(const e of g.enemies.filter(e=>!e.boss))g.strike(e,999999);for(const p of g.seals())talk(g,p.id);const boss=g.enemies.find(e=>e.boss);g.strike(boss,20);assert.equal(g.bossLocked(),false);const raw=g.save(),h=g.constructor.load(raw);assert.deepEqual(h.activated,g.activated);assert.equal(h.bossLocked(),false);assert.equal(h.enemies.find(e=>e.boss).hp,boss.hp);const d=JSON.parse(raw);d.encounter.activated=['forged-seal'];assert.throws(()=>g.constructor.load(JSON.stringify(d)));});
test('a snapshot taken at defeat recovers safely without repeated death charges or lost story',()=>{const g=inherited();g.enter('rift');g.player.hp=0;const before={gold:g.gold,progress:g.progress},h=g.constructor.load(g.save());assert.equal(h.area,'city');assert.ok(h.player.hp>0);assert.equal(h.gold,before.gold);assert.equal(h.progress,before.progress);assert.match(h.restoreNotice,/쓰러/);h.step(.05);assert.equal(h.gold,before.gold);});
test('older partial snapshot infers only seals proved by a damaged unlocked boss',()=>{const g=inherited();g.enter('ruins');for(const e of g.enemies.filter(e=>!e.boss))g.strike(e,999999);for(const p of g.seals())talk(g,p.id);g.strike(g.enemies.find(e=>e.boss),20);const d=JSON.parse(g.save());delete d.encounter.activated;delete d.encounter.exercise;delete d.encounter.suppressRemaining;const h=g.constructor.load(JSON.stringify(d));assert.equal(h.bossLocked(),false);assert.deepEqual(h.activated,g.activated);const forged=JSON.parse(g.save());forged.encounter.activated=[];assert.throws(()=>g.constructor.load(JSON.stringify(forged)));});
test('old chapter seven dungeon without deepening or preparation retains its valid location',()=>{const g=six(five('seal'),'seal');talk(g,'warden');g.chooseSevenPreparation('evacuation');g.enter('woundPass');const d=JSON.parse(g.save());delete d.encounter;delete d.improvementVersion;delete d.laterStory.deepening;delete d.laterStory.preparation;d.revision.history=d.revision.history.filter(r=>r.id!=='seven-preparation');const h=g.constructor.load(JSON.stringify(d));assert.equal(h.area,'woundPass');assert.equal(h.laterStory.deepening.legacy,true);assert.equal(h.laterStory.preparation,undefined);});
