const test=require('node:test'),assert=require('node:assert/strict'),Growth=require('../world-growth.js'),Reality=require('../reality-skills.js');
function model(){return {area:'village',worldGrowth:Growth.initial(),journey:{known:['ripple-return','ripple-guard'],selected:{ripple:'ripple-return',echo:null,seal:null},sync:{'ripple-return':1,'ripple-guard':0}}};}
function combat(key){const family=key.split('-')[0],g={area:'rift',worldGrowth:Growth.initial(),worldState:{achievements:{settled:['inherit:'+family]}},journey:{known:[key],sync:{[key]:1},worlds:[]},playTime:10,training:2,player:{x:0,y:0,r:10,face:0,hp:120,mp:80,cool:{},invuln:0},fate:{focus:100},experimentRuntime:{lastAction:0},enemies:[],events:[],effects:[],stats:()=>({attack:10}),lineClear:()=>true,bossLocked:()=>false,toast(){},emit(){},effect(){},onRealityEffect(e){this.effects.push(e);},strike(e,d){e.hp-=d;return d;},move(p,x,y){p.x+=x;p.y+=y;},enemyThreatContains:()=>false};g.worldGrowth.reality.equipped=family;g.worldGrowth.reality.interpretations={ripple:null,echo:null,seal:null,[family]:key};for(let i=0;i<2;i++)g.enemies.push({id:'e'+i,x:70+i*30,y:0,r:10,hp:500,maxHp:500,wind:1,cd:0,damage:20});return g;}
test('ripple return penetrates behind counter target and guard reduces only self damage',()=>{const g=combat('ripple-return');Reality.act(g,'signature1');Reality.absorb(g,g.enemies[0]);Reality.act(g,'signature2');assert.ok(g.effects.some(e=>e.evolution==='ripple-return'));const h=combat('ripple-guard');Reality.act(h,'signature1');Reality.absorb(h,h.enemies[0]);assert.equal(Reality.damageFactor(h),.7);h.playTime+=4.1;assert.equal(Reality.damageFactor(h),1);});
test('echo evolution never rewinds player and delayed replay fires once',()=>{const g=combat('echo-return');Reality.runtime(g).boost={family:'echo',until:20,mult:1.6};const start=g.player.x;Reality.act(g,'signature2');assert.equal(g.player.x,start);assert.ok(g.effects.some(e=>e.evolution==='echo-return'));const h=combat('echo-replay');Reality.act(h,'signature2');const hp=h.enemies[0].hp;h.playTime+=.5;Reality.step(h);assert.ok(h.enemies[0].hp<hp);assert.ok(h.effects.some(e=>e.evolution==='echo-replay'));const after=h.enemies[0].hp;h.playTime+=1;Reality.step(h);assert.equal(h.enemies[0].hp,after);});
test('seal hold is single target and guide interrupts without displacing bosses',()=>{const g=combat('seal-hold');Reality.act(g,'signature1');assert.equal(g.enemies[0].realitySuppressedUntil,16);assert.equal(g.enemies[1].wind,1);const h=combat('seal-guide');h.enemies[0].boss=true;const x=h.enemies[0].x;Reality.act(h,'signature1');Reality.act(h,'signature2');assert.equal(h.enemies[0].x,x);assert.ok(h.effects.some(e=>e.evolution==='seal-guide'));});
test('unsettled ownership and held followups cannot certify evolution',()=>{const g=combat('echo-replay');g.journey.sync['echo-replay']=0;Reality.act(g,'signature2');assert.equal(Reality.runtime(g).pending.length,0);const h=combat('echo-replay');Reality.act(h,'signature2',true);h.playTime+=1;Reality.step(h);assert.equal(h.effects.length,0);});
test('piercing reaches a distant aligned foe while base counter cannot',()=>{for(const evolved of [false,true]){const g=combat('ripple-return');if(!evolved)g.worldGrowth.reality.interpretations.ripple=null;g.enemies[1].x=250;Reality.act(g,'signature1');Reality.absorb(g,g.enemies[0]);Reality.act(g,'signature2');assert.equal(g.enemies[1].hp,evolved?470:500);}});
test('guard certifies only when subsequent damage is actually reduced',()=>{const g=combat('ripple-guard');Reality.act(g,'signature1');Reality.absorb(g,g.enemies[0]);assert.equal(g.effects.some(e=>e.evolution==='ripple-guard'),false);assert.equal(Reality.damageFactor(g,g.enemies[1]),.7);assert.ok(g.effects.some(e=>e.evolution==='ripple-guard'&&e.kind==='protection'));});
test('echo return splash reaches side foe and guide displaces only normal enemies',()=>{const g=combat('echo-return');g.enemies[1].x=0;g.enemies[1].y=80;Reality.runtime(g).boost={family:'echo',until:20,mult:1.6};Reality.act(g,'signature2');assert.ok(g.enemies[1].hp<500);const h=combat('seal-guide'),e=h.enemies[0],x=e.x;Reality.act(h,'signature1');Reality.act(h,'signature2');assert.equal(e.x,x+70);const hp=e.hp;h.playTime+=.3;Reality.step(h);assert.equal(e.hp,hp-10);h.playTime+=1;Reality.step(h);assert.equal(e.hp,hp-10);});
test('legacy selected interpretations migrate independently and ownership waits for return',()=>{const g=model();Growth.installInterpretations(g);assert.equal(g.journey.selected.ripple,'ripple-return');g.journey.selected.ripple='ripple-guard';g.area='city';assert.equal(g.journey.selected.ripple,'ripple-return');assert.equal(Growth.canEquipInterpretation(g,'ripple-guard'),false);Growth.settleInterpretations(g);assert.equal(Growth.canEquipInterpretation(g,'ripple-guard'),true);g.journey.selected.ripple='ripple-guard';g.area='village';assert.equal(g.journey.selected.ripple,'ripple-guard');g.journey.selected.ripple=null;g.area='city';assert.equal(g.journey.selected.ripple,'ripple-guard');});
test('world interpretation schema survives validation and rejects forged ownership',()=>{const g=model();Growth.installInterpretations(g);const validated=Growth.validate(g.worldGrowth);assert.equal(validated.reality.interpretations.ripple,'ripple-return');g.worldGrowth=validated;Growth.validateInterpretations(g);g.worldGrowth.reality.interpretations.ripple='ripple-guard';assert.throws(()=>Growth.validateInterpretations(g));g.worldGrowth.reality.interpretations.ripple='echo-return';assert.throws(()=>Growth.validate(g.worldGrowth));});
