const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../advancement.js');
function game(){return {worldState:{},area:'village',journey:{realm:false,worlds:['murim','reality']},revision:{inherited:['ripple']},fate:{proven:['ripple'],stage:6},worldGrowth:{murim:{mastery:{sword:8,ripple:8}},reality:{}},laterStory:{six:5,seven:5},v12ChapterCompleted:()=>true,player:{x:400,y:600,hp:100,mp:70,cool:{},r:16},enemies:[],fx:[],events:[],gold:40,potions:3,stats:()=>({hp:120,mp:80,attack:30}),emit(){}};}
test('legacy first realm migrates once with no duplicate base',()=>{let g=game();g.journey.realm=true;assert.equal(A.state(g).realm,1);assert.equal(A.bonus(g,'murim').hp,12);assert.equal(A.state(g).realm,1);assert.equal(A.confirm(g,'realm'),false);});
test('first realm uses basic family, practice and mastery; never evolution',()=>{let g=game();assert.equal(A.describe(g,'realm').canStart,true);g.fate.stage=5;g.v12ChapterCompleted=()=>false;assert.equal(A.describe(g,'realm').canStart,false);});
test('cannot click complete, trial roster is finite, retreat restores snapshot',()=>{let g=game(),before=JSON.stringify(g.player);assert.equal(A.start(g,'realm'),true);assert.equal(A.finish(g,true),false);assert.equal(A.confirm(g,'realm'),false);assert.ok(g.enemies.every(e=>e.assessment));g.player.hp=1;g.gold=0;g.potions=0;assert.equal(A.canEnter(g,'city'),false);assert.equal(g.area,'village');assert.equal(JSON.stringify(g.player),before);assert.equal(g.gold,40);assert.equal(g.potions,3);assert.equal(A.state(g).realm,0);});
test('allocation has bounded integer pools and world isolation',()=>{let g=game();A.state(g).realm=2;assert.equal(A.allocate(g,'realm',{attack:1,hp:2,mp:1}),true);assert.deepEqual(A.bonus(g,'murim'),{hp:46,mp:23,attack:6.5,speed:0});assert.equal(A.allocate(g,'realm',{attack:5,hp:0,mp:0}),false);assert.equal(A.allocate(g,'realm',{attack:NaN,hp:0,mp:0}),false);assert.equal(A.bonus(g,'reality').attack,0);});
test('confirmed realm and hunter allocations only grow per stat',()=>{for(const kind of ['realm','hunter']){const g=game(),last=kind==='realm'?'mp':'speed';g.area=kind==='realm'?'village':'city';A.state(g)[kind]=2;assert.equal(A.allocate(g,kind,{attack:1,hp:1,[last]:0}),true);const before=JSON.stringify({state:g.worldState.advancement,player:g.player});for(const a of [{attack:0,hp:0,[last]:0},{attack:0,hp:2,[last]:0},{attack:0,hp:3,[last]:0}]){assert.equal(A.allocate(g,kind,a),false);assert.equal(JSON.stringify({state:g.worldState.advancement,player:g.player}),before);}assert.equal(A.allocate(g,kind,{attack:1,hp:2,[last]:0}),true);assert.equal(A.describe(g,kind).points.available,1);}});
test('state validator rejects forged stage, points and pending completion',()=>{let g=game();A.state(g);g.worldState.advancement.realm=9;assert.throws(()=>A.validate(g));});
test('all nine assessments require combat and real threat displacement before approval',()=>{for(const kind of ['realm','hunter'])for(let stage=1;stage<A.names[kind].length;stage++){const g=game();g.area=kind==='realm'?'village':'city';g.laterStory.dualBreath=true;const s=A.state(g);s[kind]=stage-1;assert.equal(A.start(g,kind),true,kind+stage);let iterations=0;while(g.advancementTrial&&iterations++<2000){const r=g.advancementTrial;for(const e of g.enemies)e.hp=0; // Enemy deaths are normally produced by strike().
 if(r.pulse){g.player.x=r.pulse.x+250;g.player.y=r.pulse.y;}else if(r.responses>=(r.phase>0?2:1)){g.player.x=r.zone.x;g.player.y=r.zone.y;}g.player.invuln=0;A.step(g,.1);}
 assert.ok(iterations<2000);assert.equal(s[kind],stage-1);assert.equal(s.pending.stage,stage);assert.equal(kind==='hunter'?A.report(g):A.confirm(g,kind),true);assert.equal(kind==='hunter'?A.report(g):A.confirm(g,kind),false);assert.equal(s[kind],stage);assert.equal(A.describe(g,kind).points.total,stage*2);
 }});
test('saving during trial sees original hub and does not interrupt current attempt',()=>{const g=game();A.start(g,'realm');g.player.hp=5;const before=g.advancementTrial;const saved=A.withSaveSnapshot(g,()=>({area:g.area,hp:g.player.hp,trial:g.advancementTrial}));assert.deepEqual(saved,{area:'village',hp:100,trial:null});assert.equal(g.player.hp,5);assert.equal(g.advancementTrial,before);assert.throws(()=>A.withSaveSnapshot(g,()=>{throw Error('disk');}));assert.equal(g.advancementTrial,before);});
test('hunter protection phase fails when ranged objective is ignored',()=>{const g=game();g.area='city';const s=A.state(g);s.hunter=1;A.start(g,'hunter');while(g.advancementTrial?.phase===0){for(const e of g.enemies)e.hp=0;const r=g.advancementTrial;if(r.pulse)g.player.x=r.pulse.x+250;else if(r.responses){g.player.x=r.zone.x;g.player.y=r.zone.y;}A.step(g,.1);}for(let i=0;i<510;i++)A.step(g,.1);assert.equal(g.advancementTrial,null);assert.equal(s.pending,null);assert.equal(s.hunter,1);});
test('specialization preserves health and resource proportions',()=>{const g=game();A.state(g).realm=1;g.stats=()=>{const b=A.bonus(g,'murim');return {hp:120+b.hp,mp:80+b.mp};};g.player.hp=66;g.player.mp=44;assert.equal(A.allocate(g,'realm',{hp:1,mp:1,attack:0}),true);assert.equal(g.player.hp,70);assert.equal(g.player.mp,46.5);});
test('trial snapshot keeps Sets usable after retreat and during saving',()=>{const g=game();g.legendRuntime={seen:new Set(['existing'])};A.start(g,'realm');g.legendRuntime.seen.add('trial');A.withSaveSnapshot(g,()=>assert.equal(g.legendRuntime.seen.has('existing'),true));A.finish(g,false);assert.equal(g.legendRuntime.seen instanceof Set,true);assert.deepEqual([...g.legendRuntime.seen],['existing']);});
test('stages need exactly matching unique confirmation history and numeric legacy realm',()=>{const g=game();const s=A.state(g);s.hunter=5;assert.throws(()=>A.validate(g));s.hunter=0;s.realm=1;g.journey.realm=1;s.history=['realm:1:legacy'];A.validate(g);assert.equal(g.journey.realm,1);g.worldState.advancement.history.push('realm:1:confirmed');assert.throws(()=>A.validate(g));});
test('hunter UI confirmation cannot bypass NPC reporting',()=>{const g=game();g.area='city';A.state(g).pending={kind:'hunter',stage:1,event:'hunter:1:passed'};assert.equal(A.describe(g,'hunter').canConfirm,false);assert.equal(A.confirm(g,'hunter'),false);assert.equal(A.report(g),true);assert.equal(A.report(g),false);});
