const test=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../world-game.js'),D=require('../dungeon-entry.js'),C=require('../cycle-one.js'),{five,six,response,clear}=require('./helpers/world-journey.cjs'),{talk}=require('./world-fixtures.cjs');
function seven(){const g=six(five('seal'),'seal');talk(g,'warden');g.chooseSevenPreparation('evacuation');for(const area of ['woundPass','woundDock','woundCore']){if(area==='woundCore'){g.enter('village');talk(g,'master');}assert.equal(g.enter(area),true);response(g,'seal');clear(g);g.hitStop=0;g.step(.05);}g.enter('city');talk(g,'warden');assert.equal(g.laterStory.seven,5);return g;}
function at(g,area,id){assert.equal(g.enter(area),true,area);return talk(g,id);}
function fight(g,area){assert.equal(g.enter(area),true,area);clear(g);}
test('all six cycle destinations use existing world hub entries and locked predicates',()=>{const g=new Game();for(const id of C.areaIds){assert.ok(D.entries.find(e=>e.id===id),id);assert.equal(D.evaluate(g,id).canEnter,false);}for(const area of ['city','village']){g.enter(area);assert.equal(g.points().filter(p=>p.kind===D.ENTRANCE).length,1);}});
test('new archive access requires chapter four report, return receipt and invitation while legacy access survives',()=>{const g=new Game();g.progress=2;assert.equal(D.canEnter(g,'archive'),false);g.chapter4.rescued=true;g.chapter4.phase=4;g.journey.phase=1;g.enter('village');assert.equal(D.currentDestination(g),null);assert.equal(C.objective(g).destination.id,'returned-yeonhwa');talk(g,'returned-yeonhwa');assert.equal(D.canEnter(g,'archive'),false);talk(g,'master');assert.equal(D.canEnter(g,'archive'),false);talk(g,'master');assert.equal(D.canEnter(g,'archive'),true);assert.equal(D.currentDestination(g),'archive');const legacy=new Game();legacy.progress=2;C.state(legacy).legacyAccess=true;assert.equal(D.canEnter(legacy,'archive'),true);});
test('pre-v12 archive save retains its location and access without inventing invitation scenes',()=>{const g=new Game();g.progress=2;g.training=1;C.state(g).legacyAccess=true;assert.equal(g.enter('archive'),true);const d=JSON.parse(g.save());d.improvementVersion=1;delete d.worldState.cycleOne;const h=Game.load(JSON.stringify(d));assert.equal(h.area,'archive');assert.equal(C.state(h).legacyAccess,true);assert.equal(C.state(h).invited,false);assert.equal(D.canEnter(h,'archive'),true);assert.equal(C.state(Game.load(h.save())).legacyAccess,true);});
test('real damage, direct reports and reload complete the cycle without ranks or paid nodes',()=>{let g=seven();g=Game.load(g.save());assert.equal(C.state(g).bossClear,false);at(g,'village','returned-yeonhwa');assert.equal(D.currentDestination(g),'transportRoad');assert.equal(g.enter('transportRoad'),true);talk(g,'civilian-route');C.interact(g,'civilian-route','device');clear(g);at(g,'city','warden');fight(g,'transportDock');at(g,'city','warden');assert.equal(C.state(g).eightComplete,true);g=Game.load(g.save());at(g,'village','master');fight(g,'supplyRidge');talk(g,'supply-cut');at(g,'city','warden');assert.equal(g.enter('evacuationDock'),true);talk(g,'evacuation-route');clear(g);at(g,'city','warden');at(g,'village','master');assert.equal(C.state(g).nineComplete,true);g=Game.load(g.save());fight(g,'overseerApproach');assert.equal(C.state(g).confronted,false);at(g,'overseerHall','overseer-confront');assert.equal(C.state(g).bossClear,false);g.strike(g.enemies.find(e=>e.cycleBoss),g.stats().attack);g=Game.load(g.save());assert.ok(g.enemies.some(e=>e.cycleBoss&&e.human));clear(g);assert.equal(C.state(g).bossClear,true);at(g,'village','master');assert.equal(C.state(g).epilogue,false);at(g,'city','warden');assert.equal(C.state(g).epilogue,true);const gold=g.gold;talk(g,'warden');assert.equal(g.gold,gold);g=Game.load(g.save());assert.equal(C.state(g).epilogue,true);});

test('archive invitation starts first skill evolution without a separate optional exploration toggle',()=>{const g=new Game();g.progress=2;g.training=1;g.chapter4.rescued=true;g.chapter4.phase=4;g.enter('village');assert.equal(g.journey.phase,0);assert.equal(D.canEnter(g,'archive'),false);talk(g,'returned-yeonhwa');talk(g,'master');const scene=talk(g,'master');assert.equal(g.journey.phase,1);assert.equal(g.guideActive,false);assert.equal(D.currentDestination(g),'archive');assert.equal(D.canEnter(g,'archive'),true);assert.match(scene.text,/스킬 진화 · 기감 해금/);g.fate.path='ripple';g.revision.inherited=['ripple'];const o=require('../objective-model.js').resolve(g);assert.match(o.purpose,/첫 스킬 진화/);assert.equal(o.status,'discover');assert.ok(o.route.some(r=>r.to==='archive'));});
