const test=require('node:test'),assert=require('node:assert/strict'),C=require('../cycle-one.js');
function game(){return {area:'city',worldState:{},laterStory:{seven:5,completed:true},journey:{phase:5},chapter4:{rescued:true,phase:4},enemies:[],playTime:0};}
function talk(g,area,id,choice){g.area=area;return C.interact(g,id,choice);}
function kill(g,area){g.area=area;const e={id:'boss',hp:0,boss:true};g.enemies=[e];C.onDefeat(g,e);}
function prepared(){const g=game();C.sync(g);talk(g,'village','returned-yeonhwa');talk(g,'transportRoad','civilian-route','watcher');kill(g,'transportRoad');talk(g,'city','warden');kill(g,'transportDock');talk(g,'city','warden');talk(g,'village','master');kill(g,'supplyRidge');talk(g,'supplyRidge','supply-cut');talk(g,'city','warden');talk(g,'evacuationDock','evacuation-route');kill(g,'evacuationDock');talk(g,'city','warden');talk(g,'village','master');return g;}
test('legacy chapter seven stays a local victory, never chapter ten victory',()=>{const g=game(),s=C.sync(g);assert.equal(s.regionalClosed,true);assert.equal(s.bossClear,false);assert.equal(s.epilogue,false);assert.equal(C.objective(g).chapter,8);});
test('chapter eight requires civilian choice, real combat, and direct report',()=>{const g=game();C.sync(g);talk(g,'village','returned-yeonhwa');kill(g,'transportRoad');assert.equal(C.state(g).roadClear,false);talk(g,'transportRoad','civilian-route','device');kill(g,'transportRoad');assert.equal(C.canEnter(g,'transportDock'),false);talk(g,'city','warden');assert.equal(C.canEnter(g,'transportDock'),true);kill(g,'transportDock');assert.equal(C.state(g).eightComplete,false);talk(g,'city','warden');assert.equal(C.state(g).eightComplete,true);});
test('all story preparation is independent of ranks, points and family',()=>{for(const family of ['ripple','afterimage','seal']){const g=prepared();g.family=family;assert.equal(C.canEnter(g,'overseerApproach'),true);assert.equal(C.state(g).nineComplete,true);const saved=JSON.stringify(C.state(g));C.onPlayerDefeat(g);assert.equal(JSON.stringify(C.state(g)),saved);const copy=game();copy.worldState.cycleOne=JSON.parse(saved);C.validate(copy);assert.equal(C.canEnter(copy,'overseerApproach'),true);}});
test('approach, confrontation, combat win and epilogue are separate and repeat safe',()=>{const g=prepared();kill(g,'overseerApproach');assert.equal(C.state(g).approachClear,true);talk(g,'overseerHall','overseer-confront');assert.equal(C.state(g).confronted,true);assert.equal(C.state(g).bossClear,false);talk(g,'village','master');assert.equal(C.state(g).epilogue,false);g.area='overseerHall';const fake={hp:0,boss:true,id:'random'};g.enemies=[fake];C.onDefeat(g,fake);assert.equal(C.state(g).bossClear,false);const e={hp:0,boss:true,id:'overseer',cycleBoss:true};g.enemies=[e];C.onDefeat(g,e);assert.equal(C.state(g).bossClear,true);talk(g,'village','master');assert.equal(C.state(g).epilogue,false);talk(g,'city','warden');assert.equal(C.state(g).epilogue,true);const saved=JSON.stringify(C.state(g));talk(g,'city','warden');C.onDefeat(g,e);assert.equal(JSON.stringify(C.state(g)),saved);});
test('live enemies and fabricated defeat callbacks cannot complete events',()=>{const g=prepared();g.area='overseerApproach';g.enemies=[{id:'real',hp:12,boss:true}];C.onDefeat(g,{id:'fake',hp:0,boss:true});assert.equal(C.state(g).approachClear,false);assert.throws(()=>C.validate({...g,worldState:{cycleOne:{...C.initial(),bossClear:true}}}));});
test('finite internal charge never creates infinite regeneration and suppression works',()=>{const g=prepared();kill(g,'overseerApproach');g.area='overseerHall';g.enemies=[{id:'enemy',boss:true,hp:1000,maxHp:1900}];C.onEnter(g);assert.equal(g.enemies[0].human,true);C.interact(g,'overseer-confront');for(let i=0;i<6;i++)C.step(g,6);assert.equal(g.cycleRuntime.charges,0);const hp=g.enemies[0].hp;C.step(g,60);assert.equal(g.enemies[0].hp,hp);C.onPlayerDefeat(g);C.onDualLink(g);C.step(g,1);assert.equal(g.enemies[0].hp,hp);});
test('early reunion and return receipt are explicit sequential events',()=>{const g=game();g.area='ruins';assert.ok(C.sighting(g));assert.equal(C.sighting(g),null);g.area='station';assert.ok(C.sighting(g));g.area='village';assert.ok(C.earlyDialogue(g,'returned-yeonhwa'));assert.equal(C.state(g).recordDelivered,false);C.earlyDialogue(g,'master');assert.equal(C.state(g).invited,false);C.earlyDialogue(g,'master');assert.equal(C.state(g).invited,true);C.validate(g);});
test('transport choices have persistent distinct battlefield effects',()=>{const g=game();C.sync(g);talk(g,'village','returned-yeonhwa');g.area='transportRoad';g.enemies=[{boss:false,hp:80,speed:100,damage:18}];C.interact(g,'civilian-route','watcher');assert.equal(g.enemies[0].speed,45);assert.equal(g.enemies[0].damage,8);assert.equal(C.safeZone(g),null);const other=game();C.sync(other);talk(other,'village','returned-yeonhwa');talk(other,'transportRoad','civilian-route','device');assert.equal(C.safeZone(other).damageFactor,.6);});
test('clearing enemies before the civilian choice keeps genuine combat evidence without forcing a replay',()=>{const g=game();C.sync(g);talk(g,'village','returned-yeonhwa');kill(g,'transportRoad');assert.equal(C.state(g).roadClear,false);talk(g,'transportRoad','civilian-route','device');assert.equal(C.state(g).roadClear,true);C.validate(g);});
