const test=require('node:test');const assert=require('node:assert/strict');const P=require('../passive-growth.js');
test('story deepening works in reality immediately with or without a snapshot',()=>{const g=game();g.area='city';g.laterStory.dualBreath=false;P.settle(g);assert.equal(P.effects(g).deepened,false);g.laterStory.dualBreath=true;assert.equal(P.effects(g).deepened,true);g.worldState.passive.adapted=null;assert.equal(P.effects(g).deepened,true);g.worldGrowth.reality.mode='flow';assert.equal(P.effects(g).deepened,true);assert.equal(P.describe(g).nodes.find(n=>n.id==='F4').appliedLevel,1);});
test('world routing honors game resolver and final areas, upgrades only at village',()=>{const g=game();for(const area of ['transportRoad','supplyRidge','overseerHall','realmAssessment']){g.area=area;assert.equal(P.describe(g).world,'murim');assert.equal(P.upgrade(g,'F1'),false);}g.area='strongholdGate';assert.equal(P.upgrade(g,'F1'),false);g.growthWorld=()=> 'murim';g.area='custom';assert.equal(P.describe(g).world,'murim');assert.equal(P.upgrade(g,'F1'),false);g.area='village';assert.equal(P.upgrade(g,'F1'),true);assert.ok(P.describe(g).nodes.every(n=>typeof n.description==='string'&&n.description.length>5));});
function game(){const g={area:'village',training:2,journey:{realm:1,phase:5},chapter4:{phase:4,rescued:true},laterStory:{six:5,seven:5,dualBreath:true},worldGrowth:{murim:{mode:'flow'},reality:{mode:'focus'}},worldState:{},player:{hp:60,mp:40},enemies:[]};g.stats=()=>{const b=P.bonus(g,g.area==='village'?'murim':'reality');return {hp:120+b.hp,mp:80+b.mp};};return g;}
test('ledger is evidence based, twelve total and idempotent',()=>{const g=game();assert.equal(P.describe(g).total,12);const before=JSON.stringify(P.state(g));P.sync(g);assert.equal(JSON.stringify(P.state(g)),before);const fresh=game();fresh.training=0;fresh.journey={realm:0,phase:0};fresh.chapter4={phase:0};fresh.laterStory={};assert.equal(P.describe(fresh).total,0);});
test('paid upgrades enforce prerequisites and safe murim; free nodes cannot be bought',()=>{const g=game();assert.equal(P.upgrade(g,'F3'),false);assert.equal(P.upgrade(g,'F4'),false);assert.equal(P.upgrade(g,'unknown'),false);g.area='city';assert.equal(P.upgrade(g,'F1'),false);g.area='village';assert.equal(P.upgrade(g,'F1'),true);assert.equal(P.upgrade(g,'F3'),true);g.enemies=[{hp:1}];assert.equal(P.upgrade(g,'F1'),false);});
test('active effects replace base effects, reset is forbidden and preserves investment',()=>{const g=game();P.upgrade(g,'F2');assert.equal(P.effects(g,'murim').recovery,3.5);P.upgrade(g,'F5');assert.equal(g.player.hp,63);assert.equal(P.bonus(g,'murim').hp,6);assert.equal(P.reset(g),false);assert.equal(g.player.hp,63);assert.equal(P.describe(g).spent,2);assert.equal(P.state(g).levels.F4,1);g.worldGrowth.murim.mode='focus';P.upgrade(g,'C2');assert.equal(P.effects(g,'murim').focusMultiplier,1.25);assert.equal(P.effects(g,'murim').recovery,0);});
test('normal-return snapshot replaces and remains unchanged until settlement',()=>{const g=game();P.upgrade(g,'C1');assert.equal(P.bonus(g,'reality').mp,0);assert.equal(P.effects(g,'reality').focusMultiplier,1.2);P.settle(g);assert.equal(P.bonus(g,'reality').mp,4);P.upgrade(g,'C1');assert.equal(P.bonus(g,'reality').mp,4);P.settle(g);P.settle(g);assert.equal(P.bonus(g,'reality').mp,8);P.reset(g);assert.equal(P.bonus(g,'reality').mp,8);P.settle(g);assert.equal(P.bonus(g,'reality').mp,8);});
test('validation rejects forged budgets, unknown levels, invalid snapshots and unsupported versions',()=>{for(const mutate of [s=>s.ledger.fake=99,s=>s.levels.F1=9,s=>s.levels.F1=NaN,s=>s.levels.fake=1,s=>s.version=99,s=>s.adapted={levels:{F1:5}}]){const g=game();P.sync(g);mutate(g.worldState.passive);assert.throws(()=>P.validate(g));}const g=game();P.sync(g);g.worldState.passive.levels.F3=1;assert.throws(()=>P.validate(g));});
test('legacy mode and free deepening survive migration without fabricated progress',()=>{const g=game();g.training=0;g.journey={realm:0,phase:0};g.chapter4={phase:0};g.laterStory={dualBreath:true};g.worldGrowth.murim.mode='focus';const s=P.sync(g);assert.equal(s.levels.C0,1);assert.equal(s.levels.F4,1);assert.equal(s.levels.C5,1);assert.equal(P.describe(g).total,0);assert.equal(g.worldGrowth.murim.mode,'focus');});
test('limited shared pool does not overspend and late realm awards once',()=>{const g=game();g.journey={realm:0,phase:0};g.chapter4={phase:0};g.laterStory={};assert.equal(P.upgrade(g,'F1'),true);assert.equal(P.upgrade(g,'C1'),true);assert.equal(P.describe(g).available,0);const before=JSON.stringify(P.state(g));assert.equal(P.upgrade(g,'F1'),false);assert.equal(JSON.stringify(P.state(g)),before);g.journey.realm=1;assert.equal(P.describe(g).available,3);P.sync(g);assert.equal(P.describe(g).total,5);});
test('only active tree contributes stats and capped upgrades fail unchanged',()=>{const g=game();for(let i=0;i<3;i++){P.upgrade(g,'F1');P.upgrade(g,'C2');}assert.equal(P.bonus(g,'murim').mp,12);g.worldGrowth.murim.mode='focus';assert.equal(P.bonus(g,'murim').mp,0);assert.equal(P.effects(g,'murim').focusMultiplier,1.35);const before=JSON.stringify(P.state(g));assert.equal(P.upgrade(g,'C2'),false);assert.equal(JSON.stringify(P.state(g)),before);});
test('snapshot survives save reload independently and invalid pending state is rejected',()=>{const g=game();P.upgrade(g,'F1');P.settle(g);const raw=JSON.stringify(P.state(g));g.worldState.passive=JSON.parse(raw);P.validate(g);P.upgrade(g,'F1');assert.equal(g.worldState.passive.adapted.levels.F1,1);assert.equal(g.worldState.passive.levels.F1,2);const bad=game();P.sync(bad);bad.worldState.passive.ledger={};bad.worldState.passive.levels.F1=1;assert.throws(()=>P.validate(bad));});
