const test=require('node:test'),assert=require('node:assert/strict'),A=require('../advancement.js'),{Game}=require('../world-game.js'),{inherited,talk}=require('./world-fixtures.cjs');
function ready(kind='hunter',family='ripple'){const g=inherited(family);g.finishIntro();g.fate.stage=6;g.worldGrowth.murim.mastery.sword=8;g.journey.worlds=['무림','현실'];if(kind==='realm')g.enter('village');g.events=[];return g;}
function beat(g){let loops=0;while(g.advancementTrial&&loops++<5000){const r=g.advancementTrial;for(const e of g.enemies.filter(e=>e.hp>0))g.strike(e,99999,'attack');if(r.pulse){g.player.x=r.pulse.x+250;g.player.y=r.pulse.y;}else if(r.responses>=(r.phase?2:1)){g.player.x=r.zone.x;g.player.y=r.zone.y;}g.hitStop=0;g.step(.05);}assert.ok(loops<5000,'assessment must terminate');assert.ok(A.state(g).pending,'combat must earn pending result');}
test('WorldGame assessment save reloads original hub, permanent growth intact',()=>{const g=ready();const stats=JSON.stringify(g.worldGrowth),worlds=[...g.journey.worlds],gold=g.gold,potions=g.potions;g.fate.focus=70;g.combat.charges=2;g.player.cool.moon=1;const before=JSON.stringify(g.player);assert.ok(A.start(g,'hunter'));assert.equal(g.fate.focus,0);assert.equal(g.combat.charges,0);g.step(.05);g.strike(g.enemies[0],99999,'attack');assert.equal(g.gold,gold);assert.equal(JSON.stringify(g.worldGrowth),stats);assert.deepEqual(g.journey.worlds,worlds);const loaded=Game.load(g.save());assert.equal(loaded.area,'city');assert.equal(loaded.gold,gold);assert.equal(loaded.potions,potions);assert.equal(JSON.stringify(loaded.worldGrowth),stats);assert.equal(A.state(loaded).pending,null);assert.ok(g.advancementTrial);A.finish(g,false);assert.equal(JSON.stringify(g.player),before);assert.equal(g.fate.focus,70);assert.equal(g.combat.charges,2);});
test('WorldGame hunter real response and kills earn pending only; NPC report grants rank once',()=>{let g=ready('hunter','seal');const growth=JSON.stringify(g.worldGrowth),worlds=[...g.journey.worlds],settled=[...g.worldState.reality.settled];assert.ok(A.start(g,'hunter'));const e=g.enemies[0];Object.assign(g.player,{x:600,y:650,face:-Math.PI/2});Object.assign(e,{x:600,y:550,wind:.6,tx:600,ty:650});assert.equal(g.act('signature1'),true);assert.equal(e.wind,0);assert.ok(A.progress(g).responses>=1);assert.deepEqual(g.worldState.reality.settled,settled,'assessment cannot settle permanent reality skill');beat(g);assert.equal(A.state(g).hunter,0);assert.equal(JSON.stringify(g.worldGrowth),growth);assert.deepEqual(g.journey.worlds,worlds);g=Game.load(g.save());assert.equal(A.state(g).pending.kind,'hunter');assert.equal(A.confirm(g,'hunter'),false);const result=talk(g,'warden');assert.match(result.title,/승급/);assert.equal(A.state(g).hunter,1);assert.equal(A.report(g),false);assert.equal(Game.load(g.save()).worldState.advancement.hunter,1);});
test('WorldGame realm success awaits explicit confirmation and keeps numeric legacy/save contract',()=>{let g=ready('realm');const growth=JSON.stringify(g.worldGrowth),gold=g.gold;assert.ok(A.start(g,'realm'));beat(g);assert.equal(g.journey.realm,0);assert.equal(g.gold,gold);assert.equal(JSON.stringify(g.worldGrowth),growth);g=Game.load(g.save());assert.equal(g.area,'village');assert.equal(g.breakthrough(),true);assert.equal(g.journey.realm,1);assert.equal(g.breakthrough(),false);const saved=Game.load(g.save());assert.equal(A.state(saved).realm,1);assert.equal(A.describe(saved,'realm').points.total,2);});
test('actual engine movement resolves residual telegraph after early kill, defeat is reversible',()=>{const g=ready(),gold=g.gold,player=JSON.stringify(g.player);assert.ok(A.start(g,'hunter'));g.strike(g.enemies[0],99999,'attack');for(let i=0;i<40&&!g.advancementTrial.pulse;i++){g.hitStop=0;g.step(.05);}assert.ok(g.advancementTrial.pulse);for(let i=0;i<30;i++){g.hitStop=0;g.step(.05,{x:1,y:0});}assert.ok(A.progress(g).responses>=1,'moving out of actual pulse earns response');assert.equal(A.state(g).pending,null,'response alone never completes trial');g.player.hp=0;g.step(.05);assert.equal(g.area,'city');assert.equal(g.advancementTrial,null);assert.equal(g.gold,gold);assert.equal(JSON.stringify(g.player),player);assert.equal(A.state(g).pending,null);assert.ok(A.start(g,'hunter'),'defeat can retry');});
test('save rejects disagreement between legacy realm bit and confirmed advancement',()=>{const g=ready('realm');A.start(g,'realm');beat(g);g.breakthrough();const raw=JSON.parse(g.save());raw.journey.realm=0;assert.throws(()=>Game.load(JSON.stringify(raw)));raw.journey.realm=1;raw.worldState.advancement.realm=0;raw.worldState.advancement.history=[];assert.throws(()=>Game.load(JSON.stringify(raw)));});
test('save rejects fabricated rank without confirmation ledger and out of order pending result',()=>{const g=ready(),raw=JSON.parse(g.save());raw.worldState.advancement.hunter=5;assert.throws(()=>Game.load(JSON.stringify(raw)));raw.worldState.advancement.hunter=0;raw.worldState.advancement.pending={kind:'hunter',stage:2,event:'hunter:2:passed'};assert.throws(()=>Game.load(JSON.stringify(raw)));});
test('projection cannot manufacture first realm from a rank ledger with an unset realm bit',()=>{const g=ready('realm'),raw=JSON.parse(g.save());raw.worldState.advancement.realm=1;raw.worldState.advancement.history=['realm:1:confirmed'];assert.equal(raw.journey.realm,0);assert.throws(()=>Game.load(JSON.stringify(raw)),/경지/);});
test('new realm confirmation cannot bypass basic prerequisites through save projection',()=>{const g=ready('realm'),raw=JSON.parse(g.save());raw.journey.realm=1;raw.worldState.advancement.realm=1;raw.worldState.advancement.history=['realm:1:confirmed'];raw.worldGrowth.murim.mastery={sword:0,ripple:0,echo:0,seal:0};raw.journey.mastery={...raw.worldGrowth.murim.mastery};assert.throws(()=>Game.load(JSON.stringify(raw)),/선행/);});
