const assert=require('node:assert/strict'),{Game}=require('../../world-game.js'),{talk}=require('../world-fixtures.cjs'),{experiment}=require('./journey.cjs');
function clear(g){for(const e of g.enemies.filter(e=>!e.boss)){let n=0;while(e.hp>0&&n++<500)g.strike(e,g.stats().attack,'attack');assert.equal(e.hp,0);}for(const p of g.points().filter(p=>p.kind==='seal'))talk(g,p.id);for(const e of g.enemies.filter(e=>e.boss)){let n=0;while(e.hp>0&&n++<500)g.strike(e,g.stats().attack,'attack');assert.equal(e.hp,0);}g.events=[];}
function response(g,family,mode='flow'){g.setBreath(mode);const e=g.enemies.find(e=>!e.boss&&e.hp>0);assert.ok(e);Object.assign(g.player,{x:730,y:700,face:0,mp:g.stats().mp,invuln:0});Object.assign(e,{x:780,y:700,hp:e.maxHp,wind:0,cd:99});for(const key of Object.keys(g.player.cool))g.player.cool[key]=0;g.hitStop=0;g.experimentRuntime.lastAction=g.playTime-2;if(g.laterStory?.dualBreath||g.laterStory?.deepening?.stage==='trial')g.act(mode==='flow'?'moon':'attack');Object.assign(e,{wind:.1,tx:g.player.x,ty:g.player.y,range:62});g.act('signature1');if(family==='ripple')g.takeHit(e);if(family==='echo'){for(let i=0;i<5;i++){g.hitStop=0;g.step(.05);}e.x=g.player.x+45;e.y=g.player.y;}g.act('signature2');}
function five(family='ripple',stop=null){
 let g=new Game();g.beginIntro(true);g.finishIntro();g.enter('village');talk(g,'master');g.enter('forest');clear(g);g.enter('village');talk(g,'master');g.enter('city');talk(g,'warden');g.enter('rift');clear(g);g.enter('city');talk(g,'warden');g.enter('village');talk(g,'master');g.enter('ruins');clear(g);g.enter('village');talk(g,'master');g.enter('city');talk(g,'warden');g.enter('harbor');clear(g);assert.equal(g.progress,12);g.enter('city');talk(g,'warden');if(stop==='before'){g.events=[];return g;}g.enter('rift');for(let i=0;i<300&&g.area==='rift';i++){g.hitStop=0;g.step(.05);}g.enter('city');talk(g,'warden');g.enter('village');talk(g,'master');g.enter('sanctum');talk(g,'relic-'+family);assert.ok(g.beginTrial(family));const e=g.enemies[0];Object.assign(g.player,{x:e.x-40,y:e.y,face:0,invuln:0});Object.assign(e,{wind:1,tx:g.player.x,ty:g.player.y,range:90});if(family==='ripple'){g.act('signature1');g.takeHit(e);}else if(family==='echo'){g.act('signature1');for(let i=0;i<7;i++){g.hitStop=0;g.step(.05);}}else g.act('signature1');clear(g);g.enter('village');assert.ok(g.acceptFate(family));g.enter('city');assert.ok(g.equipReality(family));if(stop==='inherited'){g.events=[];return g;}if(stop==='challenge'){g.enter('village');g.events=[];return g;}talk(g,'warden');g.enter('heart');for(const guard of g.enemies.filter(e=>!e.boss))g.strike(guard,99999);for(const p of g.points().filter(p=>p.kind==='seal'))talk(g,p.id);const b=g.enemies.find(e=>e.boss);Object.assign(g.player,{x:b.x-40,y:b.y,face:0,invuln:0});Object.assign(b,{wind:.2,tx:g.player.x,ty:g.player.y,cd:99,range:90});g.act('signature1');if(family==='ripple')g.takeHit(b);if(family==='echo')for(let i=0;i<7;i++){g.hitStop=0;g.step(.05);}clear(g);g.enter('city');talk(g,'warden');talk(g,'warden');g.enter('returnPass');clear(g);talk(g,'winch');g.enter('returnDock');clear(g);g.enter('city');talk(g,'warden');talk(g,'warden');g.enter('village');talk(g,'returned-yeonhwa');talk(g,'master');const lesson=g.enemies[0];Object.assign(g.player,{x:lesson.x-40,y:lesson.y,face:0,invuln:0});Object.assign(lesson,{wind:1,tx:g.player.x,ty:g.player.y,range:90});g.act('signature1');if(family==='ripple'){g.player.invuln=0;g.takeHit(lesson);}if(family==='echo'){for(let i=0;i<5;i++){g.hitStop=0;g.step(.05);}}g.act('signature2');assert.equal(g.worldState.growthArc.learnedR,true);g.enter('village');talk(g,'master');talk(g,'master');const variant=family==='seal'?'hold':'return';experiment(g,family,variant);assert.ok(g.chooseInterpretation(family+'-'+variant));g.enter('city');assert.ok(g.chooseInterpretation(family+'-'+variant));talk(g,'warden');g.enter('station');talk(g,'station-lens');g.sense();response(g,family);assert.equal(g.journey.measured,true);clear(g);g.enter('city');talk(g,'warden');assert.equal(g.journey.phase,5);g.events=[];return g;
}
function six(g,family,mode='flow'){talk(g,'warden');g.enter('stabilization');for(let i=0;i<15;i++){g.hitStop=0;g.step(.05);}talk(g,'six-record');g.enter('village');talk(g,'master');g.worldGrowth.reality.mode=mode;g.enter('stabilization');response(g,family,mode);assert.ok(g.laterRuntime.linked);clear(g);g.hitStop=0;g.step(.05);assert.equal(g.laterStory.six,4);g.enter('city');talk(g,'warden');assert.equal(g.laterStory.six,5);return g;}
function resonanceStart(stage){if(!['before','inherited','challenge'].includes(stage))throw Error('Unknown resonance start');return five('ripple',stage);}
module.exports={five,six,response,clear,resonanceStart};
